Localization = Localization or {}

Localization["deDE"] = {
    ["Östlichen Königreiche"] = {
        ["Wald von Elwynn"] = {
            achievementID = 776,
            proxyLocation = {0, 0, "Wald von Elwynn"},
            waypoints = {
                {0, 0, "Nordhaintal"},
                {0, 0, "Goldhain"},
                {0, 0, "Jerods Anlegestelle"},
                {0, 0, "Brackbrunns Kürbisbeet"},
                {0, 0, "Kammwacht"},
                {0, 0, "Der Steinhügelsee"},
                {0, 0, "Weststromgarnison"},
                {0, 0, "Tiefenschachtmine"},
                {0, 0, "Turm von Azora"},
                {0, 0, "Holzfällerlager des Osttals"},
                {0, 0, "Kristallsee"},
            },
        },
        ["das Ödland"] = {
            achievementID = 765,
            proxyLocation = {0, 0, "das Ödland"},
            waypoints = {
                {0, 0, "Die Lethlorklamm"},
                {0, 0, "Uldaman"},
                {0, 0, "Narbe des Weltenbrechers"},
                {0, 0, "Festung Angor"},
                {0, 0, "Blutwächterposten"},
                {0, 0, "Agmondkuppe"},
                {0, 0, "Camp Cagg"},
                {0, 0, "Das Staubbecken"},
                {0, 0, "Camp Kosh"},
                {0, 0, "Neu-Kargath"},
            },
        },
        ["Brennende Steppe"] = {
            achievementID = 775,
            proxyLocation = {0, 0, "Brennende Steppe"},
            waypoints = {
                {0, 0, "Schreckensfels"},
                {0, 0, "Schreckenspfad"},
                {0, 0, "Ruinen von Thaurissan"},
                {0, 0, "Schwarzfelsfestung"},
                {0, 0, "Altar der Stürme"},
                {0, 0, "Morgans Wacht"},
                {0, 0, "Schwarzfelspass"},
                {0, 0, "Schwarzzahnunterschlupf"},
                {0, 0, "Die Schlupfhügel"},
                {0, 0, "Der Schwarzfels"},
            },
        },
        ["Dämmerwald"] = {
            achievementID = 778,
            proxyLocation = {0, 0, "Dämmerwald"},
            waypoints = {
                {0, 0, "Das Stille Ufer"},
                {0, 0, "Rabenflucht"},
                {0, 0, "Ogerhort Vul'Gol"},
                {0, 0, "Yorgens Bauernhof"},
                {0, 0, "Der Verrottende Obstgarten"},
                {0, 0, "Dunkelhain"},
                {0, 0, "Das Dunkle Ufer"},
                {0, 0, "Addles Siedlung"},
                {0, 0, "Friedhof von Rabenflucht"},
                {0, 0, "Zwielichtshain"},
                {0, 0, "Schattenhain"},
                {0, 0, "Friedhof Stille Gärten"},
                {0, 0, "Anwesen der Dunstmantels"},
            },
        },
        ["Loch Modan"] = {
            achievementID = 779,
            proxyLocation = {0, 0, "Loch Modan"},
            waypoints = {
                {0, 0, "Der Loch"},
                {0, 0, "Festung Mo'grosh"},
                {0, 0, "Nordtorpass"},
                {0, 0, "Eisenbands Ausgrabungsstätte"},
                {0, 0, "Thelsamar"},
                {0, 0, "Tal der Könige"},
                {0, 0, "Der Steinwerkdamm"},
                {0, 0, "Silberbachmine"},
                {0, 0, "Jagdhütte der Weltenwanderer"},
                {0, 0, "Grautatzengrat"},
                {0, 0, "Splittersteintal"},
            },
        },
        ["Tirisfal"] = {
            achievementID = 768,
            proxyLocation = {0, 0, "Tirisfal"},
            waypoints = {
                {0, 0, "Todesend"},
                {0, 0, "Agamands Mühlen"},
                {0, 0, "Das Verlassene Anwesen"},
                {0, 0, "Garrens Schlupfwinkel"},
                {0, 0, "Balnirs Bauernhof"},
                {0, 0, "Scharlachroter Wachposten"},
                {0, 0, "Ruinen von Lordaeron"},
                {0, 0, "Das Bollwerk"},
                {0, 0, "Sollidens Bauernhof"},
                {0, 0, "Alptraumtal"},
                {0, 0, "Brill"},
                {0, 0, "Blendwassersee"},
                {0, 0, "Außenposten der Kreuzzügler"},
                {0, 0, "Giftwebertal"},
                {0, 0, "Eingang zum Scharlachroten Kloster"},
                {0, 0, "Calstonanwesen"},
            },
        },
        ["Sengende Schlucht"] = {
            achievementID = 774,
            proxyLocation = {0, 0, "Sengende Schlucht"},
            waypoints = {
                {0, 0, "Feuerwachtgrat"},
                {0, 0, "Schwarzbrandhöhle"},
                {0, 0, "Rußschlacks Grabungsstätte"},
                {0, 0, "Thoriumspitze"},
                {0, 0, "Der Kessel"},
                {0, 0, "Das Meer der Asche"},
                {0, 0, "Staubfeuertal"},
                {0, 0, "Der Schwarzfels"},
            },
        },
        ["Geisterlande"] = {
            achievementID = 858,
            proxyLocation = {0, 0, "Geisterlande"},
            waypoints = {
                {0, 0, "Tristessa"},
                {0, 0, "Goldnebel"},
                {0, 0, "Sanktum des Mondes"},
                {0, 0, "Morgensternturm"},
                {0, 0, "Die Heulende Ziggurat"},
                {0, 0, "Zeb'Nowa"},
                {0, 0, "Windläuferturm"},
                {0, 0, "Elrendarkreuzung"},
                {0, 0, "Sonnenkuppe"},
                {0, 0, "Windläuferdorf"},
                {0, 0, "Sanktum der Sonne"},
                {0, 0, "Enklave der Weltenwanderer"},
                {0, 0, "Die Todesfestung"},
                {0, 0, "Amanipass"},
                {0, 0, "Die Blutende Ziggurat"},
                {0, 0, "Thalassischer Pass"},
            },
        },
        ["das Schlingendornkap"] = {
            achievementID = 4995,
            proxyLocation = {0, 0, "das Schlingendornkap"},
            waypoints = {
                {0, 0, "Beutebucht"},
                {0, 0, "Arena der Gurubashi"},
                {0, 0, "Die Insel Jaguero"},
                {0, 0, "Nek'maniquellbrunnen"},
                {0, 0, "Ruinen von Jubuwal"},
                {0, 0, "Kristalladermine"},
                {0, 0, "Hartzangs Versteck"},
                {0, 0, "Nebeltal"},
                {0, 0, "Ruinen von Aboraz"},
                {0, 0, "Die Wilde Küste"},
            },
        },
        ["das Hinterland"] = {
            achievementID = 773,
            proxyLocation = {0, 0, "das Hinterland"},
            waypoints = {
                {0, 0, "Nistgipfel"},
                {0, 0, "Zun'watha"},
                {0, 0, "Shadra'Alor"},
                {0, 0, "Agol'watha"},
                {0, 0, "Der Altar von Zul"},
                {0, 0, "Lauerfels"},
                {0, 0, "Jintha'Alor"},
                {0, 0, "Seuchennebelklamm"},
                {0, 0, "Jagdhütte Quel'Danil"},
                {0, 0, "Ehrenwindsee"},
                {0, 0, "Die Gruselruinen"},
                {0, 0, "Seradane"},
                {0, 0, "Shaol'watha"},
                {0, 0, "Die Aussichtsklippen"},
            },
        },
        ["das Sumpfland"] = {
            achievementID = 841,
            proxyLocation = {0, 0, "das Sumpfland"},
            waypoints = {
                {0, 0, "Hafen von Menethil"},
                {0, 0, "Blaukiemenmarschen"},
                {0, 0, "Sonnenwendmarschen"},
                {0, 0, "Eisenbarts Grabmal"},
                {0, 0, "Lager der Grollhauer"},
                {0, 0, "Hain des Sumpfhüters"},
                {0, 0, "Hügel der Düsterschmiede"},
                {0, 0, "Fliesmeißels Messstation"},
                {0, 0, "Schwarzkanalmarschen"},
                {0, 0, "Whelgars Ausgrabungsstätte"},
                {0, 0, "Salzgischtschlucht"},
                {0, 0, "Dun Modr"},
                {0, 0, "Thelgenfelsen"},
                {0, 0, "Moosfellmoor"},
                {0, 0, "Dun Algaz"},
                {0, 0, "Raptorgrat"},
            },
        },
        ["Westlichen Pestländer"] = {
            achievementID = 770,
            proxyLocation = {0, 0, "Westlichen Pestländer"},
            waypoints = {
                {0, 0, "Darromersee"},
                {0, 0, "Trauerhügel"},
                {0, 0, "Das Bollwerk"},
                {0, 0, "Dalsons Hof"},
                {0, 0, "Sägewerk des Nordkamms"},
                {0, 0, "Rotkiefersenke"},
                {0, 0, "Die Weinende Höhle"},
                {0, 0, "Darrowehr"},
                {0, 0, "Andorhal"},
                {0, 0, "Teufelssteinfeld"},
                {0, 0, "Das Trostlose Feld"},
                {0, 0, "Herdweiler"},
                {0, 0, "Gahrrons Trauerfeld"},
                {0, 0, "Thondroril"},
            },
        },
        ["Insel von Quel'Danas"] = {
            achievementID = 868,
            proxyLocation = {0, 0, "Insel von Quel'Danas"},
            waypoints = {
            },
        },
        ["das Arathihochland"] = {
            achievementID = 761,
            proxyLocation = {0, 0, "das Arathihochland"},
            waypoints = {
                {0, 0, "Kreis der Westlichen Bindung"},
                {0, 0, "Fels'gor"},
                {0, 0, "Burg Stromgarde"},
                {0, 0, "Kreis der Inneren Bindung"},
                {0, 0, "Halle der Felsfäuste"},
                {0, 0, "Kreis der Äußeren Bindung"},
                {0, 0, "Go'Sheks Hof"},
                {0, 0, "Kreis der Östlichen Bindung"},
                {0, 0, "Nordhof"},
                {0, 0, "Galens Sturz"},
                {0, 0, "Die Faldirbucht"},
                {0, 0, "Thandolübergang"},
                {0, 0, "Die Zuflucht"},
                {0, 0, "Lager der Bleichborken"},
                {0, 0, "Bauernhof der Dabyries"},
                {0, 0, "Hammerfall"},
            },
        },
        ["Verwüsteten Lande"] = {
            achievementID = 766,
            proxyLocation = {0, 0, "Verwüsteten Lande"},
            waypoints = {
                {0, 0, "Feste Schreckensfels"},
                {0, 0, "Burg Nethergarde"},
                {0, 0, "Das Dunkle Portal"},
                {0, 0, "Schreckensfelsposten"},
                {0, 0, "Anhöhe des Entweihers"},
                {0, 0, "Sonnenschleiers Exkursionstrupp"},
                {0, 0, "Die Roten Weiten"},
                {0, 0, "Versorgungslager von Nethergarde"},
                {0, 0, "Schlangenschlinge"},
                {0, 0, "Altar der Stürme"},
                {0, 0, "Die Faulende Narbe"},
                {0, 0, "Havarieküste"},
                {0, 0, "Surwich"},
                {0, 0, "Der Besudelte Wald"},
            },
        },
        ["Dun Morogh"] = {
            achievementID = 627,
            proxyLocation = {0, 0, "Dun Morogh"},
            waypoints = {
                {0, 0, "Eisklamm"},
                {0, 0, "Frontlinie der Frostmähnen"},
                {0, 0, "Flugplatz von Eisenschmiede"},
                {0, 0, "Kharanos"},
                {0, 0, "Gehöft Bernruh"},
                {0, 0, "Steinbruch Gol'Bolar"},
                {0, 0, "Höhle der Frostmähnen"},
                {0, 0, "Tore von Eisenschmiede"},
                {0, 0, "Eisklammtal"},
                {0, 0, "Neu-Tüftlerstadt"},
                {0, 0, "Schimmergrat"},
                {0, 0, "Die Tundridhügel"},
                {0, 0, "Helmsbettsee"},
                {0, 0, "Nordtoraußenposten"},
                {0, 0, "Eiswellensee"},
            },
        },
        ["das Vorgebirge des Hügellands"] = {
            achievementID = 772,
            proxyLocation = {0, 0, "das Vorgebirge des Hügellands"},
            waypoints = {
                {0, 0, "Der Azurschacht"},
                {0, 0, "Corrahns Dolch"},
                {0, 0, "Zugwindspitze"},
                {0, 0, "Dandreds Senke"},
                {0, 0, "Dun Garok"},
                {0, 0, "Galgeneck"},
                {0, 0, "Eisfellhöhle"},
                {0, 0, "Nethandersiedlung"},
                {0, 0, "Die Ruinen von Alterac"},
                {0, 0, "Schlächtergrotte"},
                {0, 0, "Südwachttor"},
                {0, 0, "Tarrens Mühle"},
                {0, 0, "Die Schlickfelder"},
                {0, 0, "Brazies Bauernhof"},
                {0, 0, "Trümmergrathöhle"},
                {0, 0, "Dalarankrater"},
                {0, 0, "Darrohügel"},
                {0, 0, "Burg Durnholde"},
                {0, 0, "Gavins Landspitze"},
                {0, 0, "Nebelufer"},
                {0, 0, "Fegefeuerinsel"},
                {0, 0, "Ruinen von Süderstade"},
                {0, 0, "Soferas Landspitze"},
                {0, 0, "Strahnbrad"},
                {0, 0, "Die Landzunge"},
                {0, 0, "Das Oberland"},
            },
        },
        ["das Rotkammgebirge"] = {
            achievementID = 780,
            proxyLocation = {0, 0, "das Rotkammgebirge"},
            waypoints = {
                {0, 0, "Seenhain"},
                {0, 0, "Drei Ecken"},
                {0, 0, "Rotkammschlucht"},
                {0, 0, "Steinwachtfälle"},
                {0, 0, "Renders Lager"},
                {0, 0, "Galardelltal"},
                {0, 0, "Immerruhlager"},
                {0, 0, "Der Immerruhsee"},
                {0, 0, "Uferpfad"},
                {0, 0, "Althers Mühle"},
                {0, 0, "Renders Tal"},
                {0, 0, "Burg Steinwacht"},
                {0, 0, "Schieferwindtal"},
            },
        },
        ["Immersangwald"] = {
            achievementID = 859,
            proxyLocation = {0, 0, "Immersangwald"},
            waypoints = {
                {0, 0, "Insel der Sonnenwanderer"},
                {0, 0, "Sanktum des Westens"},
                {0, 0, "Sanktum des Nordens"},
                {0, 0, "Zuflucht der Weltenwanderer"},
                {0, 0, "Nachtschimmergrund"},
                {0, 0, "Der Lebende Wald"},
                {0, 0, "Der Versengte Hain"},
                {0, 0, "Azurblaue Küste"},
                {0, 0, "Goldblattpass"},
                {0, 0, "Runenstein Falithas"},
                {0, 0, "Saltherils Hafen"},
                {0, 0, "Thurons Aufzucht"},
                {0, 0, "Zeb'Watha"},
                {0, 0, "Ruinen von Silbermond"},
                {0, 0, "Ankerplatz der Sonnensegel"},
                {0, 0, "Sanktum des Ostens"},
                {0, 0, "Stillwispertümpel"},
                {0, 0, "Morgenluft"},
                {0, 0, "Tor'Watha"},
                {0, 0, "Silbermond"},
                {0, 0, "Elrendarfälle"},
                {0, 0, "Elrendarsee"},
                {0, 0, "Runenstein Shan'dor"},
                {0, 0, "Der Goldene Strand"},
                {0, 0, "Die Stille Küste"},
            },
        },
        ["Silberwald"] = {
            achievementID = 769,
            proxyLocation = {0, 0, "Silberwald"},
            waypoints = {
                {0, 0, "Die Schlachtenfront"},
                {0, 0, "Frontlinie der Verlassenen"},
                {0, 0, "Nördliche Gezeitenbucht"},
                {0, 0, "Valgans Feld"},
                {0, 0, "Tiefenfelsmine"},
                {0, 0, "Mühlenbern"},
                {0, 0, "Kommandozentrale der Verlassenen"},
                {0, 0, "Rückendeckung der Verlassenen"},
                {0, 0, "Die Verfallenen Felder"},
                {0, 0, "Das Huschdunkel"},
                {0, 0, "Insel Fenris"},
                {0, 0, "Das Grabmal"},
                {0, 0, "Olsens Acker"},
                {0, 0, "Burg Schattenfang"},
                {0, 0, "Nördlicher Gezeitenstrom"},
            },
        },
        ["das Nördliche Schlingendorntal"] = {
            achievementID = 781,
            proxyLocation = {0, 0, "das Nördliche Schlingendorntal"},
            waypoints = {
                {0, 0, "Basislager Grom'gol"},
                {0, 0, "Bambala"},
                {0, 0, "Ruinen von Zuuldaia"},
                {0, 0, "Rebellenlager"},
                {0, 0, "Ruinen von Kal'ai"},
                {0, 0, "Ogerhügel der Mosh'Ogg"},
                {0, 0, "Ruinen von Bal'lal"},
                {0, 0, "Ruinen von Zul'Kunda"},
                {0, 0, "Ruinen von Balia'mah"},
                {0, 0, "Fort Livingston"},
                {0, 0, "Nesingwarys Expedition"},
                {0, 0, "Kurzens Truppenlager"},
                {0, 0, "Ruinen von Mizjah"},
                {0, 0, "Der Nazferitisee"},
                {0, 0, "Das Finstere Riff"},
                {0, 0, "Zul'Gurub"},
            },
        },
        ["Sümpfe des Elends"] = {
            achievementID = 782,
            proxyLocation = {0, 0, "Sümpfe des Elends"},
            waypoints = {
                {0, 0, "Das Neblige Tal"},
                {0, 0, "Splitterspeerkreuzung"},
                {0, 0, "Steinard"},
                {0, 0, "Stagalsumpf"},
                {0, 0, "Kraulsumpf"},
                {0, 0, "Reinquellhöhle"},
                {0, 0, "Der Sichere Hafen"},
                {0, 0, "Der Wabersumpf"},
                {0, 0, "Tränenteich"},
                {0, 0, "Sorgendunkel"},
                {0, 0, "Nebelschilfstrand"},
                {0, 0, "Sumpftidenwacht"},
            },
        },
        ["Westfall"] = {
            achievementID = 802,
            proxyLocation = {0, 0, "Westfall"},
            waypoints = {
                {0, 0, "Späherkuppe"},
                {0, 0, "Brauenwirbels Kürbishof"},
                {0, 0, "Der Jangoschacht"},
                {0, 0, "Der Todesacker"},
                {0, 0, "Alexstons Bauernhof"},
                {0, 0, "Die Dolchhügel"},
                {0, 0, "Die Staubebenen"},
                {0, 0, "Saldeans Hof"},
                {0, 0, "Jansens Hof"},
                {0, 0, "Molsens Hof"},
                {0, 0, "Mondbruch"},
                {0, 0, "Demonts Heim"},
                {0, 0, "Der Rasende Schlund"},
            },
        },
        ["Gebirgspass der Totenwinde"] = {
            achievementID = 777,
            proxyLocation = {0, 0, "Gebirgspass der Totenwinde"},
            waypoints = {
                {0, 0, "Totmannsfurt"},
                {0, 0, "Karazhan"},
                {0, 0, "Das Joch"},
            },
        },
        ["Östlichen Pestländer"] = {
            achievementID = 771,
            proxyLocation = {0, 0, "Östlichen Pestländer"},
            waypoints = {
                {0, 0, "Thondroril"},
                {0, 0, "Das Tiefgewölbe"},
                {0, 0, "Das Fungustal"},
                {0, 0, "Pestilenznarbe"},
                {0, 0, "Mereldarsee"},
                {0, 0, "Kapelle des Hoffnungsvollen Lichts"},
                {0, 0, "Das Giftige Tal"},
                {0, 0, "Faulholzsee"},
                {0, 0, "Zul'Mashar"},
                {0, 0, "Jagdhütte Quel'Lithien"},
                {0, 0, "Pestwald"},
                {0, 0, "Ruinen der Scharlachroten Enklave"},
                {0, 0, "Marris' Siedlung"},
                {0, 0, "Turm der Kronenwache"},
                {0, 0, "Darroheim"},
                {0, 0, "Corins Kreuzung"},
                {0, 0, "Tyrs Hand"},
                {0, 0, "Die Infektnarbe"},
                {0, 0, "Ostwallturm"},
                {0, 0, "Nordtal"},
                {0, 0, "Nordpassturm"},
                {0, 0, "Schreckenstal"},
                {0, 0, "Stratholme"},
            },
        },
    },  -- World of Warcraft (Vanilla)
    ["Scherbenwelt"] = {
        ["Höllenfeuerhalbinsel"] = {
            achievementID = 862,
            proxyLocation = {0, 0, "Höllenfeuerhalbinsel"},
            waypoints = {
                {0, 0, "Die Stufen des Schicksals"},
                {0, 0, "Falkenwacht"},
                {0, 0, "Ehrenfeste"},
                {0, 0, "Teiche von Aggonar"},
                {0, 0, "Tempel von Telhamat"},
                {0, 0, "Thrallmar"},
                {0, 0, "Zeth'Gor"},
                {0, 0, "Himmelssturzgrat"},
                {0, 0, "Die Sphärenfelder"},
                {0, 0, "Expeditionsrüstlager"},
                {0, 0, "Höllenfeuerzitadelle"},
                {0, 0, "Posten der Mag'har"},
                {0, 0, "Ruinen von Sha'naar"},
                {0, 0, "Die Front der Legion"},
                {0, 0, "Kil'jaedens Thron"},
                {0, 0, "Haal'eshbau"},
                {0, 0, "Leerengrat"},
                {0, 0, "Konstruktionslager: Mageddon"},
            },
        },
        ["Wälder von Terokkar"] = {
            achievementID = 867,
            proxyLocation = {0, 0, "Wälder von Terokkar"},
            waypoints = {
                {0, 0, "Ruinen des Blutenden Auges"},
                {0, 0, "Cenariusdickicht"},
                {0, 0, "Grangol'var"},
                {0, 0, "Tuurem"},
                {0, 0, "Raastokgrund"},
                {0, 0, "Messerdornbank"},
                {0, 0, "Auchenaigründe"},
                {0, 0, "Flüchtlingskarawane"},
                {0, 0, "Schattengrab"},
                {0, 0, "Rhazeversteck"},
                {0, 0, "Skettis"},
                {0, 0, "Allerias Feste"},
                {0, 0, "Posten der Feuerschwingen"},
                {0, 0, "Steinbrecherfeste"},
                {0, 0, "Shattrath"},
                {0, 0, "Die Hügelwand"},
                {0, 0, "Ruinen der Knochenmalmer"},
                {0, 0, "Aashügel"},
                {0, 0, "Ring der Beobachtung"},
                {0, 0, "Die Herrenlose Karawane"},
                {0, 0, "Der Gequälte Hügel"},
            },
        },
        ["Schergrat"] = {
            achievementID = 865,
            proxyLocation = {0, 0, "Schergrat"},
            waypoints = {
                {0, 0, "Landeplatz von Bash'ir"},
                {0, 0, "Wehr der Speerspießer"},
                {0, 0, "Außenposten der Blutschläger"},
                {0, 0, "Der Zirkel des Blutes"},
                {0, 0, "Konstruktionslager: Groll"},
                {0, 0, "Konstruktionslager: Wut"},
                {0, 0, "Gruuls Unterschlupf"},
                {0, 0, "Dorf der Mok'Nathal"},
                {0, 0, "Messergrat"},
                {0, 0, "Skald"},
                {0, 0, "Kristallrücken"},
                {0, 0, "Lashhversteck"},
                {0, 0, "Vekhaar"},
                {0, 0, "Messerschlucht"},
                {0, 0, "Lager der Blutschläger"},
                {0, 0, "Zerschlagene Wildnis"},
                {0, 0, "Schwelle des Todes"},
                {0, 0, "Konstruktionslager: Terror"},
                {0, 0, "Grishnath"},
                {0, 0, "Zackengrat"},
                {0, 0, "Rabenwald"},
                {0, 0, "Ruuanwald"},
                {0, 0, "Sylvanaar"},
                {0, 0, "Donnerfeste"},
                {0, 0, "Ruuanversteck"},
                {0, 0, "Vortexgipfel"},
            },
        },
        ["das Schattenmondtal"] = {
            achievementID = 864,
            proxyLocation = {0, 0, "das Schattenmondtal"},
            waypoints = {
                {0, 0, "Echsennarbe"},
                {0, 0, "Feste der Legion"},
                {0, 0, "Schattenmond"},
                {0, 0, "Die Todesschmiede"},
                {0, 0, "Kerker des Wächters"},
                {0, 0, "Altar der Sha'tar"},
                {0, 0, "Netherschwingenfelder"},
                {0, 0, "Stätte der Mondfinsternis"},
                {0, 0, "Netherschwingenscherbe"},
                {0, 0, "Der Schwarze Tempel"},
                {0, 0, "Die Hand von Gul'dan"},
                {0, 0, "Wildhammerfeste"},
                {0, 0, "Stätte der Illidari"},
            },
        },
        ["Zangarmarschen"] = {
            achievementID = 863,
            proxyLocation = {0, 0, "Zangarmarschen"},
            waypoints = {
                {0, 0, "Zuflucht des Cenarius"},
                {0, 0, "Wildfenn"},
                {0, 0, "Sumpflichtsee"},
                {0, 0, "Telredor"},
                {0, 0, "Die Lagune"},
                {0, 0, "Umbrafenn"},
                {0, 0, "Festung der Ango'rosh"},
                {0, 0, "Oreborzuflucht"},
                {0, 0, "Zabra'jin"},
                {0, 0, "Grund der Ango'rosh"},
                {0, 0, "Prügelsumpf"},
                {0, 0, "Quaggkamm"},
                {0, 0, "Das Todesmoor"},
                {0, 0, "Ruinen der Zwillingsspitze"},
                {0, 0, "Sporeggar"},
                {0, 0, "Blutschuppengrund"},
                {0, 0, "Das Pilzgeflecht"},
                {0, 0, "Küste der Dunkelkämme"},
            },
        },
        ["Nagrand"] = {
            achievementID = 866,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Konstruktionslager: Furcht"},
                {0, 0, "Halaa"},
                {0, 0, "Ruinen des Lachenden Schädels"},
                {0, 0, "Sonnenwindposten"},
                {0, 0, "Der Ring der Prüfung"},
                {0, 0, "Totschlägerhügel"},
                {0, 0, "Klanwacht"},
                {0, 0, "Südwindkluft"},
                {0, 0, "Schilftanzpass"},
                {0, 0, "Zangarkamm"},
                {0, 0, "Garadar"},
                {0, 0, "Festung Kil'sorge"},
                {0, 0, "Geisterfelder"},
                {0, 0, "Telaar"},
                {0, 0, "Thron der Elemente"},
                {0, 0, "Ruinen der Brennenden Klinge"},
                {0, 0, "Konstruktionslager: Hass"},
                {0, 0, "Zwielichthöhe"},
                {0, 0, "Schilftanz"},
            },
        },
        ["Nethersturm"] = {
            achievementID = 843,
            proxyLocation = {0, 0, "Nethersturm"},
            waypoints = {
                {0, 0, "Area 52"},
                {0, 0, "Manaschmiede Coruu"},
                {0, 0, "Manaschmiede Ara"},
                {0, 0, "Ruinen von Farahlon"},
                {0, 0, "Der Hügel"},
                {0, 0, "Sternensturz"},
                {0, 0, "Netherstein"},
                {0, 0, "Sonnenzornposten"},
                {0, 0, "Gyroplankenbrücke"},
                {0, 0, "Stützpunkt des Astraleums"},
                {0, 0, "Konstruktionsbasis: Vergessenheit"},
                {0, 0, "Manaschmiede B'naar"},
                {0, 0, "Manaschmiede Duro"},
                {0, 0, "Manaschmiede Ultris"},
                {0, 0, "Festung der Stürme"},
                {0, 0, "Ruinen von Arklon"},
                {0, 0, "Kirin'Var"},
                {0, 0, "Ruinen von Enkaat"},
                {0, 0, "Die Sturmsäule"},
                {0, 0, "Biokuppel Fernfeld"},
                {0, 0, "Socrethars Sitz"},
                {0, 0, "Biokuppel Mittelreich"},
            },
        },
    }, -- The Burning Crusade
    ["Kataklysmus"] = {
        ["Hyjal"] = {
            achievementID = 4863,
            proxyLocation = {0, 0, "Hyjal"},
            waypoints = {
                {0, 0, "Rand der Welt"},
                {0, 0, "Aschensee"},
                {0, 0, "Tore von Sothann"},
                {0, 0, "Sethrias Nest"},
                {0, 0, "Die Flammenschneise"},
                {0, 0, "Der Flammenthron"},
                {0, 0, "Der Aschenzirkel"},
                {0, 0, "Die Flüsternde Schlucht"},
                {0, 0, "Nordrassil"},
                {0, 0, "Schrein von Goldrinn"},
                {0, 0, "Die Verbrannte Ebene"},
            },
        },
        ["Tiefenheim"] = {
            achievementID = 4864,
            proxyLocation = {0, 0, "Tiefenheim"},
            waypoints = {
                {0, 0, "Todesschwinges Sturz"},
                {0, 0, "Nadelfelsbruch"},
                {0, 0, "Wrack der Sturmfuror"},
                {0, 0, "Der Bleiche Hort"},
                {0, 0, "Die Bebenden Felder"},
                {0, 0, "Tor der Meister"},
                {0, 0, "Nadelfelsschlucht"},
                {0, 0, "Steinruh"},
                {0, 0, "Tempel der Erde"},
                {0, 0, "Therazanes Thron"},
                {0, 0, "Zwielichtwarte"},
                {0, 0, "Rubinspanne"},
            },
        },
        ["das Schattenhochland"] = {
            achievementID = 4866,
            proxyLocation = {0, 0, "das Schattenhochland"},
            waypoints = {
                {0, 0, "Blutschlucht"},
                {0, 0, "Schmetterschlagposten"},
                {0, 0, "Hafen des Drachenmals"},
                {0, 0, "Feuerbarts Patrouille"},
                {0, 0, "Kriegslager Gorshak"},
                {0, 0, "Hochstade"},
                {0, 0, "Die Humboldtfeuersbrunst"},
                {0, 0, "Obsidianwald"},
                {0, 0, "Die Wuchernde Bucht"},
                {0, 0, "Der Rachen"},
                {0, 0, "Der Schattenriss"},
                {0, 0, "Zwielichtufer"},
                {0, 0, "Gipfel des Siegers"},
                {0, 0, "Der Schlund des Wahnsinns"},
                {0, 0, "Schmelztiegel des Gemetzels"},
                {0, 0, "Drachenmalpass"},
                {0, 0, "Ruinen von Dunwald"},
                {0, 0, "Stopfwampes Anhöhe"},
                {0, 0, "Grim Batol"},
                {0, 0, "Hochlandwald"},
                {0, 0, "Kirthafen"},
                {0, 0, "Ruinen von Drakgor"},
                {0, 0, "Der Schwarze Riss"},
                {0, 0, "Die Krazzwerke"},
                {0, 0, "Donnermar"},
                {0, 0, "Zinnoberrefugium"},
                {0, 0, "Die Wyrmbiege"},
            },
        },
        ["Vashj'ir"] = {
            achievementID = 4825,
            proxyLocation = {0, 0, "Vashj'ir"},
            waypoints = {
                {0, 0, "Das Verlassene Riff"},
                {0, 0, "Tiefenlichtkluft"},
                {0, 0, "Korthuns Ende"},
                {0, 0, "Meeresdickicht"},
                {0, 0, "Glimmertiefenschlucht"},
                {0, 0, "Gurboggels Fels"},
                {0, 0, "Seefahrergrab"},
                {0, 0, "Das Skelettriff"},
                {0, 0, "Nespirah"},
                {0, 0, "Ruinen von Vashj'ir"},
                {0, 0, "Silberfluthöhle"},
                {0, 0, "Wirbelnder Abgrund"},
                {0, 0, "Tiefenflossengrat"},
                {0, 0, "L'ghorek"},
                {0, 0, "Der Brühgraben"},
                {0, 0, "Nagers Friedhof"},
                {0, 0, "Die Umklammerung"},
                {0, 0, "Verhängnis der Legion"},
                {0, 0, "Beth'moragrat"},
                {0, 0, "Ruinen des Thelseraitempels"},
                {0, 0, "Die Schimmernde Grotte"},
            },
        },
        ["Uldum"] = {
            achievementID = 4865,
            proxyLocation = {0, 0, "Uldum"},
            waypoints = {
                {0, 0, "Felder von Akhenet"},
                {0, 0, "Grab des Khartut"},
                {0, 0, "Mar'at"},
                {0, 0, "Neferset"},
                {0, 0, "Obelisk der Sterne"},
                {0, 0, "Orsis"},
                {0, 0, "Ruinen von Ahmtul"},
                {0, 0, "Schnottz' Landeplatz"},
                {0, 0, "Tempel von Uldum"},
                {0, 0, "Tor der Ewigen Zyklen"},
                {0, 0, "Der Pfad der Verwüstung"},
                {0, 0, "Wiege der Uralten"},
                {0, 0, "Die Verlorene Stadt der Tol'vir"},
                {0, 0, "Nahom"},
                {0, 0, "Obelisk des Mondes"},
                {0, 0, "Obelisk der Sonne"},
                {0, 0, "Ramkahen"},
                {0, 0, "Ruinen von Ammon"},
                {0, 0, "Tahretgründe"},
                {0, 0, "Der Verfluchte Landeplatz"},
                {0, 0, "Gräber der Wegbereiter"},
                {0, 0, "Vir'naaldamm"},
            },
        },
    }, -- Cataclysm
    ["Draenor"] = {
        ["Frostfeuergrat"] = {
            achievementID = 8937,
            proxyLocation = {0, 0, "Frostfeuergrat"},
            waypoints = {
                {0, 0, "Speerspießerfestung"},
                {0, 0, "Knochen von Agurak"},
                {0, 0, "Dolchrachenschlucht"},
                {0, 0, "Grimmfrostberg"},
                {0, 0, "Eisernes Belagerungswerk"},
                {0, 0, "Magnarok"},
                {0, 0, "Die Knochenschlucht"},
                {0, 0, "Wor'gol"},
                {0, 0, "Blutschlägerfestung"},
                {0, 0, "Gigantensturz"},
                {0, 0, "Frostwindklippen"},
                {0, 0, "Grom'gar"},
                {0, 0, "Wegstation der Eisernen Horde"},
                {0, 0, "Steinzahnposten"},
                {0, 0, "Die Knirschenden Ebenen"},
            },
        },
        ["Gorgrond"] = {
            achievementID = 8939,
            proxyLocation = {0, 0, "Gorgrond"},
            waypoints = {
                {0, 0, "Bastionsklippe"},
                {0, 0, "Grimmgleisdepot"},
                {0, 0, "Todesgrimasse"},
                {0, 0, "Immermornquellen"},
                {0, 0, "Hochpass"},
                {0, 0, "Steinbrecherarena"},
                {0, 0, "Der Eiserne Vorstoß"},
                {0, 0, "Wildwacht"},
                {0, 0, "Der Blutrote Sumpf"},
                {0, 0, "Die Immergrüne Wildnis"},
                {0, 0, "Gronnschlucht"},
                {0, 0, "Der Iyunwald"},
                {0, 0, "Schlingenherz"},
                {0, 0, "Die Grube"},
                {0, 0, "Die Grube"},
                {0, 0, "Die Grube"},
            },
        },
        ["Spitzen von Arak"] = {
            achievementID = 8941,
            proxyLocation = {0, 0, "Spitzen von Arak"},
            waypoints = {
                {0, 0, "Skettis"},
                {0, 0, "Der Windende Morast"},
                {0, 0, "Zekkversteck"},
                {0, 0, "Südhafen"},
                {0, 0, "Morgenterrasse"},
                {0, 0, "Messerfaustfestung"},
                {0, 0, "Das Vergessene Anzuversteck"},
                {0, 0, "Rabenskar"},
                {0, 0, "Axtfall"},
                {0, 0, "Der Heulende Fels"},
                {0, 0, "Quetschpfeifenkap"},
                {0, 0, "Akrazversteck"},
                {0, 0, "Windgepeitschte Terrasse"},
                {0, 0, "Sethekkniederung"},
                {0, 0, "Admiral Taylors Garnison"},
                {0, 0, "Werkstatt Quetschpfeif"},
                {0, 0, "Blutmähnental"},
            },
        },
        ["das Schattenmondtal"] = {
            achievementID = 8938,
            proxyLocation = {0, 0, "das Schattenmondtal"},
            waypoints = {
                {0, 0, "Festung der Pein"},
                {0, 0, "Elodor"},
                {0, 0, "Schummergehölz"},
                {0, 0, "Karabor"},
                {0, 0, "Das Schimmermoor"},
                {0, 0, "Eiland der Schatten"},
                {0, 0, "Nachtflutnest"},
                {0, 0, "Embaari"},
                {0, 0, "Gul'var"},
                {0, 0, "Shaz'gul"},
                {0, 0, "Socrethars Klippe"},
            },
        },
        ["Talador"] = {
            achievementID = 8940,
            proxyLocation = {0, 0, "Talador"},
            waypoints = {
                {0, 0, "Aruuna"},
                {0, 0, "Abendlichtinsel"},
                {0, 0, "Fort Wrynn"},
                {0, 0, "Gul'rok"},
                {0, 0, "Orunaiküste"},
                {0, 0, "Shattrath"},
                {0, 0, "Grab des Lichts"},
                {0, 0, "Zangarra"},
                {0, 0, "Auchindoun"},
                {0, 0, "Hof der Seelen"},
                {0, 0, "Gordalfestung"},
                {0, 0, "Der Pfad des Ruhms"},
                {0, 0, "Anachoretenrast"},
                {0, 0, "Telmor"},
                {0, 0, "Tuurem"},
            },
        },
        ["Nagrand"] = {
            achievementID = 8942,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Ahnengrund"},
                {0, 0, "Tore von Grommashar"},
                {0, 0, "Hafen von Hochfels"},
                {0, 0, "Lok-rath"},
                {0, 0, "Wachposten von Mok'gol"},
                {0, 0, "Telaar"},
                {0, 0, "Der Ring der Prüfung"},
                {0, 0, "Küste von Zangar"},
                {0, 0, "Die Zerschlagene Anhöhe"},
                {0, 0, "Hallvalor"},
                {0, 0, "Eisenfausthafen"},
                {0, 0, "Mar'goks Wacht"},
                {0, 0, "Oshu'gun"},
                {0, 0, "Der Ring des Blutes"},
                {0, 0, "Thron der Elemente"},
            },
        },
    }, -- Warlords of Draenor
    ["Schlacht um Azeroth"] = {
        ["Tiragardesund"] = {
            achievementID = 12556,
            proxyLocation = {0, 0, "Tiragardesund"},
            waypoints = {
                {0, 0, "Angelpunktwerft"},
                {0, 0, "Farnwaldhöhe"},
                {0, 0, "Anwesen der Norwinsens"},
                {0, 0, "Verlassener Schrottplatz"},
                {0, 0, "Der Klagende Priel"},
                {0, 0, "Schmelzender Gletscher"},
                {0, 0, "Boralus"},
                {0, 0, "Freihafen"},
                {0, 0, "Krakenfluchbucht"},
                {0, 0, "Kenningers Jagdhütte"},
                {0, 0, "Wachkuppe"},
            },
        },
        ["das Sturmsangtal"] = {
            achievementID = 12558,
            proxyLocation = {0, 0, "das Sturmsangtal"},
            waypoints = {
                {0, 0, "Brennadam"},
                {0, 0, "Seemannsrinne"},
                {0, 0, "Totenschwemme"},
                {0, 0, "Weisenwall"},
                {0, 0, "Mühlsteinweiler"},
                {0, 0, "Kral der Borstenrücken"},
                {0, 0, "Reißzahnfeste"},
                {0, 0, "Fort Daelin"},
                {0, 0, "Schrein des Sturms"},
            },
        },
        ["Nazmir"] = {
            achievementID = 12561,
            proxyLocation = {0, 0, "Nazmir"},
            waypoints = {
                {0, 0, "Der Urzeitsumpf"},
                {0, 0, "Die Flussmarschen"},
                {0, 0, "Zalamar"},
                {0, 0, "Nazwatha"},
                {0, 0, "Die Froschmarschen"},
                {0, 0, "Das Herz der Dunkelheit"},
                {0, 0, "Die Nekropole"},
                {0, 0, "Torgas Ruh"},
                {0, 0, "Zal'amak"},
            },
        },
        ["Drustvar"] = {
            achievementID = 12557,
            proxyLocation = {0, 0, "Drustvar"},
            waypoints = {
                {0, 0, "Aroms Wehr"},
                {0, 0, "Schlächterhafen"},
                {0, 0, "Der Blutrote Wald"},
                {0, 0, "Schnitztal"},
                {0, 0, "Hochwegpass"},
                {0, 0, "Eisschleiergletscher"},
                {0, 0, "Grabhügelfriedhof"},
                {0, 0, "Korlach"},
                {0, 0, "Fallhafen"},
                {0, 0, "Gol Koval"},
                {0, 0, "Westwacht"},
                {0, 0, "Kronsteiganwesen"},
            },
        },
        ["Zuldazar"] = {
            achievementID = 12559,
            proxyLocation = {0, 0, "Zuldazar"},
            waypoints = {
                {0, 0, "Atal'Dazar"},
                {0, 0, "Bluttor"},
                {0, 0, "Schreckensperlenuntiefen"},
                {0, 0, "Die Wilden Lande"},
                {0, 0, "Insel der Hauer"},
                {0, 0, "Xibala"},
                {0, 0, "Atal'Gral"},
                {0, 0, "Dazar'alor"},
                {0, 0, "Garten der Loa"},
                {0, 0, "Die Spanne"},
                {0, 0, "Talanjis Tadel"},
                {0, 0, "Zeb'ahari"},
            },
        },
        ["Vol'dun"] = {
            achievementID = 12560,
            proxyLocation = {0, 0, "Vol'dun"},
            waypoints = {
                {0, 0, "Atul'Aman"},
                {0, 0, "Hafen von Zem'lan"},
                {0, 0, "Der Trümmersteinhafen"},
                {0, 0, "Der Tempel von Akunda"},
                {0, 0, "Die Knochengrube"},
                {0, 0, "Die Gebrochene Küste"},
                {0, 0, "Die Pfiffblütenoase"},
                {0, 0, "Die Finsterwaldbank"},
                {0, 0, "Der Rotfelshafen"},
                {0, 0, "Die Schlängelnde Schlucht"},
                {0, 0, "Die Terrasse der Ergebenen"},
                {0, 0, "Das Salzbecken"},
                {0, 0, "Tortakazuflucht"},
            },
        },
    }, -- Battle for Azeroth
    ["Kalimdor"] = {
        ["Durotar"] = {
            achievementID = 728,
            proxyLocation = {0, 0, "Durotar"},
            waypoints = {
                {0, 0, "Tal der Prüfungen"},
                {0, 0, "Die Südstromaue"},
                {0, 0, "Echoinseln"},
                {0, 0, "Klingenhügel"},
                {0, 0, "Donnergrat"},
                {0, 0, "Knochenhöhle"},
                {0, 0, "Vorposten der Nordwacht"},
                {0, 0, "Sen'jin"},
                {0, 0, "Burg Tiragarde"},
                {0, 0, "Revier der Klingenmähnen"},
                {0, 0, "Staubwindklamm"},
                {0, 0, "Orgrimmar"},
            },
        },
        ["Teldrassil"] = {
            achievementID = 842,
            proxyLocation = {0, 0, "Teldrassil"},
            waypoints = {
                {0, 0, "Laubschattental"},
                {0, 0, "Dolanaar"},
                {0, 0, "Höhle der Knarzklauen"},
                {0, 0, "Teiche von Arlithrien"},
                {0, 0, "Die Lichtung des Orakels"},
                {0, 0, "Darnassus"},
                {0, 0, "Die Kluft"},
                {0, 0, "Lichtung von Ban'ethil"},
                {0, 0, "Al'Amethsee"},
                {0, 0, "Sternenhauch"},
                {0, 0, "Quellsee"},
                {0, 0, "Rut'theran"},
            },
        },
        ["das Nördliche Brachland"] = {
            achievementID = 750,
            proxyLocation = {0, 0, "das Nördliche Brachland"},
            waypoints = {
                {0, 0, "Felsadermine"},
                {0, 0, "Schutzwall von Mor'shan"},
                {0, 0, "Glutnebelgipfel"},
                {0, 0, "Die Vergessenen Teiche"},
                {0, 0, "Fernwacht"},
                {0, 0, "Das Wegekreuz"},
                {0, 0, "Ratschet"},
                {0, 0, "Die Blühende Oase"},
                {0, 0, "Das Schlickmoor"},
                {0, 0, "Die Trockenen Hügel"},
                {0, 0, "Grol'doms Hof"},
                {0, 0, "Dornenhügel"},
                {0, 0, "Die Brackige Oase"},
                {0, 0, "Die Händlerküste"},
            },
        },
        ["das Südliche Brachland"] = {
            achievementID = 4996,
            proxyLocation = {0, 0, "das Südliche Brachland"},
            waypoints = {
                {0, 0, "Bael Modan"},
                {0, 0, "Gefechtsstand"},
                {0, 0, "Ehrenwacht"},
                {0, 0, "Die Feste Nordwacht"},
                {0, 0, "Überreste von Camp Taurajo"},
                {0, 0, "Vendettakuppe"},
                {0, 0, "Kriegsnarbe"},
                {0, 0, "Frazzelcraz' Hauptader"},
                {0, 0, "Der Jägerhügel"},
                {0, 0, "Kral der Klingenhauer"},
                {0, 0, "Die Überwucherung"},
            },
        },
        ["Blutmythosinsel"] = {
            achievementID = 861,
            proxyLocation = {0, 0, "Blutmythosinsel"},
            waypoints = {
                {0, 0, "Goldweberpass"},
                {0, 0, "Schwarzschlammküste"},
                {0, 0, "Insel des Blutfluchs"},
                {0, 0, "Enklave der Sichelklauen"},
                {0, 0, "Trümmerfall"},
                {0, 0, "Nazzivian"},
                {0, 0, "Ruinen von Loreth'Aran"},
                {0, 0, "Tel'athions Lager"},
                {0, 0, "Blutbrandung"},
                {0, 0, "Der Kryokern"},
                {0, 0, "Das Versteckte Riff"},
                {0, 0, "Die Vektorspule"},
                {0, 0, "Viridiangrund"},
                {0, 0, "Hassprankenzuflucht"},
                {0, 0, "Axxarien"},
                {0, 0, "Messerwinkel"},
                {0, 0, "Blutwacht"},
                {0, 0, "Kessels Wegelager"},
                {0, 0, "Mythoswald"},
                {0, 0, "Rachfederkamm"},
                {0, 0, "Krallenhoch"},
                {0, 0, "Das Riff des Blutfluchs"},
                {0, 0, "Die Purpurbrandung"},
                {0, 0, "Der Besudelte Teich"},
                {0, 0, "Die Verlorene Furt"},
                {0, 0, "Die Warpgondel"},
                {0, 0, "Verteidigers Ruh'"},
                {0, 0, "Insel Drachenfels"},
            },
        },
        ["Tausend Nadeln"] = {
            achievementID = 846,
            proxyLocation = {0, 0, "Tausend Nadeln"},
            waypoints = {
                {0, 0, "Der Große Aufzug"},
                {0, 0, "Versunkene Ausgrabungsstätte"},
                {0, 0, "Schattenödnis"},
                {0, 0, "Der Westliche Gipfel"},
                {0, 0, "Freiwindposten"},
                {0, 0, "Die Schimmernde Tiefe"},
                {0, 0, "Hügel der Klingenhauer"},
                {0, 0, "Südmeerstützpunkt"},
                {0, 0, "Schattenbollwerk"},
                {0, 0, "Düsterwolkengipfel"},
                {0, 0, "Spalthufanhöhen"},
                {0, 0, "Der Steilhang"},
            },
        },
        ["Desolace"] = {
            achievementID = 848,
            proxyLocation = {0, 0, "Desolace"},
            waypoints = {
                {0, 0, "Tethris Aran"},
                {0, 0, "Die Nijelspitze"},
                {0, 0, "Festung Donneraxt"},
                {0, 0, "Territorium der Magram"},
                {0, 0, "Tal der Speere"},
                {0, 0, "Schattenflucht"},
                {0, 0, "Zirkel der Mannoroc"},
                {0, 0, "Schattenklamm"},
                {0, 0, "Thargads Lager"},
                {0, 0, "Sargeron"},
                {0, 0, "Cenariuswildnis"},
                {0, 0, "Die Insel Ranazjar"},
                {0, 0, "Der Kodofriedhof"},
                {0, 0, "Dorf der Gelkis"},
                {0, 0, "Shok'Thokar"},
                {0, 0, "Strand der Zackenkämme"},
            },
        },
        ["Feralas"] = {
            achievementID = 849,
            proxyLocation = {0, 0, "Feralas"},
            waypoints = {
                {0, 0, "Die Untere Wildnis"},
                {0, 0, "Die Zwillingskolosse"},
                {0, 0, "Düsterbruch"},
                {0, 0, "Ruinen von Isildien"},
                {0, 0, "Camp Mojache"},
                {0, 0, "Außenposten der Gordunni"},
                {0, 0, "Mondfederfeste"},
                {0, 0, "Ruinen der Mondfederfeste"},
                {0, 0, "Die Vergessene Küste"},
                {0, 0, "Wildschrammtal"},
                {0, 0, "Die Gewundene Tiefe"},
                {0, 0, "Truppenlager der Grimmtotems"},
                {0, 0, "Graunebelruinen"},
            },
        },
        ["Azshara"] = {
            achievementID = 852,
            proxyLocation = {0, 0, "Azshara"},
            waypoints = {
                {0, 0, "Gallywix' Lustschloss"},
                {0, 0, "Bilgewasserhafen"},
                {0, 0, "Turm von Eldara"},
                {0, 0, "Darnassisches Basislager"},
                {0, 0, "Bärenkopf"},
                {0, 0, "Hinteres Tor von Orgrimmar"},
                {0, 0, "Südklippenufer"},
                {0, 0, "Mennarsee"},
                {0, 0, "Sturmklippen"},
                {0, 0, "Strand der Trümmer"},
                {0, 0, "Bittere Landzunge"},
                {0, 0, "Ruinen von Arkkoran"},
                {0, 0, "Das Geheimlabor"},
                {0, 0, "Schwarzschlundfeste"},
                {0, 0, "Ruinen von Eldarath"},
                {0, 0, "Rabenkrones Monument"},
                {0, 0, "Die Verfallenen Gegenden"},
            },
        },
        ["Krater von Un'Goro"] = {
            achievementID = 854,
            proxyLocation = {0, 0, "Krater von Un'Goro"},
            waypoints = {
                {0, 0, "Feuersäulengrat"},
                {0, 0, "Marschalls Wehr"},
                {0, 0, "Die Aufwühlenden Gärten"},
                {0, 0, "Die Heißen Quellen von Golakka"},
                {0, 0, "Die Wuchernde Narbe"},
                {0, 0, "Eisensteinplateau"},
                {0, 0, "Fungusfels"},
                {0, 0, "Der Mooshügel"},
                {0, 0, "Die Schreienden Weiten"},
                {0, 0, "Terrorflucht"},
                {0, 0, "Die Marschen"},
                {0, 0, "Teergruben von Lakkari"},
            },
        },
        ["Silithus"] = {
            achievementID = 856,
            proxyLocation = {0, 0, "Silithus"},
            waypoints = {
                {0, 0, "Das Kristalltal"},
                {0, 0, "Burg Cenarius"},
                {0, 0, "Bau des Regalschwarms"},
                {0, 0, "Bau des Ashischwarms"},
                {0, 0, "Südwindposten"},
                {0, 0, "Bau des Zoraschwarms"},
                {0, 0, "Der Skarabäuswall"},
                {0, 0, "Heldenwacht"},
            },
        },
        ["Mulgore"] = {
            achievementID = 736,
            proxyLocation = {0, 0, "Mulgore"},
            waypoints = {
                {0, 0, "Hochwolkenebene"},
                {0, 0, "Dorf der Bluthufe"},
                {0, 0, "Die Wogenden Ebenen"},
                {0, 0, "Überfallene Karawane"},
                {0, 0, "Brunnen der Donnerhörner"},
                {0, 0, "Teufelsfelsen"},
                {0, 0, "Brunnen der Wildmähnen"},
                {0, 0, "Bleichmähnenfels"},
                {0, 0, "Brunnen der Winterhufe"},
                {0, 0, "Die Mine der Venture Co."},
                {0, 0, "Die Goldenen Ebenen"},
                {0, 0, "Grabungsstätte von Bael'dun"},
                {0, 0, "Windfurienkamm"},
            },
        },
        ["Azurmythosinsel"] = {
            achievementID = 860,
            proxyLocation = {0, 0, "Azurmythosinsel"},
            waypoints = {
                {0, 0, "Am'mental"},
                {0, 0, "Azurwacht"},
                {0, 0, "Glutgrund"},
                {0, 0, "Geezles Lager"},
                {0, 0, "Odesyus' Ankerplatz"},
                {0, 0, "Kapselwrack"},
                {0, 0, "Silbermythosinsel"},
                {0, 0, "Die Exodar"},
                {0, 0, "Hassprankenterritorium"},
                {0, 0, "Am'menfluss"},
                {0, 0, "Dorf der Sichelklauen"},
                {0, 0, "Morgentaustrand"},
                {0, 0, "Mondweidenwald"},
                {0, 0, "Kapselteil"},
                {0, 0, "Schlickerküste"},
                {0, 0, "Tannenruhfeste"},
                {0, 0, "Valaars Steg"},
            },
        },
        ["Winterquell"] = {
            achievementID = 857,
            proxyLocation = {0, 0, "Winterquell"},
            waypoints = {
                {0, 0, "Die Frostfeuerquellen"},
                {0, 0, "Kel'Therilsee"},
                {0, 0, "Mazthoril"},
                {0, 0, "Eulenflügeldickicht"},
                {0, 0, "Lager der Winterfelle"},
                {0, 0, "Frostsäblerfelsen"},
                {0, 0, "Holzschlundposten"},
                {0, 0, "Sternfall"},
                {0, 0, "Ewige Warte"},
                {0, 0, "Eisdistelberge"},
                {0, 0, "Der Versteckte Hain"},
                {0, 0, "Frosthauchschlucht"},
            },
        },
        ["Dunkelküste"] = {
            achievementID = 844,
            proxyLocation = {0, 0, "Dunkelküste"},
            waypoints = {
                {0, 0, "Ruinen von Auberdine"},
                {0, 0, "Kriegslager der Splitterspeere"},
                {0, 0, "Das Welkende Dickicht"},
                {0, 0, "Das Auge des Vortex"},
                {0, 0, "Lor'danel"},
                {0, 0, "Die Meistergleve"},
                {0, 0, "Das Splitterspeertal"},
                {0, 0, "Wildschnellen"},
                {0, 0, "Die Ruinen von Mathystra"},
                {0, 0, "Ameth'Aran"},
                {0, 0, "Nazj'vel"},
            },
        },
        ["das Eschental"] = {
            achievementID = 845,
            proxyLocation = {0, 0, "das Eschental"},
            waypoints = {
                {0, 0, "Der Zoramstrand"},
                {0, 0, "Silberwindzuflucht"},
                {0, 0, "Falathimsee"},
                {0, 0, "Lager der Distelfelle"},
                {0, 0, "Astranaar"},
                {0, 0, "Das Heulende Tal"},
                {0, 0, "Himmelssturzsee"},
                {0, 0, "Satyrnaar"},
                {0, 0, "Holzfällerlager des Kriegshymnenklans"},
                {0, 0, "Orendils Zuflucht"},
                {0, 0, "Der Donnergipfel"},
                {0, 0, "Maestras Posten"},
                {0, 0, "Der Schrein von Aessina"},
                {0, 0, "Die Sternenstaubruinen"},
                {0, 0, "Rajenbaum"},
                {0, 0, "Splitterholzposten"},
                {0, 0, "Schattengrün"},
                {0, 0, "Dämonenhügel"},
            },
        },
        ["das Steinkrallengebirge"] = {
            achievementID = 847,
            proxyLocation = {0, 0, "das Steinkrallengebirge"},
            waypoints = {
                {0, 0, "Kriegsnarbental"},
                {0, 0, "Ruinen von Eldre'thar"},
                {0, 0, "Grabstätte"},
                {0, 0, "Scherwindfeste"},
                {0, 0, "Malaka'jin"},
                {0, 0, "Steinschlagklamm"},
                {0, 0, "Die Scherwindklippe"},
                {0, 0, "Das Verbrannte Tal"},
                {0, 0, "Der Steinkrallengipfel"},
                {0, 0, "Feste Krom'gar"},
                {0, 0, "Aussicht von Thal'darah"},
                {0, 0, "Weberkuhle"},
                {0, 0, "Klippenläuferposten"},
                {0, 0, "Weberpass"},
                {0, 0, "Hochwipfeltal"},
                {0, 0, "Sonnenfels"},
                {0, 0, "Mirkfallonsee"},
            },
        },
        ["Düstermarschen"] = {
            achievementID = 850,
            proxyLocation = {0, 0, "Düstermarschen"},
            waypoints = {
                {0, 0, "Die Insel Theramore"},
                {0, 0, "Grollhornposten"},
                {0, 0, "Gasthaus Zur Süßen Ruh"},
                {0, 0, "Brackenwall"},
                {0, 0, "Insel Alcaz"},
                {0, 0, "Dorf der Schwarzhufe"},
                {0, 0, "Morastwinkel"},
                {0, 0, "Schreckensmoorküste"},
                {0, 0, "Der Drachensumpf"},
            },
        },
        ["Tanaris"] = {
            achievementID = 851,
            proxyLocation = {0, 0, "Tanaris"},
            waypoints = {
                {0, 0, "Gadgetzan"},
                {0, 0, "Tal der Behüter"},
                {0, 0, "Die Ewigen Sande"},
                {0, 0, "Der Giftige Unterschlupf"},
                {0, 0, "Südbrandung"},
                {0, 0, "Ostmondruinen"},
                {0, 0, "Südmondruinen"},
                {0, 0, "Zul'Farrak"},
                {0, 0, "Sandmarterwache"},
                {0, 0, "Mast- und Schotbucht"},
                {0, 0, "Zerbrochene Säule"},
                {0, 0, "Truppenlager der Dünenbrecher"},
                {0, 0, "Die Klaffende Schlucht"},
                {0, 0, "Landendestrand"},
                {0, 0, "Disteltal"},
                {0, 0, "Höhlen der Zeit"},
            },
        },
        ["Teufelswald"] = {
            achievementID = 853,
            proxyLocation = {0, 0, "Teufelswald"},
            waypoints = {
                {0, 0, "Revier der Teufelspfoten"},
                {0, 0, "Der Eisenwald"},
                {0, 0, "Narbengrund"},
                {0, 0, "Jaedenar"},
                {0, 0, "Jadefeuertal"},
                {0, 0, "Lager der Totenwaldfelle"},
                {0, 0, "Nachtlaublichtung"},
                {0, 0, "Jadefeuerschlucht"},
                {0, 0, "Die Blutgiftfälle"},
                {0, 0, "Ruinen von Constellas"},
                {0, 0, "Das Smaragdrefugium"},
                {0, 0, "Morlos'Aran"},
            },
        },
        ["Mondlichtung"] = {
            achievementID = 855,
            proxyLocation = {0, 0, "Mondlichtung"},
            waypoints = {
                {0, 0, "See von Elune'ara"},
                {0, 0, "Schrein von Remulos"},
                {0, 0, "Nachthafen"},
                {0, 0, "Sturmgrimms Grabhügel"},
            },
        },
    }, -- World of Warcraft (Vanilla)
    ["Nordends"] = {
        ["Boreanische Tundra"] = {
            achievementID = 1264,
            proxyLocation = {0, 0, "Boreanische Tundra"},
            waypoints = {
                {0, 0, "Tempelstadt En'kilah"},
                {0, 0, "Strand der Peitschennarbe"},
                {0, 0, "Garroshs Landeplatz"},
                {0, 0, "Kaltarra"},
                {0, 0, "Bernsteinflöz"},
                {0, 0, "Valianzfeste"},
                {0, 0, "Höhlen des Todes"},
                {0, 0, "Stahlkiefers Karawane"},
                {0, 0, "Kaskala"},
                {0, 0, "Todeswehr"},
                {0, 0, "Außenposten Bor'gorok"},
                {0, 0, "Kriegshymnenfeste"},
                {0, 0, "Die Geysirfelder"},
            },
        },
        ["Drachenöde"] = {
            achievementID = 1265,
            proxyLocation = {0, 0, "Drachenöde"},
            waypoints = {
                {0, 0, "Galakronds Ruhestätte"},
                {0, 0, "Obsidiandrachenschrein"},
                {0, 0, "Naxxramas"},
                {0, 0, "Eisnebel"},
                {0, 0, "Kaltwindanhöhen"},
                {0, 0, "Agmars Hammer"},
                {0, 0, "Flüchtlingslager von Westwind"},
                {0, 0, "Der Vergessene Strand"},
                {0, 0, "Scharlachrote Wacht"},
                {0, 0, "Wasser von Indu'le"},
                {0, 0, "Neuherdweiler"},
                {0, 0, "Die Lichtwarte"},
                {0, 0, "Smaragddrachenschrein"},
                {0, 0, "Angrathar, Pforte des Zorns"},
                {0, 0, "Wyrmruhtempel"},
                {0, 0, "Gallgrimm"},
                {0, 0, "Die Kristallschlucht"},
            },
        },
        ["Zul'Drak"] = {
            achievementID = 1267,
            proxyLocation = {0, 0, "Zul'Drak"},
            waypoints = {
                {0, 0, "Gundrak"},
                {0, 0, "Amphitheater der Agonie"},
                {0, 0, "Altar von Rhunok"},
                {0, 0, "Altar von Mam'toth"},
                {0, 0, "Zim'Torga"},
                {0, 0, "Voltarus"},
                {0, 0, "Lichtbresche"},
                {0, 0, "Felder von Drak'Sotra"},
                {0, 0, "Altar von Sseratus"},
                {0, 0, "Altar von Quetz'lun"},
                {0, 0, "Altar von Har'koa"},
                {0, 0, "Zeramas"},
                {0, 0, "Thryms Ende"},
                {0, 0, "Kolramas"},
            },
        },
        ["Kristallsangwald"] = {
            achievementID = 1457,
            proxyLocation = {0, 0, "Kristallsangwald"},
            waypoints = {
                {0, 0, "Die Azurfront"},
                {0, 0, "Sonnenhäschers Schar"},
                {0, 0, "Windläufers Warte"},
                {0, 0, "Die Violette Wacht"},
                {0, 0, "Der Versiegende Strom"},
                {0, 0, "Die Trostlosen Wälder"},
                {0, 0, "Der Große Baum"},
                {0, 0, "Unbändiges Dickicht"},
            },
        },
        ["Eiskrone"] = {
            achievementID = 1270,
            proxyLocation = {0, 0, "Eiskrone"},
            waypoints = {
                {0, 0, "Das Bombardement"},
                {0, 0, "Hafen des Ansturms"},
                {0, 0, "Die Fleischwerke"},
                {0, 0, "Sindragosas Sturz"},
                {0, 0, "Tal der Echos"},
                {0, 0, "Der Großbrand"},
                {0, 0, "Jotunheim"},
                {0, 0, "Das Schattengewölbe"},
                {0, 0, "Eiskronenzitadelle"},
                {0, 0, "Die Zerbrochene Front"},
                {0, 0, "Aldur'thar: Das Tor der Verwüstung"},
                {0, 0, "Valhalas"},
                {0, 0, "Ymirheim"},
                {0, 0, "Corp'rethar: Das Tor des Schreckens"},
                {0, 0, "Geißelholme"},
            },
        },
        ["Heulenden Fjord"] = {
            achievementID = 1263,
            proxyLocation = {0, 0, "Heulenden Fjord"},
            waypoints = {
                {0, 0, "Kamagua"},
                {0, 0, "Lager der Winterhufe"},
                {0, 0, "Hafen der Vergeltung"},
                {0, 0, "Halunkeneck"},
                {0, 0, "Gjalerbron"},
                {0, 0, "Plateau der Riesen"},
                {0, 0, "Ivalds Ruine"},
                {0, 0, "Neu-Agamand"},
                {0, 0, "Siechende Lichtung"},
                {0, 0, "Westwacht"},
                {0, 0, "Quälheim"},
                {0, 0, "Kaldrosinsel"},
                {0, 0, "Apothekerlager"},
                {0, 0, "Das Stählerne Tor"},
                {0, 0, "Niffelvar"},
                {0, 0, "Glutstätte"},
                {0, 0, "Fort Wildervar"},
                {0, 0, "Halgrind"},
                {0, 0, "Skorn"},
                {0, 0, "Burg Utgarde"},
                {0, 0, "Baelguns Ausgrabungsstätte"},
            },
        },
        ["Grizzlyhügel"] = {
            achievementID = 1266,
            proxyLocation = {0, 0, "Grizzlyhügel"},
            waypoints = {
                {0, 0, "Burg Siegeswall"},
                {0, 0, "Ruinen von Drakil'jin"},
                {0, 0, "Granitquell"},
                {0, 0, "Schrein des Grollfangs"},
                {0, 0, "Venturebucht"},
                {0, 0, "Ammertannhütte"},
                {0, 0, "Camp Oneqwah"},
                {0, 0, "Feste Drak'Tharon"},
                {0, 0, "Dun Argol"},
                {0, 0, "Grauschlund"},
                {0, 0, "Thor Modan"},
                {0, 0, "Voldrune"},
                {0, 0, "Holzfällerposten Blauhimmel"},
                {0, 0, "Lager der Westfallbrigade"},
            },
        },
        ["das Sholazarbecken"] = {
            achievementID = 1268,
            proxyLocation = {0, 0, "das Sholazarbecken"},
            waypoints = {
                {0, 0, "Flussnabel"},
                {0, 0, "Die Mooslichtsäule"},
                {0, 0, "Hort der Schöpfer"},
                {0, 0, "Baldachin der Regenrufer"},
                {0, 0, "Die Lawine"},
                {0, 0, "Kartaks Stellung"},
                {0, 0, "Das Wilde Dickicht"},
                {0, 0, "Warte der Schöpfer"},
                {0, 0, "Die Sonnenstrahlsäule"},
                {0, 0, "Die Lebensblutsäule"},
                {0, 0, "Die Schimmersäule"},
                {0, 0, "Das Sturmherrenschelf"},
            },
        },
        ["Sturmgipfel"] = {
            achievementID = 1269,
            proxyLocation = {0, 0, "Sturmgipfel"},
            waypoints = {
                {0, 0, "Brunnhildar"},
                {0, 0, "Dun Niffelem"},
                {0, 0, "Valkyrion"},
                {0, 0, "Funksockels Minenfeld"},
                {0, 0, "Tempel des Lebens"},
                {0, 0, "Donnerfall"},
                {0, 0, "Die Verschneiten Ebenen"},
                {0, 0, "Eisfestung"},
                {0, 0, "Narvirs Wiege"},
                {0, 0, "Bors Atem"},
                {0, 0, "Terrasse der Schöpfer"},
                {0, 0, "Maschine der Schöpfer"},
                {0, 0, "Ulduar"},
                {0, 0, "Tempel der Stürme"},
                {0, 0, "Garms Bann"},
                {0, 0, "Nidavelir"},
            },
        },
    }, -- Wrath of the Lich King
    ["Pandaria"] = {
        ["Jadewald"] = {
            achievementID = 6351,
            proxyLocation = {0, 0, "Jadewald"},
            waypoints = {
                {0, 0, "Tiankloster"},
                {0, 0, "Pavillon des Träumers"},
                {0, 0, "Perlsee"},
                {0, 0, "Grünsteinbruch"},
                {0, 0, "Lager Nuka-Nuka"},
                {0, 0, "Das Schlangenherz"},
                {0, 0, "Tempel der Jadeschlange"},
                {0, 0, "Garrosh'ar"},
                {0, 0, "Honigtau"},
                {0, 0, "Morgenblüte"},
                {0, 0, "Omen des Kaisers"},
                {0, 0, "Flotschhügel"},
                {0, 0, "Obstgarten Nektarhauch"},
                {0, 0, "Terrasse der Zehn Donner"},
                {0, 0, "Schlingschwanzgruben"},
                {0, 0, "Das Arboretum"},
                {0, 0, "Windwärtsinsel"},
            },
        },
        ["Krasarangwildnis"] = {
            achievementID = 6975,
            proxyLocation = {0, 0, "Krasarangwildnis"},
            waypoints = {
                {0, 0, "Anlegestelle der Angler"},
                {0, 0, "Der Dojani"},
                {0, 0, "Krasarangbucht"},
                {0, 0, "Nayelilagune"},
                {0, 0, "Ruinen von Dojan"},
                {0, 0, "Tempel des Roten Kranichs"},
                {0, 0, "Der Verbotene Dschungel"},
                {0, 0, "Unga Ingu"},
                {0, 0, "Chi-Jis Wiege"},
                {0, 0, "Fallsang"},
                {0, 0, "Die Krasariruinen"},
                {0, 0, "Refugium der Kranichschwingen"},
                {0, 0, "Ruinen von Korja"},
                {0, 0, "Die Tiefwildnis"},
                {0, 0, "Die Südlichen Inseln"},
                {0, 0, "Zhus Wacht"},
            },
        },
        ["Tonlongsteppe"] = {
            achievementID = 6977,
            proxyLocation = {0, 0, "Tonlongsteppe"},
            waypoints = {
                {0, 0, "Gao-Ran-Front"},
                {0, 0, "Rensais Wachposten"},
                {0, 0, "Streitlager Osul"},
                {0, 0, "Shado-Pan-Garnison"},
                {0, 0, "Sik'vess"},
                {0, 0, "Die Sumpfbinsen"},
                {0, 0, "Kri'vess"},
                {0, 0, "Niuzaotempel"},
                {0, 0, "Haderzwinge"},
                {0, 0, "Shan'ze Dao"},
                {0, 0, "Sra'vess"},
            },
        },
        ["das Tal der Ewigen Blüten"] = {
            achievementID = 6979,
            proxyLocation = {0, 0, "das Tal der Ewigen Blüten"},
            waypoints = {
                {0, 0, "Guo-Lai-Ruinen"},
                {0, 0, "Mogu'shanpalast"},
                {0, 0, "Die Goldene Treppe"},
                {0, 0, "Die Goldene Pagode"},
                {0, 0, "Schrein der Zwei Monde"},
                {0, 0, "Die Fünf Schwestern"},
                {0, 0, "Nebelhauch"},
                {0, 0, "Garnison der Untergehenden Sonne"},
                {0, 0, "Schrein der Sieben Sterne"},
                {0, 0, "Tu-Shen-Begräbnisstätte"},
                {0, 0, "Weißblütensee"},
            },
        },
        ["das Tal der Vier Winde"] = {
            achievementID = 6969,
            proxyLocation = {0, 0, "das Tal der Vier Winde"},
            waypoints = {
                {0, 0, "Die Windschneide"},
                {0, 0, "Der Goldfächer"},
                {0, 0, "Halbhügel"},
                {0, 0, "Kunzen"},
                {0, 0, "Nesingwarys Safari"},
                {0, 0, "Teiche der Reinheit"},
                {0, 0, "Seidenfelder"},
                {0, 0, "Brauerei Sturmbräu"},
                {0, 0, "Gehöft Donnerfuß"},
                {0, 0, "Staubrückenklamm"},
                {0, 0, "Die Kaiserliche Kornkammer"},
                {0, 0, "Steinpflug"},
                {0, 0, "Trübtrunks Schenke"},
                {0, 0, "Paoquansenke"},
                {0, 0, "Polternde Terrasse"},
                {0, 0, "Singende Marschen"},
                {0, 0, "Das Kernland"},
                {0, 0, "Zhus Abstieg"},
            },
        },
        ["Kun-Lai-Gipfel"] = {
            achievementID = 6976,
            proxyLocation = {0, 0, "Kun-Lai-Gipfel"},
            waypoints = {
                {0, 0, "Binan"},
                {0, 0, "Tor der Himmlischen Erhabenen"},
                {0, 0, "Kotaspitze"},
                {0, 0, "Der Nimmerlaya"},
                {0, 0, "Gipfel der Ruhe"},
                {0, 0, "Tempel des Weißen Tigers"},
                {0, 0, "Das Tal der Kaiser"},
                {0, 0, "Feuerzweigwinkel"},
                {0, 0, "Insel der Abrechnung"},
                {0, 0, "Mogujia"},
                {0, 0, "Gehöft Moschuspranke"},
                {0, 0, "Shado-Pan-Kloster"},
                {0, 0, "Der Jutepfad"},
                {0, 0, "Zouchin"},
            },
        },
        ["Schreckensöde"] = {
            achievementID = 6978,
            proxyLocation = {0, 0, "Schreckensöde"},
            waypoints = {
                {0, 0, "Das Herz der Angst"},
                {0, 0, "Kypari Vor"},
                {0, 0, "Rikkitun"},
                {0, 0, "Terrasse von Gurthan"},
                {0, 0, "Die Gelege von Shek'zeer"},
                {0, 0, "Windegehölz"},
                {0, 0, "Klaxxi'vess"},
                {0, 0, "Kypari Zar"},
                {0, 0, "Tropfs Wagnis"},
                {0, 0, "Der Salzige Schlick"},
                {0, 0, "Abendlichtbraugarten"},
                {0, 0, "Zan'vess"},
            },
        },
    }, -- Mists of Pandaria
    ["Verheerten Inseln"] = {
        ["Azsuna"] = {
            achievementID = 10665,
            proxyLocation = {0, 0, "Azsuna"},
            waypoints = {
                {0, 0, "Faronaar"},
                {0, 0, "Die Grüne Schneise"},
                {0, 0, "Das Hochland von Llothien"},
                {0, 0, "Nar'thalas"},
                {0, 0, "Zerschlagenes Sanktum"},
                {0, 0, "Die Leyruinen von Zarkhenar"},
                {0, 0, "Der Teufelsfeuervorstoß"},
                {0, 0, "Die Insel der Behüter"},
                {0, 0, "Verlorener Obstgarten"},
                {0, 0, "Ozeanus' Bucht"},
                {0, 0, "Tempel der Lichter"},
            },
        },
        ["Hochberg"] = {
            achievementID = 10667,
            proxyLocation = {0, 0, "Hochberg"},
            waypoints = {
                {0, 0, "Das Blutjagdhochland"},
                {0, 0, "Frosthufwacht"},
                {0, 0, "Der Hort des Nachtwächters"},
                {0, 0, "Die Flusswindung"},
                {0, 0, "Die Schiffbruchgrotte"},
                {0, 0, "Die Steinhufwacht"},
                {0, 0, "Donnertotem"},
                {0, 0, "Die Blinde Marsch"},
                {0, 0, "Die Eisenhornenklave"},
                {0, 0, "Das Kieferfelsbecken"},
                {0, 0, "Das Beinharte Riff"},
                {0, 0, "Das Himmelshorn"},
                {0, 0, "Die Sylvanfälle"},
                {0, 0, "Die Volltrefferhütte"},
            },
        },
        ["Suramar"] = {
            achievementID = 10669,
            proxyLocation = {0, 0, "Suramar"},
            waypoints = {
                {0, 0, "Das Zinnobertal"},
                {0, 0, "Falanaar"},
                {0, 0, "Die Große Promenade"},
                {0, 0, "Die Mondwachenfestung"},
                {0, 0, "Die Ruinen von Elune'eth"},
                {0, 0, "Tel'anor"},
                {0, 0, "Das Purpurdickicht"},
                {0, 0, "Die Teufelsseelenbastion"},
                {0, 0, "Jandvik"},
                {0, 0, "Die Mondwisperschlucht"},
                {0, 0, "Suramar"},
            },
        },
        ["Val'sharah"] = {
            achievementID = 10666,
            proxyLocation = {0, 0, "Val'sharah"},
            waypoints = {
                {0, 0, "Andu'talah"},
                {0, 0, "Bradenbach"},
                {0, 0, "Das Dämmernde Riff"},
                {0, 0, "Lorlathil"},
                {0, 0, "Das Mondklauental"},
                {0, 0, "Das Schwelhautdickicht"},
                {0, 0, "Thas'talah"},
                {0, 0, "Die Rabenwehr"},
                {0, 0, "Der Hain der Träume"},
                {0, 0, "Der Hain des Cenarius"},
                {0, 0, "Der Nebelgrund"},
                {0, 0, "Shala'nir"},
                {0, 0, "Der Tempel von Elune"},
            },
        },
        ["Sturmheim"] = {
            achievementID = 10668,
            proxyLocation = {0, 0, "Sturmheim"},
            waypoints = {
                {0, 0, "Aggramars Kammer"},
                {0, 0, "Das Schreckensflutufer"},
                {0, 0, "Die Graue Wacht"},
                {0, 0, "Haustvald"},
                {0, 0, "Der Schlund von Nashal"},
                {0, 0, "Nastrondir"},
                {0, 0, "Der Runenwald"},
                {0, 0, "Skold-Ashil"},
                {0, 0, "Die Krallenrast"},
                {0, 0, "Valdisdall"},
                {0, 0, "Die Schwarzschnabelwarte"},
                {0, 0, "Dreyrgrot"},
                {0, 0, "Die Pforte der Tapferkeit"},
                {0, 0, "Hrydshal"},
                {0, 0, "Morheim"},
                {0, 0, "Die Wächterinsel"},
                {0, 0, "Die Schildruhinsel"},
                {0, 0, "Die Sturmkuppe"},
                {0, 0, "Der Wellenskornhafen"},
                {0, 0, "Die Weinenden Klippen"},
            },
        },
    }, -- Legion
    -- Continents dictionary ...
    ["Continents"] = {
        ["Eastern Kingdoms"] = "Östlichen Königreiche",
        ["Outland"] = "Scherbenwelt",
        ["Cataclysm"] = "Kataklysmus",
        ["Draenor"] = "Draenor",
        ["Battle for Azeroth"] = "Schlacht um Azeroth", -- Zandalar and Kul Tiras
        ["Kalimdor"] = "Kalimdor",
        ["Northrend"] = "Nordends",
        ["Pandaria"] = "Pandaria",
        ["Broken Isles"] = "Verheerten Inseln",
    }
}