Localization = Localization or {}

Localization["enUS"] = {
    ["Eastern Kingdoms"] = {
        ["Elwynn Forest"] = {
            achievementID = 776,
            proxyLocation = {0, 0, "Elwynn Forest"},
            waypoints = {
                {0, 0, "Northshire Valley"},
                {0, 0, "Goldshire"},
                {0, 0, "Jerod's Landing"},
                {0, 0, "Brackwell Pumpkin Patch"},
                {0, 0, "Ridgepoint Tower"},
                {0, 0, "Stone Cairn Lake"},
                {0, 0, "Westbrook Garrison"},
                {0, 0, "Fargodeep Mine"},
                {0, 0, "Tower of Azora"},
                {0, 0, "Eastvale Logging Camp"},
                {0, 0, "Crystal Lake"},
            },
        },
        ["Badlands"] = {
            achievementID = 765,
            proxyLocation = {0, 0, "Badlands"},
            waypoints = {
                {0, 0, "Lethlor Ravine"},
                {0, 0, "Uldaman"},
                {0, 0, "Scar of the Worldbreaker"},
                {0, 0, "Angor Fortress"},
                {0, 0, "Bloodwatcher Point"},
                {0, 0, "Agmond's End"},
                {0, 0, "Camp Cagg"},
                {0, 0, "The Dustbowl"},
                {0, 0, "Camp Kosh"},
                {0, 0, "New Kargath"},
            },
        },
        ["Burning Steppes"] = {
            achievementID = 775,
            proxyLocation = {0, 0, "Burning Steppes"},
            waypoints = {
                {0, 0, "Dreadmaul Rock"},
                {0, 0, "Terror Wing Path"},
                {0, 0, "Ruins of Thaurissan"},
                {0, 0, "Blackrock Stronghold"},
                {0, 0, "Altar of Storms"},
                {0, 0, "Morgan's Vigil"},
                {0, 0, "Blackrock Pass"},
                {0, 0, "Black Tooth Hovel"},
                {0, 0, "The Whelping Downs"},
                {0, 0, "Blackrock Mountain"},
            },
        },
        ["Duskwood"] = {
            achievementID = 778,
            proxyLocation = {0, 0, "Duskwood"},
            waypoints = {
                {0, 0, "The Hushed Bank"},
                {0, 0, "Raven Hill"},
                {0, 0, "Vul'Gol Ogre Mound"},
                {0, 0, "The Yorgen Farmstead"},
                {0, 0, "The Rotting Orchard"},
                {0, 0, "Darkshire"},
                {0, 0, "The Darkened Bank"},
                {0, 0, "Addle's Stead"},
                {0, 0, "Raven Hill Cemetery"},
                {0, 0, "Twilight Grove"},
                {0, 0, "Brightwood Grove"},
                {0, 0, "Tranquil Gardens Cemetery"},
                {0, 0, "Manor Mistmantle"},
            },
        },
        ["Loch Modan"] = {
            achievementID = 779,
            proxyLocation = {0, 0, "Loch Modan"},
            waypoints = {
                {0, 0, "The Loch"},
                {0, 0, "Mo'grosh Stronghold"},
                {0, 0, "North Gate Pass"},
                {0, 0, "Ironband's Excavation Site"},
                {0, 0, "Thelsamar"},
                {0, 0, "Valley of Kings"},
                {0, 0, "Stonewrought Dam"},
                {0, 0, "Silver Stream Mine"},
                {0, 0, "The Farstrider Lodge"},
                {0, 0, "Grizzlepaw Ridge"},
                {0, 0, "Stonesplinter Valley"},
            },
        },
        ["Tirisfal Glades"] = {
            achievementID = 768,
            proxyLocation = {0, 0, "Tirisfal Glades"},
            waypoints = {
                {0, 0, "Deathknell"},
                {0, 0, "Agamand Mills"},
                {0, 0, "Cold Hearth Manor"},
                {0, 0, "Garren's Haunt"},
                {0, 0, "Balnir Farmstead"},
                {0, 0, "Scarlet Watch Post"},
                {0, 0, "Ruins of Lordaeron"},
                {0, 0, "The Bulwark"},
                {0, 0, "Solliden Farmstead"},
                {0, 0, "Nightmare Vale"},
                {0, 0, "Brill"},
                {0, 0, "Brightwater Lake"},
                {0, 0, "Crusader Outpost"},
                {0, 0, "Venomweb Vale"},
                {0, 0, "Scarlet Monastery Entrance"},
                {0, 0, "Calston Estate"},
            },
        },
        ["Searing Gorge"] = {
            achievementID = 774,
            proxyLocation = {0, 0, "Searing Gorge"},
            waypoints = {
                {0, 0, "Firewatch Ridge"},
                {0, 0, "Blackchar Cave"},
                {0, 0, "Grimesilt Dig Site"},
                {0, 0, "Thorium Point"},
                {0, 0, "The Cauldron"},
                {0, 0, "The Sea of Cinders"},
                {0, 0, "Dustfire Valley"},
                {0, 0, "Blackrock Mountain"},
            },
        },
        ["Ghostlands"] = {
            achievementID = 858,
            proxyLocation = {0, 0, "Ghostlands"},
            waypoints = {
                {0, 0, "Tranquillien"},
                {0, 0, "Goldenmist Village"},
                {0, 0, "Sanctum of the Moon"},
                {0, 0, "Dawnstar Spire"},
                {0, 0, "Howling Ziggurat"},
                {0, 0, "Zeb'Nowa"},
                {0, 0, "Windrunner Spire"},
                {0, 0, "Elrendar Crossing"},
                {0, 0, "Suncrown Village"},
                {0, 0, "Windrunner Village"},
                {0, 0, "Sanctum of the Sun"},
                {0, 0, "Farstrider Enclave"},
                {0, 0, "Deatholme"},
                {0, 0, "Amani Pass"},
                {0, 0, "Bleeding Ziggurat"},
                {0, 0, "Thalassian Pass"},
            },
        },
        ["The Cape of Stranglethorn"] = {
            achievementID = 4995,
            proxyLocation = {0, 0, "the Cape of Stranglethorn"},
            waypoints = {
                {0, 0, "Booty Bay"},
                {0, 0, "Gurubashi Arena"},
                {0, 0, "Jaquero Isle"},
                {0, 0, "Nek'mani Wellspring"},
                {0, 0, "Ruins of Jubuwal"},
                {0, 0, "Crystalvein Mine"},
                {0, 0, "Hardwrench Hideaway"},
                {0, 0, "Mistvale Valley"},
                {0, 0, "Ruins of Aboraz"},
                {0, 0, "The Wild Shore"},
            },
        },
        ["The Hinterlands"] = {
            achievementID = 773,
            proxyLocation = {0, 0, "The Hinterlands"},
            waypoints = {
                {0, 0, "Aerie Peak"},
                {0, 0, "Zun'watha"},
                {0, 0, "Shadra'Alor"},
                {0, 0, "Agol'watha"},
                {0, 0, "The Altar of Zul"},
                {0, 0, "Skulk Rock"},
                {0, 0, "Jintha'Alor"},
                {0, 0, "Plaguemist Ravine"},
                {0, 0, "Quel'Danil Lodge"},
                {0, 0, "Valorwind Lake"},
                {0, 0, "The Creeping Ruin"},
                {0, 0, "Seradane"},
                {0, 0, "Shaol'watha"},
                {0, 0, "The Overlook Cliffs"},
            },
        },
        ["Wetlands"] = {
            achievementID = 841,
            proxyLocation = {0, 0, "Wetlands"},
            waypoints = {
                {0, 0, "Menethil Harbor"},
                {0, 0, "Bluegill Marsh"},
                {0, 0, "Sundown Marsh"},
                {0, 0, "Ironbeard's Tomb"},
                {0, 0, "Angerfang Encampment"},
                {0, 0, "Greenwarden's Grove"},
                {0, 0, "Direforge Hill"},
                {0, 0, "Slabchisel's Survey"},
                {0, 0, "Black Channel Marsh"},
                {0, 0, "Whelgar's Excavation Site"},
                {0, 0, "Saltspray Glen"},
                {0, 0, "Dun Modr"},
                {0, 0, "Thelgen Rock"},
                {0, 0, "Mosshide Fen"},
                {0, 0, "Dun Algaz"},
                {0, 0, "Raptor Ridge"},
            },
        },
        ["Western Plaguelands"] = {
            achievementID = 770,
            proxyLocation = {0, 0, "Western Plaguelands"},
            waypoints = {
                {0, 0, "Darrowmere Lake"},
                {0, 0, "Sorrow Hill"},
                {0, 0, "The Bulwark"},
                {0, 0, "Dalson's Farm"},
                {0, 0, "Northridge Lumber Camp"},
                {0, 0, "Redpine Dell"},
                {0, 0, "The Weeping Cave"},
                {0, 0, "Caer Darrow"},
                {0, 0, "Andorhal"},
                {0, 0, "Felstone Field"},
                {0, 0, "The Writhing Haunt"},
                {0, 0, "Hearthglen"},
                {0, 0, "Gahrron's Withering"},
                {0, 0, "Thondroril River"},
            },
        },
        ["Isle of Quel'Danas"] = {
            achievementID = 868,
            proxyLocation = {0, 0, "Isle of Quel'Danas"},
            waypoints = {
            },
        },
        ["Arathi Highlands"] = {
            achievementID = 761,
            proxyLocation = {0, 0, "Arathi Highlands"},
            waypoints = {
                {0, 0, "Circle of West Binding"},
                {0, 0, "Boulder'gor"},
                {0, 0, "Stromgarde Keep"},
                {0, 0, "Circle of Inner Binding"},
                {0, 0, "Boulderfist Hall"},
                {0, 0, "Circle of Outer Binding"},
                {0, 0, "Go'Shek Farm"},
                {0, 0, "Circle of East Binding"},
                {0, 0, "Northfold Manor"},
                {0, 0, "Galen's Fall"},
                {0, 0, "Faldir's Cove"},
                {0, 0, "Thandol Span"},
                {0, 0, "Refuge Pointe"},
                {0, 0, "Witherbark Village"},
                {0, 0, "Dabyrie's Farmstead"},
                {0, 0, "Hammerfall"},
            },
        },
        ["Blasted Lands"] = {
            achievementID = 766,
            proxyLocation = {0, 0, "Blasted Lands"},
            waypoints = {
                {0, 0, "Dreadmaul Hold"},
                {0, 0, "Nethergarde Keep"},
                {0, 0, "The Dark Portal"},
                {0, 0, "Dreadmaul Post"},
                {0, 0, "Rise of the Defiler"},
                {0, 0, "Sunveil Excursion"},
                {0, 0, "The Red Reaches"},
                {0, 0, "Nethergarde Supply Camps"},
                {0, 0, "Serpent's Coil"},
                {0, 0, "Altar of Storms"},
                {0, 0, "The Tainted Scar"},
                {0, 0, "Shattershore"},
                {0, 0, "Surwich"},
                {0, 0, "The Tainted Forest"},
            },
        },
        ["Dun Morogh"] = {
            achievementID = 627,
            proxyLocation = {0, 0, "Dun Morogh"},
            waypoints = {
                {0, 0, "Coldridge Pass"},
                {0, 0, "Frostmane Front"},
                {0, 0, "Ironforge Airfield"},
                {0, 0, "Kharanos"},
                {0, 0, "Amberstill Ranch"},
                {0, 0, "Gol'Bolar Quarry"},
                {0, 0, "Frostmane Hold"},
                {0, 0, "Gates of Ironforge"},
                {0, 0, "Coldridge Valley"},
                {0, 0, "New Tinkertown"},
                {0, 0, "Shimmer Ridge"},
                {0, 0, "The Tundrid Hills"},
                {0, 0, "Helm's Bed Lake"},
                {0, 0, "North Gate Outpost"},
                {0, 0, "Iceflow Lake"},
            },
        },
        ["Hillsbrad Foothills"] = {
            achievementID = 772,
            proxyLocation = {0, 0, "Hillsbrad Foothills"},
            waypoints = {
                {0, 0, "Azurelode Mine"},
                {0, 0, "Corrahn's Dagger"},
                {0, 0, "Chillwind Point"},
                {0, 0, "Dandred's Fold"},
                {0, 0, "Dun Garok"},
                {0, 0, "Gallows' Corner"},
                {0, 0, "Growless Cave"},
                {0, 0, "Nethander Stead"},
                {0, 0, "Ruins of Alterac"},
                {0, 0, "Slaughter Hollow"},
                {0, 0, "Southpoint Gate"},
                {0, 0, "Tarren Mill"},
                {0, 0, "The Sludge Fields"},
                {0, 0, "Brazie Farmstead"},
                {0, 0, "Crushridge Hold"},
                {0, 0, "Dalaran Crater"},
                {0, 0, "Darrow Hill"},
                {0, 0, "Durnholde Keep"},
                {0, 0, "Gavin's Naze"},
                {0, 0, "Misty Shore"},
                {0, 0, "Purgation Isle"},
                {0, 0, "Ruins of Southshore"},
                {0, 0, "Sofera's Naze"},
                {0, 0, "Strahnbrad"},
                {0, 0, "The Headland"},
                {0, 0, "The Uplands"},
            },
        },
        ["Redridge Mountains"] = {
            achievementID = 780,
            proxyLocation = {0, 0, "Redridge Mountains"},
            waypoints = {
                {0, 0, "Lakeshire"},
                {0, 0, "Three Corners"},
                {0, 0, "Redridge Canyons"},
                {0, 0, "Stonewatch Falls"},
                {0, 0, "Render's Camp"},
                {0, 0, "Galardell Valley"},
                {0, 0, "Camp Everstill"},
                {0, 0, "Lake Everstill"},
                {0, 0, "Lakeridge Highway"},
                {0, 0, "Alther's Mill"},
                {0, 0, "Render's Valley"},
                {0, 0, "Stonewatch Keep"},
                {0, 0, "Shalewind Canyon"},
            },
        },
        ["Eversong Woods"] = {
            achievementID = 859,
            proxyLocation = {0, 0, "Eversong Woods"},
            waypoints = {
                {34, 23, "Sunstrider Isle"},
                {0, 0, "West Sanctum"},
                {0, 0, "North Sanctum"},
                {0, 0, "Farstrider Retreat"},
                {0, 0, "Duskwither Grounds"},
                {0, 0, "The Living Wood"},
                {0, 0, "The Scorched Grove"},
                {0, 0, "Azurebreeze Coast"},
                {0, 0, "Goldenbough Pass"},
                {0, 0, "Runestone Falithas"},
                {0, 0, "Saltheril's Haven"},
                {0, 0, "Thuron's Livery"},
                {0, 0, "Zeb'Watha"},
                {0, 0, "Ruins of Silvermoon"},
                {0, 0, "Sunsail Anchorage"},
                {0, 0, "East Sanctum"},
                {0, 0, "Stillwhisper Pond"},
                {0, 0, "Fairbreeze Village"},
                {0, 0, "Tor'Watha"},
                {0, 0, "Silvermoon City"},
                {0, 0, "Elrendar Falls"},
                {0, 0, "Lake Elrendar"},
                {0, 0, "Runestone Shan'dor"},
                {0, 0, "Golden Strand"},
                {0, 0, "Tranquil Shore"},
            },
        },
        ["Silverpine Forest"] = {
            achievementID = 769,
            proxyLocation = {0, 0, "Silverpine Forest"},
            waypoints = {
                {0, 0, "The Battlefront"},
                {0, 0, "The Forsaken Front"},
                {0, 0, "North Tide's Beachhead"},
                {0, 0, "Valgan's Field"},
                {0, 0, "Deep Elem Mine"},
                {0, 0, "Ambermill"},
                {0, 0, "Forsaken High Command"},
                {0, 0, "Forsaken Rear Guard"},
                {0, 0, "The Decrepit Fields"},
                {0, 0, "The Skittering Dark"},
                {0, 0, "Fenris Isle"},
                {0, 0, "The Sepulcher"},
                {0, 0, "Olsen's Farthing"},
                {0, 0, "Shadowfang Keep"},
                {0, 0, "North Tide's Run"},
            },
        },
        ["Northern Stranglethorn"] = {
            achievementID = 781,
            proxyLocation = {0, 0, "Northern Stranglethorn"},
            waypoints = {
                {0, 0, "Grom'gol Base Camp"},
                {0, 0, "Bambala"},
                {0, 0, "Zuuldaia Ruins"},
                {0, 0, "Rebel Camp"},
                {0, 0, "Kal'ai Ruins"},
                {0, 0, "Mosh'Ogg Ogre Mound"},
                {0, 0, "Bal'lal Ruins"},
                {0, 0, "Ruins of Zul'Kunda"},
                {0, 0, "Balia'mah Ruins"},
                {0, 0, "Fort Livingston"},
                {0, 0, "Nesingwary's Expedition"},
                {0, 0, "Kurzen's Compound"},
                {0, 0, "Mizjah Ruins"},
                {0, 0, "Lake Nazferiti"},
                {0, 0, "The Vile Reef"},
                {0, 0, "Zul'Gurub"},
            },
        },
        ["Swamp of Sorrows"] = {
            achievementID = 782,
            proxyLocation = {0, 0, "Swamp of Sorrows"},
            waypoints = {
                {0, 0, "Misty Valley"},
                {0, 0, "Splinterspear Junction"},
                {0, 0, "Stonard"},
                {0, 0, "Stagalbog"},
                {0, 0, "Bogpaddle"},
                {0, 0, "Purespring Cavern"},
                {0, 0, "The Harborage"},
                {0, 0, "The Shifting Mire"},
                {0, 0, "Pool of Tears"},
                {0, 0, "Sorrowmurk"},
                {0, 0, "Misty Reed Strand"},
                {0, 0, "Marshtide Watch"},
            },
        },
        ["Westfall"] = {
            achievementID = 802,
            proxyLocation = {0, 0, "Westfall"},
            waypoints = {
                {0, 0, "Sentinel Hill"},
                {0, 0, "Furlbrow's Pumpkin Farm"},
                {0, 0, "Jangolode Mine"},
                {0, 0, "The Dead Acre"},
                {0, 0, "Alexston Farmstead"},
                {0, 0, "The Dagger Hills"},
                {0, 0, "The Dust Plains"},
                {0, 0, "Saldean's Farm"},
                {0, 0, "The Jansen Stead"},
                {0, 0, "The Molsen Farm"},
                {0, 0, "Moonbrook"},
                {0, 0, "Demont's Place"},
                {0, 0, "The Raging Chasm"},
            },
        },
        ["Deadwind Pass"] = {
            achievementID = 777,
            proxyLocation = {0, 0, "Deadwind Pass"},
            waypoints = {
                {0, 0, "Deadman's Crossing"},
                {0, 0, "Karazhan"},
                {0, 0, "The Vice"},
            },
        },
        ["Eastern Plaguelands"] = {
            achievementID = 771,
            proxyLocation = {0, 0, "Eastern Plaguelands"},
            waypoints = {
                {0, 0, "Thondroril River"},
                {0, 0, "The Undercroft"},
                {0, 0, "The Fungal Vale"},
                {0, 0, "Pestilent Scar"},
                {0, 0, "Lake Mereldar"},
                {0, 0, "Light's Hope Chapel"},
                {0, 0, "The Noxious Glade"},
                {0, 0, "Blackwood Lake"},
                {0, 0, "Zul'Mashar"},
                {0, 0, "Quel'Lithien Lodge"},
                {0, 0, "Plaguewood"},
                {0, 0, "Ruins of the Scarlet Enclave"},
                {0, 0, "The Marris Stead"},
                {0, 0, "Crown Guard Tower"},
                {0, 0, "Darrowshire"},
                {0, 0, "Corin's Crossing"},
                {0, 0, "Tyr's Hand"},
                {0, 0, "The Infectis Scar"},
                {0, 0, "Eastwall Tower"},
                {0, 0, "Northdale"},
                {0, 0, "Northpass Tower"},
                {0, 0, "Terrordale"},
                {0, 0, "Stratholme"},
            },
        },
    }, -- World of Warcraft (Vanilla)
    ["Outland"] = {
        ["Hellfire Peninsula"] = {
            achievementID = 862,
            proxyLocation = {0, 0, "Hellfire Peninsula"},
            waypoints = {
                {0, 0, "The Stair of Destiny"},
                {0, 0, "Falcon Watch"},
                {0, 0, "Honor Hold"},
                {0, 0, "Pools of Aggonar"},
                {0, 0, "Temple of Telhamat"},
                {0, 0, "Thrallmar"},
                {0, 0, "Zeth'Gor"},
                {0, 0, "Fallen Sky Ridge"},
                {0, 0, "The Warp Fields"},
                {0, 0, "Expedition Armory"},
                {0, 0, "Hellfire Citadel"},
                {0, 0, "Mag'har Post"},
                {0, 0, "Ruins of Sha'naar"},
                {0, 0, "The Legion Front"},
                {0, 0, "Throne of Kil'jaeden"},
                {0, 0, "Den of Haal'esh"},
                {0, 0, "Void Ridge"},
                {0, 0, "Forge Camp: Mageddon"},
            },
        },
        ["Terokkar Forest"] = {
            achievementID = 867,
            proxyLocation = {0, 0, "Terokkar Forest"},
            waypoints = {
                {0, 0, "Bleeding Hollow Ruins"},
                {0, 0, "Cenarion Thicket"},
                {0, 0, "Grangol'var Village"},
                {0, 0, "Tuurem"},
                {0, 0, "Raastok Glade"},
                {0, 0, "Razorthorn Shelf"},
                {0, 0, "Auchenai Grounds"},
                {0, 0, "Refugee Caravan"},
                {0, 0, "Shadow Tomb"},
                {0, 0, "Veil Rhaze"},
                {0, 0, "Skettis"},
                {0, 0, "Allerian Stronghold"},
                {0, 0, "Firewing Point"},
                {0, 0, "Stonebreaker Hold"},
                {0, 0, "Shattrath City"},
                {0, 0, "The Barrier Hills"},
                {0, 0, "Bonechewer Ruins"},
                {0, 0, "Carrion Hill"},
                {0, 0, "Ring of Observance"},
                {0, 0, "Derelict Caravan"},
                {0, 0, "Writhing Mound"},
            },
        },
        ["Blade's Edge Mountains"] = {
            achievementID = 865,
            proxyLocation = {0, 0, "Blade's Edge Mountains"},
            waypoints = {
                {0, 0, "Bash'ir Landing"},
                {0, 0, "Bladespire Hold"},
                {0, 0, "Bloodmaul Outpost"},
                {0, 0, "Circle of Blood"},
                {0, 0, "Forge Camp: Anger"},
                {0, 0, "Forge Camp: Wrath"},
                {0, 0, "Gruul's Lair"},
                {0, 0, "Mok'Nathal Village"},
                {0, 0, "Razor Ridge"},
                {0, 0, "Skald"},
                {0, 0, "Crystal Spine"},
                {0, 0, "Veil Lashh"},
                {0, 0, "Vekhaar Stand"},
                {0, 0, "Bladed Gulch"},
                {0, 0, "Bloodmaul Camp"},
                {0, 0, "Broken Wilds"},
                {0, 0, "Death's Door"},
                {0, 0, "Forge Camp: Terror"},
                {0, 0, "Grishnath"},
                {0, 0, "Jagged Ridge"},
                {0, 0, "Raven's Wood"},
                {0, 0, "Ruuan Weald"},
                {0, 0, "Sylvanaar"},
                {0, 0, "Thunderlord Stronghold"},
                {0, 0, "Veil Ruuan"},
                {0, 0, "Vortex Summit"},
            },
        },
        ["Shadowmoon Valley"] = {
            achievementID = 864,
            proxyLocation = {0, 0, "Shadowmoon Valley"},
            waypoints = {
                {0, 0, "Coilskar Point"},
                {0, 0, "Legion Hold"},
                {0, 0, "Shadowmoon Village"},
                {0, 0, "The Deathforge"},
                {0, 0, "Warden's Cage"},
                {0, 0, "Altar of Sha'tar"},
                {0, 0, "Netherwing Fields"},
                {0, 0, "Eclipse Point"},
                {0, 0, "Netherwing Ledge"},
                {0, 0, "The Black Temple"},
                {0, 0, "The Hand of Gul'dan"},
                {0, 0, "Wildhammer Stronghold"},
                {0, 0, "Illidari Point"},
            },
        },
        ["Zangarmarsh"] = {
            achievementID = 863,
            proxyLocation = {0, 0, "Zangarmarsh"},
            waypoints = {
                {0, 0, "Cenarion Refuge"},
                {0, 0, "Feralfen Village"},
                {0, 0, "Marshlight Lake"},
                {0, 0, "Telredor"},
                {0, 0, "The Lagoon"},
                {0, 0, "Umbrafen Village"},
                {0, 0, "Ango'rosh Stronghold"},
                {0, 0, "Orebor Harborage"},
                {0, 0, "Zabra'jin"},
                {0, 0, "Ango'rosh Grounds"},
                {0, 0, "Hewn Bog"},
                {0, 0, "Quagg Ridge"},
                {0, 0, "The Dead Mire"},
                {0, 0, "Twin Spire Ruins"},
                {0, 0, "Sporeggar"},
                {0, 0, "Bloodscale Grounds"},
                {0, 0, "The Spawning Glen"},
                {0, 0, "Darkcrest Shore"},
            },
        },
        ["Nagrand"] = {
            achievementID = 866,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Forge Camp: Fear"},
                {0, 0, "Halaa"},
                {0, 0, "Laughing Skull Ruins"},
                {0, 0, "Sunspring Post"},
                {0, 0, "The Ring of Trials"},
                {0, 0, "Warmaul Hill"},
                {0, 0, "Clan Watch"},
                {0, 0, "Southwind Cleft"},
                {0, 0, "Windyreed Pass"},
                {0, 0, "Zangar Ridge"},
                {0, 0, "Garadar"},
                {0, 0, "Kil'sorrow Fortress"},
                {0, 0, "Spirit Fields"},
                {0, 0, "Telaar"},
                {0, 0, "Throne of the Elements"},
                {0, 0, "Burning Blade Ruins"},
                {0, 0, "Forge Camp: Hate"},
                {0, 0, "The Twilight Ridge"},
                {0, 0, "Windyreed Village"},
            },
        },
        ["Netherstorm"] = {
            achievementID = 843,
            proxyLocation = {0, 0, "Netherstorm"},
            waypoints = {
                {0, 0, "Area 52"},
                {0, 0, "Manaforge Coruu"},
                {0, 0, "Manaforge Ara"},
                {0, 0, "Ruins of Farahlon"},
                {0, 0, "The Heap"},
                {0, 0, "Celestial Ridge"},
                {0, 0, "Netherstone"},
                {0, 0, "Sunfury Hold"},
                {0, 0, "Gyro-Plank Bridge"},
                {0, 0, "Ethereum Staging Grounds"},
                {0, 0, "Forge Base: Oblivion"},
                {0, 0, "Manaforge B'naar"},
                {0, 0, "Manaforge Duro"},
                {0, 0, "Manaforge Ultris"},
                {0, 0, "Tempest Keep"},
                {0, 0, "Arklon Ruins"},
                {0, 0, "Kirin'Var Village"},
                {0, 0, "Ruins of Enkaat"},
                {0, 0, "The Stormspire"},
                {0, 0, "Eco-Dome Farfield"},
                {0, 0, "Socrethar's Seat"},
                {0, 0, "Eco-Dome Midrealm"},
            },
        },
    }, -- The Burning Crusade
    ["Cataclysm"] = {
        ["Hyjal"] = {
            achievementID = 4863,
            proxyLocation = {0, 0, "Hyjal"},
            waypoints = {
                {0, 0, "Rim of the World"},
                {0, 0, "Ashen Lake"},
                {0, 0, "Gates of Sothann"},
                {0, 0, "Sethria's Roost"},
                {0, 0, "The Flamewake"},
                {0, 0, "The Throne of Flame"},
                {0, 0, "The Circle of Cinders"},
                {0, 0, "Darkwhisper Gorge"},
                {0, 0, "Nordrassil"},
                {0, 0, "Shrine of Goldrinn"},
                {0, 0, "The Scorched Plain"},
            },
        },
        ["Deepholm"] = {
            achievementID = 4864,
            proxyLocation = {0, 0, "Deepholm"},
            waypoints = {
                {0, 0, "Deathwing's Fall"},
                {0, 0, "Needlerock Slag"},
                {0, 0, "Storm's Fury Wreckage"},
                {0, 0, "The Pale Roost"},
                {0, 0, "The Quaking Fields"},
                {0, 0, "Masters' Gate"},
                {0, 0, "Needlerock Chasm"},
                {0, 0, "Stonehearth"},
                {0, 0, "Temple of Earth"},
                {0, 0, "Therazane's Throne"},
                {0, 0, "Twilight Overlook"},
                {0, 0, "Crimson Expanse"},
            },
        },
        ["Twilight Highlands"] = {
            achievementID = 4866,
            proxyLocation = {0, 0, "Twilight Highlands"},
            waypoints = {
                {0, 0, "Bloodgulch"},
                {0, 0, "Crushblow"},
                {0, 0, "Dragonmaw Port"},
                {0, 0, "Firebeard's Patrol"},
                {0, 0, "Gorshak War Camp"},
                {0, 0, "Highbank"},
                {0, 0, "Humboldt Conflagration"},
                {0, 0, "Obsidian Forest"},
                {0, 0, "Slithering Cove"},
                {0, 0, "The Gullet"},
                {0, 0, "The Twilight Breach"},
                {0, 0, "Twilight Shore"},
                {0, 0, "Victor's Point"},
                {0, 0, "The Maw of Madness"},
                {0, 0, "Crucible of Carnage"},
                {0, 0, "Dragonmaw Pass"},
                {0, 0, "Dunwald Ruins"},
                {0, 0, "Glopgut's Hollow"},
                {0, 0, "Grim Batol"},
                {0, 0, "Highland Forest"},
                {0, 0, "Kirthaven"},
                {0, 0, "Ruins of Drakgor"},
                {0, 0, "The Black Breach"},
                {0, 0, "The Krazzworks"},
                {0, 0, "Thundermar"},
                {0, 0, "Vermillion Redoubt"},
                {0, 0, "Wyrms' Bend"},
            },
        },
        ["Vashj'ir"] = {
            achievementID = 4825,
            proxyLocation = {0, 0, "Vashj'ir"},
            waypoints = {
                {0, 0, "Abandoned Reef"},
                {0, 0, "Underlight Canyon"},
                {0, 0, "Korthun's End"},
                {0, 0, "Seabrush"},
                {0, 0, "Glimmerdeep Gorge"},
                {0, 0, "Gurboggle's Ledge"},
                {0, 0, "Seafarer's Tomb"},
                {0, 0, "The Skeletal Reef"},
                {0, 0, "Nespirah"},
                {0, 0, "Ruins of Vashj'ir"},
                {0, 0, "Silver Tide Hollow"},
                {0, 0, "Abyssal Breach"},
                {0, 0, "Deepfin Ridge"},
                {0, 0, "L'ghorek"},
                {0, 0, "The Scalding Chasm"},
                {0, 0, "Gnaws' Boneyard"},
                {0, 0, "The Clutch"},
                {0, 0, "Legion's Fate"},
                {0, 0, "Beth'mora Ridge"},
                {0, 0, "Ruins of Thelserai Temple"},
                {0, 0, "Shimmering Grotto"},
            },
        },
        ["Uldum"] = {
            achievementID = 4865,
            proxyLocation = {0, 0, "Uldum"},
            waypoints = {
                {0, 0, "Akhenet Fields"},
                {0, 0, "Khartut's Tomb"},
                {0, 0, "Mar'at"},
                {0, 0, "Neferset City"},
                {0, 0, "Obelisk of the Stars"},
                {0, 0, "Orsis"},
                {0, 0, "Ruins of Ahmtul"},
                {0, 0, "Schnottz's Landing"},
                {0, 0, "Temple of Uldum"},
                {0, 0, "The Gate of Unending Cycles"},
                {0, 0, "The Trail of Devastation"},
                {0, 0, "Cradle of the Ancients"},
                {0, 0, "Lost City of the Tol'vir"},
                {0, 0, "Nahom"},
                {0, 0, "Obelisk of the Moon"},
                {0, 0, "Obelisk of the Sun"},
                {0, 0, "Ramkahen"},
                {0, 0, "Ruins of Ammon"},
                {0, 0, "Tahret Grounds"},
                {0, 0, "The Cursed Landing"},
                {0, 0, "Tombs of the Precursors"},
                {0, 0, "Vir'naal Dam"},
            },
        },
    }, -- Cataclysm
    ["Draenor"] = {
        ["Frostfire Ridge"] = {
            achievementID = 8937,
            proxyLocation = {0, 0, "Frostfire Ridge"},
            waypoints = {
                {0, 0, "Bladespire Citadel"},
                {0, 0, "Bones of Agurak"},
                {0, 0, "Daggermaw Ravine"},
                {0, 0, "Grimfrost Hill"},
                {0, 0, "Iron Siegeworks"},
                {0, 0, "Magnarok"},
                {0, 0, "The Boneslag"},
                {0, 0, "Wor'gol"},
                {0, 0, "Bloodmaul Stronghold"},
                {0, 0, "Colossal's Fall"},
                {0, 0, "Frostwind Crag"},
                {0, 0, "Grom'gar"},
                {0, 0, "Iron Waystation"},
                {0, 0, "Stonefang Outpost"},
                {0, 0, "The Cracking Plains"},
            },
        },
        ["Gorgrond"] = {
            achievementID = 8939,
            proxyLocation = {0, 0, "Gorgrond"},
            waypoints = {
                {0, 0, "Bastion Rise"},
                {0, 0, "Grimrail Depot"},
                {0, 0, "Deadgrin"},
                {0, 0, "Evermorn Springs"},
                {0, 0, "Highpass"},
                {0, 0, "Stonemaul Arena"},
                {0, 0, "The Iron Approach"},
                {0, 0, "Beastwatch"},
                {0, 0, "Crimson Fen"},
                {0, 0, "Everbloom Wilds"},
                {0, 0, "Gronn Canyon"},
                {0, 0, "Iyun Weald"},
                {0, 0, "Tangleheart"},
                {0, 0, "The Pit"},
                {0, 0, "The Pit"},
                {0, 0, "The Pit"},
            },
        },
        ["Spires of Arak"] = {
            achievementID = 8941,
            proxyLocation = {0, 0, "Spires of Arak"},
            waypoints = {
                {0, 0, "Skettis"},
                {0, 0, "The Writhing Mire"},
                {0, 0, "Veil Zekk"},
                {0, 0, "Southport"},
                {0, 0, "Terrace of Dawn"},
                {0, 0, "Bladefist Hold"},
                {0, 0, "Lost Veil Anzu"},
                {0, 0, "Ravenskar"},
                {0, 0, "Axefall"},
                {0, 0, "The Howling Crag"},
                {0, 0, "Pinchwhistle Point"},
                {0, 0, "Veil Akraz"},
                {0, 0, "Windswept Terrace"},
                {0, 0, "Sethekk Hollow"},
                {0, 0, "Admiral Taylor's Garrison"},
                {0, 0, "Pinchwhistle Gearworks"},
                {0, 0, "Bloodmane Valley"},
            },
        },
        ["Shadowmoon Valley"] = {
            achievementID = 8938,
            proxyLocation = {0, 0, "Shadowmoon Valley"},
            waypoints = {
                {0, 0, "Anguish Fortress"},
                {0, 0, "Elodor"},
                {0, 0, "Gloomshade Grove"},
                {0, 0, "Karabor"},
                {0, 0, "The Shimmer Moor"},
                {0, 0, "Isle of Shadows"},
                {0, 0, "Darktide Roost"},
                {0, 0, "Embaari Village"},
                {0, 0, "Gul'var"},
                {0, 0, "Shaz'gul"},
                {0, 0, "Socrethar's Rise"},
            },
        },
        ["Talador"] = {
            achievementID = 8940,
            proxyLocation = {0, 0, "Talador"},
            waypoints = {
                {0, 0, "Aruuna"},
                {0, 0, "Duskfall Island"},
                {0, 0, "Fort Wrynn"},
                {0, 0, "Gul'rok"},
                {0, 0, "Orunai Coast"},
                {0, 0, "Shattrath City"},
                {0, 0, "Tomb of Lights"},
                {0, 0, "Zangarra"},
                {0, 0, "Auchindoun"},
                {0, 0, "Court of Souls"},
                {0, 0, "Gordal Fortress"},
                {0, 0, "The Path of Glory"},
                {0, 0, "Anchorite's Sojourn"},
                {0, 0, "Telmor"},
                {0, 0, "Tuurem"},
            },
        },
        ["Nagrand"] = {
            achievementID = 8942,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Ancestral Grounds"},
                {0, 0, "Gates of Grommashar"},
                {0, 0, "Highmaul Harbor"},
                {0, 0, "Lok-rath"},
                {0, 0, "Mok'gol Watchpost"},
                {0, 0, "Telaar"},
                {0, 0, "The Ring of Trials"},
                {0, 0, "Zangar Shore"},
                {0, 0, "Broken Precipice"},
                {0, 0, "Hallvalor"},
                {0, 0, "Ironfist Harbor"},
                {0, 0, "Mar'gok's Overwatch"},
                {0, 0, "Oshu'gun"},
                {0, 0, "The Ring of Blood"},
                {0, 0, "Throne of the Elements"},
            },
        },
    }, -- Warlords of Draenor
    ["Battle for Azeroth"] = {
        ["Tiragarde Sound"] = {
            achievementID = 12556,
            proxyLocation = {0, 0, "Tiragarde Sound"},
            waypoints = {
                {0, 0, "Anglepoint Wharf"},
                {0, 0, "Fernwood Ridge"},
                {0, 0, "Norwington Estate"},
                {0, 0, "Abandoned Junkheap"},
                {0, 0, "The Wailing Tideway"},
                {0, 0, "Waning Glacier"},
                {0, 0, "Boralus"},
                {0, 0, "Freehold"},
                {0, 0, "Krakenbane Cove"},
                {0, 0, "Kennings Lodge"},
                {0, 0, "Vigil Hill"},
            },
        },
        ["Stormsong Valley"] = {
            achievementID = 12558,
            proxyLocation = {0, 0, "Stormsong Valley"},
            waypoints = {
                {0, 0, "Brennadam"},
                {0, 0, "Mariner's Strand"},
                {0, 0, "Deadwash"},
                {0, 0, "Sagehold"},
                {0, 0, "Millstone Hamlet"},
                {0, 0, "Briarback Kraul"},
                {0, 0, "Warfang Hold"},
                {0, 0, "Fort Daelin"},
                {0, 0, "Shrine of the Storm"},
            },
        },
        ["Nazmir"] = {
            achievementID = 12561,
            proxyLocation = {0, 0, "Nazmir"},
            waypoints = {
                {0, 0, "Primal Wetlands"},
                {0, 0, "The Rivermarsh"},
                {0, 0, "Zalamar"},
                {0, 0, "Nazwatha"},
                {0, 0, "The Frogmarsh"},
                {0, 0, "Heart of Darkness"},
                {0, 0, "The Necropolis"},
                {0, 0, "Torga's Rest"},
                {0, 0, "Zal'amak"},
            },
        },
        ["Drustvar"] = {
            achievementID = 12557,
            proxyLocation = {0, 0, "Drustvar"},
            waypoints = {
                {0, 0, "Arom's Stand"},
                {0, 0, "Carver's Harbor"},
                {0, 0, "Crimson Forest"},
                {0, 0, "Fletcher's Hollow"},
                {0, 0, "Highroad Pass"},
                {0, 0, "Iceveil Glacier"},
                {0, 0, "Barrowknoll Cemetery"},
                {0, 0, "Corlain"},
                {0, 0, "Fallhaven"},
                {0, 0, "Gol Koval"},
                {0, 0, "Western Watch"},
                {0, 0, "Waycrest Manor"},
            },
        },
        ["Zuldazar"] = {
            achievementID = 12559,
            proxyLocation = {0, 0, "Zuldazar"},
            waypoints = {
                {0, 0, "Atal'Dazar"},
                {0, 0, "Blood Gate"},
                {0, 0, "Dreadpearl Shallows"},
                {0, 0, "Savagelands"},
                {0, 0, "Tusk Isle"},
                {0, 0, "Xibala"},
                {0, 0, "Atal'Gral"},
                {0, 0, "Dazar'alor"},
                {0, 0, "Garden of the Loa"},
                {0, 0, "The Sliver"},
                {0, 0, "Talanji's Rebuke"},
                {0, 0, "Zeb'ahari"},
            },
        },
        ["Vol'dun"] = {
            achievementID = 12560,
            proxyLocation = {0, 0, "Vol'dun"},
            waypoints = {
                {0, 0, "Atul'Aman"},
                {0, 0, "Port of Zem'lan"},
                {0, 0, "Shatterstone Harbor"},
                {0, 0, "Temple of Akunda"},
                {0, 0, "The Bone Pit"},
                {0, 0, "The Cracked Coast"},
                {0, 0, "Whistlebloom Oasis"},
                {0, 0, "Darkwood Shoal"},
                {0, 0, "Redrock Harbor"},
                {0, 0, "Slithering Gulch"},
                {0, 0, "Terrace of the Devoted"},
                {0, 0, "The Brine Basin"},
                {0, 0, "Tortaka Refuge"},
            },
        },
    }, -- Battle for Azeroth
    ["Kalimdor"] = {
        ["Durotar"] = {
            achievementID = 728,
            proxyLocation = {0, 0, "Durotar"},
            waypoints = {
                {0, 0, "Valley of Trials"},
                {0, 0, "Southfury Watershed"},
                {0, 0, "Echo Isles"},
                {0, 0, "Razor Hill"},
                {0, 0, "Thunder Ridge"},
                {0, 0, "Skull Rock"},
                {0, 0, "Northwatch Foothold"},
                {0, 0, "Sen'jin Village"},
                {0, 0, "Tiragarde Keep"},
                {0, 0, "Razormane Grounds"},
                {0, 0, "Drygulch Ravine"},
                {0, 0, "Orgrimmar"},
            },
        },
        ["Teldrassil"] = {
            achievementID = 842,
            proxyLocation = {0, 0, "Teldrassil"},
            waypoints = {
                {0, 0, "Shadowglen"},
                {0, 0, "Dolanaar"},
                {0, 0, "Gnarlpine Hold"},
                {0, 0, "Pools of Arlithrien"},
                {0, 0, "The Oracle Glade"},
                {0, 0, "Darnassus"},
                {0, 0, "The Cleft"},
                {0, 0, "Ban'ethil Hollow"},
                {0, 0, "Lake Al'Ameth"},
                {0, 0, "Starbreeze Village"},
                {0, 0, "Wellspring Lake"},
                {0, 0, "Rut'theran Village"},
            },
        },
        ["Northern Barrens"] = {
            achievementID = 750,
            proxyLocation = {0, 0, "Northern Barrens"},
            waypoints = {
                {0, 0, "Boulder Lode Mine"},
                {0, 0, "The Mor'shan Rampart"},
                {0, 0, "Dreadmist Peak"},
                {0, 0, "The Forgotten Pools"},
                {0, 0, "Far Watch Post"},
                {0, 0, "The Crossroads"},
                {0, 0, "Ratchet"},
                {0, 0, "Lushwater Oasis"},
                {0, 0, "The Sludge Fen"},
                {0, 0, "The Dry Hills"},
                {0, 0, "Grol'dom Farm"},
                {0, 0, "Thorn Hill"},
                {0, 0, "The Stagnant Oasis"},
                {0, 0, "The Merchant Coast"},
            },
        },
        ["Southern Barrens"] = {
            achievementID = 4996,
            proxyLocation = {0, 0, "Southern Barrens"},
            waypoints = {
                {0, 0, "Bael Modan"},
                {0, 0, "Forward Command"},
                {0, 0, "Honor's Stand"},
                {0, 0, "Northwatch Hold"},
                {0, 0, "Ruins of Taurajo"},
                {0, 0, "Vendetta Point"},
                {0, 0, "Battlescar"},
                {0, 0, "Frazzlecraz Motherlode"},
                {0, 0, "Hunter's Hill"},
                {0, 0, "Razorfen Kraul"},
                {0, 0, "The Overgrowth"},
            },
        },
        ["Bloodmyst Isle"] = {
            achievementID = 861,
            proxyLocation = {0, 0, "Bloodmyst Isle"},
            waypoints = {
                {0, 0, "Amberweb Pass"},
                {0, 0, "Blacksilt Shore"},
                {0, 0, "Bloodcurse Isle"},
                {0, 0, "Bristlelimb Enclave"},
                {0, 0, "Middenvale"},
                {0, 0, "Nazzivian"},
                {0, 0, "Ruins of Loreth'Aran"},
                {0, 0, "Tel'athion's Camp"},
                {0, 0, "The Bloodwash"},
                {0, 0, "The Cryo-Core"},
                {0, 0, "The Hidden Reef"},
                {0, 0, "The Vector Coil"},
                {0, 0, "Veridian Point"},
                {0, 0, "Wrathscale Lair"},
                {0, 0, "Axxarien"},
                {0, 0, "Bladewood"},
                {0, 0, "Blood Watch"},
                {0, 0, "Kessel's Crossing"},
                {0, 0, "Mystwood"},
                {0, 0, "Ragefeather Ridge"},
                {0, 0, "Talon Stand"},
                {0, 0, "The Bloodcursed Reef"},
                {0, 0, "The Crimson Reach"},
                {0, 0, "The Foul Pool"},
                {0, 0, "The Lost Fold"},
                {0, 0, "The Warp Piston"},
                {0, 0, "Vindicator's Rest"},
                {0, 0, "Wyrmscar Island"},
            },
        },
        ["Thousand Needles"] = {
            achievementID = 846,
            proxyLocation = {0, 0, "Thousand Needles"},
            waypoints = {
                {0, 0, "The Great Lift"},
                {0, 0, "Sunken Dig Site"},
                {0, 0, "The Twilight Withering"},
                {0, 0, "Westreach Summit"},
                {0, 0, "Freewind Post"},
                {0, 0, "The Shimmering Deep"},
                {0, 0, "Razorfen Downs"},
                {0, 0, "Southsea Holdfast"},
                {0, 0, "Twilight Bulwark"},
                {0, 0, "Darkcloud Pinnacle"},
                {0, 0, "Splithoof Heights"},
                {0, 0, "Highperch"},
            },
        },
        ["Desolace"] = {
            achievementID = 848,
            proxyLocation = {0, 0, "Desolace"},
            waypoints = {
                {0, 0, "Tethris Aran"},
                {0, 0, "Nijel's Point"},
                {0, 0, "Thunder Axe Fortress"},
                {0, 0, "Magram Territory"},
                {0, 0, "Valley of Spears"},
                {0, 0, "Shadowprey Village"},
                {0, 0, "Mannoroc Coven"},
                {0, 0, "Shadowbreak Ravine"},
                {0, 0, "Thargad's Camp"},
                {0, 0, "Sargeron"},
                {0, 0, "Cenarion Wildlands"},
                {0, 0, "Ranazjar Isle"},
                {0, 0, "Kodo Graveyard"},
                {0, 0, "Gelkis Village"},
                {0, 0, "Shok'Thokar"},
                {0, 0, "Slitherblade Shore"},
            },
        },
        ["Feralas"] = {
            achievementID = 849,
            proxyLocation = {0, 0, "Feralas"},
            waypoints = {
                {0, 0, "Lower Wilds"},
                {0, 0, "The Twin Colossals"},
                {0, 0, "Dire Maul"},
                {0, 0, "Ruins of Isildien"},
                {0, 0, "Camp Mojache"},
                {0, 0, "Gordunni Outpost"},
                {0, 0, "Feathermoon Stronghold"},
                {0, 0, "Ruins of Feathermoon"},
                {0, 0, "The Forgotten Coast"},
                {0, 0, "Feral Scar Vale"},
                {0, 0, "The Writhing Deep"},
                {0, 0, "Grimtotem Compound"},
                {0, 0, "Darkmist Ruins"},
            },
        },
        ["Azshara"] = {
            achievementID = 852,
            proxyLocation = {0, 0, "Azshara"},
            waypoints = {
                {0, 0, "Gallywix Pleasure Palace"},
                {0, 0, "Bilgewater Harbor"},
                {0, 0, "Tower of Eldara"},
                {0, 0, "Darnassian Base Camp"},
                {0, 0, "Bear's Head"},
                {0, 0, "Orgrimmar Rear Gate"},
                {0, 0, "Southridge Beach"},
                {0, 0, "Lake Mennar"},
                {0, 0, "Storm Cliffs"},
                {0, 0, "The Shattered Strand"},
                {0, 0, "Bitter Reaches"},
                {0, 0, "Ruins of Arkkoran"},
                {0, 0, "The Secret Lab"},
                {0, 0, "Blackmaw Hold"},
                {0, 0, "Ruins of Eldarath"},
                {0, 0, "Ravencrest Monument"},
                {0, 0, "The Ruined Reaches"},
            },
        },
        ["Un'Goro Crater"] = {
            achievementID = 854,
            proxyLocation = {0, 0, "Un'Goro Crater"},
            waypoints = {
                {0, 0, "Fire Plume Ridge"},
                {0, 0, "Marshal's Stand"},
                {0, 0, "The Roiling Gardens"},
                {0, 0, "Golakka Hot Springs"},
                {0, 0, "The Slithering Scar"},
                {0, 0, "Ironstone Plateau"},
                {0, 0, "Fungal Rock"},
                {0, 0, "Mossy Pile"},
                {0, 0, "The Screaming Reaches"},
                {0, 0, "Terror Run"},
                {0, 0, "The Marshlands"},
                {0, 0, "Lakkari Tar Pits"},
            },
        },
        ["Silithus"] = {
            achievementID = 856,
            proxyLocation = {0, 0, "Silithus"},
            waypoints = {
                {0, 0, "The Crystal Vale"},
                {0, 0, "Cenarion Hold"},
                {0, 0, "Hive'Regal"},
                {0, 0, "Hive'Ashi"},
                {0, 0, "Southwind Village"},
                {0, 0, "Hive'Zora"},
                {0, 0, "The Scarab Wall"},
                {0, 0, "Valor's Rest"},
            },
        },
        ["Mulgore"] = {
            achievementID = 736,
            proxyLocation = {0, 0, "Mulgore"},
            waypoints = {
                {0, 0, "Red Cloud Mesa"},
                {0, 0, "Bloodhoof Village"},
                {0, 0, "The Rolling Plains"},
                {0, 0, "Ravaged Caravan"},
                {0, 0, "Thunderhorn Water Well"},
                {0, 0, "Red Rocks"},
                {0, 0, "Wildmane Water Well"},
                {0, 0, "Palemane Rock"},
                {0, 0, "Winterhoof Water Well"},
                {0, 0, "The Venture Co. Mine"},
                {0, 0, "The Golden Plains"},
                {0, 0, "Bael'dun Digsite"},
                {0, 0, "Windfury Ridge"},
            },
        },
        ["Azuremyst Isle"] = {
            achievementID = 860,
            proxyLocation = {0, 0, "Azuremyst Isle"},
            waypoints = {
                {0, 0, "Ammen Vale"},
                {0, 0, "Azure Watch"},
                {0, 0, "Emberglade"},
                {0, 0, "Geezle's Camp"},
                {0, 0, "Odesyus' Landing"},
                {0, 0, "Pod Wreckage"},
                {0, 0, "Silvermyst Isle"},
                {0, 0, "The Exodar"},
                {0, 0, "Wrathscale Point"},
                {0, 0, "Ammen Ford"},
                {0, 0, "Bristlelimb Village"},
                {0, 0, "Fairbridge Strand"},
                {0, 0, "Moongraze Woods"},
                {0, 0, "Pod Cluster"},
                {0, 0, "Silting Shore"},
                {0, 0, "Stillpine Hold"},
                {0, 0, "Valaar's Berth"},
            },
        },
        ["Winterspring"] = {
            achievementID = 857,
            proxyLocation = {0, 0, "Winterspring"},
            waypoints = {
                {0, 0, "Frostfire Hot Springs"},
                {0, 0, "Lake Kel'Theril"},
                {0, 0, "Mazthoril"},
                {0, 0, "Owl Wing Thicket"},
                {0, 0, "Winterfall Village"},
                {0, 0, "Frostsaber Rock"},
                {0, 0, "Timbermaw Post"},
                {0, 0, "Starfall Village"},
                {0, 0, "Everlook"},
                {0, 0, "Ice Thistle Hills"},
                {0, 0, "The Hidden Grove"},
                {0, 0, "Frostwhisper Gorge"},
            },
        },
        ["Darkshore"] = {
            achievementID = 844,
            proxyLocation = {0, 0, "Darkshore"},
            waypoints = {
                {0, 0, "Ruins of Auberdine"},
                {0, 0, "Shatterspear War Camp"},
                {0, 0, "Withering Thicket"},
                {0, 0, "The Eye of the Vortex"},
                {0, 0, "Lor'danel"},
                {0, 0, "The Master's Glaive"},
                {0, 0, "Shatterspear Vale"},
                {0, 0, "Wildbend River"},
                {0, 0, "Ruins of Mathystra"},
                {0, 0, "Ameth'Aran"},
                {0, 0, "Nazj'vel"},
            },
        },
        ["Ashenvale"] = {
            achievementID = 845,
            proxyLocation = {0, 0, "Ashenvale"},
            waypoints = {
                {0, 0, "The Zoram Strand"},
                {0, 0, "Silverwind Refuge"},
                {0, 0, "Lake Falathim"},
                {0, 0, "Thistlefur Village"},
                {0, 0, "Astranaar"},
                {0, 0, "The Howling Vale"},
                {0, 0, "Fallen Sky Lake"},
                {0, 0, "Satyrnaar"},
                {0, 0, "Warsong Lumber Camp"},
                {0, 0, "Orendil's Retreat"},
                {0, 0, "Thunder Peak"},
                {0, 0, "Maestra's Post"},
                {0, 0, "The Shrine of Aessina"},
                {0, 0, "The Ruins of Stardust"},
                {0, 0, "Raynewood Retreat"},
                {0, 0, "Splintertree Post"},
                {0, 0, "Bough Shadow"},
                {0, 0, "Felfire Hill"},
            },
        },
        ["Stonetalon Mountains"] = {
            achievementID = 847,
            proxyLocation = {0, 0, "Stonetalon Mountains"},
            waypoints = {
                {0, 0, "Battlescar Valley"},
                {0, 0, "Ruins of Eldre'thar"},
                {0, 0, "Unearthed Grounds"},
                {0, 0, "Windshear Hold"},
                {0, 0, "Malaka'jin"},
                {0, 0, "Boulderslide Ravine"},
                {0, 0, "Windshear Crag"},
                {0, 0, "The Charred Vale"},
                {0, 0, "Stonetalon Peak"},
                {0, 0, "Krom'gar Fortress"},
                {0, 0, "Thal'darah Overlook"},
                {0, 0, "Webwinder Hollow"},
                {0, 0, "Cliffwalker Post"},
                {0, 0, "Webwinder Path"},
                {0, 0, "Greatwood Vale"},
                {0, 0, "Sun Rock Retreat"},
                {0, 0, "Mirkfallon Lake"},
            },
        },
        ["Dustwallow Marsh"] = {
            achievementID = 850,
            proxyLocation = {0, 0, "Dustwallow Marsh"},
            waypoints = {
                {0, 0, "Theramore Isle"},
                {0, 0, "Direhorn Post"},
                {0, 0, "Shady Rest Inn"},
                {0, 0, "Brackenwall Village"},
                {0, 0, "Alcaz Island"},
                {0, 0, "Blackhoof Village"},
                {0, 0, "Mudsprocket"},
                {0, 0, "Dreadmurk Shore"},
                {0, 0, "Wyrmbog"},
            },
        },
        ["Tanaris"] = {
            achievementID = 851,
            proxyLocation = {0, 0, "Tanaris"},
            waypoints = {
                {0, 0, "Gadgetzan"},
                {0, 0, "Valley of the Watchers"},
                {0, 0, "Abyssal Sands"},
                {0, 0, "The Noxious Lair"},
                {0, 0, "Southbreak Shore"},
                {0, 0, "Eastmoon Ruins"},
                {0, 0, "Southmoon Ruins"},
                {0, 0, "Zul'Farrak"},
                {0, 0, "Sandsorrow Watch"},
                {0, 0, "Lost Rigger Cove"},
                {0, 0, "Broken Pillar"},
                {0, 0, "Dunemaul Compound"},
                {0, 0, "The Gaping Chasm"},
                {0, 0, "Land's End Beach"},
                {0, 0, "Thistleshrub Valley"},
                {0, 0, "Caverns of Time"},
            },
        },
        ["Felwood"] = {
            achievementID = 853,
            proxyLocation = {0, 0, "Felwood"},
            waypoints = {
                {0, 0, "Felpaw Village"},
                {0, 0, "Irontree Woods"},
                {0, 0, "Shatter Scar Vale"},
                {0, 0, "Jaedenar"},
                {0, 0, "Jadefire Glen"},
                {0, 0, "Deadwood Village"},
                {0, 0, "Talonbranch Glade"},
                {0, 0, "Jadefire Run"},
                {0, 0, "Bloodvenom Falls"},
                {0, 0, "Ruins of Constellas"},
                {0, 0, "Emerald Sanctuary"},
                {0, 0, "Morlos'Aran"},
            },
        },
        ["Moonglade"] = {
            achievementID = 855,
            proxyLocation = {0, 0, "Moonglade"},
            waypoints = {
                {0, 0, "Lake Elune'ara"},
                {0, 0, "Shrine of Remulos"},
                {0, 0, "Nighthaven"},
                {0, 0, "Stormrage Barrow Dens"},
            },
        },
    }, -- World of Warcraft (Vanilla)
    ["Northrend"] = {
        ["Borean Tundra"] = {
            achievementID = 1264,
            proxyLocation = {0, 0, "Borean Tundra"},
            waypoints = {
                {0, 0, "Temple City of En'kilah"},
                {0, 0, "Riplash Strand"},
                {0, 0, "Garrosh's Landing"},
                {0, 0, "Coldarra"},
                {0, 0, "Amber Ledge"},
                {0, 0, "Valiance Keep"},
                {0, 0, "The Dens of the Dying"},
                {0, 0, "Steeljaw's Caravan"},
                {0, 0, "Kaskala"},
                {0, 0, "Death's Stand"},
                {0, 0, "Bor'gorok Outpost"},
                {0, 0, "Warsong Hold"},
                {0, 0, "The Geyser Fields"},
            },
        },
        ["Dragonblight"] = {
            achievementID = 1265,
            proxyLocation = {0, 0, "Dragonblight"},
            waypoints = {
                {0, 0, "Galakrond's Rest"},
                {0, 0, "Obsidian Dragonshrine"},
                {0, 0, "Naxxramas"},
                {0, 0, "Icemist Village"},
                {0, 0, "Coldwind Heights"},
                {0, 0, "Agmar's Hammer"},
                {0, 0, "Westwind Refugee Camp"},
                {0, 0, "The Forgotten Shore"},
                {0, 0, "Scarlet Point"},
                {0, 0, "Lake Indu'le"},
                {0, 0, "New Hearthglen"},
                {0, 0, "Light's Trust"},
                {0, 0, "Emerald Dragonshrine"},
                {0, 0, "Angrathar the Wrath Gate"},
                {0, 0, "Wyrmrest Temple"},
                {0, 0, "Venomspite"},
                {0, 0, "The Crystal Vice"},
            },
        },
        ["Zul'Drak"] = {
            achievementID = 1267,
            proxyLocation = {0, 0, "Zul'Drak"},
            waypoints = {
                {0, 0, "Gundrak"},
                {0, 0, "Ampitheater of Anguish"},
                {0, 0, "Altar of Rhunok"},
                {0, 0, "Altar of Mam'toth"},
                {0, 0, "Zim'Torga"},
                {0, 0, "Voltarus"},
                {0, 0, "Light's Breach"},
                {0, 0, "Drak'Sotra Fields"},
                {0, 0, "Altar of Sseratus"},
                {0, 0, "Altar of Quetz'lun"},
                {0, 0, "Altar of Har'koa"},
                {0, 0, "Zeramas"},
                {0, 0, "Thrym's End"},
                {0, 0, "Kolramas"},
            },
        },
        ["Crystalsong Forest"] = {
            achievementID = 1457,
            proxyLocation = {0, 0, "Crystalsong Forest"},
            waypoints = {
                {0, 0, "The Azure Front"},
                {0, 0, "Sunreaver's Command"},
                {0, 0, "Windrunner's Overlook"},
                {0, 0, "Violet Stand"},
                {0, 0, "The Decrepit Flow"},
                {0, 0, "Forlorn Woods"},
                {0, 0, "The Great Tree"},
                {0, 0, "The Unbound Thicket"},
            },
        },
        ["Icecrown"] = {
            achievementID = 1270,
            proxyLocation = {0, 0, "Icecrown"},
            waypoints = {
                {0, 0, "The Bombardment"},
                {0, 0, "Onslaught Harbor"},
                {0, 0, "The Fleshwerks"},
                {0, 0, "Sindragosa's Fall"},
                {0, 0, "Valley of Echoes"},
                {0, 0, "The Conflagration"},
                {0, 0, "Jotunheim"},
                {0, 0, "The Shadow Vault"},
                {0, 0, "Icecrown Citadel"},
                {0, 0, "The Broken Front"},
                {0, 0, "Aldur'thar: The Desolation Gate"},
                {0, 0, "Valhalas"},
                {0, 0, "Ymirheim"},
                {0, 0, "Corp'rethar: The Horror Gate"},
                {0, 0, "Scourgeholme"},
            },
        },
        ["Howling Fjord"] = {
            achievementID = 1263,
            proxyLocation = {0, 0, "Howling Fjord"},
            waypoints = {
                {0, 0, "Kamagua"},
                {0, 0, "Camp Winterhoof"},
                {0, 0, "Vengeance Landing"},
                {0, 0, "Scalawag Point"},
                {0, 0, "Gjalerbron"},
                {0, 0, "Giant's Run"},
                {0, 0, "Ivald's Ruin"},
                {0, 0, "New Agamand"},
                {0, 0, "The Twisted Glade"},
                {0, 0, "Westguard Keep"},
                {0, 0, "Baleheim"},
                {0, 0, "Cauldros Isle"},
                {0, 0, "Apothecary Camp"},
                {0, 0, "Steel Gate"},
                {0, 0, "Nifflevar"},
                {0, 0, "Ember Clutch"},
                {0, 0, "Fort Wildervar"},
                {0, 0, "Halgrind"},
                {0, 0, "Skorn"},
                {0, 0, "Utgarde Keep"},
                {0, 0, "Baelgun's Excavation Site"},
            },
        },
        ["Grizzly Hills"] = {
            achievementID = 1266,
            proxyLocation = {0, 0, "Grizzly Hills"},
            waypoints = {
                {0, 0, "Conquest Hold"},
                {0, 0, "Drakil'jin Ruins"},
                {0, 0, "Granite Springs"},
                {0, 0, "Rage Fang Shrine"},
                {0, 0, "Venture Bay"},
                {0, 0, "Amberpine Lodge"},
                {0, 0, "Camp Oneqwah"},
                {0, 0, "Drak'Tharon Keep"},
                {0, 0, "Dun Argol"},
                {0, 0, "Grizzlemaw"},
                {0, 0, "Thor Modan"},
                {0, 0, "Voldrune"},
                {0, 0, "Blue Sky Logging Grounds"},
                {0, 0, "Westfall Brigade Encampment"},
            },
        },
        ["Sholazar Basin"] = {
            achievementID = 1268,
            proxyLocation = {0, 0, "Sholazar Basin"},
            waypoints = {
                {0, 0, "River's Heart"},
                {0, 0, "The Mosslight Pillar"},
                {0, 0, "Makers' Perch"},
                {0, 0, "Rainspeaker Canopy"},
                {0, 0, "The Avalanche"},
                {0, 0, "Kartak's Hold"},
                {0, 0, "The Savage Thicket"},
                {0, 0, "Makers' Overlook"},
                {0, 0, "The Suntouched Pillar"},
                {0, 0, "The Lifeblood Pillar"},
                {0, 0, "The Glimmering Pillar"},
                {0, 0, "The Stormwright's Shelf"},
            },
        },
        ["Storm Peaks"] = {
            achievementID = 1269,
            proxyLocation = {0, 0, "Storm Peaks"},
            waypoints = {
                {0, 0, "Brunnhildar Village"},
                {0, 0, "Dun Niffelem"},
                {0, 0, "Valkyrion"},
                {0, 0, "Sparksocket Minefield"},
                {0, 0, "Temple of Life"},
                {0, 0, "Thunderfall"},
                {0, 0, "Snowdrift Plains"},
                {0, 0, "Frosthold"},
                {0, 0, "Narvir's Cradle"},
                {0, 0, "Bor's Breath"},
                {0, 0, "Terrace of the Makers"},
                {0, 0, "Engine of the Makers"},
                {0, 0, "Ulduar"},
                {0, 0, "Temple of Storms"},
                {0, 0, "Garm's Bane"},
                {0, 0, "Nidavelir"},
            },
        },
    }, -- Wrath of the Lich King
    ["Pandaria"] = {
        ["Jade Forest"] = {
            achievementID = 6351,
            proxyLocation = {0, 0, "Jade Forest"},
            waypoints = {
                {0, 0, "Tian Monastery"},
                {0, 0, "Dreamer's Pavillion"},
                {0, 0, "Pearl Lake"},
                {0, 0, "Greenstone Quarry"},
                {0, 0, "Camp Nooka Nooka"},
                {0, 0, "Serpent's Heart"},
                {0, 0, "Temple of the Jade Serpent"},
                {0, 0, "Garrosh'ar Point"},
                {0, 0, "Honeydew Village"},
                {0, 0, "Dawn's Blossom"},
                {0, 0, "Emperor's Omen"},
                {0, 0, "Grookin Hill"},
                {0, 0, "Nectarbreeze Orchard"},
                {0, 0, "Terrace of Ten Thunders"},
                {0, 0, "Slingtail Pits"},
                {0, 0, "The Arboretum"},
                {0, 0, "Windward Isle"},
            },
        },
        ["Krasarang Wilds"] = {
            achievementID = 6975,
            proxyLocation = {0, 0, "Krasarang Wilds"},
            waypoints = {
                {0, 0, "Anglers Wharf"},
                {0, 0, "Dojani River"},
                {0, 0, "Krasarang Cove"},
                {0, 0, "Nayeli Lagoon"},
                {0, 0, "Ruins of Dojan"},
                {0, 0, "Temple of the Red Crane"},
                {0, 0, "The Forbidden Jungle"},
                {0, 0, "Unga Ingoo"},
                {0, 0, "Cradle of Chi-Ji"},
                {0, 0, "Fallsong Village"},
                {0, 0, "The Krasari Ruins"},
                {0, 0, "Crane Wing Refuge"},
                {0, 0, "Ruins of Korja"},
                {0, 0, "The Deepwild"},
                {0, 0, "The Southern Isles"},
                {0, 0, "Zhu's Watch"},
            },
        },
        ["Townlong Steppes"] = {
            achievementID = 6977,
            proxyLocation = {0, 0, "Townlong Steppes"},
            waypoints = {
                {0, 0, "Gao-Ran Battlefront"},
                {0, 0, "Rensai's Watchpost"},
                {0, 0, "Fire Camp Osul"},
                {0, 0, "Shado-Pan Garrison"},
                {0, 0, "Sik'vess"},
                {0, 0, "The Sumprushes"},
                {0, 0, "Kri'vess"},
                {0, 0, "Niuzao Temple"},
                {0, 0, "Hatred's Vice"},
                {0, 0, "Shan'ze Dao"},
                {0, 0, "Sra'vess"},
            },
        },
        ["Vale of Eternal Blossoms"] = {
            achievementID = 6979,
            proxyLocation = {0, 0, "Vale of Eternal Blossoms"},
            waypoints = {
                {0, 0, "Ruins of Guo-Lai"},
                {0, 0, "Mogu'shan Palace"},
                {0, 0, "The Golden Stair"},
                {0, 0, "The Golden Pagoda"},
                {0, 0, "Shrine of Two Moons"},
                {0, 0, "The Five Sisters"},
                {0, 0, "Mistfall Village"},
                {0, 0, "Setting Sun Garrison"},
                {0, 0, "Shrine of Seven Stars"},
                {0, 0, "Tu Shen Burial Ground"},
                {0, 0, "Whitepetal Lake"},
            },
        },
        ["Valley of the Four Winds"] = {
            achievementID = 6969,
            proxyLocation = {0, 0, "Valley of the Four Winds"},
            waypoints = {
                {0, 0, "Winds' Edge"},
                {0, 0, "Gilded Fan"},
                {0, 0, "Halfhill"},
                {0, 0, "Kunzen Village"},
                {0, 0, "Nesingwary Safari"},
                {0, 0, "Pools of Purity"},
                {0, 0, "Silken Fields"},
                {0, 0, "Stormstout Brewery"},
                {0, 0, "Thunderfoot Ranch"},
                {0, 0, "Dustback Gorge"},
                {0, 0, "The Imperial Granary"},
                {0, 0, "Stoneplow"},
                {0, 0, "Mudmug's Place"},
                {0, 0, "Paoquan Hollow"},
                {0, 0, "Rumbling Terrace"},
                {0, 0, "Singing Marshes"},
                {0, 0, "The Heartland"},
                {0, 0, "Zhu's Descent"},
            },
        },
        ["Kun-Lai Summit"] = {
            achievementID = 6976,
            proxyLocation = {0, 0, "Kun-Lai Summit"},
            waypoints = {
                {0, 0, "Binan Village"},
                {0, 0, "Gate of the August Celestials"},
                {0, 0, "Kota Peak"},
                {0, 0, "Mount Neverest"},
                {0, 0, "Peak of Serenity"},
                {0, 0, "Temple of the White Tiger"},
                {0, 0, "Valley of Emperors"},
                {0, 0, "Firebough Nook"},
                {0, 0, "Isle of Reckoning"},
                {0, 0, "Mogujia"},
                {0, 0, "Muskpaw Ranch"},
                {0, 0, "Shado-Pan Monastery"},
                {0, 0, "The Burlap Trail"},
                {0, 0, "Zouchin Village"},
            },
        },
        ["Dread Wastes"] = {
            achievementID = 6978,
            proxyLocation = {0, 0, "Dread Wastes"},
            waypoints = {
                {0, 0, "Heart of Fear"},
                {0, 0, "Kypari Vor"},
                {0, 0, "Rikkitun Village"},
                {0, 0, "Terrace of Gurthan"},
                {0, 0, "The Clutches of Shek'zeer"},
                {0, 0, "Writhingwood"},
                {0, 0, "Klaxxi'vess"},
                {0, 0, "Kypari Zar"},
                {0, 0, "Soggy's Gamble"},
                {0, 0, "The Briny Muck"},
                {0, 0, "The Sunset Brewgarden"},
                {0, 0, "Zan'vess"},
            },
        },
    }, -- Mists of Pandaria
    ["Broken Isles"] = {
        ["Azsuna"] = {
            achievementID = 10665,
            proxyLocation = {0, 0, "Azsuna"},
            waypoints = {
                {0, 0, "Faronaar"},
                {0, 0, "The Greenway"},
                {0, 0, "Llothien Highlands"},
                {0, 0, "Nar'thalas"},
                {0, 0, "Ruined Sanctum"},
                {0, 0, "Ley-Ruins of Zarkhenar"},
                {0, 0, "Felblaze Ingress"},
                {0, 0, "Isle of the Watchers"},
                {0, 0, "Lost Orchard"},
                {0, 0, "Oceanus Cove"},
                {0, 0, "Temple of Lights"},
            },
        },
        ["Highmountain"] = {
            achievementID = 10667,
            proxyLocation = {0, 0, "Highmountain"},
            waypoints = {
                {0, 0, "Bloodhunt Highlands"},
                {0, 0, "Frosthoof Watch"},
                {0, 0, "Nightwatcher's Perch"},
                {0, 0, "Riverbend"},
                {0, 0, "Shipwreck Cove"},
                {0, 0, "Stonehoof Watch"},
                {0, 0, "Thunder Totem"},
                {0, 0, "Blind Marshlands"},
                {0, 0, "Ironhorn Enclave"},
                {0, 0, "Pinerock Basin"},
                {0, 0, "Rockaway Shallows"},
                {0, 0, "Skyhorn"},
                {0, 0, "Sylvan Falls"},
                {0, 0, "Trueshot Lodge"},
            },
        },
        ["Suramar"] = {
            achievementID = 10669,
            proxyLocation = {0, 0, "Suramar"},
            waypoints = {
                {0, 0, "Ambervale"},
                {0, 0, "Falanaar"},
                {0, 0, "The Grand Pomenade"},
                {0, 0, "Moon Guard Stronghold"},
                {0, 0, "Ruins of Elun'eth"},
                {0, 0, "Tel'anor"},
                {0, 0, "Crimson Thicket"},
                {0, 0, "Felsoul Hold"},
                {0, 0, "Jandvik"},
                {0, 0, "Moonwhisper Gulch"},
                {0, 0, "Suramar City"},
            },
        },
        ["Val'sharah"] = {
            achievementID = 10666,
            proxyLocation = {0, 0, "Val'sharah"},
            waypoints = {
                {0, 0, "Andutalah"},
                {0, 0, "Bradensbrook"},
                {0, 0, "Gloaming Reef"},
                {0, 0, "Lorlathil"},
                {0, 0, "Moonclaw Vale"},
                {0, 0, "Smolderhide Thicket"},
                {0, 0, "Thas'talah"},
                {0, 0, "Black Rook Hold"},
                {0, 0, "The Dreamgrove"},
                {0, 0, "Grove of Cenarius"},
                {0, 0, "Mistvale"},
                {0, 0, "Shala'nir"},
                {0, 0, "Temple of Elune"},
            },
        },
        ["Stormheim"] = {
            achievementID = 10668,
            proxyLocation = {0, 0, "Stormheim"},
            waypoints = {
                {0, 0, "Aggrammar's Vault"},
                {0, 0, "Dreadwake's Landing"},
                {0, 0, "Greywatch"},
                {0, 0, "Haustvald"},
                {0, 0, "Maw of Nashal"},
                {0, 0, "Nastrondir"},
                {0, 0, "The Runewood"},
                {0, 0, "Skold-Ashil"},
                {0, 0, "Talonrest"},
                {0, 0, "Valdisdall"},
                {0, 0, "Blackbeak Overlook"},
                {0, 0, "Dreyrgrot"},
                {0, 0, "Gates of Valor"},
                {0, 0, "Hrydshal"},
                {0, 0, "Morheim"},
                {0, 0, "Watchman's Rock"},
                {0, 0, "Shield's Rest"},
                {0, 0, "Storm's Reach"},
                {0, 0, "Tideskorn Harbor"},
                {0, 0, "Weeping Bluffs"},
            },
        },
    }, -- Legion
}