Localization = Localization or {}

Localization["enUS"] = {
    -- Classic continents --

    -- World of Warcraft (Vanilla)
    ["Eastern Kingdoms"] = {
        ["Eversong Woods"] = {
            achievementID = 859, 
            proxyLocation = {56, 17, "Eversong Woods"},
            waypoints = {
                {34, 23, "Sunstrider Isle"},
                {44, 41, "Ruins of Silvermoon"},
                {35, 58, "West Sanctum"},
                {32, 70, "Sunsail Anchorage"},
                {44, 53, "North Sanctum"},
                {53, 70, "East Sanctum"},
                {60, 62, "Farstrider Retreat"},
                {54, 55, "Stillwhisper Pond"},
                {68, 47, "Duskwither Grounds"},
                {44, 71, "Fairbreeze Village"},
                {59, 72, "The Living Wood"},
                {72, 75, "Tor'Watha"},
                {36, 86, "The Scorched Grove"},
                {57, 41, "Silvermoon City"},
                {72, 45, "Azurebreeze Coast"},
                {64, 72.5, "Elrendar Falls"},
                {33, 78, "Goldenbough Pass"},
                {66, 74, "Lake Elrendar"},
                {44, 85, "Runestone Falithas"},
                {55, 84, "Runestone Shan'dor"},
                {38, 73, "Saltheril's Haven"},
                {23, 75, "Golden Strand"},
                {61, 54, "Thuron's Livery"},
                {27, 59, "Tranquil Shore"},
                {62, 80, "Zeb'Watha"}
            }
        },
        ["Ghostlands"] = {
            achievementID = 858,
            proxyLocation = { 56, 24, "Ghostlands" },
            waypoints = {
                { 46, 33, "Tranquillien" },
                { 61, 12, "Suncrown Village" },
                { 26, 15, "Goldenmist Village" },
                { 19, 43, "Windrunner Village" },
                { 33, 35, "Sanctum of the Moon" },
                { 55, 48, "Sanctum of the Sun" },
                { 79, 21, "Dawnstar Spire" },
                { 72, 31, "Farstrider Enclave" },
                { 40, 49, "Howling Ziggurat" },
                { 33, 80, "Deatholme" },
                { 65, 61, "Zeb'Nowa" },
                { 76, 64, "Amani Pass" },
                { 13, 55, "Windrunner Spire" },
                { 34, 47, "Bleeding Ziggurat" },
                { 48, 13, "Elrendar Crossing" },
                { 47, 78, "Thalassian Pass" },
            },
        },
        ["Elwynn Forest"] = {
            achievementID = 776,
            proxyLocation = { 45, 74, "Elwynn Forest" },
            waypoints = {
                { 48, 41, "Northshire Valley" },
                { 24, 76, "Westbrook Garrison" },
                { 42, 65, "Goldshire" },
                { 38, 81, "Fargodeep Mine" },
                { 48, 86, "Jerod's Landing" },
                { 64, 71, "Tower of Azora" },
                { 69, 80, "Brackwell Pumpkin Patch" },
                { 82, 67, "Eastvale Logging Camp" },
                { 84, 80, "Ridgepoint Tower" },
                { 52, 66, "Crystal Lake" },
                { 74, 52, "Stone Cairn Lake" },
            },
        },
        ["Westfall"] = {
            achievementID = 802,
            proxyLocation = { 41, 80, "Westfall" },
            waypoints = {
                { 56, 50, "Sentinel Hill" },
                { 54, 31, "Saldean's Farm" },
                { 51, 21, "Furlbrow's Pumpkin Farm" },
                { 58, 17, "The Jansen Stead" },
                { 44, 24, "Jangolode Mine" },
                { 45, 35, "The Molsen Farm" },
                { 61, 59, "The Dead Acre" },
                { 41, 66, "Moonbrook" },
                { 38, 52, "Alexston Farmstead" },
                { 34, 70, "Demont's Place" },
                { 30, 86, "Westfall Lighthouse" },
                { 44, 80, "The Dagger Hills" },
                { 38, 42, "The Raging Chasm" },
                { 61, 72, "The Dust Plains" },
            },
        },
        ["Wetlands"] = {
            achievementID = 841,
            proxyLocation = { 50, 54, "Wetlands" },
            waypoints = {
                { 10, 56, "Menethil Harbor" },
                { 25, 47, "Black Channel Marsh" },
                { 18, 37, "Bluegill Marsh" },
                { 35, 48, "Whelgar's Excavation Site" },
                { 28, 32, "Sundown Marsh" },
                { 32, 22, "Saltspray Glen" },
                { 43, 26, "Ironbeard's Tomb" },
                { 47, 16, "Dun Modr" },
                { 48, 48, "Angerfang Encampment" },
                { 51, 62, "Thelgen Rock" },
                { 57, 41, "Greenwarden's Grove" },
                { 60, 56, "Mosshide Fen" },
                { 60, 27, "Direforge Hill" },
                { 48, 77, "Dun Algaz" },
                { 58, 70, "Slabchisel's Survey" },
                { 69, 37, "Raptor Ridge" },
            },
        },
        ["Redridge Mountains"] = {
            achievementID = 780,
            proxyLocation = { 51, 76, "Redridge Mountains" },
            waypoints = {
                { 27, 42, "Lakeshire" },
                { 40, 52, "Lake Everstill" },
                { 18, 62, "Three Corners" },
                { 38, 67, "Lakeridge Highway" },
                { 25, 23, "Redridge Canyons" },
                { 48, 40, "Alther's Mill" },
                { 68, 54, "Stonewatch Falls" },
                { 65, 71, "Render's Valley" },
                { 35, 15, "Render's Camp" },
                { 60, 50, "Stonewatch Keep" },
                { 67, 39, "Galardell Valley" },
                { 78, 62, "Shalewind Canyon" },
                { 52, 55, "Camp Everstill" },
            },
        },
        ["Arathi Highlands"] = {
            achievementID = 761,
            proxyLocation = { 51, 47, "Arathi Highlands" },
            waypoints = {
                { 18, 31, "Circle of West Binding" },
                { 26, 29, "Northfold Manor" },
                { 28, 45, "Boulder'gor" },
                { 13, 36, "Galen's Fall" },
                { 19, 62, "Stromgarde Keep" },
                { 24, 81, "Faldir's Cove" },
                { 29, 59, "Circle of Inner Binding" },
                { 39, 89, "Thandol Span" },
                { 49, 78, "Boulderfist Hall" },
                { 40, 47, "Refuge Pointe" },
                { 47, 52, "Circle of Outer Binding" },
                { 60, 73, "Witherbark Village" },
                { 56, 58, "Go'Shek Farm" },
                { 50, 40, "Dabyrie's Farmstead" },
                { 61, 30, "Circle of East Binding" },
                { 69, 36, "Hammerfall" },
            },
        },
        ["Duskwood"] = {
            achievementID = 778,
            proxyLocation = { 46, 80, "Duskwood" },
            waypoints = {
                { 21, 69, "Addle's Stead" },
                { 19, 56, "Raven Hill" },
                { 19, 41, "Raven Hill Cemetery" },
                { 35, 73, "Vul'Gol Ogre Mound" },
                { 47, 40, "Twilight Grove" },
                { 49, 73, "The Yorgen Farmstead" },
                { 65, 38, "Brightwood Grove" },
                { 64, 71, "The Rotting Orchard" },
                { 79, 69, "Tranquil Gardens Cemetery" },
                { 74, 47, "Darkshire" },
                { 77, 36, "Manor Mistmantle" },
                { 56, 16, "The Darkened Bank" },
            },
        },
        ["Blasted Lands"] = {
            achievementID = 766,
            proxyLocation = { 52, 84, "Blasted Lands" },
            waypoints = {
                { 41, 14, "Dreadmaul Hold" },
                { 52, 15, "Nethergarde Supply Camps" },
                { 61, 16, "Nethergarde Keep" },
                { 60, 29, "Serpent's Coil" },
                { 54, 53, "The Dark Portal" },
                { 37, 28, "Altar of Storms" },
                { 46, 39, "Dreadmaul Post" },
                { 32, 46, "The Tainted Scar" },
                { 44, 26, "Rise of the Defiler" },
                { 69, 36, "Shattershore" },
                { 50, 72, "Sunveil Excursion" },
                { 44, 86, "Surwich" },
                { 66, 71, "The Red Reaches" },
                { 34, 73, "The Tainted Forest" },
            },
        },
        ["Deadwind Pass"] = {
            achievementID = 777,
            proxyLocation = { 50, 80, "Deadwind Pass" },
            waypoints = {
                { 45, 44, "Deadman's Crossing" },
                { 58, 67, "The Vice" },
                { 45, 73, "Karazhan" },
            },
        },
        ["Hillsbrad Foothills"] = {
            achievementID = 772,
            proxyLocation = { 47, 42, "Hillsbrad Foothills" },
            waypoints = {
                { 35, 74, "Azurelode Mine" },
                { 33, 48, "Brazie Farmstead" },
                { 50, 47, "Corrahn's Dagger" },
                { 52, 23, "Crushridge Hold" },
                { 68, 30, "Chillwind Point" },
                { 30, 37, "Dalaran Crater" },
                { 44, 9, "Dandred's Fold" },
                { 45, 57, "Darrow Hill" },
                { 62, 84, "Dun Garok" },
                { 68, 60, "Durnholde Keep" },
                { 51, 31, "Gallows' Corner" },
                { 39, 48, "Gavin's Naze" },
                { 43, 38, "Growless Cave" },
                { 40, 18, "Misty Shore" },
                { 58, 73, "Nethander Stead" },
                { 26, 86, "Purgation Isle" },
                { 43, 30, "Ruins of Alterac" },
                { 48, 70, "Ruins of Southshore" },
                { 48, 19, "Slaughter Hollow" },
                { 55, 37, "Sofera's Naze" },
                { 30, 63, "Southpoint Gate" },
                { 58, 24, "Strahnbrad" },
                { 55, 47, "Tarren Mill" },
                { 44, 50, "The Headland" },
                { 37, 60, "The Sludge Fields" },
                { 51, 14, "The Uplands" },
            },
        },
        ["The Hinterlands"] = {
            achievementID = 773,
            proxyLocation = { 52, 41, "The Hinterlands" },
            waypoints = {
                { 12, 46, "Aerie Peak" },
                { 24, 36, "Plaguemist Ravine" },
                { 22, 57, "Zun'watha" },
                { 32, 46, "Quel'Danil Lodge" },
                { 34, 71, "Shadra'Alor" },
                { 41, 59, "Valorwind Lake" },
                { 46, 40, "Agol'watha" },
                { 49, 50, "The Creeping Ruin" },
                { 48, 68, "The Altar of Zul" },
                { 63, 26, "Seradane" },
                { 58, 41, "Skulk Rock" },
                { 72, 53, "Shaol'watha" },
                { 63, 73, "Jintha'Alor" },
                { 76, 59, "The Overlook Cliffs" },
            },
        },
        ["Searing Gorge"] = {
            achievementID = 774,
            proxyLocation = { 47, 66, "Searing Gorge" },
            waypoints = {
                { 22, 37, "Firewatch Ridge" },
                { 48, 52, "The Cauldron" },
                { 20, 80, "Blackchar Cave" },
                { 60, 71, "The Sea of Cinders" },
                { 65, 58, "Grimesilt Dig Site" },
                { 72, 28, "Dustfire Valley" },
                { 36, 27, "Thorium Point" },
                { 36, 85, "Blackrock Mountain" },
            },
        },
        ["Swamp of Sorrows"] = {
            achievementID = 782,
            proxyLocation = { 53, 79, "Swamp of Sorrows" },
            waypoints = {
                { 15, 37, "Misty Valley" },
                { 28, 33, "The Harborage" },
                { 21, 50, "Splinterspear Junction" },
                { 41, 39, "The Shifting Mire" },
                { 47, 54, "Stonard" },
                { 69, 53, "Pool of Tears" },
                { 69, 74, "Stagalbog" },
                { 83, 39, "Sorrowmurk" },
                { 72, 14, "Bogpaddle" },
                { 86, 24, "Misty Reed Strand" },
                { 18, 66, "Purespring Cavern" },
                { 68, 36, "Marshtide Watch" },
            },
        },
        ["Burning Steppes"] = {
            achievementID = 775,
            proxyLocation = { 50, 71, "Burning Steppes" },
            waypoints = {
                { 69, 42, "Dreadmaul Rock" },
                { 73, 66, "Morgan's Vigil" },
                { 75, 52, "Terror Wing Path" },
                { 66, 73, "Blackrock Pass" },
                { 55, 38, "Ruins of Thaurissan" },
                { 36, 53, "Black Tooth Hovel" },
                { 32, 36, "Blackrock Stronghold" },
                { 19, 65, "The Whelping Downs" },
                { 9, 29, "Altar of Storms" },
                { 20, 35, "Blackrock Mountain" },
            },
        },
        ["Northern Stranglethorn"] = {
            achievementID = 781,
            proxyLocation = { 48, 87, "Northern Stranglethorn" },
            waypoints = {
                { 38, 50, "Grom'gol Base Camp" },
                { 60, 55, "Balia'mah Ruins" },
                { 64, 40, "Bambala" },
                { 52, 66, "Fort Livingston" },
                { 19, 24, "Zuuldaia Ruins" },
                { 44, 23, "Nesingwary's Expedition" },
                { 47, 11, "Rebel Camp" },
                { 59, 20, "Kurzen's Compound" },
                { 42, 39, "Kal'ai Ruins" },
                { 46, 53, "Mizjah Ruins" },
                { 66, 51, "Mosh'Ogg Ogre Mound" },
                { 52, 35, "Lake Nazferiti" },
                { 34, 36, "Bal'lal Ruins" },
                { 27, 50, "The Vile Reef" },
                { 26, 20, "Ruins of Zul'Kunda" },
                { 82, 30, "Zul'Gurub" },
            },
        },
        ["The Cape of Stranglethorn"] = {
            achievementID = 4995,
            proxyLocation = { 44, 92, "The Cape of Stranglethorn" },
            waypoints = {
                { 42, 71, "Booty Bay" },
                { 63, 30, "Crystalvein Mine" },
                { 47, 26, "Gurubashi Arena" },
                { 35, 32, "Hardwrench Hideaway" },
                { 60, 82, "Jaquero Isle" },
                { 50, 56, "Mistvale Valley" },
                { 41, 50, "Nek'mani Wellspring" },
                { 62, 43, "Ruins of Aboraz" },
                { 53, 31, "Ruins of Jubuwal" },
                { 49, 78, "The Wild Shore" },
            },
        },
        ["Loch Modan"] = {
            achievementID = 779,
            proxyLocation = { 53, 61, "Loch Modan" },
            waypoints = {
                { 49, 44, "The Loch" },
                { 48, 12, "Stonewrought Dam" },
                { 70, 26, "Mo'grosh Stronghold" },
                { 34, 20, "Silver Stream Mine" },
                { 19, 17, "North Gate Pass" },
                { 82, 63, "The Farstrider Lodge" },
                { 68, 63, "Ironband's Excavation Site" },
                { 36, 62, "Grizzlepaw Ridge" },
                { 35, 47, "Thelsamar" },
                { 32, 78, "Stonesplinter Valley" },
                { 21, 74, "Valley of Kings" },
            },
        },
        ["Dun Morogh"] = {
            achievementID = 627,
            proxyLocation = { 44, 62, "Dun Morogh" },
            waypoints = {
                { 42, 66, "Coldridge Pass" },
                { 35, 71, "Coldridge Valley" },
                { 58, 59, "Frostmane Front" },
                { 33, 38, "New Tinkertown" },
                { 77, 25, "Ironforge Airfield" },
                { 48, 38, "Shimmer Ridge" },
                { 53, 50, "Kharanos" },
                { 65, 57, "The Tundrid Hills" },
                { 71, 48, "Amberstill Ranch" },
                { 83, 51, "Helm's Bed Lake" },
                { 76, 56, "Gol'Bolar Quarry" },
                { 88, 40, "North Gate Outpost" },
                { 33, 49, "Frostmane Hold" },
                { 48, 55, "The Grizzled Den" },
                { 41, 40, "Iceflow Lake" },
                { 58, 36, "Gates of Ironforge" },
            },
        },
        ["Eastern Plaguelands"] = {
            achievementID = 771,
            proxyLocation = { 55, 32, "Eastern Plaguelands" },
            waypoints = {
                { 7, 64, "Thondroril River" },
                { 23, 67, "The Marris Stead" },
                { 24, 78, "The Undercroft" },
                { 35, 68, "Crown Guard Tower" },
                { 35, 46, "The Fungal Vale" },
                { 34, 83, "Darrowshire" },
                { 69, 56, "Pestilent Scar" },
                { 55, 62, "Corin's Crossing" },
                { 56, 74, "Lake Mereldar" },
                { 76, 75, "Tyr's Hand" },
                { 75, 53, "Light's Hope Chapel" },
                { 49, 65, "The Infectis Scar" },
                { 78, 37, "The Noxious Glade" },
                { 62, 42, "Eastwall Tower" },
                { 46, 43, "Blackwood Lake" },
                { 65, 27, "Northdale" },
                { 64, 12, "Zul'Mashar" },
                { 50, 20, "Northpass Tower" },
                { 48, 13, "Quel'Lithien Lodge" },
                { 12, 27, "Terrordale" },
                { 29, 26, "Plaguewood" },
                { 27, 10, "Stratholme" },
                { 88, 73, "Ruins of the Scarlet Enclave" },
            },
        },
        ["Badlands"] = {
            achievementID = 765,
            proxyLocation = { 53, 66, "Badlands" },
            waypoints = {
                { 70, 46, "Lethlor Ravine" },
                { 45, 58, "Agmond's End" },
                { 43, 11, "Uldaman" },
                { 15, 66, "Camp Cagg" },
                { 36, 51, "Scar of the Worldbreaker" },
                { 26, 45, "The Dustbowl" },
                { 40, 27, "Angor Fortress" },
                { 59, 20, "Camp Kosh" },
                { 51, 49, "Bloodwatcher Point" },
                { 16, 44, "New Kargath" },
            },
        },
        ["Tirisfal Glades"] = {
            achievementID = 768,
            proxyLocation = { 43, 33, "Tirisfal Glades" },
            waypoints = {
                { 32, 64, "Deathknell" },
                { 38, 49, "Solliden Farmstead" },
                { 46, 33, "Agamand Mills" },
                { 45, 66, "Nightmare Vale" },
                { 53, 57, "Cold Hearth Manor" },
                { 61, 51, "Brill" },
                { 58, 36, "Garren's Haunt" },
                { 68, 46, "Brightwater Lake" },
                { 75, 60, "Balnir Farmstead" },
                { 79, 55, "Crusader Outpost" },
                { 79, 27, "Scarlet Watch Post" },
                { 86, 46, "Venomweb Vale" },
                { 62, 69, "Ruins of Lordaeron" },
                { 83, 32, "Scarlet Monastery Entrance" },
                { 83, 70, "The Bulwark" },
                { 44, 53, "Calston Estate" },
            },
        },
        ["Western Plaguelands"] = {
            achievementID = 770,
            proxyLocation = { 49, 33, "Western Plaguelands" },
            waypoints = {
                { 60, 73, "Darrowmere Lake" },
                { 69, 74, "Caer Darrow" },
                { 50, 77, "Sorrow Hill" },
                { 44, 68, "Andorhal" },
                { 28, 58, "The Bulwark" },
                { 37, 56, "Felstone Field" },
                { 46, 52, "Dalson's Farm" },
                { 53, 67, "The Writhing Haunt" },
                { 48, 33, "Northridge Lumber Camp" },
                { 45, 17, "Hearthglen" },
                { 54, 46, "Redpine Dell" },
                { 62, 57, "Gahrron's Withering" },
                { 65, 41, "The Weeping Cave" },
                { 70, 48, "Thondroril River" },
            },
        },
        ["Silverpine Forest"] = {
            achievementID = 769,
            proxyLocation = { 41, 40, "Silverpine Forest" },
            waypoints = {
                { 45, 76, "The Battlefront" },
                { 54, 34, "The Decrepit Fields" },
                { 50, 68, "The Forsaken Front" },
                { 35, 14, "The Skittering Dark" },
                { 38, 27, "North Tide's Beachhead" },
                { 67, 28, "Fenris Isle" },
                { 53, 25, "Valgan's Field" },
                { 44, 41, "The Sepulcher" },
                { 56, 47, "Deep Elem Mine" },
                { 45, 51, "Olsen's Farthing" },
                { 61, 63, "Ambermill" },
                { 44, 67, "Shadowfang Keep" },
                { 57, 10, "Forsaken High Command" },
                { 34, 20, "North Tide's Run" },
                { 44, 20, "Forsaken Rear Guard" },
            },
        },
        ["Twilight Highlands"] = {
            achievementID = 4866,
            proxyLocation = { 56, 55, "Twilight Highlands" },
            waypoints = {
                { 54, 41, "Bloodgulch" },
                { 50, 56, "Crucible of Carnage" },
                { 47, 77, "Crushblow" },
                { 25, 37, "Dragonmaw Pass" },
                { 75, 57, "Dragonmaw Port" },
                { 48, 70, "Dunwald Ruins" },
                { 61, 56, "Firebeard's Patrol" },
                { 36, 35, "Glopgut's Hollow" },
                { 62, 46, "Gorshak War Camp" },
                { 21, 55, "Grim Batol" },
                { 78, 75, "Highbank" },
                { 54, 63, "Highland Forest" },
                { 39, 21, "Humboldt Conflagration" },
                { 57, 18, "Kirthaven" },
                { 57, 81, "Obsidian Forest" },
                { 44, 14, "Ruins of Drakgor" },
                { 70, 41, "Slithering Cove" },
                { 59, 30, "The Black Breach" },
                { 37, 39, "The Gullet" },
                { 76, 16, "The Krazzworks" },
                { 40, 46, "The Twilight Breach" },
                { 47, 28, "Thundermar" },
                { 71, 71, "Twilight Shore" },
                { 28, 25, "Vermillion Redoubt" },
                { 42, 58, "Victor's Point" },
                { 29, 48, "Wyrms' Bend" },
                { 50, 14, "The Maw of Madness" },
            },
        },
        ["Isle of Quel'Danas"] = {
            achievementID = 868,
            proxyLocation = { 55.7,  4.7, "Isle of Quel'Danas" },
            waypoints = {
                { 55.7, 4.7, "Isle of Quel'Danas" }
            },
        },
    },
    ["Kalimdor"] = {
        ["Southern Barrens"] = {
            achievementID = 4996,
            proxyLocation = { 52, 62, "Southern Barrens" },
            waypoints = {
                { 41, 94, "Razorfen Kraul" },
                { 49, 85, "Bael Modan" },
                { 42, 77, "Frazzlecraz Motherlode" },
                { 45, 69, "Battlescar" },
                { 44, 51, "Ruins of Taurajo" },
                { 49, 49, "Forward Command" },
                { 41, 46, "Vendetta Point" },
                { 45, 35, "The Overgrowth" },
                { 39, 20, "Hunter's Hill" },
                { 38, 13, "Honor's Stand" },
                { 66, 47, "Northwatch Hold" },
            },
        },
        ["Bloodmyst Isle"] = {
            achievementID = 861,
            proxyLocation = { 30, 19, "Bloodmyst Isle" },
            waypoints = {
                { 17, 28, "Amberweb Pass" },
                { 80, 26, "The Bloodcursed Reef" },
                { 38, 20, "The Bloodwash" },
                { 66, 49, "The Crimson Reach" },
                { 29, 36, "The Foul Pool" },
                { 34, 23, "The Hidden Reef" },
                { 57, 81, "The Lost Fold" },
                { 18, 51, "The Vector Coil" },
                { 53, 16, "The Warp Piston" },
                { 74, 9, "Veridian Point" },
                { 30, 45, "Vindicator's Rest" },
                { 69, 67, "Wrathscale Lair" },
                { 71, 16, "Wyrmscar Island" },
                { 25, 42, "Tel'athion's Camp" },
                { 73, 20, "Talon Stand" },
                { 40, 33, "Axxarien" },
                { 31, 87, "Blacksilt Shore" },
                { 46, 45, "Bladewood" },
                { 85, 51, "Bloodcurse Isle" },
                { 54, 55, "Blood Watch" },
                { 66, 78, "Bristlelimb Enclave" },
                { 62, 89, "Kessel's Crossing" },
                { 51, 76, "Middenvale" },
                { 42, 84, "Mystwood" },
                { 38, 79, "Nazzivian" },
                { 55, 35, "Ragefeather Ridge" },
                { 61, 44, "Ruins of Loreth'Aran" },
                { 39, 61, "The Cryo-Core" },
            },
        },
        ["Ashenvale"] = {
            achievementID = 845,
            proxyLocation = { 50, 42, "Ashenvale" },
            waypoints = {
                { 13, 25, "The Zoram Strand" },
                { 26, 22, "Orendil's Retreat" },
                { 50, 66, "Silverwind Refuge" },
                { 50, 48, "Thunder Peak" },
                { 20, 40, "Lake Falathim" },
                { 27, 36, "Maestra's Post" },
                { 36, 33, "Thistlefur Village" },
                { 21, 53, "The Shrine of Aessina" },
                { 36, 50, "Astranaar" },
                { 34, 70, "The Ruins of Stardust" },
                { 53, 38, "The Howling Vale" },
                { 61, 50, "Raynewood Retreat" },
                { 66, 81, "Fallen Sky Lake" },
                { 73, 61, "Splintertree Post" },
                { 80, 49, "Satyrnaar" },
                { 92, 38, "Bough Shadow" },
                { 87, 57, "Warsong Lumber Camp" },
                { 84, 71, "Felfire Hill" },
            },
        },
        ["Un'Goro Crater"] = {
            achievementID = 854,
            proxyLocation = { 50, 81, "Un'Goro Crater" },
            waypoints = {
                { 51, 50, "Fire Plume Ridge" },
                { 63, 17, "Fungal Rock" },
                { 55, 62, "Marshal's Stand" },
                { 43, 41, "Mossy Pile" },
                { 69, 34, "The Roiling Gardens" },
                { 30, 37, "The Screaming Reaches" },
                { 30, 54, "Golakka Hot Springs" },
                { 33, 70, "Terror Run" },
                { 50, 79, "The Slithering Scar" },
                { 69, 60, "The Marshlands" },
                { 80, 40, "Ironstone Plateau" },
                { 50, 25, "Lakkari Tar Pits" },
            },
        },
        ["Durotar"] = {
            achievementID = 728,
            proxyLocation = { 58, 50, "Durotar" },
            waypoints = {
                { 43, 65, "Valley of Trials" },
                { 50, 79, "Northwatch Foothold" },
                { 40, 40, "Southfury Watershed" },
                { 55, 74, "Sen'jin Village" },
                { 62, 81, "Echo Isles" },
                { 57, 57, "Tiragarde Keep" },
                { 53, 43, "Razor Hill" },
                { 46, 49, "Razormane Grounds" },
                { 40, 26, "Thunder Ridge" },
                { 53, 23, "Drygulch Ravine" },
                { 54, 13, "Skull Rock" },
                { 59, 45, "Orgrimmar" },
            },
        },
        ["Dustwallow Marsh"] = {
            achievementID = 850,
            proxyLocation = { 55, 68, "Dustwallow Marsh" },
            waypoints = {
                { 66, 49, "Theramore Isle" },
                { 41, 11, "Blackhoof Village" },
                { 46, 47, "Direhorn Post" },
                { 41, 74, "Mudsprocket" },
                { 29, 48, "Shady Rest Inn" },
                { 61, 21, "Dreadmurk Shore" },
                { 36, 31, "Brackenwall Village" },
                { 52, 77, "Wyrmbog" },
                { 75, 18, "Alcaz Island" },
            },
        },
        ["Stonetalon Mountains"] = {
            achievementID = 847,
            proxyLocation = { 44, 47, "Stonetalon Mountains" },
            waypoints = {
                { 41, 39, "Battlescar Valley" },
                { 66, 65, "Krom'Gar Fortress" },
                { 48, 76, "Ruins of Eldre'thar" },
                { 38, 32, "Thal'darah Overlook" },
                { 76, 76, "Unearthed Grounds" },
                { 57, 73, "Webwinder Hollow" },
                { 58, 57, "Windshear Hold" },
                { 45, 32, "Cliffwalker Post" },
                { 70, 91, "Malaka'jin" },
                { 58, 66, "Webwinder Path" },
                { 63, 87, "Boulderslide Ravine" },
                { 75, 86, "Greatwood Vale" },
                { 68, 51, "Windshear Crag" },
                { 49, 61, "Sun Rock Retreat" },
                { 32, 68, "The Charred Vale" },
                { 51, 45, "Mirkfallon Lake" },
                { 41, 22, "Stonetalon Peak" },
            },
        },
        ["Tanaris"] = {
            achievementID = 851,
            proxyLocation = { 55, 87, "Tanaris" },
            waypoints = {
                { 51, 29, "Gadgetzan" },
                { 40, 28, "Sandsorrow Watch" },
                { 37, 78, "Valley of the Watchers" },
                { 72, 47, "Lost Rigger Cove" },
                { 45, 41, "Abyssal Sands" },
                { 52, 46, "Broken Pillar" },
                { 34, 46, "The Noxious Lair" },
                { 40, 55, "Dunemaul Compound" },
                { 68, 54, "Southbreak Shore" },
                { 54, 67, "The Gaping Chasm" },
                { 47, 64, "Eastmoon Ruins" },
                { 53, 91, "Land's End Beach" },
                { 40, 71, "Southmoon Ruins" },
                { 31, 65, "Thistleshrub Valley" },
                { 39, 19, "Zul'Farrak" },
                { 63, 50, "Caverns of Time" },
            },
        },
        ["Moonglade"] = {
            achievementID = 855,
            proxyLocation = { 53, 20, "Moonglade" },
            waypoints = {
                { 55, 55, "Lake Elune'ara" },
                { 48, 39, "Nighthaven" },
                { 36, 41, "Shrine of Remulos" },
                { 66, 55, "Stormrage Barrow Dens" },
            },
        },
        ["Teldrassil"] = {
            achievementID = 842,
            proxyLocation = { 43, 11, "Teldrassil" },
            waypoints = {
                { 58, 36, "Shadowglen" },
                { 46, 51, "Ban'ethil Hollow" },
                { 51, 38, "The Cleft" },
                { 55, 52, "Dolanaar" },
                { 44, 67, "Gnarlpine Hold" },
                { 53, 60, "Lake Al'Ameth" },
                { 42, 57, "Pools of Arlithrien" },
                { 64, 50, "Starbreeze Village" },
                { 39, 29, "The Oracle Glade" },
                { 44, 35, "Wellspring Lake" },
                { 30, 49, "Darnassus" },
                { 55, 91, "Rut'theran Village" },
            },
        },
        ["Desolace"] = {
            achievementID = 848,
            proxyLocation = { 42, 56, "Desolace" },
            waypoints = {
                { 54, 10, "Tethris Aran" },
                { 36, 71, "Thargad's Camp" },
                { 65, 10, "Nijel's Point" },
                { 76, 22, "Sargeron" },
                { 54, 25, "Thunder Axe Fortress" },
                { 56, 49, "Cenarion Wildlands" },
                { 74, 46, "Magram Territory" },
                { 29, 9, "Ranazjar Isle" },
                { 33, 55, "Valley of Spears" },
                { 51, 59, "Kodo Graveyard" },
                { 24, 70, "Shadowprey Village" },
                { 37, 86, "Gelkis Village" },
                { 52, 78, "Mannoroc Coven" },
                { 71, 73, "Shok'Thokar" },
                { 79, 79, "Shadowbreak Ravine" },
                { 37, 32, "Slitherblade Shore" },
            },
        },
        ["Darkshore"] = {
            achievementID = 844,
            proxyLocation = { 46, 27, "Darkshore" },
            waypoints = {
                { 50, 18, "Lor'danel" },
                { 43, 39, "Withering Thicket" },
                { 38, 42, "Ruins of Auberdine" },
                { 43, 53, "The Eye of the Vortex" },
                { 43, 58, "Ameth'Aran" },
                { 42, 70, "Wildbend River" },
                { 40, 85, "The Master's Glaive" },
                { 32, 84, "Nazj'vel" },
                { 61, 20, "Ruins of Mathystra" },
                { 62, 9, "Shatterspear War Camp" },
                { 70, 19, "Shatterspear Vale" },
            },
        },
        ["Northern Barrens"] = {
            achievementID = 750,
            proxyLocation = { 53, 50, "Northern Barrens" },
            waypoints = {
                { 66, 12, "Boulder Lode Mine" },
                { 57, 19, "The Sludge Fen" },
                { 42, 15, "The Mor'shan Rampart" },
                { 27, 31, "The Dry Hills" },
                { 36, 45, "The Forgotten Pools" },
                { 42, 38, "Dreadmist Peak" },
                { 53, 41, "Grol'dom Farm" },
                { 67, 39, "Far Watch Post" },
                { 58, 49, "Thorn Hill" },
                { 49, 58, "The Crossroads" },
                { 67, 72, "Ratchet" },
                { 70, 89, "The Merchant Coast" },
                { 55, 80, "The Stagnant Oasis" },
                { 40, 74, "Lushwater Oasis" },
            },
        },
        ["Azshara"] = {
            achievementID = 852,
            proxyLocation = { 62, 39, "Azshara" },
            waypoints = {
                { 20, 56, "Gallywix Pleasure Palace" },
                { 45, 50, "The Shattered Strand" },
                { 58, 51, "Bilgewater Harbor" },
                { 57, 12, "Bitter Reaches" },
                { 80, 31, "Tower of Eldara" },
                { 71, 33, "Ruins of Arkkoran" },
                { 50, 27, "Darnassian Base Camp" },
                { 43, 75, "The Secret Lab" },
                { 25, 38, "Bear's Head" },
                { 38, 30, "Blackmaw Hold" },
                { 24, 80, "Orgrimmar Rear Gate" },
                { 34, 53, "Ruins of Eldarath" },
                { 68, 69, "Southridge Beach" },
                { 64, 81, "Ravencrest Monument" },
                { 35, 74, "Lake Mennar" },
                { 58, 90, "The Ruined Reaches" },
                { 54, 73, "Storm Cliffs" },
            },
        },
        ["Azuremyst Isle"] = {
            achievementID = 860,
            proxyLocation = { 32, 27, "Azuremyst Isle" },
            waypoints = {
                { 77, 43, "Ammen Vale" },
                { 62, 54, "Ammen Ford" },
                { 49, 50, "Azure Watch" },
                { 26, 66, "Bristlelimb Village" },
                { 58, 17, "Emberglade" },
                { 47, 5, "Fairbridge Strand" },
                { 59, 68, "Geezle's Camp" },
                { 52, 42, "Moongraze Woods" },
                { 46, 71, "Odesyus' Landing" },
                { 37, 59, "Pod Cluster" },
                { 53, 61, "Pod Wreckage" },
                { 34, 12, "Silting Shore" },
                { 13, 80, "Silvermyst Isle" },
                { 45, 20, "Stillpine Hold" },
                { 31, 40, "The Exodar" },
                { 21, 54, "Valaar's Berth" },
                { 32, 77, "Wrathscale Point" },
            },
        },
        ["Mulgore"] = {
            achievementID = 736,
            proxyLocation = { 47, 61, "Mulgore" },
            waypoints = {
                { 45, 77, "Red Cloud Mesa" },
                { 34, 62, "Palemane Rock" },
                { 49, 58, "Bloodhoof Village" },
                { 53, 66, "Winterhoof Water Well" },
                { 61, 67, "The Rolling Plains" },
                { 62, 48, "The Venture Co. Mine" },
                { 53, 47, "Ravaged Caravan" },
                { 49, 35, "The Golden Plains" },
                { 44, 45, "Thunderhorn Water Well" },
                { 32, 48, "Bael'Dun Digsite" },
                { 60, 21, "Red Rocks" },
                { 52, 11, "Windfury Ridge" },
                { 42, 14, "Wildmane Water Well" },
            },
        },
        ["Thousand Needles"] = {
            achievementID = 846,
            proxyLocation = { 52, 74, "Thousand Needles" },
            waypoints = {
                { 31, 21, "The Great Lift" },
                { 48, 26, "Razorfen Downs" },
                { 67, 85, "Sunken Dig Site" },
                { 90, 83, "Southsea Holdfast" },
                { 54, 61, "The Twilight Withering" },
                { 31, 58, "Twilight Bulwark" },
                { 13, 11, "Westreach Summit" },
                { 34, 38, "Darkcloud Pinnacle" },
                { 45, 50, "Freewind Post" },
                { 88, 48, "Splithoof Heights" },
                { 78, 72, "The Shimmering Deep" },
                { 11, 36, "Highperch" },
            },
        },
        ["Feralas"] = {
            achievementID = 849,
            proxyLocation = { 44, 69, "Feralas" },
            waypoints = {
                { 83, 41, "Lower Wilds" },
                { 28, 49, "Ruins of Feathermoon" },
                { 46, 20, "The Twin Colossals" },
                { 39, 36, "The Forgotten Coast" },
                { 59, 41, "Dire Maul" },
                { 55, 57, "Feral Scar Vale" },
                { 58, 72, "Ruins of Isildien" },
                { 75, 62, "The Writhing Deep" },
                { 75, 43, "Camp Mojache" },
                { 70, 38, "Grimtotem Compound" },
                { 77, 34, "Gordunni Outpost" },
                { 64, 59, "Darkmist Ruins" },
                { 45, 49, "Feathermoon Stronghold" },
            },
        },
        ["Silithus"] = {
            achievementID = 856,
            proxyLocation = { 43, 81, "Silithus" },
            waypoints = {
                { 30, 16, "The Crystal Vale" },
                { 64, 49, "Southwind Village" },
                { 54, 34, "Cenarion Hold" },
                { 31, 54, "Hive'Zora" },
                { 60, 72, "Hive'Regal" },
                { 35, 80, "The Scarab Wall" },
                { 49, 23, "Hive'Ashi" },
                { 79, 19, "Valor's Rest" },
            },
        },
        ["Felwood"] = {
            achievementID = 853,
            proxyLocation = { 48, 29, "Felwood" },
            waypoints = {
                { 61, 11, "Felpaw Village" },
                { 62, 26, "Talonbranch Glade" },
                { 49, 25, "Irontree Woods" },
                { 43, 18, "Jadefire Run" },
                { 42, 40, "Shatter Scar Vale" },
                { 41, 48, "Bloodvenom Falls" },
                { 37, 60, "Jaedenar" },
                { 40, 74, "Ruins of Constellas" },
                { 41, 84, "Jadefire Glen" },
                { 51, 80, "Emerald Sanctuary" },
                { 48, 91, "Deadwood Village" },
                { 55, 85, "Morlos'Aran" },
            },
        },
        ["Winterspring"] = {
            achievementID = 857,
            proxyLocation = { 58, 23, "Winterspring" },
            waypoints = {
                { 30, 37, "Frostfire Hot Springs" },
                { 36, 56, "Timbermaw Post" },
                { 50, 55, "Lake Kel'Theril" },
                { 55, 64, "Mazthoril" },
                { 49, 40, "Starfall Village" },
                { 59, 49, "Everlook" },
                { 64, 76, "Owl Wing Thicket" },
                { 66, 55, "Ice Thistle Hills" },
                { 66, 46, "Winterfall Village" },
                { 64, 28, "The Hidden Grove" },
                { 46, 18, "Frostsaber Rock" },
                { 60, 86, "Frostwhisper Gorge" },
            },
        },
        ["Uldum"] = {
            achievementID = 4865,
            proxyLocation = { 47, 92, "Uldum" },
            waypoints = {
                { 54, 51, "Akhenet Fields" },
                { 42, 71, "Cradle of the Ancients" },
                { 64, 18, "Khartut's Tomb" },
                { 62, 73, "Lost City of the Tol'vir" },
                { 48, 38, "Mar'at" },
                { 67, 41, "Nahom" },
                { 50, 81, "Neferset City" },
                { 39, 23, "Obelisk of the Moon" },
                { 64, 29, "Obelisk of the Stars" },
                { 45, 58, "Obelisk of the Sun" },
                { 40, 41, "Orsis" },
                { 54, 33, "Ramkahen" },
                { 45, 14, "Ruins of Ahmtul" },
                { 32, 62, "Ruins of Ammon" },
                { 22, 61, "Schnottz's Landing" },
                { 60, 41, "Tahret Grounds" },
                { 33, 31, "Temple of Uldum" },
                { 83, 56, "The Cursed Landing" },
                { 71, 21, "The Gate of Unending Cycles" },
                { 72, 50, "Tombs of the Precursors" },
                { 72, 62, "The Trial of Devastation" },
                { 54, 42, "Vir'naal Dam" },
            },
        },
        ["Mount Hyjal"] = {
            achievementID = 4863,
            proxyLocation = { 54, 32, "Mount Hyjal" },
            waypoints = {
                { 33, 14, "Rim of the World" },
                { 19, 42, "Ashen Lake" },
                { 84, 53, "Darkwhisper Gorge" },
                { 70, 74, "Gates of Sothann" },
                { 62, 21, "Nordrassil" },
                { 31, 84, "Sethria's Roost" },
                { 29, 32, "Shrine of Goldrinn" },
                { 33, 53, "The Flamewake" },
                { 57, 55, "The Scorched Plain" },
                { 49, 79, "The Throne of Flame" },
            },
        },
    },

    -- The Burning Crusade
    ["Outland"] = {
        ["Hellfire Peninsula"] = {
            achievementID = 862,
            proxyLocation = { 56, 54, "Hellfire Peninsula" },
            waypoints = {
                { 86, 45, "The Stair of Destiny" },
                { 54, 83, "Expedition Armory" },
                { 27, 61, "Falcon Watch" },
                { 47, 52, "Hellfire Citadel" },
                { 55, 64, "Honor Hold" },
                { 31, 28, "Mag'har Post" },
                { 40, 34, "Pools of Aggonar" },
                { 14, 60, "Ruins of Sha'naar" },
                { 23, 40, "Temple of Telhamat" },
                { 69, 52, "The Legion Front" },
                { 55, 37, "Thrallmar" },
                { 61, 18, "Throne of Kil'jaeden" },
                { 68, 75, "Zeth'Gor" },
                { 27, 79, "Den of Haal'esh" },
                { 14, 42, "Fallen Sky Ridge" },
                { 78, 72, "Void Ridge" },
                { 46, 84, "The Warp Fields" },
                { 64, 32, "Forge Camp: Mageddon" },
            },
        },
        ["Zangarmarsh"] = {
            achievementID = 863,
            proxyLocation = { 34, 48, "Zangarmarsh" },
            waypoints = {
                { 18, 21, "Ango'rosh Grounds" },
                { 46, 64, "Feralfen Village" },
                { 32, 38, "Hewn Bog" },
                { 22, 40, "Marshlight Lake" },
                { 28, 63, "Quagg Ridge" },
                { 68, 49, "Telredor" },
                { 81, 39, "The Dead Mire" },
                { 58, 63, "The Lagoon" },
                { 47, 50, "Twin Spire Ruins" },
                { 82, 83, "Umbrafen Village" },
                { 18, 49, "Sporeggar" },
                { 18, 7, "Ango'rosh Stronghold" },
                { 61, 41, "Bloodscale Grounds" },
                { 42, 27, "Orebor Harborage" },
                { 15, 61, "The Spawning Glen" },
                { 31, 50, "Zabra'jin" },
                { 70, 82, "Darkcrest Shore" },
                { 79, 65, "Cenarion Refuge" },
            },
        },
        ["Terokkar Forest"] = {
            achievementID = 867,
            proxyLocation = { 48, 73, "Terokkar Forest" },
            waypoints = {
                { 20, 65, "Bleeding Hollow Ruins" },
                { 57, 54, "Allerian Stronghold" },
                { 43, 22, "Cenarion Thicket" },
                { 71, 37, "Firewing Point" },
                { 39, 40, "Grangol'var Village" },
                { 49, 45, "Stonebreaker Hold" },
                { 60, 32, "Tuurem" },
                { 29, 23, "Shattrath City" },
                { 58, 40, "Raastok Glade" },
                { 22, 11, "The Barrier Hills" },
                { 60, 17, "Razorthorn Shelf" },
                { 67, 52, "Bonechewer Ruins" },
                { 34, 72, "Auchenai Grounds" },
                { 43, 53, "Carrion Hill" },
                { 37, 51, "Refugee Caravan" },
                { 39, 65, "Ring of Observance" },
                { 31, 53, "Shadow Tomb" },
                { 43, 77, "Derelict Caravan" },
                { 26, 54, "Veil Rhaze" },
                { 49, 65, "Writhing Mound" },
                { 68, 82, "Skettis" },
            },
        },
        ["Nagrand"] = {
            achievementID = 866,
            proxyLocation = { 32, 65, "Nagrand" },
            waypoints = {
                { 19, 51, "Forge Camp: Fear" },
                { 56, 36, "Garadar" },
                { 42, 44, "Halaa" },
                { 69, 81, "Kil'sorrow Fortress" },
                { 46, 19, "Laughing Skull Ruins" },
                { 36, 71, "Spirit Fields" },
                { 31, 43, "Sunspring Post" },
                { 54, 70, "Telaar" },
                { 65, 56, "The Ring of Trials" },
                { 60, 23, "Throne of the Elements" },
                { 26, 21, "Warmaul Hill" },
                { 76, 64, "Burning Blade Ruins" },
                { 62, 64, "Clan Watch" },
                { 24, 36, "Forge Camp: Hate" },
                { 49, 56, "Southwind Cleft" },
                { 9, 41, "The Twilight Ridge" },
                { 72, 38, "Windyreed Pass" },
                { 73, 53, "Windyreed Village" },
                { 35.8, 16.2, "Zangar Ridge" },
            },
        },
        ["Blade's Edge Mountains"] = {
            achievementID = 865,
            proxyLocation = { 38, 29, "Blade's Edge Mountains" },
            waypoints = {
                { 51, 15, "Bash'ir Landing" },
                { 70, 36, "Bladed Gulch" },
                { 41, 52, "Bladespire Hold" },
                { 55, 26, "Bloodmaul Camp" },
                { 45, 78, "Bloodmaul Outpost" },
                { 80, 28, "Broken Wilds" },
                { 53, 44, "Circle of Blood" },
                { 63, 65, "Death's Door" },
                { 74, 41, "Forge Camp: Anger" },
                { 29, 81, "Forge Camp: Terror" },
                { 36, 40, "Forge Camp: Wrath" },
                { 40, 20, "Grishnath" },
                { 66, 22, "Gruul's Lair" },
                { 52, 74, "Jagged Ridge" },
                { 74, 63, "Mok'Nathal Village" },
                { 33, 25, "Raven's Wood" },
                { 57, 70, "Razor Ridge" },
                { 61, 38, "Ruuan Weald" },
                { 73, 20, "Skald" },
                { 37, 65, "Sylvanaar" },
                { 63, 11, "Crystal Spine" },
                { 51, 57, "Thunderlord Stronghold" },
                { 36, 76, "Veil Lashh" },
                { 65, 31, "Veil Ruuan" },
                { 74, 73, "Vekhaar Stand" },
                { 30, 59, "Vortex Summit" },
            },
        },
        ["Netherstorm"] = {
            achievementID = 843,
            proxyLocation = { 56, 20, "Netherstorm" },
            waypoints = {
                { 33, 65, "Area 52" },
                { 23, 71, "Manaforge B'naar" },
                { 48, 83, "Manaforge Coruu" },
                { 59, 67, "Manaforge Duro" },
                { 26, 40, "Manaforge Ara" },
                { 61, 40, "Manaforge Ultris" },
                { 54, 22, "Ruins of Farahlon" },
                { 76, 65, "Tempest Keep" },
                { 30, 77, "The Heap" },
                { 39, 74, "Arklon Ruins" },
                { 71, 39, "Celestial Ridge" },
                { 57, 87, "Kirin'Var Village" },
                { 49, 18, "Netherstone" },
                { 33, 54, "Ruins of Enkaat" },
                { 56, 78, "Sunfury Hold" },
                { 44, 35, "The Stormspire" },
                { 21, 55, "Gyro-Plank Bridge" },
                { 45, 10, "Eco-Dome Farfield" },
                { 55, 43, "Ethereum Staging Grounds" },
                { 30, 15, "Socrethar's Seat" },
                { 37, 28, "Forge Base: Oblivion" },
                { 45, 53, "Eco-Dome Midrealm" },
            },
        },
        ["Shadowmoon Valley"] = {
            achievementID = 864,
            proxyLocation = { 65, 79, "Shadowmoon Valley" },
            waypoints = {
                { 45, 28, "Coilskar Point" },
                { 45, 68, "Eclipse Point" },
                { 22, 38, "Legion Hold" },
                { 70, 85, "Netherwing Ledge" },
                { 29, 28, "Shadowmoon Village" },
                { 72, 43, "The Black Temple" },
                { 40, 41, "The Deathforge" },
                { 50, 44, "The Hand of Gul'dan" },
                { 59, 48, "Warden's Cage" },
                { 35, 57, "Wildhammer Stronghold" },
                { 61, 28, "Altar of Sha'tar" },
                { 29, 54, "Illidari Point" },
                { 63, 58, "Netherwing Fields" },
            },
        },
    },

    -- Wrath of the Lich King
    ["Northrend"] = {
        ["Dragonblight"] = {
            achievementID = 1265,
            proxyLocation = { 50, 55, "Dragonblight" },
            waypoints = {
                { 55, 34, "Galakrond's Rest" },
                { 40, 67, "Lake Indu'le" },
                { 47, 49, "Ruby Dragonshrine" },
                { 39, 32, "Obsidian Dragonshrine" },
                { 70, 76, "New Hearthglen" },
                { 88, 45, "Naxxramas" },
                { 83, 27, "Light's Trust" },
                { 25, 41, "Icemist Village" },
                { 50, 18, "Coldwind Heights" },
                { 38, 19, "Angrathar the Wrath Gate" },
                { 36, 47, "Agmar's Hammer" },
                { 60, 55, "Wyrmrest Temple" },
                { 14, 48, "Westwind Refugee Camp" },
                { 76, 61, "Venomspite" },
                { 82, 70, "The Forgotten Shore" },
                { 60, 18, "The Crystal Vice" },
                { 73, 26, "Scarlet Point" },
                { 63, 73, "Emerald Dragonshrine" },
            }
        },
        ["Zul'Drak"] = {
            achievementID = 1267,
            proxyLocation = { 68, 43, "Zul'Drak" },
            waypoints = {
                { 83, 18, "Gundrak" },
                { 41, 77, "Drak'Sotra Fields" },
                { 47, 57, "Ampitheater of Anguish" },
                { 40, 40, "Altar of Sseratus" },
                { 53, 35, "Altar of Rhunok" },
                { 77, 58, "Altar of Quetz'lun" },
                { 72, 45, "Altar of Mam'toth" },
                { 63, 69, "Altar of Har'koa" },
                { 59, 57, "Zim'Torga" },
                { 21, 76, "Zeramas" },
                { 28, 46, "Voltarus" },
                { 16, 58, "Thrym's End" },
                { 31, 74, "Light's Breach" },
                { 61, 77, "Kolramas" },
            },
        },
        ["The Storm Peaks"] = {
            achievementID = 1269,
            proxyLocation = { 59, 25, "Storm Peaks" },
            waypoints = {
                { 48, 69, "Brunnhildar Village" },
                { 33, 39, "Narvir's Cradle" },
                { 64, 59, "Dun Niffelem" },
                { 34, 68, "Bor's Breath" },
                { 25, 61, "Valkyrion" },
                { 52, 49, "Terrace of the Makers" },
                { 34, 85, "Sparksocket Minefield" },
                { 40, 57, "Engine of the Makers" },
                { 64, 46, "Temple of Life" },
                { 41, 18, "Ulduar" },
                { 71, 49, "Thunderfall" },
                { 33, 58, "Temple of Storms" },
                { 27, 41, "Snowdrift Plains" },
                { 45, 81, "Garm's Bane" },
                { 28, 74, "Frosthold" },
                { 24, 50, "Nidavelir" },
            },
        },
        ["Borean Tundra"] = {
            achievementID = 1264,
            proxyLocation = { 24, 59, "Borean Tundra" },
            waypoints = {
                { 86, 24, "Temple City of En'kilah" },
                { 49, 25, "Steeljaw's Caravan" },
                { 46, 78, "Riplash Strand" },
                { 65, 48, "Kaskala" },
                { 31, 53, "Garrosh's Landing" },
                { 83, 44, "Death's Strand" },
                { 27, 26, "Coldarra" },
                { 51, 10, "Bor'gorok Outpost" },
                { 46, 33, "Amber Ledge" },
                { 42, 54, "Warsong Hold" },
                { 56, 70, "Valiance Keep" },
                { 66, 28, "The Geyser Fields" },
                { 75, 16, "The Dens of the Dying" },
                { 83, 42, "Death's Stand" },
            },
        },
        ["Howling Fjord"] = {
            achievementID = 1263,
            proxyLocation = { 78, 74, "Howling Fjord" },
            waypoints = {
                { 29, 62, "Kamagua" },
                { 57, 36, "Cauldros Isle" },
                { 48, 10, "Camp Winterhoof" },
                { 26, 24, "Apothecary Camp" },
                { 77, 29, "Vengeance Landing" },
                { 31, 26, "Steel Gate" },
                { 34, 78, "Scalawag Point" },
                { 68, 54, "Nifflevar" },
                { 36, 11, "Gjalerbron" },
                { 39, 50, "Ember Clutch" },
                { 68, 25, "Giant's Run" },
                { 61, 16, "Fort Wildervar" },
                { 78, 47, "Ivald's Ruin" },
                { 49, 54, "Halgrind" },
                { 52, 67, "New Agamand" },
                { 44, 33, "Skorn" },
                { 54, 17, "The Twisted Glade" },
                { 58, 46, "Utgarde Keep" },
                { 30, 42, "Westguard Keep" },
                { 74, 70, "Baelgun's Excavation Site" },
                { 66, 40, "Baleheim" },
            },
        },
        ["Grizzly Hills"] = {
            achievementID = 1266,
            proxyLocation = { 71, 55, "Grizzly Hills" },
            waypoints = {
                { 21, 64, "Conquest Hold" },
                { 17, 24, "Drak'Tharon Keep" },
                { 71, 26, "Drakil'jin Ruins" },
                { 77, 59, "Dun Argol" },
                { 16, 48, "Granite Springs" },
                { 49, 44, "Grizzlemaw" },
                { 49, 57, "Rage Fang Shrine" },
                { 67, 15, "Thor Modan" },
                { 14, 85, "Venture Bay" },
                { 29, 74, "Voldrune" },
                { 35, 38, "Blue Sky Logging Grounds" },
                { 65, 45, "Camp Oneqwah" },
                { 59, 28, "Westfall Brigade Encampment" },
                { 31, 59, "Amberpine Lodge" },
            },
        },
        ["Sholazar Basin"] = {
            achievementID = 1268,
            proxyLocation = { 25, 41, "Sholazar Basin" },
            waypoints = {
                { 48, 64, "River's Heart" },
                { 46, 26, "The Savage Thicket" },
                { 36, 75, "The Mosslight Pillar" },
                { 80, 55, "Makers' Overlook" },
                { 28, 39, "Makers' Perch" },
                { 33, 52, "The Suntouched Pillar" },
                { 53, 56, "Rainspeaker Canopy" },
                { 66, 59, "The Lifeblood Pillar" },
                { 73, 36, "The Avalanche" },
                { 49, 38, "The Glimmering Pillar" },
                { 24, 80, "Kartak's Hold" },
                { 23, 33, "The Stormwright's Shelf" },
            },
        },
        ["Icecrown"] = {
            achievementID = 1270,
            proxyLocation = { 40, 28, "Icecrown" },
            waypoints = {
                { 64, 45, "The Bombardment" },
                { 54, 87, "Icecrown Citadel" },
                { 9, 44, "Onslaught Harbor" },
                { 69, 66, "The Broken Front" },
                { 34, 68, "The Fleshwerks" },
                { 53, 34, "Aldur'thar: The Desolation Gate" },
                { 74, 39, "Sindragosa's Fall" },
                { 33, 27, "Valhalas" },
                { 85, 74, "Valley of Echoes" },
                { 56, 56, "Ymirheim" },
                { 44, 54, "The Conflagration" },
                { 48, 69, "Corp'rethar: The Horror Gate" },
                { 29, 37, "Jotunheim" },
                { 78, 55, "Scourgeholme" },
                { 43, 22, "The Shadow Vault" },
            },
        },
        ["Crystalsong Forest"] = {
            achievementID = 1457,
            proxyLocation = { 51, 41, "Crystalsong Forest" },
            waypoints = {
                { 26, 64, "The Azure Front" },
                { 16, 13, "The Decrepit Flow" },
                { 76, 48, "Sunreaver's Command" },
                { 45, 45, "Forlorn Woods" },
                { 74, 81, "Windrunner's Overlook" },
                { 13, 34, "The Great Tree" },
                { 14, 43, "Violet Stand" },
                { 73, 63, "The Unbound Thicket" },
            },
        },
    },

    -- Cataclysm
    ["The Maelstrom"] = {
        ["Deepholm"] = {
            achievementID = 4864,
            proxyLocation = { 51, 28, "Deepholm" },
            waypoints = {
                { 62, 59, "Deathwing's Fall" },
                { 26, 33, "Needlerock Chasm" },
                { 22, 48, "Needlerock Slag" },
                { 26, 70, "Stonehearth" },
                { 56, 76, "Storm's Fury Wreckage" },
                { 49, 49, "Temple of Earth" },
                { 41, 18, "The Pale Roost" },
                { 56, 13, "Therazane's Throne" },
                { 35, 82, "The Quaking Fields" },
                { 68, 78, "Twilight Overlook" },
                { 39, 69, "Masters' Gate" },
                { 72, 41, "Crimson Expanse" },
            },
        },
    },
    ["Vashj'ir"] = {
        ["Kelp'thar Forest"] = {
            achievementID = 4825,
            proxyLocation = { 73, 24, "Kelp'thar Forest" },
            waypoints = {
                { 40, 29, "Legion's Fate" },
                { 50, 26, "Seafarer's Tomb" },
                { 54, 55, "Gurboggle's Ledge" },
                { 61, 50, "The Skeletal Reef" },
                { 61, 61, "Gnaws' Boneyard" },
                { 58, 80, "The Clutch" },
            },
        },
        ["Shimmering Expanse"] = {
            achievementID = 4825,
            proxyLocation = { 63, 57, "Shimmering Expanse" },
            waypoints = {
                { 51, 23, "Shimmering Grotto" },
                { 48, 38, "Silver Tide Hollow" },
                { 45, 50, "Glimmerdeep Gorge" },
                { 59, 55, "Nespirah" },
                { 65, 44, "Ruins of Thelserai Temple" },
                { 34, 74, "Ruins of Vashj'ir" },
                { 56, 82, "Beth'mora Ridge" },
            },
        },
        ["Abyssal Depths"] = {
            achievementID = 4825,
            proxyLocation = { 42, 48, "Abyssal Depths" },
            waypoints = {
                { 70, 29, "Abyssal Breach" },
                { 40, 19, "Deepfin Ridge" },
                { 47, 33, "The Scalding Chasm" },
                { 54, 48, "Seabrush" },
                { 33, 53, "L'ghorek" },
                { 44, 72, "Underlight Canyon" },
                { 54, 72, "Korthun's End" },
                { 23, 75, "Abandoned Reef" },
            },
        },
    },

    -- Retail continents

    -- Mists of Pandaria
    ["Pandaria"] = {
        ["The Jade Forest"] = {
            achievementID = 6351,
            proxyLocation = { 66, 48, "Jade Forest" },
            waypoints = {
                { 41, 21, "Tian Monastery" },
                { 48, 45, "Dawn's Blossom" },
                { 61, 91, "Dreamer's Pavillion" },
                { 50, 26, "Emperor's Omen" },
                { 57, 78, "Pearl Lake" },
                { 26, 49, "Grookin Hill" },
                { 47, 29, "Greenstone Quarry" },
                { 40, 73, "Nectarbreeze Orchard" },
                { 25, 37, "Camp Nooka Nooka" },
                { 40, 13, "Terrace of Ten Thunders" },
                { 47, 60, "Serpent's Heart" },
                { 52, 82, "Slingtail Pits" },
                { 57, 57, "Temple of the Jade Serpent" },
                { 57, 44, "The Arboretum" },
                { 46, 90, "Garrosh'ar Point" },
                { 65, 30, "Windward Isle" },
                { 29, 13, "Honeydew Village" },
            },
        },
        ["Krasarang Wilds"] = {
            achievementID = 6975,
            proxyLocation = { 52, 76, "Krasarang Wilds" },
            waypoints = {
                { 67, 44, "Anglers Wharf" },
                { 33, 70, "Cradle of Chi-Ji" },
                { 64, 31, "Dojani River" },
                { 29, 38, "Fallsong Village" },
                { 82, 26, "Krasarang Cove" },
                { 70, 22, "The Krasari Ruins" },
                { 41, 75, "Nayeli Lagoon" },
                { 40, 33, "Crane Wing Refuge" },
                { 55, 34, "Ruins of Dojan" },
                { 24, 45, "Ruins of Korja" },
                { 40, 55, "Temple of the Red Crane" },
                { 46, 38, "The Deepwild" },
                { 21, 35, "The Forbidden Jungle" },
                { 16, 56, "The Southern Isles" },
                { 47, 90, "Unga Ingoo" },
                { 77, 10, "Zhu's Watch" },
            },
        },
        ["Townlong Steppes"] = {
            achievementID = 6977,
            proxyLocation = { 34, 46, "Townlong Steppes" },
            waypoints = {
                { 76, 82, "Gao-Ran Battlefront" },
                { 55, 52, "Kri'vess" },
                { 54, 78, "Rensai's Watchpost" },
                { 41, 63, "Niuzao Temple" },
                { 67, 47, "Fire Camp Osul" },
                { 84, 72, "Hatred's Vice" },
                { 48, 70, "Shado-Pan Garrison" },
                { 29, 27, "Shan'ze Dao" },
                { 22, 52, "Sra'vess" },
                { 45, 86, "Sik'vess" },
                { 66, 65, "The Sumprushes" },
            },
        },
        ["Vale of Eternal Blossoms"] = {
            achievementID = 6979,
            proxyLocation = { 51, 53, "Vale of Eternal Blossoms" },
            waypoints = {
                { 29, 37, "Ruins of Guo-Lai" },
                { 38, 73, "Mistfall Village" },
                { 80, 34, "Mogu'shan Palace" },
                { 21, 71, "Setting Sun Garrison" },
                { 46, 16, "The Golden Stair" },
                { 86, 65, "Shrine of Seven Stars" },
                { 62, 20, "Shrine of Two Moons" },
                { 56, 43, "The Golden Pagoda" },
                { 44, 61, "Tu Shen Burial Ground" },
                { 41, 46, "Whitepetal Lake" },
                { 17, 45, "The Five Sisters" },
            },
        },
        ["Valley of the Four Winds"] = {
            achievementID = 6969,
            proxyLocation = { 51, 65, "Valley of the Four Winds" },
            waypoints = {
                { 51, 77, "Wind's Edge" },
                { 13, 76, "Dustback Gorge" },
                { 56, 36, "Gilded Fan" },
                { 51, 63, "The Imperial Granary" },
                { 54, 46, "Halfhill" },
                { 18, 55, "Stoneplow" },
                { 31, 30, "Kunzen Village" },
                { 68, 43, "Mudmug's Place" },
                { 18, 81, "Nesingwary Safari" },
                { 16, 35, "Paoquan Hollow" },
                { 60, 27, "Pools of Purity" },
                { 70, 65, "Rumbling Terrace" },
                { 63, 57, "Silken Fields" },
                { 25, 43, "Singing Marshes" },
                { 34, 70, "Stormstout Brewery" },
                { 39, 39, "The Heartland" },
                { 75, 25, "Thunderfoot Ranch" },
                { 80, 41, "Zhu's Descent" },
            },
        },
        ["Kun-Lai Summit"] = {
            achievementID = 6976,
            proxyLocation = { 47, 36, "Kun-Lai Summit" },
            waypoints = {
                { 72, 91, "Binan Village" },
                { 44, 86, "Firebough Nook" },
                { 55, 91, "Gate of the August Celestials" },
                { 75, 13, "Isle of Reckoning" },
                { 35, 65, "Kota Peak" },
                { 59, 72, "Mogujia" },
                { 45, 51, "Mont Neverest" },
                { 68, 73, "Muskpaw Ranch" },
                { 49, 40, "Peak of Serenity" },
                { 34, 47, "Shado-Pan Monastery" },
                { 68, 48, "Temple of the White Tiger" },
                { 47, 67, "The Burlap Trail" },
                { 57, 47, "Valley of Emperors" },
                { 62, 29, "Zouchin Village" },
            },
        },
        ["Dread Wastes"] = {
            achievementID = 6978,
            proxyLocation = { 35, 64, "Dread Wastes" },
            waypoints = {
                { 40, 34, "Heart of Fear" },
                { 55, 35, "Klaxxi'vess" },
                { 57, 17, "Kypari Vor" },
                { 59, 57, "Kypari Zar" },
                { 35, 19, "Rikkitun Village" },
                { 56, 70, "Soggy's Gamble" },
                { 70, 25, "Terrace of Gurthan" },
                { 39, 65, "The Briny Muck" },
                { 47, 35, "The Clutches of Shek'zeer" },
                { 50, 11, "The Sunset Brewgarden" },
                { 66, 44, "Writhingwood" },
                { 30, 75, "Zan'vess" },
            },
        },
    },

    -- Warlords of Draenor
    ["Draenor"] = {
        ["Frostfire Ridge"] = {
            achievementID = 8937,
            proxyLocation = { 33, 29, "Frostfire Ridge" },
            waypoints = {
                { 58.3, 31.4, "Colossal's Fall" },
                { 52.2, 45.5, "The Cracking Plains" },
                { 48.7, 46.8, "The Boneslag" },
                { 23.4, 54.1, "Wor'gol" },
                { 27, 36, "Bladespire Citadel" },
                { 31.2, 23.5, "Frostwind Crag" },
                { 44.6, 31.2, "Daggermaw Ravine" },
                { 65.4, 47.3, "Grimfrost Hill" },
                { 74.7, 61.2, "Iron Waystation" },
                { 41.7, 19.8, "Bloodmaul Stronghold" },
                { 82.5, 60.4, "Bones of Agurak" },
                { 59.9, 58.5, "Grom'gar" },
                { 82, 57.4, "Iron Siegeworks" },
                { 68, 32, "Magnarok" },
                { 46.4, 52.2, "Stonefang Outpost" },
            },
        },
        ["Shadowmoon Valley"] = {
            achievementID = 8938,
            proxyLocation = { 57, 68, "Shadowmoon Valley" },
            waypoints = {
                { 28, 35, "Anguish Fortress" },
                { 57, 26, "Elodor" },
                { 36, 27, "Gloomshade Grove" },
                { 79, 46, "Karabor" },
                { 58, 59, "The Shimmer Moor" },
                { 42, 80, "Isle of Shadows" },
                { 43, 35, "Embaari Village" },
                { 20, 13, "Gul'var" },
                { 41, 58, "Shaz'gul" },
                { 44, 69, "Socrethar's Rise" },
                { 44, 69, "Darktide Roost" },
            },
        },
        ["Gorgrond"] = {
            achievementID = 8939,
            proxyLocation = { 50, 27, "Gorgrond" },
            waypoints = {
                { 48, 79, "Bastion Rise" },
                { 54, 33, "Grimrail Depot" },
                { 37, 75, "Deadgrin" },
                { 44, 79, "Evermorn Springs" },
                { 52, 59, "Highpass" },
                { 43, 66, "Stonemaul Arena" },
                { 43, 20, "The Iron Approach" },
                { 45, 71, "Beastwatch" },
                { 50, 69, "Crimson Fen" },
                { 54, 44, "Everbloom Wilds" },
                { 46, 45, "Gronn Canyon" },
                { 61, 51, "Iyun Weald" },
                { 50, 70, "Tangleheart" },
                { 59, 88, "The Pit" },
            },
        },
        ["Talador"] = {
            achievementID = 8940,
            proxyLocation = { 42, 58, "Talador" },
            waypoints = {
                { 79, 43, "Aruuna" },
                { 49, 60, "Auchindoun" },
                { 41, 58, "Court of Souls" },
                { 70, 57, "Duskfall Island" },
                { 69, 21, "Fort Wrynn" },
                { 69, 69, "Gordal Fortress" },
                { 38, 79, "Gul'rok" },
                { 59, 9, "Orunai Coast" },
                { 49, 35, "Shattrath City" },
                { 46, 89, "Telmor" },
                { 66, 9, "The Path of Glory" },
                { 58, 65, "Tomb of Lights" },
                { 59, 32, "Tuurem" },
                { 78, 27, "Zangarra" },
                { 78, 55, "Anchorite's Sojourn" },
            },
        },
        ["Spires of Arak"] = {
            achievementID = 8941,
            proxyLocation = { 47, 74, "Spires of Arak" },
            waypoints = {
                { 52, 6, "Skettis" },
                { 36, 42, "The Writhing Mire" },
                { 62, 57, "Veil Zekk" },
                { 42, 58, "Southport" },
                { 50, 47, "Terrace of Dawn" },
                { 31, 28, "Bladefist Hold" },
                { 73, 34, "Lost Veil Anzu" },
                { 53, 51, "Ravenskar" },
                { 39, 44, "Axefall" },
                { 64, 22, "The Howling Crag" },
                { 56, 85, "Pinchwhistle Point" },
                { 41, 23, "Veil Akraz" },
                { 47, 52, "Windswept Terrace" },
                { 64, 49, "Sethekk Hollow" },
                { 40, 49, "Admiral Taylor's Garrison" },
                { 61, 70, "Pinchwhistle Gearworks" },
                { 48, 61, "Bloodmane Valley" },
            },
        },
        ["Nagrand"] = {
            achievementID = 8942,
            proxyLocation = { 29, 51, "Nagrand" },
            waypoints = {
                { 41, 56, "Ancestral Grounds" },
                { 42, 27, "Broken Precipice" },
                { 75, 68, "Gates of Grommashar" },
                { 85, 51, "Hallvalor" },
                { 37, 32, "Highmaul Harbor" },
                { 44, 76, "Ironfist Harbor" },
                { 59, 45, "Lok-rath" },
                { 80, 67, "Mar'gok's Overwatch" },
                { 44, 31, "Mok'gol Watchpost" },
                { 51, 61, "Oshu'gun" },
                { 69, 64, "Telaar" },
                { 55, 15, "The Ring of Blood" },
                { 79, 49, "The Ring of Trials" },
                { 71, 19, "Throne of the Elements" },
                { 86, 27, "Zangar Shore" },
            },
        },
    },

    -- Legion
    ["Broken Isles"] = {
        ["Azsuna"] = {
            achievementID = 10665,
            proxyLocation = { 33, 56, "Azsuna" },
            waypoints = {
                { 39.6, 50.2, "Faronaar" },
                { 60.6, 34.9, "The Greenway" },
                { 41.4, 39.0, "Llothien Highlands" },
                { 55.7, 41.4, "Nar'thalas" },
                { 65.6, 49.0, "Ruined Sanctum" },
                { 52.7, 16.8, "Ley-Ruins of Zarkhenar" },
                { 65.8, 27.9, "Felblaze Ingress" },
                { 46.8, 73.1, "Isle of the Watchers" },
                { 48.0, 13.6, "Lost Orchard" },
                { 53.3, 58.9, "Oceanus Cove" },
                { 57.1, 64.8, "Temple of Lights" },
            },
        },
        ["Highmountain"] = {
            achievementID = 10667,
            proxyLocation = { 46, 21, "Highmountain" },
            waypoints = {
                { 43.0, 33.5, "Bloodhunt Highlands" },
                { 48, 79, "Frosthoof Watch" }, -- Coordinates need to be added
                { 27.3, 54.6, "Nightwatcher's Perch" },
                { 38.9, 67.8, "Riverbend" },
                { 43.7, 8.7, "Shipwreck Cove" },
                { 58.7, 64.7, "Stonehoof Watch" },
                { 46.2, 61.4, "Thunder Totem" },
                { 29.3, 33.4, "Blind Marshlands" },
                { 55.6, 83.9, "Ironhorn Enclave" },
                { 43.1, 51.7, "Pinerock Basin" },
                { 56.4, 21.8, "Rockaway Shallows" },
                { 52.6, 44.8, "Skyhorn" },
                { 35.6, 63.6, "Sylvan Falls" },
                { 35, 54, "Trueshot Lodge" },
            },
        },
        ["Stormheim"] = {
            achievementID = 10668,
            proxyLocation = { 58, 32, "Stormheim" },
            waypoints = {
                { 47.2, 44.8, "Aggrammar's Vault" },
                { 55.6, 73.6, "Dreadwake's Landing" },
                { 72.0, 60.0, "Greywatch" },
                { 73.4, 39.7, "Haustvald" },
                { 35, 27, "Maw of Nashal" },
                { 44.9, 37.0, "Nastrondir" },
                { 71.5, 50.1, "The Runewood" },
                { 60.8, 65.5, "Skold-Ashil" },
                { 51.4, 57.0, "Talonrest" },
                { 60.4, 51.1, "Valdisdall" },
                { 33.9, 34.7, "Blackbeak Overlook" },
                { 75.2, 54.8, "Dreyrgrot" },
                { 66.8, 64.1, "Gates of Valor" },
                { 44.3, 64.5, "Hrydshal" },
                { 80.1, 59.2, "Morheim" },
                { 69.9, 22.0, "Watchman's Rock" },
                { 77.8, 6.7, "Shield's Rest" },
                { 59.1, 31.2, "Storm's Reach" },
                { 58.0, 44.4, "Tideskorn Harbor" },
                { 34.5, 51.3, "Weeping Bluffs" },
            },
        },
        ["Suramar"] = {
            achievementID = 10669,
            proxyLocation = { 45, 44, "Suramar" },
            waypoints = {
                { 30.4, 42.3, "Ambervale" },
                { 19.5, 45.2, "Falanaar" },
                { 47.3, 50.4, "The Grand Promenade" },
                { 38.1, 22.9, "Moon Guard Stronghold" },
                { 37.0, 45.9, "Ruins of Elun'eth" },
                { 46.2, 36.5, "Tel'anor" },
                { 64.0, 42.0, "Crimson Thicket" },
                { 34.3, 74.8, "Felsoul Hold" },
                { 71.5, 51.1, "Jandvik" },
                { 34.9, 31.0, "Moonwhisper Gulch" },
                { 46.1, 59.8, "Suramar City" },
            },
        },
        ["Val'sharah"] = {
            achievementID = 10666,  -- Achievement ID for exploring Val'sharah
            proxyLocation = { 34, 34, "Val'sharah" },
            waypoints = {
                { 67.6, 56.4, "Andutalah" },
                { 42.4, 58.6, "Bradensbrook" },
                { 25.5, 66.5, "Gloaming Reef" },
                { 54.6, 73.0, "Lorlathil" },
                { 61.2, 73.1, "Moonclaw Vale" },
                { 47.3, 85.1, "Smolderhide Thicket" },
                { 47.9, 69.6, "Thas'talah" },
                { 38.8, 51.8, "Black Rook Hold" },
                { 44.2, 30.4, "The Dreamgrove" },
                { 51.9, 64.0, "Grove of Cenarius" },
                { 71.6, 39.1, "Mistvale" },
                { 61.1, 31.1, "Shala'nir" },
                { 54.1, 55.4, "Temple of Elune" },
            },
        },
    },

    -- Battle for Azeroth
    ["Zandalar"] = {
        ["Zuldazar"] = {
            achievementID = 12559,
            proxyLocation = { 54, 55, "Zuldazar" },
            waypoints = {
                { 43.69, 39.10, "Atal'Dazar" },
                { 59.25, 18.77, "Blood Gate" },
                { 72.35, 66.27, "Dreadpearl Shallows" },
                { 69.30, 31.63, "Savagelands" },
                { 59.38, 77.95, "Tusk Isle" },
                { 45.26, 70.65, "Xibala" },
                { 78.70, 38.72, "Atal'Gral" },
                { 59.21, 41.63, "Dazar'alor" },
                { 49.72, 26.55, "Garden of the Loa" },
                { 51.11, 26.88, "The Sliver" },
                { 77.62, 49.91, "Talanji's Rebuke" },
                { 74.07, 20.68, "Zeb'ahari" },
            },
        },
        ["Vol'dun"] = {
            achievementID = 12560,
            proxyLocation = { 38, 30, "Vol'dun" },
            waypoints = {
                { 44.92, 58.99, "Atul'Aman" },
                { 33.03, 76.82, "Port of Zem'lan" },
                { 39.15, 34.28, "Shatterstone Harbor" },
                { 53.19, 89.49, "Temple of Akunda" },
                { 43.44, 49.80, "The Bone Pit" },
                { 24.04, 66.45, "The Cracked Coast" },
                { 42.88, 61.42, "Whistlebloom Oasis" },
                { 62.84, 26.79, "Darkwood Shoal" },
                { 43.57, 87.94, "Redrock Harbor" },
                { 51.94, 33.05, "Slithering Gulch" },
                { 29.20, 51.24, "Terrace of the Devoted" },
                { 57.13, 41.45, "The Brine Basin" },
                { 61.63, 21.33, "Tortaka Refuge" },
            },
        },
        ["Nazmir"] = {
            achievementID = 12561,
            proxyLocation = { 57, 29, "Nazmir" },
            waypoints = {
                { 37.00, 73.39, "Primal Wetlands" },
                { 42.82, 83.27, "The Rivermarsh" },
                { 30.92, 46.30, "Zalamar" },
                { 65.14, 40.21, "Nazwatha" },
                { 71.92, 49.90, "The Frogmarsh" },
                { 51.61, 59.68, "Heart of Darkness" },
                { 39.53, 33.52, "The Necropolis" },
                { 61.66, 29.99, "Torga's Rest" },
                { 63.60, 61.21, "Zal'amak" },
            },
        },
    },
    ["Kul Tiras"] = {
        ["Stormsong Valley"] = {
            achievementID = 12558,
            proxyLocation = { 54, 26, "Stormsong Valley" },  -- Using Brennadam as a central point
            waypoints = {
                { 56.79, 69.34, "Brennadam" },
                { 63.70, 64.27, "Mariner's Strand" },
                { 44.39, 52.36, "Deadwash" },
                { 62.76, 40.96, "Sagehold" },
                { 29.74, 64.23, "Millstone Hamlet" },
                { 47.46, 72.46, "Briarback Kraul" },
                { 49.53, 35.10, "Warfang Hold" },
                { 36.29, 50.52, "Fort Daelin" },
                { 78.20, 26.67, "Shrine of the Storm" },
            },
        },
        ["Drustvar"] = {
            achievementID = 12557,
            proxyLocation = { 36, 68, "Drustvar" },  -- Using a central point in Drustvar
            waypoints = {
                { 36.76, 48.89, "Arom's Stand" },
                { 64.94, 31.58, "Carver's Harbor" },
                { 25.51, 54.10, "Crimson Forest" },
                { 67.46, 67.31, "Fletcher's Hollow" },
                { 44.76, 37.44, "Highroad Pass" },
                { 50.41, 73.13, "Iceveil Glacier" },
                { 61.19, 44.73, "Barrowknoll Cemetery" },
                { 28.48, 27.42, "Corlain" },
                { 56.97, 33.90, "Fallhaven" },
                { 58.99, 66.66, "Gol Koval" },
                { 19.36, 8.83, "Western Watch" },
                { 33.75, 13.26, "Waycrest Manor" },
            },
        },
        ["Tiragarde Sound"] = {
            achievementID = 12556,
            proxyLocation = { 58, 56, "Tiragarde Sound" },  -- Using Boralus as a central point
            waypoints = {
                { 41.14, 26.80, "Anglepoint Wharf" },
                { 71.90, 17.51, "Fernwood Ridge" },
                { 52.59, 28.67, "Norwington Estate" },
                { 63.96, 62.15, "Abandoned Junkheap" },
                { 87.12, 76.77, "The Wailing Tideway" },
                { 42.08, 16.53, "Waning Glacier" },
                { 67.15, 30.1, "Boralus" },
                { 76.97, 82.44, "Freehold" },
                { 35.50, 28.98, "Krakenbane Cove" },
                { 76.40, 63.49, "Kennings Lodge" },
                { 56.01, 60.46, "Vigil Hill" },
            },
        },
    },
}