Localization = Localization or {}

Localization["esES"] = {
    ["Reinos del Este"] = {
        ["Bosque de Elwynn"] = {
            achievementID = 776,
            proxyLocation = {45, 74, "Bosque de Elwynn"},
            waypoints = {
                {48, 41, "Valle de Villanorte"},
                {42, 65, "Villadorada"},
                {48, 86, "Embarcadero de Jerod"},
                {69, 80, "Plantación de Calabazas de Brackwell"},
                {84, 80, "Torre de la Peña"},
                {74, 52, "Lago del Hito"},
                {24, 76, "Cuartel de Arroyoeste"},
                {38, 81, "Mina Abisal"},
                {64, 71, "Torre de Azora"},
                {82, 67, "Aserradero de la Vega del Este"},
                {52, 66, "Lago de Cristal"},
            },
        },
        ["Tierras Inhóspitas"] = {
            achievementID = 765,
            proxyLocation = {53, 66, "Tierras Inhóspitas"},
            waypoints = {
                {70, 46, "Barranco Lethlor"},
                {43, 11, "Uldaman"},
                {36, 51, "Cicatriz del Rompemundos"},
                {40, 27, "Fortaleza de Angor"},
                {51, 49, "Paso de Mirasangre"},
                {45, 58, "El Final de Agmond"},
                {15, 66, "Asentamiento Cagg"},
                {26, 45, "Terraseca"},
                {59, 20, "Asentamiento Kosh"},
                {16, 44, "Nuevo Kargath"},
            },
        },
        ["Las Estepas Ardientes"] = {
            achievementID = 775,
            proxyLocation = {50, 71, "Las Estepas Ardientes"},
            waypoints = {
                {69, 42, "Roca Machacamiedo"},
                {75, 52, "Senda del Ala del Terror"},
                {55, 38, "Ruinas de Thaurissan"},
                {32, 36, "Bastión de Roca Negra"},
                {9, 29, "Altar de la Tempestad"},
                {73, 66, "Vigilia de Morgan"},
                {66, 73, "Desfiladero de Roca Negra"},
                {36, 53, "Cobertizo Diente Negro"},
                {19, 65, "Las Colinas de los Vástagos"},
                {20, 35, "Montaña Roca Negra"},
            },
        },
        ["Bosque del Ocaso"] = {
            achievementID = 778,
            proxyLocation = {46, 80, "Bosque del Ocaso"},
            waypoints = {
                --{0, 0, "The Hushed Bank"},
                {35, 73, "Cerro del Cuervo"},
                {49, 73, "Túmulo de Vul'Gol"},
                {64, 71, "La Hacienda Yorgen"},
                {74, 47, "El Vergel Pútrido"},
                {56, 16, "Villa Oscura"},
                {21, 69, "La Ribera Lóbrega"},
                {19, 41, "Granja de Addle"},
                {47, 40, "Cementerio del Cerro del Cuervo"},
                {65, 38, "Arboleda del Crepúsculo"},
                {79, 69, "Arboleda del Destello"},
                {77, 36, "Cementerio del Jardín Sereno"},
                {0, 0, "Mansión Mantoniebla"},
            },
        },
        ["Loch Modan"] = {
            achievementID = 779,
            proxyLocation = {0, 0, "Loch Modan"},
            waypoints = {
                {70, 26, "Loch Modan"},
                {19, 17, "Fortaleza de Mo'grosh"},
                {68, 63, "Paso de la Puerta Norte"},
                {35, 47, "Excavación de Vetaferro"},
                {21, 74, "Thelsamar"},
                {48, 12, "Valle de los Reyes"},
                {34, 20, "Presa de las Tres Cabezas"},
                {82, 63, "Mina de Fuenteplata"},
                {36, 62, "Cabaña del Errante"},
                {32, 78, "Fuerte Zarpagris"},
                {0, 0, "Valle Rompecantos"},
            },
        },
        ["Claros de Tirisfal"] = {
            achievementID = 768,
            proxyLocation = {0, 0, "Claros de Tirisfal"},
            waypoints = {
                {46, 33, "Camposanto"},
                {53, 57, "Molinos de Agamand"},
                {58, 36, "Mansión Friogar"},
                {75, 60, "Granja de Garren"},
                {79, 27, "Hacienda Balnir"},
                {62, 69, "Atalaya Escarlata"},
                {28, 58, "Ruinas de Lordaeron"},
                {38, 49, "El Baluarte"},
                {45, 66, "Hacienda Solliden"},
                {61, 51, "Vega Pesadilla"},
                {68, 46, "Rémol"},
                {79, 55, "Lago Aguasclaras"},
                {86, 46, "Avanzada de los Cruzados"},
                {83, 32, "Vega Venerácnidas"},
                {44, 53, "Entrada del Monasterio Escarlata"},
                {0, 0, "Dominios de Calston"},
            },
        },
        ["La Garganta de Fuego"] = {
            achievementID = 774,
            proxyLocation = {0, 0, "La Garganta de Fuego"},
            waypoints = {
                {20, 80, "Cresta Vigía"},
                {65, 58, "Cueva Tizonegro"},
                {36, 27, "Excavación de Limugre"},
                {48, 52, "Puesto del Torio"},
                {60, 71, "La Caldera"},
                {72, 28, "El Mar de las Cenizas"},
                {20, 35, "Valle Polvofuego"},
                {0, 0, "Montaña Roca Negra"},
            },
        },
        ["Tierras Fantasma"] = {
            achievementID = 858,
            proxyLocation = {0, 0, "Tierras Fantasma"},
            waypoints = {
                {26, 15, "Tranquillien"},
                {33, 35, "Aldea Bruma Dorada"},
                {79, 21, "Sagrario de la Luna"},
                {40, 49, "Aguja de la Estrella del Alba"},
                {65, 61, "Zigurat Aullante"},
                {13, 55, "Zeb'Nowa"},
                {48, 13, "Aguja Brisaveloz"},
                {61, 12, "Cruce Elrendar"},
                {19, 43, "Aldea Corona del Sol"},
                {55, 48, "Aldea Brisaveloz"},
                {72, 31, "Sagrario del Sol"},
                {33, 80, "Enclave del Errante"},
                {76, 64, "Ciudad de la Muerte"},
                {34, 47, "Paso de Amani"},
                {47, 78, "Zigurat Sangrante"},
                {0, 0, "Desfiladero Thalassiano"},
            },
        },
        ["El Cabo de Tuercespina"] = {
            achievementID = 4995,
            proxyLocation = {0, 0, "El Cabo de Tuercespina"},
            waypoints = {
                {47, 26, "Bahía del Botín"},
                {60, 82, "Arena Gurubashi"},
                {41, 50, "Isla Jaquero"},
                {53, 31, "Manantial Nek'mani"},
                {63, 30, "Ruinas de Jubuwal"},
                {35, 32, "Mina de Cristal"},
                {50, 56, "Escondrijo Malallave"},
                {62, 43, "Valle del Velo de Bruma"},
                {49, 78, "Ruinas de Aboraz"},
                {0, 0, "La Orilla Salvaje"},
            },
        },
        ["Las Tierras del Interior"] = {
            achievementID = 773,
            proxyLocation = {0, 0, "Las Tierras del Interior"},
            waypoints = {
                {22, 57, "Pico Nidal"},
                {34, 71, "Zun'watha"},
                {46, 40, "Shadra'Alor"},
                {48, 68, "Agol'watha"},
                {58, 41, "El Altar de Zul"},
                {63, 73, "Roca Oculta"},
                {24, 36, "Jintha'Alor"},
                {32, 46, "Barranco Bruma Enferma"},
                {41, 59, "Avanzada Quel'Danil"},
                {49, 50, "Lago Ventobravo"},
                {63, 26, "Las Ruinas Abyectas"},
                {72, 53, "Seradane"},
                {76, 59, "Shaol'watha"},
                {0, 0, "Los Acantilados Dominantes"},
            },
        },
        ["Los Humedales"] = {
            achievementID = 841,
            proxyLocation = {0, 0, "Los Humedales"},
            waypoints = {
                {18, 37, "Puerto de Menethil"},
                {28, 32, "Pantano Branquiazul"},
                {43, 26, "Pantano del Ocaso"},
                {48, 48, "Tumba de Barbaférrea"},
                {57, 41, "Campamento Dentellada"},
                {60, 27, "Arboleda del Guardaverde"},
                {58, 70, "Cerro Fraguaferoz"},
                {25, 47, "Peritaje de Tallalosas"},
                {35, 48, "Pantano del Canal Negro"},
                {32, 22, "Excavación de Whelgar"},
                {47, 16, "Cañada Salobre"},
                {51, 62, "Dun Modr"},
                {60, 56, "Roca Thelgen"},
                {48, 77, "Pantano Pellejomusgo"},
                {69, 37, "Dun Algaz"},
                {0, 0, "Colina del Raptor"},
            },
        },
        ["Tierras de la Peste del Oeste"] = {
            achievementID = 770,
            proxyLocation = {0, 0, "Tierras de la Peste del Oeste"},
            waypoints = {
                {50, 77, "Lago Darrowmere"},
                {28, 58, "Colina de las Penas"},
                {46, 52, "El Baluarte"},
                {48, 33, "Granja de Dalson"},
                {54, 46, "Aserradero Crestanorte"},
                {65, 41, "Valle Pinorrojo"},
                {69, 74, "La Cueva del Llanto"},
                {44, 68, "Castel Darrow"},
                {37, 56, "Andorhal"},
                {53, 67, "Campo de Piedramácula"},
                {45, 17, "El Tormento"},
                {62, 57, "Vega del Amparo"},
                {70, 48, "Gangrena de Gahrron"},
                {0, 0, "Río Thondroril"},
            },
        },
        ["Isla de Quel'Danas"] = {
            achievementID = 868,
            proxyLocation = {55.7, 4.7, "Isla de Quel'Danas"},
            waypoints = {
                {55.7, 4.7, "Isla de Quel'Danas"}
            },
        },
        ["Tierras Altas de Arathi"] = {
            achievementID = 761,
            proxyLocation = {51, 47, "Tierras Altas de Arathi"},
            waypoints = {
                {18, 31, "Círculo de Vínculo Oeste"},
                {28, 45, "Roca'gor"},
                {19, 62, "Castillo de Stromgarde"},
                {29, 59, "Círculo de Vínculo Interior"},
                {49, 78, "Sala Puño de Roca"},
                {47, 52, "Círculo de Vínculo Exterior"},
                {56, 58, "Granja Go'shek"},
                {61, 30, "Círculo de Vínculo Este"},
                {26, 29, "Mansión Redilnorte"},
                {13, 36, "Caída de Galen"},
                {24, 81, "Cala de Faldir"},
                {39, 89, "Puente Thandol"},
                {40, 47, "Refugio de la Zaga"},
                {60, 73, "Poblado Secacorteza"},
                {50, 40, "Granja de Dabyrie"},
                {69, 36, "Sentencia"},
            },
        },
        ["Las Tierras Devastadas"] = {
            achievementID = 766,
            proxyLocation = {52, 84, "Las Tierras Devastadas"},
            waypoints = {
                {41, 14, "Bastión Machacamiedo"},
                {61, 16, "Castillo de Nethergarde"},
                {54, 53, "El Portal Oscuro"},
                {46, 39, "Puesto Machacamiedo"},
                {44, 26, "Alto de los Rapiñadores"},
                {50, 72, "Excursión Velosolar"},
                {66, 71, "Las Costas Rojas"},
                {52, 15, "Campamento de Suministros de Nethergarde"},
                {60, 29, "Serpiente Enroscada"},
                {9, 29, "Altar de la Tempestad"},
                {32, 46, "Escara Impía"},
                {69, 36, "Costa Quebrada"},
                {44, 86, "Mechasur"},
                {34, 73, "El Bosque Corrupto"},
            },
        },
        ["Dun Morogh"] = {
            achievementID = 627,
            proxyLocation = {44, 62, "Dun Morogh"},
            waypoints = {
                {42, 66, "Desfiladero de Crestanevada"},
                {58, 59, "Frente de Peloescarcha"},
                {77, 25, "Base Aérea de Forjaz"},
                {53, 50, "Kharanos"},
                {71, 48, "Granja de Semperámbar"},
                {76, 56, "Cantera de Gol'Bolar"},
                {33, 49, "Poblado Peloescarcha"},
                {58, 36, "Puertas de Forjaz"},
                {35, 71, "Valle de Crestanevada"},
                {33, 38, "Nueva Ciudad Manitas"},
                {48, 38, "Monte Luz"},
                {65, 57, "Las Colinas Tundra"},
                {83, 51, "Lago de Helm"},
                {88, 40, "Avanzada de la Puerta Norte"},
                {41, 40, "Lago Glacial"},
            },
        },
        ["Laderas de Trabalomas"] = {
            achievementID = 772,
            proxyLocation = {47, 42, "Laderas de Trabalomas"},
            waypoints = {
                {35, 74, "Mina Azur"},
                {50, 47, "Daga de Corrahn"},
                {68, 30, "Alto del Orvallo"},
                {44, 9, "Redil de Dandred"},
                {62, 84, "Dun Garok"},
                {51, 31, "Camino de la Horca"},
                {43, 38, "Caverna Estrecha"},
                {58, 73, "Granja Nethander"},
                {43, 30, "Ruinas de Alterac"},
                {48, 19, "Cuenca de la Matanza"},
                {30, 63, "Puerta Austral"},
                {55, 47, "Molino Tarren"},
                {37, 60, "Los Campos de Lodo"},
                {33, 48, "Granja de Brazie"},
                {52, 23, "Dominios de los Aplastacresta"},
                {30, 37, "Cráter de Dalaran"},
                {45, 57, "Colinas de Darrow"},
                {68, 60, "Castillo de Durnholde"},
                {39, 48, "Saliente de Gavin"},
                {40, 18, "Costa de la Neblina"},
                {26, 86, "Isla del Purgatorio"},
                {48, 70, "Ruinas de Costasur"},
                {55, 37, "Saliente de Sofera"},
                {58, 24, "Strahnbrad"},
                {44, 50, "La Punta"},
                {51, 14, "Las Tierras Altas"},
            },
        },
        ["Montañas Crestagrana"] = {
            achievementID = 780,
            proxyLocation = {51, 76, "Montañas Crestagrana"},
            waypoints = {
                {27, 42, "Villa del Lago"},
                {18, 62, "Tres Caminos"},
                {25, 23, "Cañones de Crestagrana"},
                {68, 54, "Cascadas Petravista"},
                {35, 15, "Campamento de Render"},
                {67, 39, "Valle de Galardell"},
                {52, 55, "Campamento Sempiterno"},
                {40, 52, "Lago Sempiterno"},
                {38, 67, "Camino del Lago"},
                {48, 40, "Molino de Alther"},
                {65, 71, "Valle de Render"},
                {60, 50, "Fuerte de Petravista"},
                {78, 62, "Cañón del Viento Calizo"},
            },
        },
        ["Bosque Canción Eterna"] = {
            achievementID = 859,
            proxyLocation = {56, 17, "Bosque Canción Eterna"},
            waypoints = {
                {34, 23, "Isla del Caminante del Sol"},
                {35, 58, "Sagrario del Oeste"},
                {44, 53, "Sagrario del Norte"},
                {60, 62, "El Retiro del Errante"},
                {68, 47, "Tierras Ocaso Marchito"},
                {59, 72, "El Bosque Viviente"},
                {36, 86, "La Arboleda Agostada"},
                {72, 45, "Costa Bris Azur"},
                {33, 78, "Desfiladero Ramadorada"},
                {44, 85, "Piedra Rúnica Falithas"},
                {38, 73, "Refugio de Saltheril"},
                {61, 54, "Caballería de Thuron"},
                {62, 80, "Zeb'Watha"},
                {44, 41, "Ruinas de Lunargenta"},
                {32, 70, "Fondeadero Vela del Sol"},
                {53, 70, "Sagrario del Este"},
                {54, 55, "Charca Plácido Susurro"},
                {44, 71, "Aldea Brisa Pura"},
                {72, 75, "Tor'Watha"},
                {57, 41, "Ciudad de Lunargenta"},
                {0, 0, "Cascadas Elrendar"},
                {66, 74, "Lago Elrendar"},
                {55, 84, "Piedra Rúnica Shan'dor"},
                {23, 75, "La Ensenada Dorada"},
                {27, 59, "Orilla Tranquila"},
            },
        },
        ["Bosque de Argénteos"] = {
            achievementID = 769,
            proxyLocation = {41, 40, "Bosque de Argénteos"},
            waypoints = {
                {45, 76, "El Frente de Batalla"},
                {50, 68, "El Frente Renegado"},
                {38, 27, "Desembarco Mareanorte"},
                {53, 25, "Campo de Valgan"},
                {56, 47, "Mina de Elem"},
                {61, 63, "Molino Ámbar"},
                {57, 10, "Alto Mando Renegado"},
                {44, 20, "Puesto de Retaguardia Renegado"},
                {54, 34, "Los Campos Decrépitos"},
                {35, 14, "Penumbra de las Celerácnidas"},
                {67, 28, "Isla de Fenris"},
                {44, 41, "El Sepulcro"},
                {45, 51, "Finca de Olsen"},
                {44, 67, "Castillo de Colmillo Oscuro"},
                {34, 20, "Cala Mareanorte"},
            },
        },
        ["Norte de la Vega de Tuercespina"] = {
            achievementID = 781,
            proxyLocation = {48, 87, "Norte de la Vega de Tuercespina"},
            waypoints = {
                {38, 50, "Campamento Grom'gol"},
                {64, 40, "Bambala"},
                {19, 24, "Ruinas Zuuldaia"},
                {47, 11, "Asentamiento Rebelde"},
                {42, 39, "Ruinas de Kal'ai"},
                {66, 51, "Túmulo Ogro Mosh'Ogg"},
                {34, 36, "Ruinas de Bal'lal"},
                {26, 20, "Ruinas de Zul'Kunda"},
                {60, 55, "Ruinas de Balia'mah"},
                {52, 66, "Fuerte Livingston"},
                {44, 23, "Expedición de Nesingwary"},
                {59, 20, "Base de Kurzen"},
                {46, 53, "Ruinas de Mizjah"},
                {52, 35, "Lago Nazferiti"},
                {27, 50, "El Arrecife Mortal"},
                {82, 30, "Zul'Gurub"},
            },
        },
        ["Pantano de las Penas"] = {
            achievementID = 782,
            proxyLocation = {53, 79, "Pantano de las Penas"},
            waypoints = {
                {15, 37, "Valle Brumoso"},
                {21, 50, "Cruce Lanzarrota"},
                {47, 54, "Rocal"},
                {69, 74, "Stagalbog"},
                {72, 14, "Chapaleos"},
                {18, 66, "Cueva de Manantial"},
                {28, 33, "El Puerto"},
                {41, 39, "Lodo Traicionero"},
                {69, 53, "Charca de Lágrimas"},
                {83, 39, "Tinieblas de las Penas"},
                {86, 24, "Playa Juncobruma"},
                {68, 36, "Avanzada Marea Pantanosa"},
            },
        },
        ["Páramos de Poniente"] = {
            achievementID = 802,
            proxyLocation = {41, 80, "Páramos de Poniente"},
            waypoints = {
                {56, 50, "Colina del Centinela"},
                {51, 21, "Plantación de Calabazas de Cejade"},
                {44, 24, "Mina de Jango"},
                {61, 59, "El Campo Funesto"},
                {38, 52, "Hacienda de Alexston"},
                {44, 80, "Las Colinas Afiladas"},
                {61, 72, "Los Yermos Polvorientos"},
                {54, 31, "Finca de Saldean"},
                {58, 17, "La Finca de Jansen"},
                {45, 35, "La Granja de Molsen"},
                {41, 66, "Arroyo de la Luna"},
                {34, 70, "Paraje de Demont"},
                {38, 42, "La Sima Enfurecida"},
            },
        },
        ["Paso de la Muerte"] = {
            achievementID = 777,
            proxyLocation = {50, 80, "Paso de la Muerte"},
            waypoints = {
                {45, 44, "Cruce de la Muerte"},
                {45, 73, "Karazhan"},
                {58, 67, "El Vicio"},
            },
        },
        ["Tierras de la Peste del Este"] = {
            achievementID = 771,
            proxyLocation = {55, 32, "Tierras de la Peste del Este"},
            waypoints = {
                {70, 48, "Río Thondroril"},
                {24, 78, "La Subgranja"},
                {35, 46, "Cuenca Fungal"},
                {69, 56, "Cicatriz Pestilente"},
                {56, 74, "Lago Mereldar"},
                {75, 53, "Capilla de la Esperanza de la Luz"},
                {78, 37, "El Claro Ponzoñoso"},
                {46, 43, "Lago del Bosque Negro"},
                {64, 12, "Zul'Mashar"},
                {48, 13, "Refugio Quel'Lithien"},
                {29, 26, "Bosque de la Peste"},
                {88, 73, "Ruinas de El Enclave Escarlata"},
                {23, 67, "Hacienda de Marris"},
                {35, 68, "Torre de la Corona"},
                {34, 83, "Villa Darrow"},
                {55, 62, "Cruce de Corin"},
                {76, 75, "Mano de Tyr"},
                {49, 65, "La Cicatriz Purulenta"},
                {62, 42, "Torre de la Muralla del Este"},
                {65, 27, "Vallenorte"},
                {50, 20, "Torre del Paso Norte"},
                {12, 27, "Valle del Terror"},
                {27, 10, "Stratholme"},
            },
        },
        ["Tierras Altas Crepusculares"] = {
            achievementID = 4866,
            proxyLocation = {56, 55, "Tierras Altas Crepusculares"},
            waypoints = {
                {54, 41, "Garganta de Sangre"},
                {47, 77, "Machacolpe"},
                {75, 57, "Puerto Faucedraco"},
                {61, 56, "Patrulla de Barbafuego"},
                {62, 46, "Campamento de Guerra Gorshak"},
                {78, 75, "Bancalto"},
                {39, 21, "Conflagración de Humboldt"},
                {57, 81, "Bosque Obsidiana"},
                {70, 41, "Cala Serpenteante"},
                {37, 39, "La Garganta"},
                {40, 46, "La Brecha Crepuscular"},
                {71, 71, "Orilla Crepuscular"},
                {42, 58, "Paso del Invicto"},
                {50, 14, "Las Fauces de la Locura"},
                {50, 56, "Crisol de Matanza"},
                {25, 37, "Paso Faucedraco"},
                {48, 70, "Ruinas Montocre"},
                {36, 35, "Foso Tripal"},
                {21, 55, "Grim Batol"},
                {54, 63, "Bosque de las Tierras Altas"},
                {57, 18, "Kirthaven"},
                {44, 14, "Ruinas de Drakgor"},
                {59, 30, "La Brecha Negra"},
                {76, 16, "La Krazzería"},
                {47, 28, "Bramal"},
                {28, 25, "Reducto Bermellón"},
                {29, 48, "Recodo de Vermis"},
            },
        }, -- Cataclysm
        ["Vashj'ir"] = {
            achievementID = 4825,
            proxyLocation = {32, 63, "Vashj'ir"},
            waypoints = {
                {23, 75, "Arrecife Abandonado"},
                {44, 72, "Cañón Sondaluz"},
                {54, 72, "Fin de Korthun"},
                {54, 48, "Malezamarina"},
                {45, 50, "Barranco Brillohondo"},
                {54, 55, "Saliente de Guraturdido"},
                {50, 26, "Tumba del Navegante"},
                {61, 50, "Arrecife de Huesos"},
                {59, 55, "Nespirah"},
                {34, 74, "Ruinas de Vashj'ir"},
                {48, 38, "Cuenca de Marea Argenta"},
                {70, 29, "Brecha Abisal"},
                {40, 19, "Cresta de Aleta Profunda"},
                {33, 53, "L'ghorek"},
                {47, 33, "La Sima Escaldante"},
                {61, 61, "Fosa de Bocados"},
                {58, 80, "El Encierro"},
                {40, 29, "Destino de la Legión"},
                {56, 82, "Cresta de Beth'mora"},
                {65, 44, "Ruinas del Templo Thelserai"},
                {51, 23, "Gruta Bruñida"},
            },
        }, -- Cataclysm
    }, -- World of Warcraft (Vanilla)
    ["Terrallende"] = {
        ["Península del Fuego Infernal"] = {
            achievementID = 862,
            proxyLocation = {56, 54, "Península del Fuego Infernal"},
            waypoints = {
                {86, 45, "Los Peldaños del Destino"},
                {27, 61, "Avanzada del Halcón"},
                {55, 64, "Bastión del Honor"},
                {40, 34, "Pozas de Aggonar"},
                {23, 40, "Templo de Telhamat"},
                {55, 37, "Thrallmar"},
                {68, 75, "Zeth'Gor"},
                {14, 42, "Cresta Cielo Estrellado"},
                {46, 84, "Los Campos Alabeados"},
                {54, 83, "Armería de Expedición"},
                {47, 52, "Ciudadela del Fuego Infernal"},
                {31, 28, "Puesto Mag'har"},
                {14, 60, "Ruinas de Sha'naar"},
                {69, 52, "La Avanzadilla de la Legión"},
                {61, 18, "Trono de Kil'jaeden"},
                {27, 79, "Cubil de Haal'esh"},
                {78, 72, "Cresta del Vacío"},
                {64, 32, "Campamento Forja: Mageddon"},
            },
        },
        ["Bosque de Terokkar"] = {
            achievementID = 867,
            proxyLocation = {48, 73, "Bosque de Terokkar"},
            waypoints = {
                {20, 65, "Ruinas Foso Sangrante"},
                {43, 22, "Matorral Cenarion"},
                {39, 40, "Poblado Grangol'var"},
                {59, 32, "Tuurem"},
                {58, 40, "Claro Raastok"},
                {60, 17, "Saliente Rajaespina"},
                {34, 72, "Tierras Auchenai"},
                {37, 51, "Caravana de Refugiados"},
                {31, 53, "Tumba Umbría"},
                {26, 54, "Velo Rhaze"},
                {52, 6, "Skettis"},
                {57, 54, "Bastión Allerian"},
                {71, 37, "Alto Ala de Fuego"},
                {49, 45, "Bastión Rompepedras"},
                {49, 35, "Ciudad de Shattrath"},
                {22, 11, "Las Colinas Barrera"},
                {67, 52, "Ruinas Mascahuesos"},
                {43, 53, "Colina Carroña"},
                {39, 65, "Círculo de la Observancia"},
                {43, 77, "Caravana Derelicta"},
                {49, 65, "Alcor Tortuoso"},
            },
        },
        ["Montañas Filospada"] = {
            achievementID = 865,
            proxyLocation = {38, 29, "Montañas Filospada"},
            waypoints = {
                {51, 15, "Alto Bash'ir"},
                {41, 52, "Bastión Aguja del Filo"},
                {45, 78, "Avanzada Machacasangre"},
                {53, 44, "Anillo de Sangre"},
                {74, 41, "Campamento Forja: Inquina"},
                {36, 40, "Campamento Forja: Cólera"},
                {66, 22, "Guarida de Gruul"},
                {74, 63, "Aldea Mok'Nathal"},
                {57, 70, "Loma Tajo"},
                {73, 20, "Skald"},
                {63, 11, "Espina de Cristal"},
                {36, 76, "Velo Lashh"},
                {74, 73, "Alto Vekhaar"},
                {70, 36, "Barranco del Filo"},
                {55, 26, "Campamento Machacasangre"},
                {80, 28, "Landas Tábidas"},
                {63, 65, "Puerta de la Muerte"},
                {29, 81, "Campamento Forja: Terror"},
                {40, 20, "Grishnath"},
                {52, 74, "Cresta Dentada"},
                {33, 25, "Bosque del Cuervo"},
                {61, 38, "Foresta Ruuan"},
                {37, 65, "Sylvanaar"},
                {51, 57, "Bastión Señor del Trueno"},
                {65, 31, "Velo Ruuan"},
                {30, 59, "Cumbre del Vórtice"},
            },
        },
        ["Valle Sombraluna"] = {
            achievementID = 864,
            proxyLocation = {57, 68, "Valle Sombraluna"},
            waypoints = {
                {45, 28, "Alto Cicatriz Espiral"},
                {22, 38, "Bastión de la Legión"},
                {29, 28, "Aldea Sombraluna"},
                {40, 41, "La Forja Muerta"},
                {59, 48, "Jaula de la Guardiana"},
                {61, 28, "Altar de Sha'tar"},
                {63, 58, "Campos del Ala Abisal"},
                {45, 68, "Punta Eclipse"},
                {70, 85, "Arrecife del Ala Abisal"},
                {72, 43, "El Templo Oscuro"},
                {50, 44, "La Mano de Gul'dan"},
                {35, 57, "Bastión Martillo Salvaje"},
                {29, 54, "Alto Illidari"},
            },
        },
        ["Marisma de Zangar"] = {
            achievementID = 863,
            proxyLocation = {34, 48, "Marisma de Zangar"},
            waypoints = {
                {79, 65, "Refugio Cenarion"},
                {46, 64, "Aldea Feropantano"},
                {22, 40, "Lago Luz Pantanosa"},
                {68, 49, "Telredor"},
                {58, 63, "La Laguna"},
                {82, 83, "Aldea Umbropantano"},
                {18, 7, "Bastión Ango'rosh"},
                {42, 27, "Puerto Orebor"},
                {31, 50, "Zabra'jin"},
                {18, 21, "Dominios Ango'rosh"},
                {32, 38, "Ciénaga Talada"},
                {28, 63, "Cresta Quagg"},
                {81, 39, "El Lodo Muerto"},
                {47, 50, "Ruinas de las Agujas Gemelas"},
                {18, 49, "Esporaggar"},
                {61, 41, "Tierras Escamas de Sangre"},
                {15, 61, "La Cañada Emergente"},
                {70, 82, "Playa Crestanegra"},
            },
        },
        ["Nagrand"] = {
            achievementID = 866,
            proxyLocation = {29, 51, "Nagrand"},
            waypoints = {
                {19, 51, "Campamento Forja: Miedo"},
                {42, 44, "Halaa"},
                {46, 19, "Ruinas Riecráneos"},
                {31, 43, "Puesto Primasol"},
                {79, 49, "El Círculo de los Retos"},
                {26, 21, "Colina Mazo de Guerra"},
                {62, 64, "Avanzada del Clan"},
                {49, 56, "Grieta del Viento Sur"},
                {72, 38, "Paso Junco Alabeado"},
                {0, 0, "Loma de Zangar"},
                {56, 36, "Garadar"},
                {69, 81, "Fortaleza Mata'penas"},
                {36, 71, "Campos de Espíritus"},
                {69, 64, "Telaar"},
                {71, 19, "El Trono de los Elementos"},
                {76, 64, "Ruinas Filo Ardiente"},
                {24, 36, "Campamento Forja: Odio"},
                {9, 41, "La Cresta del Crepúsculo"},
                {73, 53, "Aldea Junco Alabeado"},
            },
        },
        ["Tormenta Abisal"] = {
            achievementID = 843,
            proxyLocation = {56, 20, "Tormenta Abisal"},
            waypoints = {
                {33, 65, "Área 52"},
                {48, 83, "Forja de Maná Coruu"},
                {26, 40, "Forja de Maná Ara"},
                {54, 22, "Ruinas de Farahlon"},
                {30, 77, "La Pila"},
                {71, 39, "Cresta Celestial"},
                {49, 18, "Piedra Abisal"},
                {56, 78, "Bastión Furia del Sol"},
                {21, 55, "Puente Girolámina"},
                {55, 43, "Punto de Escala de El Etereum"},
                {37, 28, "Base Forja: Olvido"},
                {23, 71, "Forja de Maná B'naar"},
                {59, 67, "Forja de Maná Duro"},
                {61, 40, "Forja de Maná Ultris"},
                {76, 65, "El Castillo de la Tempestad"},
                {39, 74, "Ruinas Arklon"},
                {57, 87, "Poblado Kirin'Var"},
                {33, 54, "Ruinas de Enkaat"},
                {44, 35, "Flecha de la Tormenta"},
                {45, 10, "Ecodomo Campolejano"},
                {30, 15, "Trono de Socrethar"},
                {45, 53, "Ecodomo de la Tierra Media"},
            },
        },
    }, -- The Burning Crusade
    ["La Vorágine"] = {
        ["Infralar"] = {
            achievementID = 4864,
            proxyLocation = {51, 28, "Infralar"},
            waypoints = {
                {62, 59, "Caída de Alamuerte"},
                {22, 48, "Fosa Rocaguja"},
                {56, 76, "Restos de la Furia de la Tormenta"},
                {41, 18, "El Nidal Pálido"},
                {35, 82, "Los Campos Convulsos"},
                {39, 69, "Puerta de los Maestros"},
                {26, 33, "Sima Rocaguja"},
                {26, 70, "Hogar Pétreo"},
                {49, 49, "Templo de la Tierra"},
                {56, 13, "Trono de Therazane"},
                {68, 78, "Mirador Crepuscular"},
                {72, 41, "Extensión Carmesí"},
            },
        },
    }, -- Cataclysm
    ["Draenor"] = {
        ["Cresta Fuego Glacial"] = {
            achievementID = 8937,
            proxyLocation = {33, 29, "Cresta Fuego Glacial"},
            waypoints = {
                {27, 36, "Ciudadela Aguja del Filo"},
                {0, 0, "Huesos de Agurak"},
                {0, 0, "Barranco Faucedaga"},
                {0, 0, "Cerro Siniescarcha"},
                {0, 0, "Factoría de Hierro"},
                {68, 32, "Magnarok"},
                {0, 0, "Los Despojos"},
                {0, 0, "Wor'gol"},
                {0, 0, "Bastión Machacasangre"},
                {0, 0, "Óbito del Coloso"},
                {0, 0, "Risco Viento Gélido"},
                {0, 0, "Grom'gar"},
                {0, 0, "Apeadero de la Horda de Hierro"},
                {0, 0, "Avanzada Colmillo Pétreo"},
                {0, 0, "Llanuras Agrietadas"},
            },
        },
        ["Gorgrond"] = {
            achievementID = 8939,
            proxyLocation = {50, 27, "Gorgrond"},
            waypoints = {
                {48, 79, "Alto del Bastión"},
                {54, 33, "Terminal Malavía"},
                {37, 75, "Risayerta"},
                {44, 79, "Floración Sol Eterno"},
                {52, 59, "Paso Alto"},
                {43, 66, "Arena Quebrantarrocas"},
                {43, 20, "La Vereda de Hierro"},
                {45, 71, "Avanzada de las Bestias"},
                {50, 69, "Pantano Carmesí"},
                {54, 44, "Fronda del Vergel"},
                {46, 45, "Cañón de Gronns"},
                {61, 51, "Espesura Iyun"},
                {50, 70, "Madreselva"},
                {59, 88, "El Foso"},
                {59, 88, "El Foso"},
                {59, 88, "El Foso"},
            },
        },
        ["Cumbres de Arak"] = {
            achievementID = 8941,
            proxyLocation = {47, 74, "Cumbres de Arak"},
            waypoints = {
                {52, 6, "Skettis"},
                {36, 42, "Cenagal Sinuoso"},
                {62, 57, "Velo Zekk"},
                {42, 58, "Puerto Sur"},
                {50, 47, "Bancal del Alba"},
                {31, 28, "Bastión Garrafilada"},
                {73, 34, "Velo Perdido de Anzu"},
                {53, 51, "Marca del Cuervo"},
                {39, 44, "Hachazo"},
                {64, 22, "Risco Aullante"},
                {56, 85, "Alto Silbapellizco"},
                {41, 23, "Velo Akraz"},
                {47, 52, "Bancal de las Tierras Bajas Arrasadas"},
                {64, 49, "Cuenca de Sethekk"},
                {40, 49, "Ciudadela del almirante Taylor"},
                {61, 70, "Taller Silbapellizco"},
                {48, 61, "Valle Sangremelena"},
            },
        },
        ["Valle Sombraluna"] = {
            achievementID = 8938,
            proxyLocation = {57, 68, "Valle Sombraluna"},
            waypoints = {
                {28, 35, "Fortaleza de la Angustia"},
                {57, 26, "Elodar"},
                {36, 27, "Arboleda Sombra Umbría"},
                {79, 46, "Karabor"},
                {58, 59, "Bosque Fulgurante"},
                {42, 80, "Isla de las Sombras"},
                {44, 69, "Nidal Marea Oscura"},
                {43, 35, "Aldea Embaari"},
                {20, 13, "Gul'var"},
                {41, 58, "Shaz'gul"},
                {44, 69, "Alto de Socrethar"},
            },
        },
        ["Talador"] = {
            achievementID = 8940,
            proxyLocation = {42, 58, "Talador"},
            waypoints = {
                {79, 43, "Aruuna"},
                {70, 57, "Isla Caeocaso"},
                {69, 21, "Fuerte Wrynn"},
                {38, 79, "Gul'rok"},
                {59, 9, "Costa Orunai"},
                {49, 35, "Ciudad de Shattrath"},
                {58, 65, "Tumba de las Luces"},
                {78, 27, "Zangarra"},
                {49, 60, "Auchindoun"},
                {41, 58, "Patio de las Almas"},
                {69, 69, "Fortaleza Gordal"},
                {66, 9, "El Camino a la Gloria"},
                {78, 55, "Estadía del Anacoreta"},
                {46, 89, "Telmor"},
                {59, 32, "Tuurem"},
            },
        },
        ["Nagrand"] = {
            achievementID = 8942,
            proxyLocation = {29, 51, "Nagrand"},
            waypoints = {
                {41, 56, "Tierras Ancestrales"},
                {75, 68, "Puertas de Grommashar"},
                {37, 32, "Puerto de Ogrópolis"},
                {59, 45, "Lok-rath"},
                {44, 31, "Puesto de Vigilancia Mok'gol"},
                {69, 64, "Telaar"},
                {79, 49, "El Círculo de los Retos"},
                {86, 27, "Costa de Zangar"},
                {42, 27, "Despeñadero Quebrado"},
                {85, 51, "Salvalor"},
                {44, 76, "Puerto Puño de Hierro"},
                {80, 67, "Avanzada de Mar'gok"},
                {51, 61, "Oshu'gun"},
                {55, 15, "El Círculo de Sangre"},
                {71, 19, "El Trono de los Elementos"},
            },
        },
    }, -- Warlords of Draenor
    ["Kul Tiras"] = {
        ["Estrecho de Tiragarde"] = {
            achievementID = 12556,
            proxyLocation = {58, 56, "Estrecho de Tiragarde"},
            waypoints = {
                {0, 0, "Embarcadero Puntamuelle"},
                {0, 0, "Risco Troncohelecho"},
                {0, 0, "Hacienda de Norwington"},
                {0, 0, "Chatarralandia"},
                {0, 0, "Canal Ululante"},
                {0, 0, "Glaciar Menguante"},
                {0, 0, "Boralus"},
                {0, 0, "Fuerte Libre"},
                {0, 0, "Cala Aterrakraken"},
                {0, 0, "Residencia Kennings"},
                {0, 0, "Alto del Vigía"},
            },
        },
        ["Valle Canto Tormenta"] = {
            achievementID = 12558,
            proxyLocation = {54, 26, "Valle Canto Tormenta"},
            waypoints = {
                {0, 0, "Brennadam"},
                {0, 0, "Ribera del Marinero"},
                {0, 0, "Ribera Inerte"},
                {0, 0, "Fuerte Sabio"},
                {0, 0, "Aldea Muelerroca"},
                {0, 0, "Horado Lomozarza"},
                {0, 0, "Fuerte Guerracolmillo"},
                {0, 0, "Fuerte Daelin"},
                {0, 0, "Altar de la Tormenta"},
            },
        },
        ["Drustvar"] = {
            achievementID = 12557,
            proxyLocation = {36, 68, "Drustvar"},
            waypoints = {
                {0, 0, "Puesto de Arom"},
                {0, 0, "Puerto del Tallador"},
                {0, 0, "Bosque Carmesí"},
                {0, 0, "Cuenca del Flechero"},
                {0, 0, "Camino Paso Alto"},
                {0, 0, "Glacial Veloaterido"},
                {0, 0, "Cementerio Lomatúmulo"},
                {0, 0, "Corlain"},
                {0, 0, "Albergue del Ocaso"},
                {0, 0, "Gol Koval"},
                {0, 0, "Guardia Occidente"},
                {0, 0, "Mansión Crestavía"},
            },
        },
    }, -- BFA -  Kul Tiras
    ["Zandalar"] = {
        ["Nazmir"] = {
            achievementID = 12561,
            proxyLocation = {57, 29, "Nazmir"},
            waypoints = {
                {0, 0, "Humedales Primigenios"},
                {0, 0, "Ciénaga Fluvial"},
                {0, 0, "Zalamar"},
                {0, 0, "Nazwatha"},
                {0, 0, "Fangorrana"},
                {0, 0, "Corazón de la Oscuridad"},
                {0, 0, "La Necrópolis"},
                {0, 0, "Reposo de Torga"},
                {0, 0, "Zal'amak"},
            },
        },
        ["Zuldazar"] = {
            achievementID = 12559,
            proxyLocation = {54, 55, "Zuldazar"},
            waypoints = {
                {0, 0, "Atal'Dazar"},
                {0, 0, "Puerta de Sangre"},
                {0, 0, "Bajíos Perlatriste"},
                {0, 0, "Tierras Salvajes"},
                {0, 0, "Isla Colmillo"},
                {0, 0, "Xibala"},
                {0, 0, "Atal'Gral"},
                {0, 0, "Dazar'alor"},
                {0, 0, "Jardín de los Loa"},
                {0, 0, "Resquicio Frondoso"},
                {0, 0, "Reproche de Talanji"},
                {0, 0, "Zeb'ahari"},
            },
        },
        ["Vol'dun"] = {
            achievementID = 12560,
            proxyLocation = {38, 30, "Vol'dun"},
            waypoints = {
                {0, 0, "Atul'Aman"},
                {0, 0, "Puerto de Zem'lan"},
                {0, 0, "Puerto Ruina Pétrea"},
                {0, 0, "Templo de Akunda"},
                {0, 0, "Foso de Huesos"},
                {0, 0, "Costa Escarpada"},
                {0, 0, "Oasis Silbaflor"},
                {0, 0, "Marisma Selva Umbría"},
                {0, 0, "Puerto Peñarroja"},
                {0, 0, "Barranco Sinuoso"},
                {0, 0, "Bancal de los Devotos"},
                {0, 0, "Cauce Salobre"},
                {0, 0, "Refugio Tortuka"},
            },
        },
    }, -- BFA -  Zandalar
    ["Kalimdor"] = {
        ["Durotar"] = {
            achievementID = 728,
            proxyLocation = {58, 50, "Durotar"},
            waypoints = {
                {43, 65, "Valle de los Retos"},
                {40, 40, "Cuenca Furia del Sur"},
                {62, 81, "Islas del Eco"},
                {53, 43, "Cerrotajo"},
                {40, 26, "Monte del Trueno"},
                {54, 13, "Roca del Cráneo"},
                {50, 79, "Ciudadela del Fuerte del Norte"},
                {55, 74, "Poblado Sen'jin"},
                {57, 57, "Fuerte de Tiragarde"},
                {46, 49, "Tierras Crines de Acero"},
                {53, 23, "Barranco Árido"},
                {59, 45, "Orgrimmar"},
            },
        },
        ["Teldrassil"] = {
            achievementID = 842,
            proxyLocation = {43, 11, "Teldrassil"},
            waypoints = {
                {58, 36, "Cañada Umbría"},
                {55, 52, "Dolanaar"},
                {44, 67, "Tierras de los Tuercepinos"},
                {42, 57, "Estanques de Arlithrien"},
                {39, 29, "El Claro del Oráculo"},
                {30, 49, "Darnassus"},
                {51, 38, "La Grieta"},
                {46, 51, "Hondonada Ban'ethil"},
                {53, 60, "Lago Al'Ameth"},
                {64, 50, "Aldea Brisa Estelar"},
                {44, 35, "Lago Primigenio"},
                {55, 91, "Aldea Rut'theran"},
            },
        },
        ["Los Baldíos del Norte"] = {
            achievementID = 750,
            proxyLocation = {53, 50, "Los Baldíos del Norte"},
            waypoints = {
                {66, 12, "Mina Pedrusco"},
                {42, 15, "La Empalizada de Mor'shan"},
                {42, 38, "Cima Calígine"},
                {36, 45, "Las Charcas del Olvido"},
                {67, 39, "Avanzada del Puente"},
                {49, 58, "El Cruce"},
                {67, 72, "Trinquete"},
                {40, 74, "Oasis Aguaverde"},
                {57, 19, "El Fangal"},
                {27, 31, "Las Colinas Áridas"},
                {53, 41, "Granja de Grol'dom"},
                {58, 49, "Colina Espinosa"},
                {55, 80, "El Oasis Estancado"},
                {70, 89, "La Costa Mercante"},
            },
        },
        ["Los Baldíos del Sur"] = {
            achievementID = 4996,
            proxyLocation = {52, 62, "Los Baldíos del Sur"},
            waypoints = {
                {49, 85, "Bael Modan"},
                {49, 49, "Mando de Vanguardia"},
                {38, 13, "El Alto del Honor"},
                {66, 47, "Fuerte del Norte"},
                {44, 51, "Ruinas de Taurajo"},
                {41, 46, "Punta Vendetta"},
                {45, 69, "Marca de Guerra"},
                {42, 77, "Filón Catacroquer"},
                {39, 20, "Cerro del Cazador"},
                {41, 94, "Horado Rajacieno"},
                {45, 35, "La Hojarasca"},
            },
        },
        ["Isla Bruma de Sangre"] = {
            achievementID = 861,
            proxyLocation = {30, 19, "Isla Bruma de Sangre"},
            waypoints = {
                {17, 28, "Paso de Redámbar"},
                {31, 87, "Costa Cienonegro"},
                {85, 51, "Isla Sangre Maldita"},
                {66, 78, "Enclave Brazolanudo"},
                {51, 76, "Mediavega"},
                {38, 79, "Nazzivian"},
                {61, 44, "Ruinas de Loreth'Aran"},
                {25, 42, "Campamento de Tel'athion"},
                {38, 20, "La Playa de Sangre"},
                {39, 61, "El Crionúcleo"},
                {34, 23, "El Arrecife Oculto"},
                {18, 51, "La Espiral Vectorial"},
                {74, 9, "Punta Veridiana"},
                {69, 67, "Guarida Escama de Cólera"},
                {40, 33, "Axxarien"},
                {46, 45, "Bosquespada"},
                {54, 55, "Avanzada de Sangre"},
                {62, 89, "Encrucijada de Kessel"},
                {42, 84, "Bosque Bruma"},
                {55, 35, "Loma Plumira"},
                {73, 20, "Alto de la Garra"},
                {80, 26, "El Arrecife Sangre Maldita"},
                {66, 49, "El Tramo Carmesí"},
                {29, 36, "La Poza del Hediondo"},
                {57, 81, "El Aprisco Perdido"},
                {53, 16, "El Pistón de Distorsión"},
                {30, 45, "El Reposo del Vindicador"},
                {71, 16, "Isla Cicatriz de Vermis"},
            },
        },
        ["Las Mil Agujas"] = {
            achievementID = 846,
            proxyLocation = {52, 74, "Las Mil Agujas"},
            waypoints = {
                {31, 21, "El Gran Elevador"},
                {67, 85, "Excavación Sumergida"},
                {54, 61, "Quebranto Crepuscular"},
                {13, 11, "Cima Tramo Oeste"},
                {45, 50, "Poblado Viento Libre"},
                {78, 72, "El Piélago de Sal"},
                {48, 26, "Zahúrda Rajacieno"},
                {90, 83, "Sargazo de los Mares del Sur"},
                {31, 58, "Baluarte Crepuscular"},
                {34, 38, "Cumbre de la Nube Negra"},
                {88, 48, "Cumbres Pezuña Quebrada"},
                {11, 36, "Nido Alto"},
            },
        },
        ["Desolace"] = {
            achievementID = 848,
            proxyLocation = {42, 56, "Desolace"},
            waypoints = {
                {54, 10, "Tethris Aran"},
                {65, 10, "Punta de Nijel"},
                {54, 25, "Fortaleza del Hacha de Trueno"},
                {74, 46, "Territorio Magram"},
                {33, 55, "Valle de las Lanzas"},
                {24, 70, "Aldea Cazasombras"},
                {52, 78, "Aquelarre Mannoroc"},
                {79, 79, "Barranco Rompesombras"},
                {36, 71, "Campo de Thargad"},
                {76, 22, "Sargeron"},
                {56, 49, "Tierras Vírgenes Cenarion"},
                {29, 9, "Isla Ranazjar"},
                {51, 59, "Cementerio de Kodos"},
                {37, 86, "Poblado Gelkis"},
                {71, 73, "Shok'Thokar"},
                {37, 32, "Costa Filozante"},
            },
        },
        ["Feralas"] = {
            achievementID = 849,
            proxyLocation = {44, 69, "Feralas"},
            waypoints = {
                {83, 41, "Bajas Tierras Salvajes"},
                {46, 20, "Los Dos Colosos"},
                {59, 41, "La Masacre"},
                {58, 72, "Ruinas de Isildien"},
                {75, 43, "Campamento Mojache"},
                {77, 34, "Avanzada Gordunni"},
                {45, 49, "Bastión Plumaluna"},
                {28, 49, "Ruinas de Plumaluna"},
                {39, 36, "La Costa Olvidada"},
                {55, 57, "Vega Cicatriz Feral"},
                {75, 62, "Las Galerías Retorcidas"},
                {70, 38, "Dominios Tótem Siniestro"},
                {64, 59, "Ruinas Niebla Negra"},
            },
        },
        ["Azshara"] = {
            achievementID = 852,
            proxyLocation = {62, 39, "Azshara"},
            waypoints = {
                {20, 56, "Palacete de Gallywix"},
                {58, 51, "Muelle Pantoque"},
                {80, 31, "Torre de Eldara"},
                {50, 27, "Campamento Base Darnassiano"},
                {25, 38, "Cabeza de Oso"},
                {24, 80, "Puerta Trasera de Orgrimmar"},
                {68, 69, "Playa del Arrecife Sur"},
                {35, 74, "Lago Mennar"},
                {54, 73, "Acantilados de la Tormenta"},
                {45, 50, "La Playa Arrasada"},
                {57, 12, "Costa Amarga"},
                {71, 33, "Ruinas de Arkkoran"},
                {43, 75, "El Laboratorio Secreto"},
                {38, 30, "Bastión Faucenegra"},
                {34, 53, "Ruinas de Eldarath"},
                {64, 81, "Monumento Cresta Cuervo"},
                {58, 90, "Las Ruinas"},
            },
        },
        ["Cráter de Un'Goro"] = {
            achievementID = 854,
            proxyLocation = {50, 81, "Cráter de Un'Goro"},
            waypoints = {
                {51, 50, "Cresta del Penacho en Llamas"},
                {55, 62, "Alto de Marshal"},
                {69, 34, "Los Jardines Turbados"},
                {30, 54, "Baños de Golakka"},
                {50, 79, "La Cicatriz Serpenteante"},
                {80, 40, "Meseta Roca de Hierro"},
                {63, 17, "Roca Fungal"},
                {43, 41, "Pilote Musgoso"},
                {30, 37, "Cuenca de los Gritos"},
                {33, 70, "Camino del Terror"},
                {69, 60, "Los Pantanales"},
                {50, 25, "Fosas de Alquitrán Lakkari"},
            },
        },
        ["Silithus"] = {
            achievementID = 856,
            proxyLocation = {43, 81, "Silithus"},
            waypoints = {
                {30, 16, "Vega de Cristal"},
                {54, 34, "Fuerte Cenarion"},
                {60, 72, "Colmen'Regal"},
                {49, 23, "Colmen'Ashi"},
                {64, 49, "Aldea del Viento del Sur"},
                {31, 54, "Colmen'Zora"},
                {35, 80, "El Muro del Escarabajo"},
                {79, 19, "Sosiego del Valor"},
            },
        },
        ["Mulgore"] = {
            achievementID = 736,
            proxyLocation = {47, 61, "Mulgore"},
            waypoints = {
                {45, 77, "Mesa de la Nube Roja"},
                {49, 58, "Poblado Pezuña de Sangre"},
                {61, 67, "Las Llanuras Onduladas"},
                {53, 47, "Caravana Devastada"},
                {44, 45, "Pozo Tronacuerno"},
                {60, 21, "Roca Roja"},
                {42, 14, "Pozo Ferocrín"},
                {34, 62, "Roca Crines Pálidas"},
                {53, 66, "Pozo Pezuña Invernal"},
                {62, 48, "Mina Ventura y Cía."},
                {49, 35, "Las Llanuras Doradas"},
                --{0, 0, "Bael'dun Digsite"},
                {52, 11, "Cresta Viento Furioso"},
            },
        },
        ["Isla Bruma Azur"] = {
            achievementID = 860,
            proxyLocation = {32, 27, "Isla Bruma Azur"},
            waypoints = {
                {77, 43, "Valle Ammen"},
                {49, 50, "Avanzada Azur"},
                {58, 17, "El Claro de Ascuas"},
                {59, 68, "Campamento de Geezle"},
                {46, 71, "Desembarco de Odesyus"},
                {53, 61, "El Cementerio de Cápsulas"},
                {13, 80, "Isla Bruma de Plata"},
                {31, 40, "El Exodar"},
                {32, 77, "Punto Escama de Cólera"},
                {62, 54, "Vado Ammen"},
                {26, 66, "Aldea Brazolanudo"},
                {47, 5, "Playa Puentegrato"},
                {52, 42, "Bosque Pasto Lunar"},
                {37, 59, "La Maraña de Cápsulas"},
                {34, 12, "La Costa de Cieno"},
                {45, 20, "Bastión Semprepino"},
                {21, 54, "Atracadero de Valaar"},
            },
        },
        ["Cuna del Invierno"] = {
            achievementID = 857,
            proxyLocation = {58, 23, "Cuna del Invierno"},
            waypoints = {
                {30, 37, "Baños de Fuego de Escarcha"},
                {50, 55, "Lago Kel'Theril"},
                {55, 64, "Mazthoril"},
                {64, 76, "Matorral del Ala del Búho"},
                {66, 46, "Poblado Nevada"},
                {46, 18, "Roca Sable de Hielo"},
                {36, 56, "Puesto de los Fauces de Madera"},
                {49, 40, "Aldea Estrella Fugaz"},
                {59, 49, "Vista Eterna"},
                {66, 55, "Colinas Cardo Nevado"},
                {64, 28, "La Arboleda Oculta"},
                {60, 86, "Cañón Levescarcha"},
            },
        },
        ["Costa Oscura"] = {
            achievementID = 844,
            proxyLocation = {46, 27, "Costa Oscura"},
            waypoints = {
                {38, 42, "Ruinas de Auberdine"},
                {62, 9, "Campamento de Guerra Rompelanzas"},
                {43, 39, "Arboleda Marchita"},
                {43, 53, "El Ojo del Vórtice"},
                {50, 18, "Lor'danel"},
                {40, 85, "La Espada del Maestro"},
                {70, 19, "Valle Rompelanzas"},
                {42, 70, "Río Culebra"},
                {61, 20, "Ruinas de Mathystra"},
                {43, 58, "Ameth'Aran"},
                {32, 84, "Nazj'vel"},
            },
        },
        ["Vallefresno"] = {
            achievementID = 845,
            proxyLocation = {50, 42, "Vallefresno"},
            waypoints = {
                {13, 25, "La Ensenada de Zoram"},
                {50, 66, "Refugio Brisa de Plata"},
                {20, 40, "Lago Falathim"},
                {36, 33, "Poblado Piel de Cardo"},
                {36, 50, "Astranaar"},
                {53, 38, "Vega del Aullido"},
                {66, 81, "Lago Cielo Estrellado"},
                {80, 49, "Satyrnaar"},
                {87, 57, "Aserradero Grito de Guerra"},
                {26, 22, "Refugio de Orendil"},
                {50, 48, "Pico del Trueno"},
                {27, 36, "Atalaya de Maestra"},
                {21, 53, "El Santuario de Aessina"},
                {34, 70, "Las Ruinas del Polvo Estelar"},
                {61, 50, "Refugio de la Algaba"},
                {73, 61, "Puesto del Hachazo"},
                {92, 38, "Talloumbrío"},
                {84, 71, "Cerro Lumbrevil"},
            },
        },
        ["Sierra Espolón"] = {
            achievementID = 847,
            proxyLocation = {44, 47, "Sierra Espolón"},
            waypoints = {
                {41, 39, "Valle Marca de Guerra"},
                {48, 76, "Ruinas de Eldre'thar"},
                {76, 76, "Campos Desenterrados"},
                {58, 57, "Bastión Cortaviento"},
                {70, 91, "Malaka'jin"},
                {63, 87, "Barranco del Alud"},
                {68, 51, "Risco Cortaviento"},
                {32, 68, "La Vega Carbonizada"},
                {41, 22, "Cima del Espolón"},
                --{0, 0, "Krom'gar Fortress"},
                {38, 32, "Mirador Thal'darah"},
                {57, 73, "Cuenca de las Tejedoras"},
                {45, 32, "Puesto Caminarrisco"},
                {58, 66, "Senda de las Tejedoras"},
                {75, 86, "Vega del Gran Bosque"},
                {49, 61, "Refugio Roca del Sol"},
                {51, 45, "Lago Mirkfallon"},
            },
        },
        ["Marjal Revolcafango"] = {
            achievementID = 850,
            proxyLocation = {55, 68, "Marjal Revolcafango"},
            waypoints = {
                {66, 49, "Isla Theramore"},
                {46, 47, "Puesto Cuernoatroz"},
                {29, 48, "Posada Reposo Umbrío"},
                {36, 31, "Poblado Murohelecho"},
                {75, 18, "Isla de Alcaz"},
                {41, 11, "Poblado Pezuñanegra"},
                {41, 74, "Piñón de Barro"},
                {61, 21, "Playa Tenebruma"},
                {52, 77, "Ciénaga de Fuego"},
            },
        },
        ["Tanaris"] = {
            achievementID = 851,
            proxyLocation = {55, 87, "Tanaris"},
            waypoints = {
                {51, 29, "Gadgetzan"},
                {37, 78, "Valle de los Vigías"},
                {45, 41, "Arenas Abisales"},
                {34, 46, "La Guarida Ponzoñosa"},
                {68, 54, "Tierras del Sur"},
                {47, 64, "Ruinas de Lunaeste"},
                {40, 71, "Ruinas de Lunasur"},
                {39, 19, "Zul'Farrak"},
                {40, 28, "Vigía Penas de Arena"},
                {72, 47, "Cala del Aparejo Perdido"},
                {52, 46, "Pilar Partido"},
                {40, 55, "Base Machacaduna"},
                {54, 67, "Sima Abierta"},
                {53, 91, "Playa Finisterrae"},
                {31, 65, "Valle Cardizal"},
                {63, 50, "Cavernas del Tiempo"},
            },
        },
        ["Frondavil"] = {
            achievementID = 853,
            proxyLocation = {48, 29, "Frondavil"},
            waypoints = {
                {61, 11, "Poblado Zarpavil"},
                {49, 25, "Bosque de Troncoferro"},
                {42, 40, "Cañada Gran Cicatriz"},
                {37, 60, "Jaedenar"},
                {41, 84, "Cañada Fuego de Jade"},
                {48, 91, "Aldea Muertobosque"},
                {62, 26, "Claro Ramaespolón"},
                {43, 18, "Camino Fuego de Jade"},
                {41, 48, "Cascadas del Veneno"},
                {40, 74, "Ruinas de Constellas"},
                {51, 80, "Santuario Esmeralda"},
                {55, 85, "Morlos'Aran"},
            },
        },
        ["Claro de la Luna"] = {
            achievementID = 855,
            proxyLocation = {53, 20, "Claro de la Luna"},
            waypoints = {
                {55, 55, "Lago Elune'ara"},
                {36, 41, "Santuario de Remulos"},
                {48, 39, "Amparo de la Noche"},
                {66, 55, "Túmulo de Tempestira"},
            },
        },
        ["Hyjal"] = {
            achievementID = 4863,
            proxyLocation = {54, 30, "Hyjal"},
            waypoints = {
                {33, 14, "Límite del Mundo"},
                {19, 42, "Lago Cinéreo"},
                {70, 74, "Puertas de Sothann"},
                {31, 84, "Nidal de Sethria"},
                {33, 53, "La Estela Ardiente"},
                {49, 79, "El Trono de la Llama"},
                --{0, 0, "The Circle of Cinders"},
                {84, 53, "Garganta Negro Rumor"},
                {62, 21, "Nordrassil"},
                {29, 32, "Santuario de Goldrinn"},
                {57, 55, "La Llanura Agostada"},
            },
        }, -- Cataclysm
        ["Uldum"] = {
            achievementID = 4865,
            proxyLocation = {47, 92, "Uldum"},
            waypoints = {
                {54, 51, "Campos de Akhenet"},
                {64, 18, "Tumba de Khartut"},
                {48, 38, "Mar'at"},
                {50, 81, "Ciudad de Neferset"},
                {64, 29, "Obelisco de las Estrellas"},
                {40, 41, "Orsis"},
                {45, 14, "Ruinas de Ahmtul"},
                {22, 61, "Embarcadero de Schnottz"},
                {33, 31, "Templo de Uldum"},
                {71, 21, "La Puerta de los Ciclos Eternos"},
                --{0, 0, "The Trail of Devastation"},
                {42, 71, "Cuna de los Ancestros"},
                {62, 73, "Ciudad Perdida de los Tol'vir"},
                {67, 41, "Nahom"},
                {39, 23, "Obelisco de la Luna"},
                {45, 58, "Obelisco del Sol"},
                {54, 33, "Ramkahen"},
                {32, 62, "Ruinas de Ammon"},
                {60, 41, "Tierras de Tahret"},
                {83, 56, "El Embarcadero Maldito"},
                {72, 50, "Tumbas de los Precursores"},
                {54, 42, "Presa Vir'naal"},
            },
        }, -- Cataclysm
    }, -- World of Warcraft (Vanilla)
    ["Rasganorte"] = {
        ["Tundra Boreal"] = {
            achievementID = 1264,
            proxyLocation = {24, 59, "Tundra Boreal"},
            waypoints = {
                {86, 24, "Ciudad Templo de En'kilah"},
                {46, 78, "Litoral Tralladón"},
                {31, 53, "Desembarco de Garrosh"},
                {27, 26, "Gelidar"},
                {46, 33, "El Saliente Ámbar"},
                {56, 70, "Fortaleza Denuedo"},
                {75, 16, "Los Cubiles de los Moribundos"},
                {49, 25, "Caravana de Quijacero"},
                {65, 48, "Kashala"},
                {83, 42, "Confín de la Muerte"},
                {51, 10, "Avanzada Bor'gorok"},
                {42, 54, "Bastión Grito de Guerra"},
                {66, 28, "Los Campos de Géiseres"},
            },
        },
        ["Cementerio de Dragones"] = {
            achievementID = 1265,
            proxyLocation = {50, 55, "Cementerio de Dragones"},
            waypoints = {
                {55, 34, "Reposo de Galakrond"},
                {39, 32, "Santuario de Dragones Obsidiana"},
                {88, 45, "Naxxramas"},
                {25, 41, "Poblado Bruma de Hielo"},
                {50, 18, "Altos Viento Helado"},
                {36, 47, "Martillo de Agmar"},
                {14, 48, "Campo de Refugiados de Viento Oeste"},
                {82, 70, "La Orilla Olvidada"},
                {73, 26, "Punta Escarlata"},
                {40, 67, "Lago Indu'le"},
                {70, 76, "Nueva Vega del Amparo"},
                {83, 27, "Confianza de la Luz"},
                {63, 73, "Santuario de Dragones Esmeralda"},
                {38, 19, "Angrathar la Puerta de Cólera"},
                {60, 55, "Templo del Reposo del Dragón"},
                {76, 61, "Rencor Venenoso"},
                {60, 18, "Vicio de Cristal"},
            },
        },
        ["Zul'Drak"] = {
            achievementID = 1267,
            proxyLocation = {68, 43, "Zul'Drak"},
            waypoints = {
                {83, 18, "Gundrak"},
                {47, 57, "Anfiteatro de la Angustia"},
                {53, 35, "Altar de Rhunok"},
                {72, 45, "Altar de Mam'toth"},
                {59, 57, "Zim'Torga"},
                {28, 46, "Voltarus"},
                {31, 74, "Brecha de la Luz"},
                {41, 77, "Campos Drak'Sotra"},
                {40, 40, "Altar de Sseratus"},
                {77, 58, "Altar de Quetz'lun"},
                {63, 69, "Altar de Har'koa"},
                {21, 76, "Zeramas"},
                {16, 58, "Fin de Thrym"},
                {61, 77, "Kolramas"},
            },
        },
        ["Bosque Canto de Cristal"] = {
            achievementID = 1457,
            proxyLocation = {51, 41, "Bosque Canto de Cristal"},
            waypoints = {
                {26, 64, "El Frente Azur"},
                {76, 48, "Dominio de los Atracasol"},
                {74, 81, "Mirador Brisaveloz"},
                {14, 43, "El Confín Violeta"},
                {16, 13, "La Corriente Decrépita"},
                {45, 45, "El Bosque Desolado"},
                {13, 34, "El Gran Árbol"},
                {73, 63, "El Matorral Desatado"},
            },
        },
        ["Corona de Hielo"] = {
            achievementID = 1270,
            proxyLocation = {40, 28, "Corona de Hielo"},
            waypoints = {
                {64, 45, "El Bombardeo"},
                {9, 44, "Puerto del Embate"},
                {34, 68, "La Factoría de Carne"},
                {74, 39, "La Caída de Sindragosa"},
                {85, 74, "Valle de los Ecos"},
                {44, 54, "La Conflagración"},
                {29, 37, "Jotunheim"},
                {43, 22, "La Cámara de las Sombras"},
                {54, 87, "Ciudadela de la Corona de Hielo"},
                {69, 66, "El Frente Roto"},
                {53, 34, "Aldur'thar: La Puerta de la Desolación"},
                {33, 27, "Valhalas"},
                {56, 56, "Ymirheim"},
                {48, 69, "Corp'rethar: La Puerta del Horror"},
                {78, 55, "Ciudad de la Plaga"},
            },
        },
        ["Fiordo Aquilonal"] = {
            achievementID = 1263,
            proxyLocation = {78, 74, "Fiordo Aquilonal"},
            waypoints = {
                {29, 62, "Komawa"},
                {48, 10, "Campamento Pezuña Invernal"},
                {77, 29, "Campo Venganza"},
                {34, 78, "Cabo Pillastre"},
                {36, 11, "Gjalerbron"},
                {68, 25, "El Paso del Gigante"},
                {78, 47, "Ruinas de Ivald"},
                {52, 67, "Nuevo Agamand"},
                {54, 17, "El Claro Retorcido"},
                {30, 42, "Fortaleza de la Guardia Oeste"},
                {66, 40, "Baleheim"},
                {57, 36, "Isla Caldros"},
                {26, 24, "Campamento de los Boticarios"},
                {31, 26, "Las Puertas de Acero"},
                {68, 54, "Nafsavar"},
                {39, 50, "Encierro Ámbar"},
                {61, 16, "Fuerte Vildervar"},
                {49, 54, "Haltorboll"},
                {44, 33, "Skorn"},
                {58, 46, "Fortaleza de Utgarde"},
                {74, 70, "Excavación de Baelgun"},
            },
        },
        ["Colinas Pardas"] = {
            achievementID = 1266,
            proxyLocation = {71, 55, "Colinas Pardas"},
            waypoints = {
                {21, 64, "Bastión de la Conquista"},
                {71, 26, "Ruinas de Drakil'jin"},
                {16, 48, "Manantial de Granito"},
                {49, 57, "Santuario Colmillo Iracundo"},
                {14, 85, "Bahía Ventura"},
                {31, 59, "Refugio Pino Ámbar"},
                {65, 45, "Campamento Oneqwah"},
                {17, 24, "Fortaleza de Drak'Tharon"},
                {77, 59, "Dun Argol"},
                {49, 44, "Fauceparda"},
                {67, 15, "Thor Modan"},
                {29, 74, "Runavold"},
                {35, 38, "Aserradero Cielo Azul"},
                {59, 28, "Campamento de la Brigada de los Páramos de Poniente"},
            },
        },
        ["Cuenca de Sholazar"] = {
            achievementID = 1268,
            proxyLocation = {25, 41, "Cuenca de Sholazar"},
            waypoints = {
                {48, 64, "Corazón del Río"},
                {36, 75, "El Pilar Musgoluz"},
                {28, 39, "El Pedestal de los Creadores"},
                {53, 56, "Canope de Hablalluvia"},
                {73, 36, "La Avalancha"},
                {24, 80, "Bastión de Kartak"},
                {46, 26, "El Matorral Silvestre"},
                {80, 55, "El Mirador de los Creadores"},
                {33, 52, "El Pilar Toquesol"},
                {66, 59, "El Pilar Sangrevida"},
                {49, 38, "El Pilar Iluminado"},
                {23, 33, "La Plataforma del Tormentoso"},
            },
        },
        ["Las Cumbres Tormentosas"] = {
            achievementID = 1269,
            proxyLocation = {59, 25, "Las Cumbres Tormentosas"},
            waypoints = {
                {48, 69, "Poblado Brunnhildar"},
                {64, 59, "Dun Niffelem"},
                {25, 61, "Valkyrion"},
                {34, 85, "Campo de Minas Encajebujía"},
                {64, 46, "Templo de la Vida"},
                {71, 49, "Truenotoño"},
                {27, 41, "Llanuras Ventisquero"},
                {28, 74, "Fuerte Escarcha"},
                {33, 39, "Cuna de Narvir"},
                {34, 68, "Aliento de Bor"},
                {52, 49, "Bancal de los Creadores"},
                {40, 57, "Motor de los Creadores"},
                {41, 18, "Ulduar"},
                {33, 58, "Templo de las Tormentas"},
                {45, 81, "Pesadilla de Garm"},
                {24, 50, "Nidavelir"},
            },
        },
    }, -- Wrath of the Lich King
    ["Pandaria"] = {
        ["El Bosque de Jade"] = {
            achievementID = 6351,
            proxyLocation = {66, 48, "El Bosque de Jade"},
            waypoints = {
                {41, 21, "Monasterio Tian"},
                {61, 91, "Pabellón del Soñador"},
                {57, 78, "Lago de Nácar"},
                {47, 29, "Cantera Verdemar"},
                {25, 37, "Campamento Nooka Nooka"},
                {47, 60, "Corazón del Dragón"},
                {57, 57, "Templo del Dragón de Jade"},
                {46, 90, "Puesto Garrosh'ar"},
                {29, 13, "Poblado Almíbar"},
                {48, 45, "Floralba"},
                {50, 26, "Augurio del Emperador"},
                {26, 49, "Cerro Makaku"},
                {40, 73, "Huerto Brisa Dulce"},
                {40, 13, "Bancal de los Diez Truenos"},
                {52, 82, "Fosas Colafusta"},
                {57, 44, "El Arboretum"},
                {65, 30, "Isla de Barlovento"},
            },
        },
        ["Espesura Krasarang"] = {
            achievementID = 6975,
            proxyLocation = {52, 76, "Espesura Krasarang"},
            waypoints = {
                {67, 44, "Muelle de los Pescadores"},
                {64, 31, "Río Dojani"},
                {82, 26, "Cala Krasarang"},
                {41, 75, "Laguna Nayeli"},
                {55, 34, "Ruinas de Dojan"},
                {40, 55, "Templo de la Grulla Roja"},
                {21, 35, "La Jungla Prohibida"},
                {47, 90, "Unga Ingoo"},
                {33, 70, "Cuna de Chi-Ji"},
                {29, 38, "Poblado Canción de Otoño"},
                {70, 22, "Las Ruinas Krasari"},
                {40, 33, "Refugio Ala de Grulla"},
                {24, 45, "Ruinas de Korja"},
                {46, 38, "La Jungla Salvaje"},
                {16, 56, "Las Islas del Sur"},
                {77, 10, "Atalaya de Zhu"},
            },
        },
        ["Estepas de Tong Long"] = {
            achievementID = 6977,
            proxyLocation = {34, 46, "Estepas de Tong Long"},
            waypoints = {
                {76, 82, "Frente Gao-Ran"},
                {54, 78, "Vigilancia de Rensai"},
                {67, 47, "Campamento Osul"},
                {48, 70, "Cuartel del Shadopan"},
                {45, 86, "Sik'vess"},
                {66, 65, "El Sumidero"},
                {55, 52, "Kri'vess"},
                {41, 63, "Templo de Niuzao"},
                {84, 72, "Corrupción del Odio"},
                {29, 27, "Shan'ze Dao"},
                {22, 52, "Sra'vess"},
            },
        },
        ["Valle de la Flor Eterna"] = {
            achievementID = 6979,
            proxyLocation = {51, 53, "Valle de la Flor Eterna"},
            waypoints = {
                {29, 37, "Ruinas de Guo-Lai"},
                {80, 34, "Palacio Mogu'shan"},
                {46, 16, "La Escalera Dorada"},
                {56, 43, "La Pagoda Dorada"},
                {62, 20, "Santuario de las Dos Lunas"},
                {17, 45, "Las Cinco Hermanas"},
                {38, 73, "Aldea Bruma Otoñal"},
                {21, 71, "Baluarte del Sol Poniente"},
                {86, 65, "Santuario de las Siete Estrellas"},
                {44, 61, "Cementerio Tu Shen"},
                {41, 46, "Lago Pétalo Níveo"},
            },
        },
        ["Valle de los Cuatro Vientos"] = {
            achievementID = 6969,
            proxyLocation = {51, 65, "Valle de los Cuatro Vientos"},
            waypoints = {
                --{0, 0, "Winds' Edge"},
                {56, 36, "El Abanico Dorado"},
                {54, 46, "El Alcor"},
                {31, 30, "Poblado Kunzen"},
                {18, 81, "Safari Nesingwary"},
                {60, 27, "Pozas de la Pureza"},
                {63, 57, "Campos de Seda"},
                {34, 70, "Cervecería del Trueno"},
                {75, 25, "Rancho Pie Atronador"},
                {13, 76, "Despeñadero Loma Agreste"},
                {51, 63, "El Granero Imperial"},
                {18, 55, "Villarroca"},
                {68, 43, "Hogar de Caolín"},
                {16, 35, "Espesura Paoquan"},
                {70, 65, "Bancal del Fragor"},
                {25, 43, "Marjal Exótico"},
                {39, 39, "Los Cultivos Florecientes"},
                {80, 41, "Descenso de Zhu"},
            },
        },
        ["Cima Kun-Lai"] = {
            achievementID = 6976,
            proxyLocation = {47, 36, "Cima Kun-Lai"},
            waypoints = {
                {72, 91, "Aldea Binan"},
                {55, 91, "Puerta de los Augustos Celestiales"},
                {35, 65, "Cumbre Kota"},
                --{0, 0, "Mount Neverest"},
                {49, 40, "Pico de la Serenidad"},
                {68, 48, "Templo del Tigre Blanco"},
                {57, 47, "Valle de los Emperadores"},
                {44, 86, "Rincón Tallo Ardiente"},
                {75, 13, "Isla de la Venganza"},
                {59, 72, "Mogujia"},
                {68, 73, "Rancho Zarpa Lanuda"},
                {34, 47, "Monasterio del Shadopan"},
                {47, 67, "La Senda Arpillera"},
                {62, 29, "Aldea Zouchin"},
            },
        },
        ["Desierto del Pavor"] = {
            achievementID = 6978,
            proxyLocation = {35, 64, "Desierto del Pavor"},
            waypoints = {
                {40, 34, "Corazón del Miedo"},
                {57, 17, "Kypari Vor"},
                {35, 19, "Aldea Rikkitun"},
                {70, 25, "Bancal Gurthan"},
                {47, 35, "La Nidada de Shek'zeer"},
                {66, 44, "Bosquetormento"},
                {55, 35, "Klaxxi'vess"},
                {59, 57, "Kypari Zar"},
                {56, 70, "Lance de Aguado"},
                {39, 65, "La Mugre Salobre"},
                {50, 11, "Jardín de la Cebada Crepuscular"},
                {30, 75, "Zan'vess"},
            },
        },
    }, -- Mists of Pandaria
    ["Islas Quebradas"] = {
        ["Azsuna"] = {
            achievementID = 10665,
            proxyLocation = {33, 56, "Azsuna"},
            waypoints = {
                {0, 0, "Faronaar"},
                {0, 0, "Senda Verde"},
                {0, 0, "Tierras Altas de Llothien"},
                {0, 0, "Nar'thalas"},
                {0, 0, "Sagrario en Ruinas"},
                {0, 0, "Ruinas Ley de Zarkhenar"},
                {0, 0, "Acceso Llamarada Vil"},
                {0, 0, "Isla de los Vigías"},
                {0, 0, "Vega Baldía"},
                {0, 0, "Cala de Oceanus"},
                {0, 0, "Templo de Luces"},
            },
        },
        ["Monte Alto"] = {
            achievementID = 10667,
            proxyLocation = {46, 21, "Monte Alto"},
            waypoints = {
                {0, 0, "Tierras Altas Cazasangre"},
                {48, 79, "Avanzada Pezuña Helada"},
                {0, 0, "Pedestal del Vigía de la Noche"},
                {0, 0, "Recodo del Río"},
                {0, 0, "Cala del Naufragio"},
                {0, 0, "Avanzada Pezuña Pétrea"},
                {0, 0, "Tótem del Trueno"},
                {0, 0, "Pantano Ciego"},
                {0, 0, "Enclave Cuerno Férreo"},
                {0, 0, "Cuenca Roca Escarpada"},
                {0, 0, "Arrecifes Roca Lejana"},
                {0, 0, "Cuerno del Cielo"},
                {0, 0, "Cascadas Nemorosas"},
                {35, 54, "Refugio Alblanco"},
            },
        },
        ["Suramar"] = {
            achievementID = 10669,
            proxyLocation = {45, 44, "Suramar"},
            waypoints = {
                {0, 0, "Valle Ámbar"},
                {0, 0, "Falanaar"},
                --{0, 0, "The Grand Pomenade"},
                {0, 0, "Bastión de la Guardia Lunar"},
                {0, 0, "Ruinas de Elun'eth"},
                {0, 0, "Tel'anor"},
                {0, 0, "Espesura Carmesí"},
                {0, 0, "Bastión Alma Vil"},
                {0, 0, "Jandvik"},
                {0, 0, "Quebrada Susurrolunar"},
                {0, 0, "Ciudad de Suramar"},
            },
        },
        ["Val'sharah"] = {
            achievementID = 10666,
            proxyLocation = {34, 34, "Val'sharah"},
            waypoints = {
                {0, 0, "Andu'talah"},
                {0, 0, "Arroyo Braden"},
                {0, 0, "Arrecife del Ocaso"},
                {0, 0, "Lorlathil"},
                {0, 0, "Valle Zarpaluna"},
                {0, 0, "Bosque Torracuero"},
                {0, 0, "Thas'talah"},
                {0, 0, "Torreón Grajo Negro"},
                {0, 0, "Arboleda de los Sueños"},
                {0, 0, "Arboleda de Cenarius"},
                {0, 0, "Velo de Bruma"},
                {0, 0, "Shala'nir"},
                {0, 0, "Templo de Elune"},
            },
        },
        ["Tormenheim"] = {
            achievementID = 10668,
            proxyLocation = {58, 32, "Tormenheim"},
            waypoints = {
                {0, 0, "Cámara de Aggramar"},
                {0, 0, "Desembarco Rastro del Pavor"},
                {0, 0, "Guardia Gris"},
                {0, 0, "Haustvald"},
                {35, 27, "Fauces de Nashal"},
                {0, 0, "Nastrondir"},
                {0, 0, "Bosque de las Runas"},
                {0, 0, "Skold-Ashil"},
                {0, 0, "Refugio de la Garra"},
                {0, 0, "Valdisdall"},
                {0, 0, "Mirador Pico Negro"},
                {0, 0, "Dreyrgrot"},
                {0, 0, "Puertas del Valor"},
                {0, 0, "Hrydshal"},
                {0, 0, "Morheim"},
                {0, 0, "Roca del Velador"},
                {0, 0, "Reposo del Escudo"},
                {0, 0, "Cima de la Tormenta"},
                {0, 0, "Puerto Mareskorn"},
                {0, 0, "Cimas Anegadas"},
            },
        },
    }, -- Legion
    -- Continents dictionary ...
    ["Continents"] = {
        ["Eastern Kingdoms"] = "Reinos del Este",
        ["Outland"] = "Terrallende",
        ["The Maelstrom"] = "La Vorágine",
        ["Draenor"] = "Draenor",
        ["Zandalar"] = "Zandalar",
        ["Kul Tiras"] = "Kul Tiras",
        ["Kalimdor"] = "Kalimdor",
        ["Northrend"] = "Rasganorte",
        ["Pandaria"] = "Pandaria",
        ["Broken Isles"] = "Islas Quebradas",
    },
    -- Zone Overrides dictionary --
    ["ZoneOverrides"] = {
        ["Dalaran"] = { continent = "Rasganorte"},
        ["Escudo de tormenta"] = { continent = "Draenor" },
        ["Ashran"] = { continent = "Draenor" },
        ["Ciudad de Ventormenta"] = { continent = "Reinos del Este"},
        ["Sentencia de muerte"] = { continent = "Reinos del Este"},
        ["Valle de Coldridge"] = { continent = "Reinos del Este"},
        ["Nueva ciudad de hojalatero"] = { continent = "Reinos del Este"},
        ["Vashj'ir"] = { continent = "Reinos del Este" },
        ["Profundidades Abisales"] = { continent = "Reinos del Este" },
        ["Extensión brillante"] = { continent = "Reinos del Este" },
        ["Bosque de Kelp'thar"] = { continent = "Reinos del Este" },
        ["El Cabo de Tuercespina"] = { continent = "Reinos del Este" },
        ["Norte de Tuercespina"] = { continent = "Reinos del Este" },
        ["Puerto de Boralus"] = {continent = "Kul Tiras"},
        ["Sonido de Tiragarde"] = { continent = "Kul Tiras" },
        ["Drustvar"] = { continent = "Kul Tiras" },
        ["Valle Canto Tormenta"] = { continent = "Kul Tiras" },
    }
}