Localization = Localization or {}

Localization["esES"] = {
    ["Reinos del Este"] = {
        ["Bosque de Elwynn"] = {
            achievementID = 776,
            proxyLocation = {0, 0, "Bosque de Elwynn"},
            waypoints = {
                {0, 0, "Valle de Villanorte"},
                {0, 0, "Villadorada"},
                {0, 0, "Embarcadero de Jerod"},
                {0, 0, "Plantación de Calabazas de Brackwell"},
                {0, 0, "Torre de la Peña"},
                {0, 0, "Lago del Hito"},
                {0, 0, "Cuartel de Arroyoeste"},
                {0, 0, "Mina Abisal"},
                {0, 0, "Torre de Azora"},
                {0, 0, "Aserradero de la Vega del Este"},
                {0, 0, "Lago de Cristal"},
            },
        },
        ["Tierras Inhóspitas"] = {
            achievementID = 765,
            proxyLocation = {0, 0, "Tierras Inhóspitas"},
            waypoints = {
                {0, 0, "Barranco Lethlor"},
                {0, 0, "Uldaman"},
                {0, 0, "Cicatriz del Rompemundos"},
                {0, 0, "Fortaleza de Angor"},
                {0, 0, "Paso de Mirasangre"},
                {0, 0, "El Final de Agmond"},
                {0, 0, "Asentamiento Cagg"},
                {0, 0, "Terraseca"},
                {0, 0, "Asentamiento Kosh"},
                {0, 0, "Nuevo Kargath"},
            },
        },
        ["Las Estepas Ardientes"] = {
            achievementID = 775,
            proxyLocation = {0, 0, "Las Estepas Ardientes"},
            waypoints = {
                {0, 0, "Roca Machacamiedo"},
                {0, 0, "Senda del Ala del Terror"},
                {0, 0, "Ruinas de Thaurissan"},
                {0, 0, "Bastión de Roca Negra"},
                {0, 0, "Altar de la Tempestad"},
                {0, 0, "Vigilia de Morgan"},
                {0, 0, "Desfiladero de Roca Negra"},
                {0, 0, "Cobertizo Diente Negro"},
                {0, 0, "Las Colinas de los Vástagos"},
                {0, 0, "Montaña Roca Negra"},
            },
        },
        ["Bosque del Ocaso"] = {
            achievementID = 778,
            proxyLocation = {0, 0, "Bosque del Ocaso"},
            waypoints = {
                {0, 0, "La Ribera Silente"},
                {0, 0, "Cerro del Cuervo"},
                {0, 0, "Túmulo de Vul'Gol"},
                {0, 0, "La Hacienda Yorgen"},
                {0, 0, "El Vergel Pútrido"},
                {0, 0, "Villa Oscura"},
                {0, 0, "La Ribera Lóbrega"},
                {0, 0, "Granja de Addle"},
                {0, 0, "Cementerio del Cerro del Cuervo"},
                {0, 0, "Arboleda del Crepúsculo"},
                {0, 0, "Arboleda del Destello"},
                {0, 0, "Cementerio del Jardín Sereno"},
                {0, 0, "Mansión Mantoniebla"},
            },
        },
        ["Loch Modan"] = {
            achievementID = 779,
            proxyLocation = {0, 0, "Loch Modan"},
            waypoints = {
                {0, 0, "Loch Modan"},
                {0, 0, "Fortaleza de Mo'grosh"},
                {0, 0, "Paso de la Puerta Norte"},
                {0, 0, "Excavación de Vetaferro"},
                {0, 0, "Thelsamar"},
                {0, 0, "Valle de los Reyes"},
                {0, 0, "Presa de las Tres Cabezas"},
                {0, 0, "Mina de Fuenteplata"},
                {0, 0, "Cabaña del Errante"},
                {0, 0, "Fuerte Zarpagris"},
                {0, 0, "Valle Rompecantos"},
            },
        },
        ["Claros de Tirisfal"] = {
            achievementID = 768,
            proxyLocation = {0, 0, "Claros de Tirisfal"},
            waypoints = {
                {0, 0, "Camposanto"},
                {0, 0, "Molinos de Agamand"},
                {0, 0, "Mansión Friogar"},
                {0, 0, "Granja de Garren"},
                {0, 0, "Hacienda Balnir"},
                {0, 0, "Atalaya Escarlata"},
                {0, 0, "Ruinas de Lordaeron"},
                {0, 0, "El Baluarte"},
                {0, 0, "Hacienda Solliden"},
                {0, 0, "Vega Pesadilla"},
                {0, 0, "Rémol"},
                {0, 0, "Lago Aguasclaras"},
                {0, 0, "Avanzada de los Cruzados"},
                {0, 0, "Vega Venerácnidas"},
                {0, 0, "Entrada del Monasterio Escarlata"},
                {0, 0, "Dominios de Calston"},
            },
        },
        ["La Garganta de Fuego"] = {
            achievementID = 774,
            proxyLocation = {0, 0, "La Garganta de Fuego"},
            waypoints = {
                {0, 0, "Cresta Vigía"},
                {0, 0, "Cueva Tizonegro"},
                {0, 0, "Excavación de Limugre"},
                {0, 0, "Puesto del Torio"},
                {0, 0, "La Caldera"},
                {0, 0, "El Mar de las Cenizas"},
                {0, 0, "Valle Polvofuego"},
                {0, 0, "Montaña Roca Negra"},
            },
        },
        ["Tierras Fantasma"] = {
            achievementID = 858,
            proxyLocation = {0, 0, "Tierras Fantasma"},
            waypoints = {
                {0, 0, "Tranquillien"},
                {0, 0, "Aldea Bruma Dorada"},
                {0, 0, "Sagrario de la Luna"},
                {0, 0, "Aguja de la Estrella del Alba"},
                {0, 0, "Zigurat Aullante"},
                {0, 0, "Zeb'Nowa"},
                {0, 0, "Aguja Brisaveloz"},
                {0, 0, "Cruce Elrendar"},
                {0, 0, "Aldea Corona del Sol"},
                {0, 0, "Aldea Brisaveloz"},
                {0, 0, "Sagrario del Sol"},
                {0, 0, "Enclave del Errante"},
                {0, 0, "Ciudad de la Muerte"},
                {0, 0, "Paso de Amani"},
                {0, 0, "Zigurat Sangrante"},
                {0, 0, "Desfiladero Thalassiano"},
            },
        },
        ["El Cabo de Tuercespina"] = {
            achievementID = 4995,
            proxyLocation = {0, 0, "El Cabo de Tuercespina"},
            waypoints = {
                {0, 0, "Bahía del Botín"},
                {0, 0, "Arena Gurubashi"},
                {0, 0, "Isla Jaquero"},
                {0, 0, "Manantial Nek'mani"},
                {0, 0, "Ruinas de Jubuwal"},
                {0, 0, "Mina de Cristal"},
                {0, 0, "Escondrijo Malallave"},
                {0, 0, "Valle del Velo de Bruma"},
                {0, 0, "Ruinas de Aboraz"},
                {0, 0, "La Orilla Salvaje"},
            },
        },
        ["Las Tierras del Interior"] = {
            achievementID = 773,
            proxyLocation = {0, 0, "Las Tierras del Interior"},
            waypoints = {
                {0, 0, "Pico Nidal"},
                {0, 0, "Zun'watha"},
                {0, 0, "Shadra'Alor"},
                {0, 0, "Agol'watha"},
                {0, 0, "El Altar de Zul"},
                {0, 0, "Roca Oculta"},
                {0, 0, "Jintha'Alor"},
                {0, 0, "Barranco Bruma Enferma"},
                {0, 0, "Avanzada Quel'Danil"},
                {0, 0, "Lago Ventobravo"},
                {0, 0, "Las Ruinas Abyectas"},
                {0, 0, "Seradane"},
                {0, 0, "Shaol'watha"},
                {0, 0, "Los Acantilados Dominantes"},
            },
        },
        ["Los Humedales"] = {
            achievementID = 841,
            proxyLocation = {0, 0, "Los Humedales"},
            waypoints = {
                {0, 0, "Puerto de Menethil"},
                {0, 0, "Pantano Branquiazul"},
                {0, 0, "Pantano del Ocaso"},
                {0, 0, "Tumba de Barbaférrea"},
                {0, 0, "Campamento Dentellada"},
                {0, 0, "Arboleda del Guardaverde"},
                {0, 0, "Cerro Fraguaferoz"},
                {0, 0, "Peritaje de Tallalosas"},
                {0, 0, "Pantano del Canal Negro"},
                {0, 0, "Excavación de Whelgar"},
                {0, 0, "Cañada Salobre"},
                {0, 0, "Dun Modr"},
                {0, 0, "Roca Thelgen"},
                {0, 0, "Pantano Pellejomusgo"},
                {0, 0, "Dun Algaz"},
                {0, 0, "Colina del Raptor"},
            },
        },
        ["Tierras de la Peste del Oeste"] = {
            achievementID = 770,
            proxyLocation = {0, 0, "Tierras de la Peste del Oeste"},
            waypoints = {
                {0, 0, "Lago Darrowmere"},
                {0, 0, "Colina de las Penas"},
                {0, 0, "El Baluarte"},
                {0, 0, "Granja de Dalson"},
                {0, 0, "Aserradero Crestanorte"},
                {0, 0, "Valle Pinorrojo"},
                {0, 0, "La Cueva del Llanto"},
                {0, 0, "Castel Darrow"},
                {0, 0, "Andorhal"},
                {0, 0, "Campo de Piedramácula"},
                {0, 0, "El Tormento"},
                {0, 0, "Vega del Amparo"},
                {0, 0, "Gangrena de Gahrron"},
                {0, 0, "Río Thondroril"},
            },
        },
        ["Isla de Quel'Danas"] = {
            achievementID = 868,
            proxyLocation = {0, 0, "Isla de Quel'Danas"},
            waypoints = {
            },
        },
        ["Tierras Altas de Arathi"] = {
            achievementID = 761,
            proxyLocation = {0, 0, "Tierras Altas de Arathi"},
            waypoints = {
                {0, 0, "Círculo de Vínculo Oeste"},
                {0, 0, "Roca'gor"},
                {0, 0, "Castillo de Stromgarde"},
                {0, 0, "Círculo de Vínculo Interior"},
                {0, 0, "Sala Puño de Roca"},
                {0, 0, "Círculo de Vínculo Exterior"},
                {0, 0, "Granja Go'shek"},
                {0, 0, "Círculo de Vínculo Este"},
                {0, 0, "Mansión Redilnorte"},
                {0, 0, "Caída de Galen"},
                {0, 0, "Cala de Faldir"},
                {0, 0, "Puente Thandol"},
                {0, 0, "Refugio de la Zaga"},
                {0, 0, "Poblado Secacorteza"},
                {0, 0, "Granja de Dabyrie"},
                {0, 0, "Sentencia"},
            },
        },
        ["Las Tierras Devastadas"] = {
            achievementID = 766,
            proxyLocation = {0, 0, "Las Tierras Devastadas"},
            waypoints = {
                {0, 0, "Bastión Machacamiedo"},
                {0, 0, "Castillo de Nethergarde"},
                {0, 0, "El Portal Oscuro"},
                {0, 0, "Puesto Machacamiedo"},
                {0, 0, "Alto de los Rapiñadores"},
                {0, 0, "Excursión Velosolar"},
                {0, 0, "Las Costas Rojas"},
                {0, 0, "Campamento de Suministros de Nethergarde"},
                {0, 0, "Serpiente Enroscada"},
                {0, 0, "Altar de la Tempestad"},
                {0, 0, "Escara Impía"},
                {0, 0, "Costa Quebrada"},
                {0, 0, "Mechasur"},
                {0, 0, "El Bosque Corrupto"},
            },
        },
        ["Dun Morogh"] = {
            achievementID = 627,
            proxyLocation = {0, 0, "Dun Morogh"},
            waypoints = {
                {0, 0, "Desfiladero de Crestanevada"},
                {0, 0, "Frente de Peloescarcha"},
                {0, 0, "Base Aérea de Forjaz"},
                {0, 0, "Kharanos"},
                {0, 0, "Granja de Semperámbar"},
                {0, 0, "Cantera de Gol'Bolar"},
                {0, 0, "Poblado Peloescarcha"},
                {0, 0, "Puertas de Forjaz"},
                {0, 0, "Valle de Crestanevada"},
                {0, 0, "Nueva Ciudad Manitas"},
                {0, 0, "Monte Luz"},
                {0, 0, "Las Colinas Tundra"},
                {0, 0, "Lago de Helm"},
                {0, 0, "Avanzada de la Puerta Norte"},
                {0, 0, "Lago Glacial"},
            },
        },
        ["Laderas de Trabalomas"] = {
            achievementID = 772,
            proxyLocation = {0, 0, "Laderas de Trabalomas"},
            waypoints = {
                {0, 0, "Mina Azur"},
                {0, 0, "Daga de Corrahn"},
                {0, 0, "Alto del Orvallo"},
                {0, 0, "Redil de Dandred"},
                {0, 0, "Dun Garok"},
                {0, 0, "Camino de la Horca"},
                {0, 0, "Caverna Estrecha"},
                {0, 0, "Granja Nethander"},
                {0, 0, "Ruinas de Alterac"},
                {0, 0, "Cuenca de la Matanza"},
                {0, 0, "Puerta Austral"},
                {0, 0, "Molino Tarren"},
                {0, 0, "Los Campos de Lodo"},
                {0, 0, "Granja de Brazie"},
                {0, 0, "Dominios de los Aplastacresta"},
                {0, 0, "Cráter de Dalaran"},
                {0, 0, "Colinas de Darrow"},
                {0, 0, "Castillo de Durnholde"},
                {0, 0, "Saliente de Gavin"},
                {0, 0, "Costa de la Neblina"},
                {0, 0, "Isla del Purgatorio"},
                {0, 0, "Ruinas de Costasur"},
                {0, 0, "Saliente de Sofera"},
                {0, 0, "Strahnbrad"},
                {0, 0, "La Punta"},
                {0, 0, "Las Tierras Altas"},
            },
        },
        ["Montañas Crestagrana"] = {
            achievementID = 780,
            proxyLocation = {0, 0, "Montañas Crestagrana"},
            waypoints = {
                {0, 0, "Villa del Lago"},
                {0, 0, "Tres Caminos"},
                {0, 0, "Cañones de Crestagrana"},
                {0, 0, "Cascadas Petravista"},
                {0, 0, "Campamento de Render"},
                {0, 0, "Valle de Galardell"},
                {0, 0, "Campamento Sempiterno"},
                {0, 0, "Lago Sempiterno"},
                {0, 0, "Camino del Lago"},
                {0, 0, "Molino de Alther"},
                {0, 0, "Valle de Render"},
                {0, 0, "Fuerte de Petravista"},
                {0, 0, "Cañón del Viento Calizo"},
            },
        },
        ["Bosque Canción Eterna"] = {
            achievementID = 859,
            proxyLocation = {0, 0, "Bosque Canción Eterna"},
            waypoints = {
                {0, 0, "Isla del Caminante del Sol"},
                {0, 0, "Sagrario del Oeste"},
                {0, 0, "Sagrario del Norte"},
                {0, 0, "El Retiro del Errante"},
                {0, 0, "Tierras Ocaso Marchito"},
                {0, 0, "El Bosque Viviente"},
                {0, 0, "La Arboleda Agostada"},
                {0, 0, "Costa Bris Azur"},
                {0, 0, "Desfiladero Ramadorada"},
                {0, 0, "Piedra Rúnica Falithas"},
                {0, 0, "Refugio de Saltheril"},
                {0, 0, "Caballería de Thuron"},
                {0, 0, "Zeb'Watha"},
                {0, 0, "Ruinas de Lunargenta"},
                {0, 0, "Fondeadero Vela del Sol"},
                {0, 0, "Sagrario del Este"},
                {0, 0, "Charca Plácido Susurro"},
                {0, 0, "Aldea Brisa Pura"},
                {0, 0, "Tor'Watha"},
                {0, 0, "Ciudad de Lunargenta"},
                {0, 0, "Cascadas Elrendar"},
                {0, 0, "Lago Elrendar"},
                {0, 0, "Piedra Rúnica Shan'dor"},
                {0, 0, "La Ensenada Dorada"},
                {0, 0, "Orilla Tranquila"},
            },
        },
        ["Bosque de Argénteos"] = {
            achievementID = 769,
            proxyLocation = {0, 0, "Bosque de Argénteos"},
            waypoints = {
                {0, 0, "El Frente de Batalla"},
                {0, 0, "El Frente Renegado"},
                {0, 0, "Desembarco Mareanorte"},
                {0, 0, "Campo de Valgan"},
                {0, 0, "Mina de Elem"},
                {0, 0, "Molino Ámbar"},
                {0, 0, "Alto Mando Renegado"},
                {0, 0, "Puesto de Retaguardia Renegado"},
                {0, 0, "Los Campos Decrépitos"},
                {0, 0, "Penumbra de las Celerácnidas"},
                {0, 0, "Isla de Fenris"},
                {0, 0, "El Sepulcro"},
                {0, 0, "Finca de Olsen"},
                {0, 0, "Castillo de Colmillo Oscuro"},
                {0, 0, "Cala Mareanorte"},
            },
        },
        ["Norte de la Vega de Tuercespina"] = {
            achievementID = 781,
            proxyLocation = {0, 0, "Norte de la Vega de Tuercespina"},
            waypoints = {
                {0, 0, "Campamento Grom'gol"},
                {0, 0, "Bambala"},
                {0, 0, "Ruinas Zuuldaia"},
                {0, 0, "Asentamiento Rebelde"},
                {0, 0, "Ruinas de Kal'ai"},
                {0, 0, "Túmulo Ogro Mosh'Ogg"},
                {0, 0, "Ruinas de Bal'lal"},
                {0, 0, "Ruinas de Zul'Kunda"},
                {0, 0, "Ruinas de Balia'mah"},
                {0, 0, "Fuerte Livingston"},
                {0, 0, "Expedición de Nesingwary"},
                {0, 0, "Base de Kurzen"},
                {0, 0, "Ruinas de Mizjah"},
                {0, 0, "Lago Nazferiti"},
                {0, 0, "El Arrecife Mortal"},
                {0, 0, "Zul'Gurub"},
            },
        },
        ["Pantano de las Penas"] = {
            achievementID = 782,
            proxyLocation = {0, 0, "Pantano de las Penas"},
            waypoints = {
                {0, 0, "Valle Brumoso"},
                {0, 0, "Cruce Lanzarrota"},
                {0, 0, "Rocal"},
                {0, 0, "Stagalbog"},
                {0, 0, "Chapaleos"},
                {0, 0, "Cueva de Manantial"},
                {0, 0, "El Puerto"},
                {0, 0, "Lodo Traicionero"},
                {0, 0, "Charca de Lágrimas"},
                {0, 0, "Tinieblas de las Penas"},
                {0, 0, "Playa Juncobruma"},
                {0, 0, "Avanzada Marea Pantanosa"},
            },
        },
        ["Páramos de Poniente"] = {
            achievementID = 802,
            proxyLocation = {0, 0, "Páramos de Poniente"},
            waypoints = {
                {0, 0, "Colina del Centinela"},
                {0, 0, "Plantación de Calabazas de Cejade"},
                {0, 0, "Mina de Jango"},
                {0, 0, "El Campo Funesto"},
                {0, 0, "Hacienda de Alexston"},
                {0, 0, "Las Colinas Afiladas"},
                {0, 0, "Los Yermos Polvorientos"},
                {0, 0, "Finca de Saldean"},
                {0, 0, "La Finca de Jansen"},
                {0, 0, "La Granja de Molsen"},
                {0, 0, "Arroyo de la Luna"},
                {0, 0, "Paraje de Demont"},
                {0, 0, "La Sima Enfurecida"},
            },
        },
        ["Paso de la Muerte"] = {
            achievementID = 777,
            proxyLocation = {0, 0, "Paso de la Muerte"},
            waypoints = {
                {0, 0, "Cruce de la Muerte"},
                {0, 0, "Karazhan"},
                {0, 0, "El Vicio"},
            },
        },
        ["Tierras de la Peste del Este"] = {
            achievementID = 771,
            proxyLocation = {0, 0, "Tierras de la Peste del Este"},
            waypoints = {
                {0, 0, "Río Thondroril"},
                {0, 0, "La Subgranja"},
                {0, 0, "Cuenca Fungal"},
                {0, 0, "Cicatriz Pestilente"},
                {0, 0, "Lago Mereldar"},
                {0, 0, "Capilla de la Esperanza de la Luz"},
                {0, 0, "El Claro Ponzoñoso"},
                {0, 0, "Lago del Bosque Negro"},
                {0, 0, "Zul'Mashar"},
                {0, 0, "Refugio Quel'Lithien"},
                {0, 0, "Bosque de la Peste"},
                {0, 0, "Ruinas de El Enclave Escarlata"},
                {0, 0, "Hacienda de Marris"},
                {0, 0, "Torre de la Corona"},
                {0, 0, "Villa Darrow"},
                {0, 0, "Cruce de Corin"},
                {0, 0, "Mano de Tyr"},
                {0, 0, "La Cicatriz Purulenta"},
                {0, 0, "Torre de la Muralla del Este"},
                {0, 0, "Vallenorte"},
                {0, 0, "Torre del Paso Norte"},
                {0, 0, "Valle del Terror"},
                {0, 0, "Stratholme"},
            },
        },
    },
    ["Terrallende"] = {
        ["Península del Fuego Infernal"] = {
            achievementID = 862,
            proxyLocation = {0, 0, "Península del Fuego Infernal"},
            waypoints = {
                {0, 0, "Los Peldaños del Destino"},
                {0, 0, "Avanzada del Halcón"},
                {0, 0, "Bastión del Honor"},
                {0, 0, "Pozas de Aggonar"},
                {0, 0, "Templo de Telhamat"},
                {0, 0, "Thrallmar"},
                {0, 0, "Zeth'Gor"},
                {0, 0, "Cresta Cielo Estrellado"},
                {0, 0, "Los Campos Alabeados"},
                {0, 0, "Armería de Expedición"},
                {0, 0, "Ciudadela del Fuego Infernal"},
                {0, 0, "Puesto Mag'har"},
                {0, 0, "Ruinas de Sha'naar"},
                {0, 0, "La Avanzadilla de la Legión"},
                {0, 0, "Trono de Kil'jaeden"},
                {0, 0, "Cubil de Haal'esh"},
                {0, 0, "Cresta del Vacío"},
                {0, 0, "Campamento Forja: Mageddon"},
            },
        },
        ["Bosque de Terokkar"] = {
            achievementID = 867,
            proxyLocation = {0, 0, "Bosque de Terokkar"},
            waypoints = {
                {0, 0, "Ruinas Foso Sangrante"},
                {0, 0, "Matorral Cenarion"},
                {0, 0, "Poblado Grangol'var"},
                {0, 0, "Tuurem"},
                {0, 0, "Claro Raastok"},
                {0, 0, "Saliente Rajaespina"},
                {0, 0, "Tierras Auchenai"},
                {0, 0, "Caravana de Refugiados"},
                {0, 0, "Tumba Umbría"},
                {0, 0, "Velo Rhaze"},
                {0, 0, "Skettis"},
                {0, 0, "Bastión Allerian"},
                {0, 0, "Alto Ala de Fuego"},
                {0, 0, "Bastión Rompepedras"},
                {0, 0, "Ciudad de Shattrath"},
                {0, 0, "Las Colinas Barrera"},
                {0, 0, "Ruinas Mascahuesos"},
                {0, 0, "Colina Carroña"},
                {0, 0, "Círculo de la Observancia"},
                {0, 0, "Caravana Derelicta"},
                {0, 0, "Alcor Tortuoso"},
            },
        },
        ["Montañas Filospada"] = {
            achievementID = 865,
            proxyLocation = {0, 0, "Montañas Filospada"},
            waypoints = {
                {0, 0, "Alto Bash'ir"},
                {0, 0, "Bastión Aguja del Filo"},
                {0, 0, "Avanzada Machacasangre"},
                {0, 0, "Anillo de Sangre"},
                {0, 0, "Campamento Forja: Inquina"},
                {0, 0, "Campamento Forja: Cólera"},
                {0, 0, "Guarida de Gruul"},
                {0, 0, "Aldea Mok'Nathal"},
                {0, 0, "Loma Tajo"},
                {0, 0, "Skald"},
                {0, 0, "Espina de Cristal"},
                {0, 0, "Velo Lashh"},
                {0, 0, "Alto Vekhaar"},
                {0, 0, "Barranco del Filo"},
                {0, 0, "Campamento Machacasangre"},
                {0, 0, "Landas Tábidas"},
                {0, 0, "Puerta de la Muerte"},
                {0, 0, "Campamento Forja: Terror"},
                {0, 0, "Grishnath"},
                {0, 0, "Cresta Dentada"},
                {0, 0, "Bosque del Cuervo"},
                {0, 0, "Foresta Ruuan"},
                {0, 0, "Sylvanaar"},
                {0, 0, "Bastión Señor del Trueno"},
                {0, 0, "Velo Ruuan"},
                {0, 0, "Cumbre del Vórtice"},
            },
        },
        ["Valle Sombraluna"] = {
            achievementID = 864,
            proxyLocation = {0, 0, "Valle Sombraluna"},
            waypoints = {
                {0, 0, "Alto Cicatriz Espiral"},
                {0, 0, "Bastión de la Legión"},
                {0, 0, "Aldea Sombraluna"},
                {0, 0, "La Forja Muerta"},
                {0, 0, "Jaula de la Guardiana"},
                {0, 0, "Altar de Sha'tar"},
                {0, 0, "Campos del Ala Abisal"},
                {0, 0, "Punta Eclipse"},
                {0, 0, "Arrecife del Ala Abisal"},
                {0, 0, "El Templo Oscuro"},
                {0, 0, "La Mano de Gul'dan"},
                {0, 0, "Bastión Martillo Salvaje"},
                {0, 0, "Alto Illidari"},
            },
        },
        ["Marisma de Zangar"] = {
            achievementID = 863,
            proxyLocation = {0, 0, "Marisma de Zangar"},
            waypoints = {
                {0, 0, "Refugio Cenarion"},
                {0, 0, "Aldea Feropantano"},
                {0, 0, "Lago Luz Pantanosa"},
                {0, 0, "Telredor"},
                {0, 0, "La Laguna"},
                {0, 0, "Aldea Umbropantano"},
                {0, 0, "Bastión Ango'rosh"},
                {0, 0, "Puerto Orebor"},
                {0, 0, "Zabra'jin"},
                {0, 0, "Dominios Ango'rosh"},
                {0, 0, "Ciénaga Talada"},
                {0, 0, "Cresta Quagg"},
                {0, 0, "El Lodo Muerto"},
                {0, 0, "Ruinas de las Agujas Gemelas"},
                {0, 0, "Esporaggar"},
                {0, 0, "Tierras Escamas de Sangre"},
                {0, 0, "La Cañada Emergente"},
                {0, 0, "Playa Crestanegra"},
            },
        },
        ["Nagrand"] = {
            achievementID = 866,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Campamento Forja: Miedo"},
                {0, 0, "Halaa"},
                {0, 0, "Ruinas Riecráneos"},
                {0, 0, "Puesto Primasol"},
                {0, 0, "El Círculo de los Retos"},
                {0, 0, "Colina Mazo de Guerra"},
                {0, 0, "Avanzada del Clan"},
                {0, 0, "Grieta del Viento Sur"},
                {0, 0, "Paso Junco Alabeado"},
                {0, 0, "Loma de Zangar"},
                {0, 0, "Garadar"},
                {0, 0, "Fortaleza Mata'penas"},
                {0, 0, "Campos de Espíritus"},
                {0, 0, "Telaar"},
                {0, 0, "El Trono de los Elementos"},
                {0, 0, "Ruinas Filo Ardiente"},
                {0, 0, "Campamento Forja: Odio"},
                {0, 0, "La Cresta del Crepúsculo"},
                {0, 0, "Aldea Junco Alabeado"},
            },
        },
        ["Tormenta Abisal"] = {
            achievementID = 843,
            proxyLocation = {0, 0, "Tormenta Abisal"},
            waypoints = {
                {0, 0, "Área 52"},
                {0, 0, "Forja de Maná Coruu"},
                {0, 0, "Forja de Maná Ara"},
                {0, 0, "Ruinas de Farahlon"},
                {0, 0, "La Pila"},
                {0, 0, "Cresta Celestial"},
                {0, 0, "Piedra Abisal"},
                {0, 0, "Bastión Furia del Sol"},
                {0, 0, "Puente Girolámina"},
                {0, 0, "Punto de Escala de El Etereum"},
                {0, 0, "Base Forja: Olvido"},
                {0, 0, "Forja de Maná B'naar"},
                {0, 0, "Forja de Maná Duro"},
                {0, 0, "Forja de Maná Ultris"},
                {0, 0, "El Castillo de la Tempestad"},
                {0, 0, "Ruinas Arklon"},
                {0, 0, "Poblado Kirin'Var"},
                {0, 0, "Ruinas de Enkaat"},
                {0, 0, "Flecha de la Tormenta"},
                {0, 0, "Ecodomo Campolejano"},
                {0, 0, "Trono de Socrethar"},
                {0, 0, "Ecodomo de la Tierra Media"},
            },
        },
    },
    ["Cataclysm"] = {
        ["Hyjal"] = {
            achievementID = 4863,
            proxyLocation = {0, 0, "Hyjal"},
            waypoints = {
                {0, 0, "Límite del Mundo"},
                {0, 0, "Lago Cinéreo"},
                {0, 0, "Puertas de Sothann"},
                {0, 0, "Nidal de Sethria"},
                {0, 0, "La Estela Ardiente"},
                {0, 0, "El Trono de la Llama"},
                {0, 0, "El Círculo de las Cenizas"},
                {0, 0, "Garganta Negro Rumor"},
                {0, 0, "Nordrassil"},
                {0, 0, "Santuario de Goldrinn"},
                {0, 0, "La Llanura Agostada"},
            },
        },
        ["Infralar"] = {
            achievementID = 4864,
            proxyLocation = {0, 0, "Infralar"},
            waypoints = {
                {0, 0, "Caída de Alamuerte"},
                {0, 0, "Fosa Rocaguja"},
                {0, 0, "Restos de la Furia de la Tormenta"},
                {0, 0, "El Nidal Pálido"},
                {0, 0, "Los Campos Convulsos"},
                {0, 0, "Puerta de los Maestros"},
                {0, 0, "Sima Rocaguja"},
                {0, 0, "Hogar Pétreo"},
                {0, 0, "Templo de la Tierra"},
                {0, 0, "Trono de Therazane"},
                {0, 0, "Mirador Crepuscular"},
                {0, 0, "Extensión Carmesí"},
            },
        },
        ["Tierras Altas Crepusculares"] = {
            achievementID = 4866,
            proxyLocation = {0, 0, "Tierras Altas Crepusculares"},
            waypoints = {
                {0, 0, "Garganta de Sangre"},
                {0, 0, "Machacolpe"},
                {0, 0, "Puerto Faucedraco"},
                {0, 0, "Patrulla de Barbafuego"},
                {0, 0, "Campamento de Guerra Gorshak"},
                {0, 0, "Bancalto"},
                {0, 0, "Conflagración de Humboldt"},
                {0, 0, "Bosque Obsidiana"},
                {0, 0, "Cala Serpenteante"},
                {0, 0, "La Garganta"},
                {0, 0, "La Brecha Crepuscular"},
                {0, 0, "Orilla Crepuscular"},
                {0, 0, "Paso del Invicto"},
                {0, 0, "Las Fauces de la Locura"},
                {0, 0, "Crisol de Matanza"},
                {0, 0, "Paso Faucedraco"},
                {0, 0, "Ruinas Montocre"},
                {0, 0, "Foso Tripal"},
                {0, 0, "Grim Batol"},
                {0, 0, "Bosque de las Tierras Altas"},
                {0, 0, "Kirthaven"},
                {0, 0, "Ruinas de Drakgor"},
                {0, 0, "La Brecha Negra"},
                {0, 0, "La Krazzería"},
                {0, 0, "Bramal"},
                {0, 0, "Reducto Bermellón"},
                {0, 0, "Recodo de Vermis"},
            },
        },
        ["Vashj'ir"] = {
            achievementID = 4825,
            proxyLocation = {0, 0, "Vashj'ir"},
            waypoints = {
                {0, 0, "Arrecife Abandonado"},
                {0, 0, "Cañón Sondaluz"},
                {0, 0, "Fin de Korthun"},
                {0, 0, "Malezamarina"},
                {0, 0, "Barranco Brillohondo"},
                {0, 0, "Saliente de Guraturdido"},
                {0, 0, "Tumba del Navegante"},
                {0, 0, "Arrecife de Huesos"},
                {0, 0, "Nespirah"},
                {0, 0, "Ruinas de Vashj'ir"},
                {0, 0, "Cuenca de Marea Argenta"},
                {0, 0, "Brecha Abisal"},
                {0, 0, "Cresta de Aleta Profunda"},
                {0, 0, "L'ghorek"},
                {0, 0, "La Sima Escaldante"},
                {0, 0, "Fosa de Bocados"},
                {0, 0, "El Encierro"},
                {0, 0, "Destino de la Legión"},
                {0, 0, "Cresta de Beth'mora"},
                {0, 0, "Ruinas del Templo Thelserai"},
                {0, 0, "Gruta Bruñida"},
            },
        },
        ["Uldum"] = {
            achievementID = 4865,
            proxyLocation = {0, 0, "Uldum"},
            waypoints = {
                {0, 0, "Campos de Akhenet"},
                {0, 0, "Tumba de Khartut"},
                {0, 0, "Mar'at"},
                {0, 0, "Ciudad de Neferset"},
                {0, 0, "Obelisco de las Estrellas"},
                {0, 0, "Orsis"},
                {0, 0, "Ruinas de Ahmtul"},
                {0, 0, "Embarcadero de Schnottz"},
                {0, 0, "Templo de Uldum"},
                {0, 0, "La Puerta de los Ciclos Eternos"},
                {0, 0, "La Senda de la Devastación"},
                {0, 0, "Cuna de los Ancestros"},
                {0, 0, "Ciudad Perdida de los Tol'vir"},
                {0, 0, "Nahom"},
                {0, 0, "Obelisco de la Luna"},
                {0, 0, "Obelisco del Sol"},
                {0, 0, "Ramkahen"},
                {0, 0, "Ruinas de Ammon"},
                {0, 0, "Tierras de Tahret"},
                {0, 0, "El Embarcadero Maldito"},
                {0, 0, "Tumbas de los Precursores"},
                {0, 0, "Presa Vir'naal"},
            },
        },
    },
    ["Draenor"] = {
        ["Cresta Fuego Glacial"] = {
            achievementID = 8937,
            proxyLocation = {0, 0, "Cresta Fuego Glacial"},
            waypoints = {
                {0, 0, "Ciudadela Aguja del Filo"},
                {0, 0, "Huesos de Agurak"},
                {0, 0, "Barranco Faucedaga"},
                {0, 0, "Cerro Siniescarcha"},
                {0, 0, "Factoría de Hierro"},
                {0, 0, "Magnarok"},
                {0, 0, "Los Despojos"},
                {0, 0, "Wor'gol"},
                {0, 0, "Bastión Machacasangre"},
                {0, 0, "Óbito del Coloso"},
                {0, 0, "Risco Viento Gélido"},
                {0, 0, "Grom'gar"},
                {0, 0, "Apeadero de la Horda de Hierro"},
                {0, 0, "Avanzada Colmillo Pétreo"},
                {0, 0, "Llanuras Agrietadas"},
            },
        },
        ["Gorgrond"] = {
            achievementID = 8939,
            proxyLocation = {0, 0, "Gorgrond"},
            waypoints = {
                {0, 0, "Alto del Bastión"},
                {0, 0, "Terminal Malavía"},
                {0, 0, "Risayerta"},
                {0, 0, "Floración Sol Eterno"},
                {0, 0, "Paso Alto"},
                {0, 0, "Arena Quebrantarrocas"},
                {0, 0, "La Vereda de Hierro"},
                {0, 0, "Avanzada de las Bestias"},
                {0, 0, "Pantano Carmesí"},
                {0, 0, "Fronda del Vergel"},
                {0, 0, "Cañón de Gronns"},
                {0, 0, "Espesura Iyun"},
                {0, 0, "Madreselva"},
                {0, 0, "El Foso"},
                {0, 0, "El Foso"},
                {0, 0, "El Foso"},
            },
        },
        ["Cumbres de Arak"] = {
            achievementID = 8941,
            proxyLocation = {0, 0, "Cumbres de Arak"},
            waypoints = {
                {0, 0, "Skettis"},
                {0, 0, "Cenagal Sinuoso"},
                {0, 0, "Velo Zekk"},
                {0, 0, "Puerto Sur"},
                {0, 0, "Bancal del Alba"},
                {0, 0, "Bastión Garrafilada"},
                {0, 0, "Velo Perdido de Anzu"},
                {0, 0, "Marca del Cuervo"},
                {0, 0, "Hachazo"},
                {0, 0, "Risco Aullante"},
                {0, 0, "Alto Silbapellizco"},
                {0, 0, "Velo Akraz"},
                {0, 0, "Bancal de las Tierras Bajas Arrasadas"},
                {0, 0, "Cuenca de Sethekk"},
                {0, 0, "Ciudadela del almirante Taylor"},
                {0, 0, "Taller Silbapellizco"},
                {0, 0, "Valle Sangremelena"},
            },
        },
        ["Valle Sombraluna"] = {
            achievementID = 8938,
            proxyLocation = {0, 0, "Valle Sombraluna"},
            waypoints = {
                {0, 0, "Fortaleza de la Angustia"},
                {0, 0, "Elodar"},
                {0, 0, "Arboleda Sombra Umbría"},
                {0, 0, "Karabor"},
                {0, 0, "Bosque Fulgurante"},
                {0, 0, "Isla de las Sombras"},
                {0, 0, "Nidal Marea Oscura"},
                {0, 0, "Aldea Embaari"},
                {0, 0, "Gul'var"},
                {0, 0, "Shaz'gul"},
                {0, 0, "Alto de Socrethar"},
            },
        },
        ["Talador"] = {
            achievementID = 8940,
            proxyLocation = {0, 0, "Talador"},
            waypoints = {
                {0, 0, "Aruuna"},
                {0, 0, "Isla Caeocaso"},
                {0, 0, "Fuerte Wrynn"},
                {0, 0, "Gul'rok"},
                {0, 0, "Costa Orunai"},
                {0, 0, "Ciudad de Shattrath"},
                {0, 0, "Tumba de las Luces"},
                {0, 0, "Zangarra"},
                {0, 0, "Auchindoun"},
                {0, 0, "Patio de las Almas"},
                {0, 0, "Fortaleza Gordal"},
                {0, 0, "El Camino a la Gloria"},
                {0, 0, "Estadía del Anacoreta"},
                {0, 0, "Telmor"},
                {0, 0, "Tuurem"},
            },
        },
        ["Nagrand"] = {
            achievementID = 8942,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Tierras Ancestrales"},
                {0, 0, "Puertas de Grommashar"},
                {0, 0, "Puerto de Ogrópolis"},
                {0, 0, "Lok-rath"},
                {0, 0, "Puesto de Vigilancia Mok'gol"},
                {0, 0, "Telaar"},
                {0, 0, "El Círculo de los Retos"},
                {0, 0, "Costa de Zangar"},
                {0, 0, "Despeñadero Quebrado"},
                {0, 0, "Salvalor"},
                {0, 0, "Puerto Puño de Hierro"},
                {0, 0, "Avanzada de Mar'gok"},
                {0, 0, "Oshu'gun"},
                {0, 0, "El Círculo de Sangre"},
                {0, 0, "El Trono de los Elementos"},
            },
        },
    },
    ["Battle for Azeroth"] = {
        ["Estrecho de Tiragarde"] = {
            achievementID = 12556,
            proxyLocation = {0, 0, "Estrecho de Tiragarde"},
            waypoints = {
                {0, 0, "Embarcadero Puntamuelle"},
                {0, 0, "Risco Troncohelecho"},
                {0, 0, "Hacienda de Norwington"},
                {0, 0, "Chatarralandia"},
                {0, 0, "Canal Ululante"},
                {0, 0, "Glaciar Menguante"},
                {0, 0, "Boralus"},
                {0, 0, "Fuerte Libre"},
                {0, 0, "Cala Aterrakraken"},
                {0, 0, "Residencia Kennings"},
                {0, 0, "Alto del Vigía"},
            },
        },
        ["Valle Canto Tormenta"] = {
            achievementID = 12558,
            proxyLocation = {0, 0, "Valle Canto Tormenta"},
            waypoints = {
                {0, 0, "Brennadam"},
                {0, 0, "Ribera del Marinero"},
                {0, 0, "Ribera Inerte"},
                {0, 0, "Fuerte Sabio"},
                {0, 0, "Aldea Muelerroca"},
                {0, 0, "Horado Lomozarza"},
                {0, 0, "Fuerte Guerracolmillo"},
                {0, 0, "Fuerte Daelin"},
                {0, 0, "Altar de la Tormenta"},
            },
        },
        ["Nazmir"] = {
            achievementID = 12561,
            proxyLocation = {0, 0, "Nazmir"},
            waypoints = {
                {0, 0, "Humedales Primigenios"},
                {0, 0, "Ciénaga Fluvial"},
                {0, 0, "Zalamar"},
                {0, 0, "Nazwatha"},
                {0, 0, "Fangorrana"},
                {0, 0, "Corazón de la Oscuridad"},
                {0, 0, "La Necrópolis"},
                {0, 0, "Reposo de Torga"},
                {0, 0, "Zal'amak"},
            },
        },
        ["Drustvar"] = {
            achievementID = 12557,
            proxyLocation = {0, 0, "Drustvar"},
            waypoints = {
                {0, 0, "Puesto de Arom"},
                {0, 0, "Puerto del Tallador"},
                {0, 0, "Bosque Carmesí"},
                {0, 0, "Cuenca del Flechero"},
                {0, 0, "Camino Paso Alto"},
                {0, 0, "Glacial Veloaterido"},
                {0, 0, "Cementerio Lomatúmulo"},
                {0, 0, "Corlain"},
                {0, 0, "Albergue del Ocaso"},
                {0, 0, "Gol Koval"},
                {0, 0, "Guardia Occidente"},
                {0, 0, "Mansión Crestavía"},
            },
        },
        ["Zuldazar"] = {
            achievementID = 12559,
            proxyLocation = {0, 0, "Zuldazar"},
            waypoints = {
                {0, 0, "Atal'Dazar"},
                {0, 0, "Puerta de Sangre"},
                {0, 0, "Bajíos Perlatriste"},
                {0, 0, "Tierras Salvajes"},
                {0, 0, "Isla Colmillo"},
                {0, 0, "Xibala"},
                {0, 0, "Atal'Gral"},
                {0, 0, "Dazar'alor"},
                {0, 0, "Jardín de los Loa"},
                {0, 0, "Resquicio Frondoso"},
                {0, 0, "Reproche de Talanji"},
                {0, 0, "Zeb'ahari"},
            },
        },
        ["Vol'dun"] = {
            achievementID = 12560,
            proxyLocation = {0, 0, "Vol'dun"},
            waypoints = {
                {0, 0, "Atul'Aman"},
                {0, 0, "Puerto de Zem'lan"},
                {0, 0, "Puerto Ruina Pétrea"},
                {0, 0, "Templo de Akunda"},
                {0, 0, "Foso de Huesos"},
                {0, 0, "Costa Escarpada"},
                {0, 0, "Oasis Silbaflor"},
                {0, 0, "Marisma Selva Umbría"},
                {0, 0, "Puerto Peñarroja"},
                {0, 0, "Barranco Sinuoso"},
                {0, 0, "Bancal de los Devotos"},
                {0, 0, "Cauce Salobre"},
                {0, 0, "Refugio Tortuka"},
            },
        },
    },
    ["Kalimdor"] = {
        ["Durotar"] = {
            achievementID = 728,
            proxyLocation = {0, 0, "Durotar"},
            waypoints = {
                {0, 0, "Valle de los Retos"},
                {0, 0, "Cuenca Furia del Sur"},
                {0, 0, "Islas del Eco"},
                {0, 0, "Cerrotajo"},
                {0, 0, "Monte del Trueno"},
                {0, 0, "Roca del Cráneo"},
                {0, 0, "Ciudadela del Fuerte del Norte"},
                {0, 0, "Poblado Sen'jin"},
                {0, 0, "Fuerte de Tiragarde"},
                {0, 0, "Tierras Crines de Acero"},
                {0, 0, "Barranco Árido"},
                {0, 0, "Orgrimmar"},
            },
        },
        ["Teldrassil"] = {
            achievementID = 842,
            proxyLocation = {0, 0, "Teldrassil"},
            waypoints = {
                {0, 0, "Cañada Umbría"},
                {0, 0, "Dolanaar"},
                {0, 0, "Tierras de los Tuercepinos"},
                {0, 0, "Estanques de Arlithrien"},
                {0, 0, "El Claro del Oráculo"},
                {0, 0, "Darnassus"},
                {0, 0, "La Grieta"},
                {0, 0, "Hondonada Ban'ethil"},
                {0, 0, "Lago Al'Ameth"},
                {0, 0, "Aldea Brisa Estelar"},
                {0, 0, "Lago Primigenio"},
                {0, 0, "Aldea Rut'theran"},
            },
        },
        ["Los Baldíos del Norte"] = {
            achievementID = 750,
            proxyLocation = {0, 0, "Los Baldíos del Norte"},
            waypoints = {
                {0, 0, "Mina Pedrusco"},
                {0, 0, "La Empalizada de Mor'shan"},
                {0, 0, "Cima Calígine"},
                {0, 0, "Las Charcas del Olvido"},
                {0, 0, "Avanzada del Puente"},
                {0, 0, "El Cruce"},
                {0, 0, "Trinquete"},
                {0, 0, "Oasis Aguaverde"},
                {0, 0, "El Fangal"},
                {0, 0, "Las Colinas Áridas"},
                {0, 0, "Granja de Grol'dom"},
                {0, 0, "Colina Espinosa"},
                {0, 0, "El Oasis Estancado"},
                {0, 0, "La Costa Mercante"},
            },
        },
        ["Los Baldíos del Sur"] = {
            achievementID = 4996,
            proxyLocation = {0, 0, "Los Baldíos del Sur"},
            waypoints = {
                {0, 0, "Bael Modan"},
                {0, 0, "Mando de Vanguardia"},
                {0, 0, "El Alto del Honor"},
                {0, 0, "Fuerte del Norte"},
                {0, 0, "Ruinas de Taurajo"},
                {0, 0, "Punta Vendetta"},
                {0, 0, "Marca de Guerra"},
                {0, 0, "Filón Catacroquer"},
                {0, 0, "Cerro del Cazador"},
                {0, 0, "Horado Rajacieno"},
                {0, 0, "La Hojarasca"},
            },
        },
        ["Isla Bruma de Sangre"] = {
            achievementID = 861,
            proxyLocation = {0, 0, "Isla Bruma de Sangre"},
            waypoints = {
                {0, 0, "Paso de Redámbar"},
                {0, 0, "Costa Cienonegro"},
                {0, 0, "Isla Sangre Maldita"},
                {0, 0, "Enclave Brazolanudo"},
                {0, 0, "Mediavega"},
                {0, 0, "Nazzivian"},
                {0, 0, "Ruinas de Loreth'Aran"},
                {0, 0, "Campamento de Tel'athion"},
                {0, 0, "La Playa de Sangre"},
                {0, 0, "El Crionúcleo"},
                {0, 0, "El Arrecife Oculto"},
                {0, 0, "La Espiral Vectorial"},
                {0, 0, "Punta Veridiana"},
                {0, 0, "Guarida Escama de Cólera"},
                {0, 0, "Axxarien"},
                {0, 0, "Bosquespada"},
                {0, 0, "Avanzada de Sangre"},
                {0, 0, "Encrucijada de Kessel"},
                {0, 0, "Bosque Bruma"},
                {0, 0, "Loma Plumira"},
                {0, 0, "Alto de la Garra"},
                {0, 0, "El Arrecife Sangre Maldita"},
                {0, 0, "El Tramo Carmesí"},
                {0, 0, "La Poza del Hediondo"},
                {0, 0, "El Aprisco Perdido"},
                {0, 0, "El Pistón de Distorsión"},
                {0, 0, "El Reposo del Vindicador"},
                {0, 0, "Isla Cicatriz de Vermis"},
            },
        },
        ["Las Mil Agujas"] = {
            achievementID = 846,
            proxyLocation = {0, 0, "Las Mil Agujas"},
            waypoints = {
                {0, 0, "El Gran Elevador"},
                {0, 0, "Excavación Sumergida"},
                {0, 0, "Quebranto Crepuscular"},
                {0, 0, "Cima Tramo Oeste"},
                {0, 0, "Poblado Viento Libre"},
                {0, 0, "El Piélago de Sal"},
                {0, 0, "Zahúrda Rajacieno"},
                {0, 0, "Sargazo de los Mares del Sur"},
                {0, 0, "Baluarte Crepuscular"},
                {0, 0, "Cumbre de la Nube Negra"},
                {0, 0, "Cumbres Pezuña Quebrada"},
                {0, 0, "Nido Alto"},
            },
        },
        ["Desolace"] = {
            achievementID = 848,
            proxyLocation = {0, 0, "Desolace"},
            waypoints = {
                {0, 0, "Tethris Aran"},
                {0, 0, "Punta de Nijel"},
                {0, 0, "Fortaleza del Hacha de Trueno"},
                {0, 0, "Territorio Magram"},
                {0, 0, "Valle de las Lanzas"},
                {0, 0, "Aldea Cazasombras"},
                {0, 0, "Aquelarre Mannoroc"},
                {0, 0, "Barranco Rompesombras"},
                {0, 0, "Campo de Thargad"},
                {0, 0, "Sargeron"},
                {0, 0, "Tierras Vírgenes Cenarion"},
                {0, 0, "Isla Ranazjar"},
                {0, 0, "Cementerio de Kodos"},
                {0, 0, "Poblado Gelkis"},
                {0, 0, "Shok'Thokar"},
                {0, 0, "Costa Filozante"},
            },
        },
        ["Feralas"] = {
            achievementID = 849,
            proxyLocation = {0, 0, "Feralas"},
            waypoints = {
                {0, 0, "Bajas Tierras Salvajes"},
                {0, 0, "Los Dos Colosos"},
                {0, 0, "La Masacre"},
                {0, 0, "Ruinas de Isildien"},
                {0, 0, "Campamento Mojache"},
                {0, 0, "Avanzada Gordunni"},
                {0, 0, "Bastión Plumaluna"},
                {0, 0, "Ruinas de Plumaluna"},
                {0, 0, "La Costa Olvidada"},
                {0, 0, "Vega Cicatriz Feral"},
                {0, 0, "Las Galerías Retorcidas"},
                {0, 0, "Dominios Tótem Siniestro"},
                {0, 0, "Ruinas Niebla Negra"},
            },
        },
        ["Azshara"] = {
            achievementID = 852,
            proxyLocation = {0, 0, "Azshara"},
            waypoints = {
                {0, 0, "Palacete de Gallywix"},
                {0, 0, "Muelle Pantoque"},
                {0, 0, "Torre de Eldara"},
                {0, 0, "Campamento Base Darnassiano"},
                {0, 0, "Cabeza de Oso"},
                {0, 0, "Puerta Trasera de Orgrimmar"},
                {0, 0, "Playa del Arrecife Sur"},
                {0, 0, "Lago Mennar"},
                {0, 0, "Acantilados de la Tormenta"},
                {0, 0, "La Playa Arrasada"},
                {0, 0, "Costa Amarga"},
                {0, 0, "Ruinas de Arkkoran"},
                {0, 0, "El Laboratorio Secreto"},
                {0, 0, "Bastión Faucenegra"},
                {0, 0, "Ruinas de Eldarath"},
                {0, 0, "Monumento Cresta Cuervo"},
                {0, 0, "Las Ruinas"},
            },
        },
        ["Cráter de Un'Goro"] = {
            achievementID = 854,
            proxyLocation = {0, 0, "Cráter de Un'Goro"},
            waypoints = {
                {0, 0, "Cresta del Penacho en Llamas"},
                {0, 0, "Alto de Marshal"},
                {0, 0, "Los Jardines Turbados"},
                {0, 0, "Baños de Golakka"},
                {0, 0, "La Cicatriz Serpenteante"},
                {0, 0, "Meseta Roca de Hierro"},
                {0, 0, "Roca Fungal"},
                {0, 0, "Pilote Musgoso"},
                {0, 0, "Cuenca de los Gritos"},
                {0, 0, "Camino del Terror"},
                {0, 0, "Los Pantanales"},
                {0, 0, "Fosas de Alquitrán Lakkari"},
            },
        },
        ["Silithus"] = {
            achievementID = 856,
            proxyLocation = {0, 0, "Silithus"},
            waypoints = {
                {0, 0, "Vega de Cristal"},
                {0, 0, "Fuerte Cenarion"},
                {0, 0, "Colmen'Regal"},
                {0, 0, "Colmen'Ashi"},
                {0, 0, "Aldea del Viento del Sur"},
                {0, 0, "Colmen'Zora"},
                {0, 0, "El Muro del Escarabajo"},
                {0, 0, "Sosiego del Valor"},
            },
        },
        ["Mulgore"] = {
            achievementID = 736,
            proxyLocation = {0, 0, "Mulgore"},
            waypoints = {
                {0, 0, "Mesa de la Nube Roja"},
                {0, 0, "Poblado Pezuña de Sangre"},
                {0, 0, "Las Llanuras Onduladas"},
                {0, 0, "Caravana Devastada"},
                {0, 0, "Pozo Tronacuerno"},
                {0, 0, "Roca Roja"},
                {0, 0, "Pozo Ferocrín"},
                {0, 0, "Roca Crines Pálidas"},
                {0, 0, "Pozo Pezuña Invernal"},
                {0, 0, "Mina Ventura y Cía."},
                {0, 0, "Las Llanuras Doradas"},
                {0, 0, "Excavación de Bael'dun"},
                {0, 0, "Cresta Viento Furioso"},
            },
        },
        ["Isla Bruma Azur"] = {
            achievementID = 860,
            proxyLocation = {0, 0, "Isla Bruma Azur"},
            waypoints = {
                {0, 0, "Valle Ammen"},
                {0, 0, "Avanzada Azur"},
                {0, 0, "El Claro de Ascuas"},
                {0, 0, "Campamento de Geezle"},
                {0, 0, "Desembarco de Odesyus"},
                {0, 0, "El Cementerio de Cápsulas"},
                {0, 0, "Isla Bruma de Plata"},
                {0, 0, "El Exodar"},
                {0, 0, "Punto Escama de Cólera"},
                {0, 0, "Vado Ammen"},
                {0, 0, "Aldea Brazolanudo"},
                {0, 0, "Playa Puentegrato"},
                {0, 0, "Bosque Pasto Lunar"},
                {0, 0, "La Maraña de Cápsulas"},
                {0, 0, "La Costa de Cieno"},
                {0, 0, "Bastión Semprepino"},
                {0, 0, "Atracadero de Valaar"},
            },
        },
        ["Cuna del Invierno"] = {
            achievementID = 857,
            proxyLocation = {0, 0, "Cuna del Invierno"},
            waypoints = {
                {0, 0, "Baños de Fuego de Escarcha"},
                {0, 0, "Lago Kel'Theril"},
                {0, 0, "Mazthoril"},
                {0, 0, "Matorral del Ala del Búho"},
                {0, 0, "Poblado Nevada"},
                {0, 0, "Roca Sable de Hielo"},
                {0, 0, "Puesto de los Fauces de Madera"},
                {0, 0, "Aldea Estrella Fugaz"},
                {0, 0, "Vista Eterna"},
                {0, 0, "Colinas Cardo Nevado"},
                {0, 0, "La Arboleda Oculta"},
                {0, 0, "Cañón Levescarcha"},
            },
        },
        ["Costa Oscura"] = {
            achievementID = 844,
            proxyLocation = {0, 0, "Costa Oscura"},
            waypoints = {
                {0, 0, "Ruinas de Auberdine"},
                {0, 0, "Campamento de Guerra Rompelanzas"},
                {0, 0, "Arboleda Marchita"},
                {0, 0, "El Ojo del Vórtice"},
                {0, 0, "Lor'danel"},
                {0, 0, "La Espada del Maestro"},
                {0, 0, "Valle Rompelanzas"},
                {0, 0, "Río Culebra"},
                {0, 0, "Ruinas de Mathystra"},
                {0, 0, "Ameth'Aran"},
                {0, 0, "Nazj'vel"},
            },
        },
        ["Vallefresno"] = {
            achievementID = 845,
            proxyLocation = {0, 0, "Vallefresno"},
            waypoints = {
                {0, 0, "La Ensenada de Zoram"},
                {0, 0, "Refugio Brisa de Plata"},
                {0, 0, "Lago Falathim"},
                {0, 0, "Poblado Piel de Cardo"},
                {0, 0, "Astranaar"},
                {0, 0, "Vega del Aullido"},
                {0, 0, "Lago Cielo Estrellado"},
                {0, 0, "Satyrnaar"},
                {0, 0, "Aserradero Grito de Guerra"},
                {0, 0, "Refugio de Orendil"},
                {0, 0, "Pico del Trueno"},
                {0, 0, "Atalaya de Maestra"},
                {0, 0, "El Santuario de Aessina"},
                {0, 0, "Las Ruinas del Polvo Estelar"},
                {0, 0, "Refugio de la Algaba"},
                {0, 0, "Puesto del Hachazo"},
                {0, 0, "Talloumbrío"},
                {0, 0, "Cerro Lumbrevil"},
            },
        },
        ["Sierra Espolón"] = {
            achievementID = 847,
            proxyLocation = {0, 0, "Sierra Espolón"},
            waypoints = {
                {0, 0, "Valle Marca de Guerra"},
                {0, 0, "Ruinas de Eldre'thar"},
                {0, 0, "Campos Desenterrados"},
                {0, 0, "Bastión Cortaviento"},
                {0, 0, "Malaka'jin"},
                {0, 0, "Barranco del Alud"},
                {0, 0, "Risco Cortaviento"},
                {0, 0, "La Vega Carbonizada"},
                {0, 0, "Cima del Espolón"},
                {0, 0, "Fortaleza Krom'gar"},
                {0, 0, "Mirador Thal'darah"},
                {0, 0, "Cuenca de las Tejedoras"},
                {0, 0, "Puesto Caminarrisco"},
                {0, 0, "Senda de las Tejedoras"},
                {0, 0, "Vega del Gran Bosque"},
                {0, 0, "Refugio Roca del Sol"},
                {0, 0, "Lago Mirkfallon"},
            },
        },
        ["Marjal Revolcafango"] = {
            achievementID = 850,
            proxyLocation = {0, 0, "Marjal Revolcafango"},
            waypoints = {
                {0, 0, "Isla Theramore"},
                {0, 0, "Puesto Cuernoatroz"},
                {0, 0, "Posada Reposo Umbrío"},
                {0, 0, "Poblado Murohelecho"},
                {0, 0, "Isla de Alcaz"},
                {0, 0, "Poblado Pezuñanegra"},
                {0, 0, "Piñón de Barro"},
                {0, 0, "Playa Tenebruma"},
                {0, 0, "Ciénaga de Fuego"},
            },
        },
        ["Tanaris"] = {
            achievementID = 851,
            proxyLocation = {0, 0, "Tanaris"},
            waypoints = {
                {0, 0, "Gadgetzan"},
                {0, 0, "Valle de los Vigías"},
                {0, 0, "Arenas Abisales"},
                {0, 0, "La Guarida Ponzoñosa"},
                {0, 0, "Tierras del Sur"},
                {0, 0, "Ruinas de Lunaeste"},
                {0, 0, "Ruinas de Lunasur"},
                {0, 0, "Zul'Farrak"},
                {0, 0, "Vigía Penas de Arena"},
                {0, 0, "Cala del Aparejo Perdido"},
                {0, 0, "Pilar Partido"},
                {0, 0, "Base Machacaduna"},
                {0, 0, "Sima Abierta"},
                {0, 0, "Playa Finisterrae"},
                {0, 0, "Valle Cardizal"},
                {0, 0, "Cavernas del Tiempo"},
            },
        },
        ["Frondavil"] = {
            achievementID = 853,
            proxyLocation = {0, 0, "Frondavil"},
            waypoints = {
                {0, 0, "Poblado Zarpavil"},
                {0, 0, "Bosque de Troncoferro"},
                {0, 0, "Cañada Gran Cicatriz"},
                {0, 0, "Jaedenar"},
                {0, 0, "Cañada Fuego de Jade"},
                {0, 0, "Aldea Muertobosque"},
                {0, 0, "Claro Ramaespolón"},
                {0, 0, "Camino Fuego de Jade"},
                {0, 0, "Cascadas del Veneno"},
                {0, 0, "Ruinas de Constellas"},
                {0, 0, "Santuario Esmeralda"},
                {0, 0, "Morlos'Aran"},
            },
        },
        ["Claro de la Luna"] = {
            achievementID = 855,
            proxyLocation = {0, 0, "Claro de la Luna"},
            waypoints = {
                {0, 0, "Lago Elune'ara"},
                {0, 0, "Santuario de Remulos"},
                {0, 0, "Amparo de la Noche"},
                {0, 0, "Túmulo de Tempestira"},
            },
        },
    },
    ["Rasganorte"] = {
        ["Tundra Boreal"] = {
            achievementID = 1264,
            proxyLocation = {0, 0, "Tundra Boreal"},
            waypoints = {
                {0, 0, "Ciudad Templo de En'kilah"},
                {0, 0, "Litoral Tralladón"},
                {0, 0, "Desembarco de Garrosh"},
                {0, 0, "Gelidar"},
                {0, 0, "El Saliente Ámbar"},
                {0, 0, "Fortaleza Denuedo"},
                {0, 0, "Los Cubiles de los Moribundos"},
                {0, 0, "Caravana de Quijacero"},
                {0, 0, "Kashala"},
                {0, 0, "Confín de la Muerte"},
                {0, 0, "Avanzada Bor'gorok"},
                {0, 0, "Bastión Grito de Guerra"},
                {0, 0, "Los Campos de Géiseres"},
            },
        },
        ["Cementerio de Dragones"] = {
            achievementID = 1265,
            proxyLocation = {0, 0, "Cementerio de Dragones"},
            waypoints = {
                {0, 0, "Reposo de Galakrond"},
                {0, 0, "Santuario de Dragones Obsidiana"},
                {0, 0, "Naxxramas"},
                {0, 0, "Poblado Bruma de Hielo"},
                {0, 0, "Altos Viento Helado"},
                {0, 0, "Martillo de Agmar"},
                {0, 0, "Campo de Refugiados de Viento Oeste"},
                {0, 0, "La Orilla Olvidada"},
                {0, 0, "Punta Escarlata"},
                {0, 0, "Lago Indu'le"},
                {0, 0, "Nueva Vega del Amparo"},
                {0, 0, "Confianza de la Luz"},
                {0, 0, "Santuario de Dragones Esmeralda"},
                {0, 0, "Angrathar la Puerta de Cólera"},
                {0, 0, "Templo del Reposo del Dragón"},
                {0, 0, "Rencor Venenoso"},
                {0, 0, "Vicio de Cristal"},
            },
        },
        ["Zul'Drak"] = {
            achievementID = 1267,
            proxyLocation = {0, 0, "Zul'Drak"},
            waypoints = {
                {0, 0, "Gundrak"},
                {0, 0, "Anfiteatro de la Angustia"},
                {0, 0, "Altar de Rhunok"},
                {0, 0, "Altar de Mam'toth"},
                {0, 0, "Zim'Torga"},
                {0, 0, "Voltarus"},
                {0, 0, "Brecha de la Luz"},
                {0, 0, "Campos Drak'Sotra"},
                {0, 0, "Altar de Sseratus"},
                {0, 0, "Altar de Quetz'lun"},
                {0, 0, "Altar de Har'koa"},
                {0, 0, "Zeramas"},
                {0, 0, "Fin de Thrym"},
                {0, 0, "Kolramas"},
            },
        },
        ["Bosque Canto de Cristal"] = {
            achievementID = 1457,
            proxyLocation = {0, 0, "Bosque Canto de Cristal"},
            waypoints = {
                {0, 0, "El Frente Azur"},
                {0, 0, "Dominio de los Atracasol"},
                {0, 0, "Mirador Brisaveloz"},
                {0, 0, "El Confín Violeta"},
                {0, 0, "La Corriente Decrépita"},
                {0, 0, "El Bosque Desolado"},
                {0, 0, "El Gran Árbol"},
                {0, 0, "El Matorral Desatado"},
            },
        },
        ["Corona de Hielo"] = {
            achievementID = 1270,
            proxyLocation = {0, 0, "Corona de Hielo"},
            waypoints = {
                {0, 0, "El Bombardeo"},
                {0, 0, "Puerto del Embate"},
                {0, 0, "La Factoría de Carne"},
                {0, 0, "La Caída de Sindragosa"},
                {0, 0, "Valle de los Ecos"},
                {0, 0, "La Conflagración"},
                {0, 0, "Jotunheim"},
                {0, 0, "La Cámara de las Sombras"},
                {0, 0, "Ciudadela de la Corona de Hielo"},
                {0, 0, "El Frente Roto"},
                {0, 0, "Aldur'thar: La Puerta de la Desolación"},
                {0, 0, "Valhalas"},
                {0, 0, "Ymirheim"},
                {0, 0, "Corp'rethar: La Puerta del Horror"},
                {0, 0, "Ciudad de la Plaga"},
            },
        },
        ["Fiordo Aquilonal"] = {
            achievementID = 1263,
            proxyLocation = {0, 0, "Fiordo Aquilonal"},
            waypoints = {
                {0, 0, "Komawa"},
                {0, 0, "Campamento Pezuña Invernal"},
                {0, 0, "Campo Venganza"},
                {0, 0, "Cabo Pillastre"},
                {0, 0, "Gjalerbron"},
                {0, 0, "El Paso del Gigante"},
                {0, 0, "Ruinas de Ivald"},
                {0, 0, "Nuevo Agamand"},
                {0, 0, "El Claro Retorcido"},
                {0, 0, "Fortaleza de la Guardia Oeste"},
                {0, 0, "Baleheim"},
                {0, 0, "Isla Caldros"},
                {0, 0, "Campamento de los Boticarios"},
                {0, 0, "Las Puertas de Acero"},
                {0, 0, "Nafsavar"},
                {0, 0, "Encierro Ámbar"},
                {0, 0, "Fuerte Vildervar"},
                {0, 0, "Haltorboll"},
                {0, 0, "Skorn"},
                {0, 0, "Fortaleza de Utgarde"},
                {0, 0, "Excavación de Baelgun"},
            },
        },
        ["Colinas Pardas"] = {
            achievementID = 1266,
            proxyLocation = {0, 0, "Colinas Pardas"},
            waypoints = {
                {0, 0, "Bastión de la Conquista"},
                {0, 0, "Ruinas de Drakil'jin"},
                {0, 0, "Manantial de Granito"},
                {0, 0, "Santuario Colmillo Iracundo"},
                {0, 0, "Bahía Ventura"},
                {0, 0, "Refugio Pino Ámbar"},
                {0, 0, "Campamento Oneqwah"},
                {0, 0, "Fortaleza de Drak'Tharon"},
                {0, 0, "Dun Argol"},
                {0, 0, "Fauceparda"},
                {0, 0, "Thor Modan"},
                {0, 0, "Runavold"},
                {0, 0, "Aserradero Cielo Azul"},
                {0, 0, "Campamento de la Brigada de los Páramos de Poniente"},
            },
        },
        ["Cuenca de Sholazar"] = {
            achievementID = 1268,
            proxyLocation = {0, 0, "Cuenca de Sholazar"},
            waypoints = {
                {0, 0, "Corazón del Río"},
                {0, 0, "El Pilar Musgoluz"},
                {0, 0, "El Pedestal de los Creadores"},
                {0, 0, "Canope de Hablalluvia"},
                {0, 0, "La Avalancha"},
                {0, 0, "Bastión de Kartak"},
                {0, 0, "El Matorral Silvestre"},
                {0, 0, "El Mirador de los Creadores"},
                {0, 0, "El Pilar Toquesol"},
                {0, 0, "El Pilar Sangrevida"},
                {0, 0, "El Pilar Iluminado"},
                {0, 0, "La Plataforma del Tormentoso"},
            },
        },
        ["Las Cumbres Tormentosas"] = {
            achievementID = 1269,
            proxyLocation = {0, 0, "Las Cumbres Tormentosas"},
            waypoints = {
                {0, 0, "Poblado Brunnhildar"},
                {0, 0, "Dun Niffelem"},
                {0, 0, "Valkyrion"},
                {0, 0, "Campo de Minas Encajebujía"},
                {0, 0, "Templo de la Vida"},
                {0, 0, "Truenotoño"},
                {0, 0, "Llanuras Ventisquero"},
                {0, 0, "Fuerte Escarcha"},
                {0, 0, "Cuna de Narvir"},
                {0, 0, "Aliento de Bor"},
                {0, 0, "Bancal de los Creadores"},
                {0, 0, "Motor de los Creadores"},
                {0, 0, "Ulduar"},
                {0, 0, "Templo de las Tormentas"},
                {0, 0, "Pesadilla de Garm"},
                {0, 0, "Nidavelir"},
            },
        },
    },
    ["Pandaria"] = {
        ["El Bosque de Jade"] = {
            achievementID = 6351,
            proxyLocation = {0, 0, "El Bosque de Jade"},
            waypoints = {
                {0, 0, "Monasterio Tian"},
                {0, 0, "Pabellón del Soñador"},
                {0, 0, "Lago de Nácar"},
                {0, 0, "Cantera Verdemar"},
                {0, 0, "Campamento Nooka Nooka"},
                {0, 0, "Corazón del Dragón"},
                {0, 0, "Templo del Dragón de Jade"},
                {0, 0, "Puesto Garrosh'ar"},
                {0, 0, "Poblado Almíbar"},
                {0, 0, "Floralba"},
                {0, 0, "Augurio del Emperador"},
                {0, 0, "Cerro Makaku"},
                {0, 0, "Huerto Brisa Dulce"},
                {0, 0, "Bancal de los Diez Truenos"},
                {0, 0, "Fosas Colafusta"},
                {0, 0, "El Arboretum"},
                {0, 0, "Isla de Barlovento"},
            },
        },
        ["Espesura Krasarang"] = {
            achievementID = 6975,
            proxyLocation = {0, 0, "Espesura Krasarang"},
            waypoints = {
                {0, 0, "Muelle de los Pescadores"},
                {0, 0, "Río Dojani"},
                {0, 0, "Cala Krasarang"},
                {0, 0, "Laguna Nayeli"},
                {0, 0, "Ruinas de Dojan"},
                {0, 0, "Templo de la Grulla Roja"},
                {0, 0, "La Jungla Prohibida"},
                {0, 0, "Unga Ingoo"},
                {0, 0, "Cuna de Chi-Ji"},
                {0, 0, "Poblado Canción de Otoño"},
                {0, 0, "Las Ruinas Krasari"},
                {0, 0, "Refugio Ala de Grulla"},
                {0, 0, "Ruinas de Korja"},
                {0, 0, "La Jungla Salvaje"},
                {0, 0, "Las Islas del Sur"},
                {0, 0, "Atalaya de Zhu"},
            },
        },
        ["Estepas de Tong Long"] = {
            achievementID = 6977,
            proxyLocation = {0, 0, "Estepas de Tong Long"},
            waypoints = {
                {0, 0, "Frente Gao-Ran"},
                {0, 0, "Vigilancia de Rensai"},
                {0, 0, "Campamento Osul"},
                {0, 0, "Cuartel del Shadopan"},
                {0, 0, "Sik'vess"},
                {0, 0, "El Sumidero"},
                {0, 0, "Kri'vess"},
                {0, 0, "Templo de Niuzao"},
                {0, 0, "Corrupción del Odio"},
                {0, 0, "Shan'ze Dao"},
                {0, 0, "Sra'vess"},
            },
        },
        ["Valle de la Flor Eterna"] = {
            achievementID = 6979,
            proxyLocation = {0, 0, "Valle de la Flor Eterna"},
            waypoints = {
                {0, 0, "Ruinas de Guo-Lai"},
                {0, 0, "Palacio Mogu'shan"},
                {0, 0, "La Escalera Dorada"},
                {0, 0, "La Pagoda Dorada"},
                {0, 0, "Santuario de las Dos Lunas"},
                {0, 0, "Las Cinco Hermanas"},
                {0, 0, "Aldea Bruma Otoñal"},
                {0, 0, "Baluarte del Sol Poniente"},
                {0, 0, "Santuario de las Siete Estrellas"},
                {0, 0, "Cementerio Tu Shen"},
                {0, 0, "Lago Pétalo Níveo"},
            },
        },
        ["Valle de los Cuatro Vientos"] = {
            achievementID = 6969,
            proxyLocation = {0, 0, "Valle de los Cuatro Vientos"},
            waypoints = {
                {0, 0, "Acantilado del Céfiro"},
                {0, 0, "El Abanico Dorado"},
                {0, 0, "El Alcor"},
                {0, 0, "Poblado Kunzen"},
                {0, 0, "Safari Nesingwary"},
                {0, 0, "Pozas de la Pureza"},
                {0, 0, "Campos de Seda"},
                {0, 0, "Cervecería del Trueno"},
                {0, 0, "Rancho Pie Atronador"},
                {0, 0, "Despeñadero Loma Agreste"},
                {0, 0, "El Granero Imperial"},
                {0, 0, "Villarroca"},
                {0, 0, "Hogar de Caolín"},
                {0, 0, "Espesura Paoquan"},
                {0, 0, "Bancal del Fragor"},
                {0, 0, "Marjal Exótico"},
                {0, 0, "Los Cultivos Florecientes"},
                {0, 0, "Descenso de Zhu"},
            },
        },
        ["Cima Kun-Lai"] = {
            achievementID = 6976,
            proxyLocation = {0, 0, "Cima Kun-Lai"},
            waypoints = {
                {0, 0, "Aldea Binan"},
                {0, 0, "Puerta de los Augustos Celestiales"},
                {0, 0, "Cumbre Kota"},
                {0, 0, "Monte Nieverest"},
                {0, 0, "Pico de la Serenidad"},
                {0, 0, "Templo del Tigre Blanco"},
                {0, 0, "Valle de los Emperadores"},
                {0, 0, "Rincón Tallo Ardiente"},
                {0, 0, "Isla de la Venganza"},
                {0, 0, "Mogujia"},
                {0, 0, "Rancho Zarpa Lanuda"},
                {0, 0, "Monasterio del Shadopan"},
                {0, 0, "La Senda Arpillera"},
                {0, 0, "Aldea Zouchin"},
            },
        },
        ["Desierto del Pavor"] = {
            achievementID = 6978,
            proxyLocation = {0, 0, "Desierto del Pavor"},
            waypoints = {
                {0, 0, "Corazón del Miedo"},
                {0, 0, "Kypari Vor"},
                {0, 0, "Aldea Rikkitun"},
                {0, 0, "Bancal Gurthan"},
                {0, 0, "La Nidada de Shek'zeer"},
                {0, 0, "Bosquetormento"},
                {0, 0, "Klaxxi'vess"},
                {0, 0, "Kypari Zar"},
                {0, 0, "Lance de Aguado"},
                {0, 0, "La Mugre Salobre"},
                {0, 0, "Jardín de la Cebada Crepuscular"},
                {0, 0, "Zan'vess"},
            },
        },
    },
    ["Islas Abruptas"] = {
        ["Azsuna"] = {
            achievementID = 10665,
            proxyLocation = {0, 0, "Azsuna"},
            waypoints = {
                {0, 0, "Faronaar"},
                {0, 0, "Senda Verde"},
                {0, 0, "Tierras Altas de Llothien"},
                {0, 0, "Nar'thalas"},
                {0, 0, "Sagrario en Ruinas"},
                {0, 0, "Ruinas Ley de Zarkhenar"},
                {0, 0, "Acceso Llamarada Vil"},
                {0, 0, "Isla de los Vigías"},
                {0, 0, "Vega Baldía"},
                {0, 0, "Cala de Oceanus"},
                {0, 0, "Templo de Luces"},
            },
        },
        ["Monte Alto"] = {
            achievementID = 10667,
            proxyLocation = {0, 0, "Monte Alto"},
            waypoints = {
                {0, 0, "Tierras Altas Cazasangre"},
                {0, 0, "Avanzada Pezuña Helada"},
                {0, 0, "Pedestal del Vigía de la Noche"},
                {0, 0, "Recodo del Río"},
                {0, 0, "Cala del Naufragio"},
                {0, 0, "Avanzada Pezuña Pétrea"},
                {0, 0, "Tótem del Trueno"},
                {0, 0, "Pantano Ciego"},
                {0, 0, "Enclave Cuerno Férreo"},
                {0, 0, "Cuenca Roca Escarpada"},
                {0, 0, "Arrecifes Roca Lejana"},
                {0, 0, "Cuerno del Cielo"},
                {0, 0, "Cascadas Nemorosas"},
                {0, 0, "Refugio Alblanco"},
            },
        },
        ["Suramar"] = {
            achievementID = 10669,
            proxyLocation = {0, 0, "Suramar"},
            waypoints = {
                {0, 0, "Valle Ámbar"},
                {0, 0, "Falanaar"},
                {0, 0, "Gran Paseo"},
                {0, 0, "Bastión de la Guardia Lunar"},
                {0, 0, "Ruinas de Elun'eth"},
                {0, 0, "Tel'anor"},
                {0, 0, "Espesura Carmesí"},
                {0, 0, "Bastión Alma Vil"},
                {0, 0, "Jandvik"},
                {0, 0, "Quebrada Susurrolunar"},
                {0, 0, "Ciudad de Suramar"},
            },
        },
        ["Val'sharah"] = {
            achievementID = 10666,
            proxyLocation = {0, 0, "Val'sharah"},
            waypoints = {
                {0, 0, "Andu'talah"},
                {0, 0, "Arroyo Braden"},
                {0, 0, "Arrecife del Ocaso"},
                {0, 0, "Lorlathil"},
                {0, 0, "Valle Zarpaluna"},
                {0, 0, "Bosque Torracuero"},
                {0, 0, "Thas'talah"},
                {0, 0, "Torreón Grajo Negro"},
                {0, 0, "Arboleda de los Sueños"},
                {0, 0, "Arboleda de Cenarius"},
                {0, 0, "Velo de Bruma"},
                {0, 0, "Shala'nir"},
                {0, 0, "Templo de Elune"},
            },
        },
        ["Tormenheim"] = {
            achievementID = 10668,
            proxyLocation = {0, 0, "Tormenheim"},
            waypoints = {
                {0, 0, "Cámara de Aggramar"},
                {0, 0, "Desembarco Rastro del Pavor"},
                {0, 0, "Guardia Gris"},
                {0, 0, "Haustvald"},
                {0, 0, "Fauces de Nashal"},
                {0, 0, "Nastrondir"},
                {0, 0, "Bosque de las Runas"},
                {0, 0, "Skold-Ashil"},
                {0, 0, "Refugio de la Garra"},
                {0, 0, "Valdisdall"},
                {0, 0, "Mirador Pico Negro"},
                {0, 0, "Dreyrgrot"},
                {0, 0, "Puertas del Valor"},
                {0, 0, "Hrydshal"},
                {0, 0, "Morheim"},
                {0, 0, "Roca del Velador"},
                {0, 0, "Reposo del Escudo"},
                {0, 0, "Cima de la Tormenta"},
                {0, 0, "Puerto Mareskorn"},
                {0, 0, "Cimas Anegadas"},
            },
        },
    },
    -- Añada otros continentes...
    ["Continents"] = {
        ["Eastern Kingdoms"] = "Reinos del Este",
        ["Kalimdor"]         = "Kalimdor",
        ["Outland"]          = "Terrallende",
        ["Northrend"]        = "Rasganorte",
        ["Pandaria"]         = "Pandaria",
        ["Draenor"]          = "Draenor",
        ["Broken Isles"]     = "Islas Quebradas",
        ["Zandalar"]         = "Zandalar",
        ["Kul Tiras"]        = "Kul Tiras",
        ["Shadowlands"]      = "Tierras Sombrías",
        ["Dragon Isles"]     = "Islas Dragón",
        ["The Maelstrom"]    = "La Vorágine",
        ["Vashj'ir"]         = "Vashj'ir",
    }
}
