-- frFR.lua

Localization = Localization or {}

Localization["frFR"] = {
    ["Royaumes de l’Est"] = {
        ["la forêt d'Elwynn"] = {
            achievementID = 776,
            proxyLocation = {0, 0, "la forêt d'Elwynn"},
            waypoints = {
                {0, 0, "Vallée de Comté-du-Nord"},
                {0, 0, "Comté-de-l’Or"},
                {0, 0, "Le débarcadère de Jerod"},
                {0, 0, "Champ de potirons des Saumepuits"},
                {0, 0, "Tour de la Crête"},
                {0, 0, "Lac du Cairn"},
                {0, 0, "Garnison du ruisseau de l’Ouest"},
                {0, 0, "Mine de Fondugouffre"},
                {0, 0, "Tour d’Azora"},
                {0, 0, "Camp de bûcherons du val d’Est"},
                {0, 0, "Lac de Cristal"},
            },
        },
        ["Terres Ingrates"] = {
            achievementID = 765,
            proxyLocation = {0, 0, "terres Ingrates"},
            waypoints = {
                {0, 0, "Ravin de Lethlor"},
                {0, 0, "Uldaman"},
                {0, 0, "Balafre du Brise-monde"},
                {0, 0, "Forteresse d’Angor"},
                {0, 0, "Halte de Guettesang"},
                {0, 0, "Fin d’Agmond"},
                {0, 0, "Camp Cagg"},
                {0, 0, "Vallée de la Poussière"},
                {0, 0, "Camp Kosh"},
                {0, 0, "Nouvelle-Kargath"},
            },
        },
        ["steppes Ardentes"] = {
            achievementID = 775,
            proxyLocation = {0, 0, "steppes Ardentes"},
            waypoints = {
                {0, 0, "Rocher des Cognepeurs"},
                {0, 0, "Chemin de l’Aile de la terreur"},
                {0, 0, "Ruines de Thaurissan"},
                {0, 0, "Bastion Rochenoire"},
                {0, 0, "Autel des Tempêtes"},
                {0, 0, "Veille de Morgan"},
                {0, 0, "Défilé des Rochenoires"},
                {0, 0, "Taudis de Noirdent"},
                {0, 0, "Butte aux Dragonnets"},
                {0, 0, "Mont Rochenoire"},
            },
        },
        ["Exploration du bois de la Pénombre"] = {
            achievementID = 778,
            proxyLocation = {0, 0, "Exploration du bois de la Pénombre"},
            waypoints = {
                {0, 0, "La rive Silencieuse"},
                {0, 0, "Colline-aux-Corbeaux"},
                {0, 0, "Tertre des Ogres vul’Gol"},
                {0, 0, "La ferme des Yorgen"},
                {0, 0, "Le verger Pourrissant"},
                {0, 0, "Sombre-Comté"},
                {0, 0, "La rive Sombre"},
                {0, 0, "Ferme des Addle"},
                {0, 0, "Cimetière de Colline-aux-Corbeaux"},
                {0, 0, "Bosquet crépusculaire"},
                {0, 0, "Bosquet de Clairbois"},
                {0, 0, "Cimetière des Jardins paisibles"},
                {0, 0, "Manoir Mantebrume"},
            },
        },
        ["Exploration du Loch Modan"] = {
            achievementID = 779,
            proxyLocation = {0, 0, "Exploration du Loch Modan"},
            waypoints = {
                {0, 0, "Le Loch"},
                {0, 0, "Bastion des Mo’grosh"},
                {0, 0, "Passage de la porte Nord"},
                {0, 0, "Excavations de Baguefer"},
                {0, 0, "Thelsamar"},
                {0, 0, "Vallée des Rois"},
                {0, 0, "Barrage de Formepierre"},
                {0, 0, "Mine du Ru d’argent"},
                {0, 0, "Le pavillon des Pérégrins"},
                {0, 0, "Falaise de Vieillegriffe"},
                {0, 0, "Vallée des Brisepierre"},
            },
        },
        ["clairières de Tirisfal"] = {
            achievementID = 768,
            proxyLocation = {0, 0, "clairières de Tirisfal"},
            waypoints = {
                {0, 0, "Le Glas"},
                {0, 0, "Moulins d’Agamand"},
                {0, 0, "Manoir du Foyer froid"},
                {0, 0, "Antre de Garren"},
                {0, 0, "Ferme des Balnir"},
                {0, 0, "Poste de garde de la Croisade"},
                {0, 0, "Ruines de Lordaeron"},
                {0, 0, "La Barricade"},
                {0, 0, "Ferme des Solliden"},
                {0, 0, "Vallée des Cauchemars"},
                {0, 0, "Brill"},
                {0, 0, "Lac Étincelant"},
                {0, 0, "Avant-poste des Croisés"},
                {0, 0, "Vallée de Tissevenin"},
                {0, 0, "Entrée du Monastère Écarlate"},
                {0, 0, "Domaine Calston"},
            },
        },
        ["la gorge des Vents brûlants"] = {
            achievementID = 774,
            proxyLocation = {0, 0, "la gorge des Vents brûlants"},
            waypoints = {
                {0, 0, "Crête de Guet-du-Feu"},
                {0, 0, "Caverne de Noircharbon"},
                {0, 0, "Site de fouilles de Crasseboue"},
                {0, 0, "Halte du Thorium"},
                {0, 0, "Le Chaudron"},
                {0, 0, "La mer de Braises"},
                {0, 0, "Vallée des Escarbilles"},
                {0, 0, "Mont Rochenoire"},
            },
        },
        ["terres Fantômes"] = {
            achievementID = 858,
            proxyLocation = {0, 0, "terres Fantômes"},
            waypoints = {
                {0, 0, "Tranquillien"},
                {0, 0, "Brume-d’Or"},
                {0, 0, "Sanctum de la Lune"},
                {0, 0, "Flèche d’Aubétoile"},
                {0, 0, "Ziggourat Hurlante"},
                {0, 0, "Zeb’Nowa"},
                {0, 0, "Flèche de Coursevent"},
                {0, 0, "Passage de l’Elrendar"},
                {0, 0, "Solcouronne"},
                {0, 0, "Coursevent"},
                {0, 0, "Sanctum du Soleil"},
                {0, 0, "Enclave des Pérégrins"},
                {0, 0, "Mortholme"},
                {0, 0, "Passage des Amani"},
                {0, 0, "Ziggourat Sanguinolente"},
                {0, 0, "Passe Thalassienne"},
            },
        },
        ["Exploration du cap Strangleronce"] = {
            achievementID = 4995,
            proxyLocation = {0, 0, "Exploration du cap Strangleronce"},
            waypoints = {
                {0, 0, "Baie-du-Butin"},
                {0, 0, "Arène des Gurubashi"},
                {0, 0, "Île aux jagueros"},
                {0, 0, "Fontaine des Nek’mani"},
                {0, 0, "Ruines de Jubuwal"},
                {0, 0, "Mine aux Cristaux"},
                {0, 0, "Planque de Serrelavis"},
                {0, 0, "Valbrume"},
                {0, 0, "Ruines d’Aboraz"},
                {0, 0, "Le rivage Cruel"},
            },
        },
        ["Hinterlands"] = {
            achievementID = 773,
            proxyLocation = {0, 0, "Hinterlands"},
            waypoints = {
                {0, 0, "Nid-de-l’Aigle"},
                {0, 0, "Zun’watha"},
                {0, 0, "Shadra’Alor"},
                {0, 0, "Agol’watha"},
                {0, 0, "L’Autel de Zul"},
                {0, 0, "Rocher de l’Affût"},
                {0, 0, "Jintha’Alor"},
                {0, 0, "Ravin de Pestebrume"},
                {0, 0, "Gîte de Quel’Danil"},
                {0, 0, "Lac Vent-vaillant"},
                {0, 0, "Les ruines aux Rampants"},
                {0, 0, "Seradane"},
                {0, 0, "Shaol’watha"},
                {0, 0, "Les Hauts-Surplombs"},
            },
        },
        ["Paluns"] = {
            achievementID = 841,
            proxyLocation = {0, 0, "Paluns"},
            waypoints = {
                {0, 0, "Port de Menethil"},
                {0, 0, "Marais des Branchies-bleues"},
                {0, 0, "Marais du Couchant"},
                {0, 0, "Tombe de Barbe-de-fer"},
                {0, 0, "Campement de Hargnecroc"},
                {0, 0, "Bosquet du Gardien vert"},
                {0, 0, "Colline de Morneforge"},
                {0, 0, "Mission de Cisepierre"},
                {0, 0, "Marais des Eaux-Noires"},
                {0, 0, "Excavations de Whelgar"},
                {0, 0, "Vallon des Embruns"},
                {0, 0, "Dun Modr"},
                {0, 0, "Rocher de Thelgen"},
                {0, 0, "Marais des Poils-moussus"},
                {0, 0, "Dun Algaz"},
                {0, 0, "Crête des Raptors"},
            },
        },
        ["Maleterres de l'Ouest"] = {
            achievementID = 770,
            proxyLocation = {0, 0, "Maleterres de l'Ouest"},
            waypoints = {
                {0, 0, "Lac Darrowmere"},
                {0, 0, "Colline des Chagrins"},
                {0, 0, "La Barricade"},
                {0, 0, "Ferme de Dalson"},
                {0, 0, "Camp de bûcherons de la Crête du Nord"},
                {0, 0, "Cluse des Rougepins"},
                {0, 0, "La grotte des Pleurs"},
                {0, 0, "Caer Darrow"},
                {0, 0, "Andorhal"},
                {0, 0, "Champ de Gangrepierre"},
                {0, 0, "Le repaire Putride"},
                {0, 0, "Âtreval"},
                {0, 0, "La Flétrissure de Gahrron"},
                {0, 0, "La Thondroril"},
            },
        },
        ["l'île de Quel'Danas"] = {
            achievementID = 868,
            proxyLocation = {0, 0, "l'île de Quel'Danas"},
            waypoints = {
            },
        },
        ["hautes-terres Arathies"] = {
            achievementID = 761,
            proxyLocation = {0, 0, "hautes-terres Arathies"},
            waypoints = {
                {0, 0, "Cercle de Lien occidental"},
                {0, 0, "Roche’gor"},
                {0, 0, "Donjon de Stromgarde"},
                {0, 0, "Cercle de Lien intérieur"},
                {0, 0, "Hall Rochepoing"},
                {0, 0, "Cercle de Lien extérieur"},
                {0, 0, "Ferme de Go’Shek"},
                {0, 0, "Cercle de Lien oriental"},
                {0, 0, "Manoir de Nordclos"},
                {0, 0, "Chute de Galen"},
                {0, 0, "Crique de Faldir"},
                {0, 0, "Viaduc de Thandol"},
                {0, 0, "Refuge de l’Ornière"},
                {0, 0, "Fanécorce"},
                {0, 0, "Ferme des Dabyrie"},
                {0, 0, "Trépas-d’Orgrim"},
            },
        },
        ["terres Foudroyées"] = {
            achievementID = 766,
            proxyLocation = {0, 0, "terres Foudroyées"},
            waypoints = {
                {0, 0, "Bastion Cognepeur"},
                {0, 0, "Rempart-du-Néant"},
                {0, 0, "La porte des Ténèbres"},
                {0, 0, "Poste Cognepeur"},
                {0, 0, "Cime du Souilleur"},
                {0, 0, "Expédition de Solevoile"},
                {0, 0, "Les confins Rouges"},
                {0, 0, "Camps de ravitaillement de Rempart-du-Néant"},
                {0, 0, "Anneaux du serpent"},
                {0, 0, "Autel des Tempêtes"},
                {0, 0, "La Balafre impure"},
                {0, 0, "Rivage Ravagé"},
                {0, 0, "Surwich"},
                {0, 0, "La forêt Impure"},
            },
        },
        ["Dun Morogh"] = {
            achievementID = 627,
            proxyLocation = {0, 0, "Dun Morogh"},
            waypoints = {
                {0, 0, "Passe des Frigères"},
                {0, 0, "Front Crins-de-Givre"},
                {0, 0, "Aérodrome de Forgefer"},
                {0, 0, "Kharanos"},
                {0, 0, "Ferme des Distillambre"},
                {0, 0, "Carrière de Gol’Bolar"},
                {0, 0, "Repaire des Crins-de-Givre"},
                {0, 0, "Portes de Forgefer"},
                {0, 0, "Vallée des Frigères"},
                {0, 0, "La Nouvelle-Brikabrok"},
                {0, 0, "Crête Scintillante"},
                {0, 0, "Les collines de Tundrid"},
                {0, 0, "Lac du Lit d’Helm"},
                {0, 0, "Avant-poste de la porte Nord"},
                {0, 0, "Lac Glacial"},
            },
        },
        ["contreforts de Hautebrande"] = {
            achievementID = 772,
            proxyLocation = {0, 0, "contreforts de Hautebrande"},
            waypoints = {
                {0, 0, "Mine de Veine-Azur"},
                {0, 0, "Dague de Corrahn"},
                {0, 0, "Pointe du Noroît"},
                {0, 0, "Clos de Dandred"},
                {0, 0, "Dun Garok"},
                {0, 0, "Fourche du Gibet"},
                {0, 0, "Caverne Stérile"},
                {0, 0, "Ferme des Nethander"},
                {0, 0, "Ruines d’Alterac"},
                {0, 0, "Creux du Massacre"},
                {0, 0, "Porte de la Pointe du Midi"},
                {0, 0, "Moulin-de-Tarren"},
                {0, 0, "Champs Fangeux"},
                {0, 0, "Ferme de Brazie"},
                {0, 0, "Bastion Cassecrête"},
                {0, 0, "Cratère de Dalaran"},
                {0, 0, "Colline de Darrow"},
                {0, 0, "Donjon de Fort-de-Durn"},
                {0, 0, "Promontoire de Gavin"},
                {0, 0, "Rivage Brumeux"},
                {0, 0, "Île de la Purification"},
                {0, 0, "Ruines d’Austrivage"},
                {0, 0, "Promontoire de Sofera"},
                {0, 0, "Strahnbrande"},
                {0, 0, "L’Avancée"},
                {0, 0, "Les Hauteurs"},
            },
        },
        ["Carmines"] = {
            achievementID = 780,
            proxyLocation = {0, 0, "Carmines"},
            waypoints = {
                {0, 0, "Comté-du-Lac"},
                {0, 0, "Trois chemins"},
                {0, 0, "Canyons des Carmines"},
                {0, 0, "Chutes de Guet-de-Pierre"},
                {0, 0, "Camp des Étripeurs"},
                {0, 0, "Vallée de Galardell"},
                {0, 0, "Camp Placide"},
                {0, 0, "Lac Placide"},
                {0, 0, "Grand-route de la crête du Lac"},
                {0, 0, "Scierie d’Alther"},
                {0, 0, "Vallée des Étripeurs"},
                {0, 0, "Donjon de Guet-de-Pierre"},
                {0, 0, "Canyon Vent-de-schiste"},
            },
        },
        ["Exploration du bois des Chants éternels"] = {
            achievementID = 859,
            proxyLocation = {0, 0, "Exploration du bois des Chants éternels"},
            waypoints = {
                {0, 0, "Île de Haut-Soleil"},
                {0, 0, "Sanctum Occidental"},
                {0, 0, "Sanctum Septentrional"},
                {0, 0, "Retraite des pérégrins"},
                {0, 0, "Terres de Ternesoir"},
                {0, 0, "Le bois Vivant"},
                {0, 0, "Le bosquet Incendié"},
                {0, 0, "Côte de Brise-d’Azur"},
                {0, 0, "Passe du Rameau d’or"},
                {0, 0, "Pierre runique Falithas"},
                {0, 0, "Havre de Saltheril"},
                {0, 0, "Écurie de Thuron"},
                {0, 0, "Zeb’Watha"},
                {0, 0, "Ruines de Lune-d’Argent"},
                {0, 0, "Mouillage des Voiles du soleil"},
                {0, 0, "Sanctum Oriental"},
                {0, 0, "Étang des Murmures-sereins"},
                {0, 0, "Brise-Clémente"},
                {0, 0, "Tor’Watha"},
                {0, 0, "Lune-d’Argent"},
                {0, 0, "Chutes de l’Elrendar"},
                {0, 0, "Lac Elrendar"},
                {0, 0, "Pierre runique Shan’dor"},
                {0, 0, "Grève dorée"},
                {0, 0, "Rivage Paisible"},
            },
        },
        ["la forêt des Pins-Argentés"] = {
            achievementID = 769,
            proxyLocation = {0, 0, "la forêt des Pins-Argentés"},
            waypoints = {
                {0, 0, "La Ligne de front"},
                {0, 0, "Le front des Réprouvés"},
                {0, 0, "Tête de pont de la Côte Nord"},
                {0, 0, "Champ de Valgan"},
                {0, 0, "Mine du gouffre d’Elem"},
                {0, 0, "Moulin-de-l’Ambre"},
                {0, 0, "Haut-commandement Réprouvé"},
                {0, 0, "Arrière-garde des Réprouvés"},
                {0, 0, "Les champs Délabrés"},
                {0, 0, "Le Grouillement"},
                {0, 0, "Île de Fenris"},
                {0, 0, "Le Sépulcre"},
                {0, 0, "Essarts des Olsen"},
                {0, 0, "Donjon d’Ombrecroc"},
                {0, 0, "La côte Nord"},
            },
        },
        ["la Strangleronce septentrionale"] = {
            achievementID = 781,
            proxyLocation = {0, 0, "la Strangleronce septentrionale"},
            waypoints = {
                {0, 0, "Campement Grom’gol"},
                {0, 0, "Bambala"},
                {0, 0, "Ruines de Zuuldaia"},
                {0, 0, "Camp Rebelle"},
                {0, 0, "Ruines de Kal’ai"},
                {0, 0, "Tertre des Ogres mosh’Ogg"},
                {0, 0, "Ruines de Bal’lal"},
                {0, 0, "Ruines de Zul’Kunda"},
                {0, 0, "Ruines de Balia’mah"},
                {0, 0, "Fort-Livingston"},
                {0, 0, "Expédition de Nesingwary"},
                {0, 0, "Base de Kurzen"},
                {0, 0, "Ruines de Mizjah"},
                {0, 0, "Lac Nazfériti"},
                {0, 0, "Le récif Infâme"},
                {0, 0, "Zul’Gurub"},
            },
        },
        ["Exploration du marais des Chagrins"] = {
            achievementID = 782,
            proxyLocation = {0, 0, "Exploration du marais des Chagrins"},
            waypoints = {
                {0, 0, "Vallée des Brumes"},
                {0, 0, "Croisement de Lance-brisée"},
                {0, 0, "Pierrêche"},
                {0, 0, "Stagalbog"},
                {0, 0, "Brasse-Tourbe"},
                {0, 0, "Caverne de la Source pure"},
                {0, 0, "Le havre Boueux"},
                {0, 0, "Le bourbier Changeant"},
                {0, 0, "Bassin des Larmes"},
                {0, 0, "Noirchagrin"},
                {0, 0, "Grève de Brumejonc"},
                {0, 0, "Guet de l’Estran"},
            },
        },
        ["la marche de l'Ouest"] = {
            achievementID = 802,
            proxyLocation = {0, 0, "la marche de l'Ouest"},
            waypoints = {
                {0, 0, "Colline des Sentinelles"},
                {0, 0, "Ferme de potirons des Froncebouille"},
                {0, 0, "Mine Veine-de-Jango"},
                {0, 0, "L’acre Mort"},
                {0, 0, "Ferme des Alexston"},
                {0, 0, "Les collines de la Dague"},
                {0, 0, "Les plaines de Poussière"},
                {0, 0, "Ferme des Saldean"},
                {0, 0, "La ferme des Jansen"},
                {0, 0, "La ferme des Molsen"},
                {0, 0, "Ruisselune"},
                {0, 0, "Maison de Demont"},
                {0, 0, "Le gouffre Déchaîné"},
            },
        },
        ["Exploration du défilé de Deuillevent"] = {
            achievementID = 777,
            proxyLocation = {0, 0, "Exploration du défilé de Deuillevent"},
            waypoints = {
                {0, 0, "Croisée de l’Homme mort"},
                {0, 0, "Karazhan"},
                {0, 0, "L’Étau"},
            },
        },
        ["Maleterres de l'Est"] = {
            achievementID = 771,
            proxyLocation = {0, 0, "Maleterres de l'Est"},
            waypoints = {
                {0, 0, "La Thondroril"},
                {0, 0, "Le caveau de Zaeldarr"},
                {0, 0, "La vallée des Fongus"},
                {0, 0, "Balafre Pestilentielle"},
                {0, 0, "Lac Mereldar"},
                {0, 0, "Chapelle de l’Espoir de Lumière"},
                {0, 0, "La clairière Nocive"},
                {0, 0, "Lac de Noirbois"},
                {0, 0, "Zul’Mashar"},
                {0, 0, "Gîte de Quel’Lithien"},
                {0, 0, "Pestebois"},
                {0, 0, "Ruines de l’enclave Écarlate"},
                {0, 0, "La ferme des Marris"},
                {0, 0, "Tour de garde de la Couronne"},
                {0, 0, "Comté-de-Darrow"},
                {0, 0, "La Croisée de Corin"},
                {0, 0, "Main de Tyr"},
                {0, 0, "La Balafre infecte"},
                {0, 0, "Tour du Mur d’Est"},
                {0, 0, "Valnord"},
                {0, 0, "Tour du Col du Nord"},
                {0, 0, "Val-Terreur"},
                {0, 0, "Stratholme"},
            },
        },
    },
    ["L’Outreterre"] = {
        ["la péninsule des Flammes infernales"] = {
            achievementID = 862,
            proxyLocation = {0, 0, "la péninsule des Flammes infernales"},
            waypoints = {
                {0, 0, "L’escalier du Destin"},
                {0, 0, "Guet de l’Épervier"},
                {0, 0, "Bastion de l’Honneur"},
                {0, 0, "Bassins d’Aggonar"},
                {0, 0, "Temple de Telhamat"},
                {0, 0, "Thrallmar"},
                {0, 0, "Zeth’Gor"},
                {0, 0, "Crête Tombeciel"},
                {0, 0, "Les champs de Distorsion"},
                {0, 0, "Armurerie de l’Expédition"},
                {0, 0, "Citadelle des Flammes infernales"},
                {0, 0, "Poste Mag’har"},
                {0, 0, "Ruines de Sha’naar"},
                {0, 0, "Le front de la Légion"},
                {0, 0, "Trône de Kil’jaeden"},
                {0, 0, "Tanière des Haal’esh"},
                {0, 0, "Crête du Vide"},
                {0, 0, "Camp de forge : Mageddon"},
            },
        },
        ["la forêt de Terokkar"] = {
            achievementID = 867,
            proxyLocation = {0, 0, "la forêt de Terokkar"},
            waypoints = {
                {0, 0, "Ruines de l’Orbite-Sanglante"},
                {0, 0, "Fourré Cénarien"},
                {0, 0, "Grangol’var"},
                {0, 0, "Tuurem"},
                {0, 0, "Clairière de Raastok"},
                {0, 0, "Saillie de Tranchépine"},
                {0, 0, "Terres Auchenaï"},
                {0, 0, "Caravane de réfugiés"},
                {0, 0, "Tombe des Ombres"},
                {0, 0, "Voile Rhaze"},
                {0, 0, "Skettis"},
                {0, 0, "Bastion Allérien"},
                {0, 0, "Halte Aile-de-feu"},
                {0, 0, "Fort des Brise-Pierres"},
                {0, 0, "Shattrath"},
                {0, 0, "La Barrière"},
                {0, 0, "Ruines Mâche-les-os"},
                {0, 0, "Colline des Charognes"},
                {0, 0, "Cercle d’observance"},
                {0, 0, "Caravane Abandonnée"},
                {0, 0, "Monticule Grouillant"},
            },
        },
        ["Tranchantes"] = {
            achievementID = 865,
            proxyLocation = {0, 0, "Tranchantes"},
            waypoints = {
                {0, 0, "Point d’ancrage de Bash’ir"},
                {0, 0, "Bastion de Flèchelame"},
                {0, 0, "Avant-poste de la Masse-Sanglante"},
                {0, 0, "Cercle de sang"},
                {0, 0, "Camp de forge : Colère"},
                {0, 0, "Camp de forge : Courroux"},
                {0, 0, "Repaire de Gruul"},
                {0, 0, "Mok’Nathal"},
                {0, 0, "Tranchecrête"},
                {0, 0, "Skald"},
                {0, 0, "Éperon de cristal"},
                {0, 0, "Voile Lashh"},
                {0, 0, "Le séjour de Vekhaar"},
                {0, 0, "Goulet des Lames"},
                {0, 0, "Camp de la Masse-Sanglante"},
                {0, 0, "Landes Brisées"},
                {0, 0, "Porte de la mort"},
                {0, 0, "Camp de forge : Terreur"},
                {0, 0, "Grishnath"},
                {0, 0, "La crête Dentelée"},
                {0, 0, "Bois aux Corbeaux"},
                {0, 0, "Sylve Ruuan"},
                {0, 0, "Sylvanaar"},
                {0, 0, "Bastion des Sire-tonnerre"},
                {0, 0, "Voile Ruuan"},
                {0, 0, "Sommet du Vortex"},
            },
        },
        ["la vallée d'Ombrelune"] = {
            achievementID = 864,
            proxyLocation = {0, 0, "la vallée d'Ombrelune"},
            waypoints = {
                {0, 0, "Halte de Glissentaille"},
                {0, 0, "Bastion de la Légion"},
                {0, 0, "Village d’Ombrelune"},
                {0, 0, "La Forgemort"},
                {0, 0, "La Cage de la gardienne"},
                {0, 0, "Autel de Sha’tar"},
                {0, 0, "Champs de l’Aile-du-Néant"},
                {0, 0, "Halte de l’Éclipse"},
                {0, 0, "Escarpement de l’Aile-du-Néant"},
                {0, 0, "Le Temple noir"},
                {0, 0, "La Main de Gul’dan"},
                {0, 0, "Bastion des Marteaux-Hardis"},
                {0, 0, "Halte Illidari"},
            },
        },
        ["Exploration du marécage de Zangar"] = {
            achievementID = 863,
            proxyLocation = {0, 0, "Exploration du marécage de Zangar"},
            waypoints = {
                {0, 0, "Refuge Cénarien"},
                {0, 0, "Tourbe-Farouche"},
                {0, 0, "Lac des Furoles"},
                {0, 0, "Telredor"},
                {0, 0, "Le Lagon"},
                {0, 0, "Umbretourbe"},
                {0, 0, "Bastion Ango’rosh"},
                {0, 0, "Havre d’Orebor"},
                {0, 0, "Zabra’jin"},
                {0, 0, "Terres Ango’rosh"},
                {0, 0, "Tourbière Taillée"},
                {0, 0, "Crête des Boues"},
                {0, 0, "La Morte-bourbe"},
                {0, 0, "Ruines des Flèches jumelles"},
                {0, 0, "Sporeggar"},
                {0, 0, "Terres des Écailles-sanglantes"},
                {0, 0, "Le vallon des Pontes"},
                {0, 0, "Rivage des Sombrecrêtes"},
            },
        },
        ["Nagrand"] = {
            achievementID = 866,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Camp de forge : Peur"},
                {0, 0, "Halaa"},
                {0, 0, "Ruines du Crâne-Ricanant"},
                {0, 0, "Poste de Berceau-de-l’Été"},
                {0, 0, "Arène des Épreuves"},
                {0, 0, "Colline des Cogneguerre"},
                {0, 0, "Guet des Clans"},
                {0, 0, "Faille de Sudevent"},
                {0, 0, "Passe de Ventejonc"},
                {0, 0, "Crête de Zangar"},
                {0, 0, "Garadar"},
                {0, 0, "Forteresse Kil’sorrau"},
                {0, 0, "Champs des Esprits"},
                {0, 0, "Telaar"},
                {0, 0, "Trône des éléments"},
                {0, 0, "Ruines de la Lame-Ardente"},
                {0, 0, "Camp de forge : Haine"},
                {0, 0, "La crête du Crépuscule"},
                {0, 0, "Ventejonc"},
            },
        },
        ["Raz-de-Néant"] = {
            achievementID = 843,
            proxyLocation = {0, 0, "Raz-de-Néant"},
            waypoints = {
                {0, 0, "Zone 52"},
                {0, 0, "Manaforge Coruu"},
                {0, 0, "Manaforge Ara"},
                {0, 0, "Ruines de Farahlon"},
                {0, 0, "Le Monceau"},
                {0, 0, "Crête Céleste"},
                {0, 0, "Pierre-de-Néant"},
                {0, 0, "Bastion des Solfurie"},
                {0, 0, "Pont de Gyro-passerelles"},
                {0, 0, "Lieu de rassemblement de l’Ethereum"},
                {0, 0, "Base de forge : Oubli"},
                {0, 0, "Manaforge B’naar"},
                {0, 0, "Manaforge Duro"},
                {0, 0, "Manaforge Ultris"},
                {0, 0, "Donjon de la Tempête"},
                {0, 0, "Ruines Arklon"},
                {0, 0, "Kirin’Var"},
                {0, 0, "Ruines d’Enkaat"},
                {0, 0, "La Foudreflèche"},
                {0, 0, "Écodôme Champlointain"},
                {0, 0, "Siège de Socrethar"},
                {0, 0, "Écodôme Terres-Médianes"},
            },
        },
    },
    ["Exploration du Cataclysme"] = {
        ["Exploration d'Hyjal"] = {
            achievementID = 4863,
            proxyLocation = {0, 0, "Exploration d'Hyjal"},
            waypoints = {
                {0, 0, "Bord-du-Monde"},
                {0, 0, "Lac des Cendres"},
                {0, 0, "Portes de Sothann"},
                {0, 0, "Perchoir de Sethria"},
                {0, 0, "Le Sillage des flammes"},
                {0, 0, "Le Trône des Flammes"},
                {0, 0, "Le cercle des Braises"},
                {0, 0, "Gorge du Sombre murmure"},
                {0, 0, "Nordrassil"},
                {0, 0, "Sanctuaire de Goldrinn"},
                {0, 0, "La plaine Incendiée"},
            },
        },
        ["Exploration du Tréfonds"] = {
            achievementID = 4864,
            proxyLocation = {0, 0, "Exploration du Tréfonds"},
            waypoints = {
                {0, 0, "La Chute d’Aile de mort"},
                {0, 0, "Scories-de-Rochepointe"},
                {0, 0, "Épave de la Furie de l’orage"},
                {0, 0, "Le perchoir Diaphane"},
                {0, 0, "Les fonds Tremblants"},
                {0, 0, "Porte des Maîtres"},
                {0, 0, "Gouffre de Rochepointe"},
                {0, 0, "Âtrepierre"},
                {0, 0, "Temple de la Terre"},
                {0, 0, "Trône de Therazane"},
                {0, 0, "Surplomb du Crépuscule"},
                {0, 0, "Étendues Cramoisies"},
            },
        },
        ["hautes-terres du Crépuscule"] = {
            achievementID = 4866,
            proxyLocation = {0, 0, "hautes-terres du Crépuscule"},
            waypoints = {
                {0, 0, "Goulet Sanglant"},
                {0, 0, "Frakass"},
                {0, 0, "Port Gueule-de-dragon"},
                {0, 0, "Patrouille de Barbe-en-Feu"},
                {0, 0, "Camp de guerre Gorshak"},
                {0, 0, "Hauterive"},
                {0, 0, "Déflagration de Humboldt"},
                {0, 0, "Forêt Obsidienne"},
                {0, 0, "Crique Sinueuse"},
                {0, 0, "Le Gosier"},
                {0, 0, "La Brèche du Crépuscule"},
                {0, 0, "Rivage du Crépuscule"},
                {0, 0, "Halte de la Victoire"},
                {0, 0, "L’antre de la Folie"},
                {0, 0, "Creuset du carnage"},
                {0, 0, "Passe des Gueules-de-dragon"},
                {0, 0, "Ruines de Dunwald"},
                {0, 0, "Creux des Crassentrailles"},
                {0, 0, "Grim Batol"},
                {0, 0, "Forêt des Hautes-Terres"},
                {0, 0, "Havran’iliz"},
                {0, 0, "Ruines de Drakgor"},
                {0, 0, "La brèche Noire"},
                {0, 0, "Le Kraazar"},
                {0, 0, "Tonnemar"},
                {0, 0, "La redoute Vermillon"},
                {0, 0, "Tournant du Wyrm"},
            },
        },
        ["Vashj'ir"] = {
            achievementID = 4825,
            proxyLocation = {0, 0, "Vashj'ir"},
            waypoints = {
                {0, 0, "Récif Abandonné"},
                {0, 0, "Canyon de Terradiance"},
                {0, 0, "Fin de Korthun"},
                {0, 0, "Frôlemer"},
                {0, 0, "Gorge du Gouffre scintillant"},
                {0, 0, "Escarpement de Globulle"},
                {0, 0, "Tombe du marin"},
                {0, 0, "Le récif Squelettique"},
                {0, 0, "Nespirah"},
                {0, 0, "Ruines de Vashj’ir"},
                {0, 0, "Creux des Flots argentés"},
                {0, 0, "Brèche Abyssale"},
                {0, 0, "Crête Nagegouffre"},
                {0, 0, "L’ghorek"},
                {0, 0, "Le gouffre Brûlant"},
                {0, 0, "Charnier de Ronge-la-mort"},
                {0, 0, "L’Étreinte"},
                {0, 0, "Le Destin de la Légion"},
                {0, 0, "Crête de Beth’mora"},
                {0, 0, "Ruines du temple de Thelserai"},
                {0, 0, "Grotte Chatoyante"},
            },
        },
        ["Exploration d'Uldum"] = {
            achievementID = 4865,
            proxyLocation = {0, 0, "Exploration d'Uldum"},
            waypoints = {
                {0, 0, "Champs d’Akhenet"},
                {0, 0, "Tombe de Khartut"},
                {0, 0, "Mar’at"},
                {0, 0, "Neferset"},
                {0, 0, "Obélisque des Étoiles"},
                {0, 0, "Orsis"},
                {0, 0, "Ruines d’Ahmtul"},
                {0, 0, "Accostage de Schnottz"},
                {0, 0, "Temple d’Uldum"},
                {0, 0, "La porte des Cycles infinis"},
                {0, 0, "La piste Dévastée"},
                {0, 0, "Berceau des Anciens"},
                {0, 0, "Cité perdue des Tol’vir"},
                {0, 0, "Nahom"},
                {0, 0, "Obélisque de la Lune"},
                {0, 0, "Obélisque du Soleil"},
                {0, 0, "Ramkahen"},
                {0, 0, "Ruines d’Ammon"},
                {0, 0, "Terres de Tahret"},
                {0, 0, "L’accostage Maudit"},
                {0, 0, "Tombes des Précurseurs"},
                {0, 0, "Barrage de la Vir’naal"},
            },
        },
    },
    ["Draenor"] = {
        ["la crête de Givrefeu"] = {
            achievementID = 8937,
            proxyLocation = {0, 0, "la crête de Givrefeu"},
            waypoints = {
                {0, 0, "Citadelle de Flèchelame"},
                {0, 0, "Restes d’Agurak"},
                {0, 0, "Ravin des Crocs-Lames"},
                {0, 0, "Colline de Triste-Givre"},
                {0, 0, "Atelier de siège de Fer"},
                {0, 0, "Magnarok"},
                {0, 0, "Crâne-de-Lave"},
                {0, 0, "Wor’gol"},
                {0, 0, "Bastion de la Masse-Sanglante"},
                {0, 0, "Trépas-du-Colosse"},
                {0, 0, "Combe de Givrevent"},
                {0, 0, "Grom’gar"},
                {0, 0, "Relais de Fer"},
                {0, 0, "Avant-poste Croc-de-Pierre"},
                {0, 0, "Plaines Craquelées"},
            },
        },
        ["Gorgrond"] = {
            achievementID = 8939,
            proxyLocation = {0, 0, "Gorgrond"},
            waypoints = {
                {0, 0, "Bastion insoumis"},
                {0, 0, "Dépôt de Tristerail"},
                {0, 0, "Mort-Grimaçante"},
                {0, 0, "Sources de l’Aube-Éternelle"},
                {0, 0, "La Haute-Route"},
                {0, 0, "Arène Cognepierre"},
                {0, 0, "La marche de Fer"},
                {0, 0, "Guet des Bêtes"},
                {0, 0, "Marais Rouge"},
                {0, 0, "Séjour de la Flore éternelle"},
                {0, 0, "Canyon des Gronns"},
                {0, 0, "Sylve Iyun"},
                {0, 0, "L’Enchevêtrement"},
                {0, 0, "La Fosse"},
                {0, 0, "La Fosse"},
                {0, 0, "La Fosse"},
            },
        },
        ["flèches d’Arak"] = {
            achievementID = 8941,
            proxyLocation = {0, 0, "flèches d’Arak"},
            waypoints = {
                {0, 0, "Skettis"},
                {0, 0, "Le bourbier Putride"},
                {0, 0, "Voile Zekk"},
                {0, 0, "Port-Austral"},
                {0, 0, "Terrasse de l’Aube"},
                {0, 0, "Bastion Lamepoing"},
                {0, 0, "Voile perdu d’Anzu"},
                {0, 0, "Brèche-aux-Corbeaux"},
                {0, 0, "Tombe-Hache"},
                {0, 0, "La combe Hurlante"},
                {0, 0, "Poste de Sifflepince"},
                {0, 0, "Voile Akraz"},
                {0, 0, "Terrasse Souffle-Bise"},
                {0, 0, "Creux des Sethekk"},
                {0, 0, "Fief de l’amiral Taylor"},
                {0, 0, "Boulonnerie de Sifflepince"},
                {0, 0, "Vallée Crin-de-Sang"},
            },
        },
        ["la vallée d’Ombrelune"] = {
            achievementID = 8938,
            proxyLocation = {0, 0, "la vallée d’Ombrelune"},
            waypoints = {
                {0, 0, "Forteresse de l’Angoisse"},
                {0, 0, "Élodor"},
                {0, 0, "Bosquet des Ténombres"},
                {0, 0, "Karabor"},
                {0, 0, "Lande Scintillante"},
                {0, 0, "Île des Ombres"},
                {0, 0, "Perchoir de Sombreflux"},
                {0, 0, "Embaari"},
                {0, 0, "Gul’var"},
                {0, 0, "Shaz’gul"},
                {0, 0, "Cime de Socrethar"},
            },
        },
        ["Talador"] = {
            achievementID = 8940,
            proxyLocation = {0, 0, "Talador"},
            waypoints = {
                {0, 0, "Aruuna"},
                {0, 0, "Île de Sombre-Soir"},
                {0, 0, "Fort Wrynn"},
                {0, 0, "Gul’rok"},
                {0, 0, "Côte Orunaï"},
                {0, 0, "Shattrath"},
                {0, 0, "Tombeau des Lumières"},
                {0, 0, "Zangarra"},
                {0, 0, "Auchindoun"},
                {0, 0, "Cloître des Âmes"},
                {0, 0, "Forteresse de Gordal"},
                {0, 0, "Le sentier de la Gloire"},
                {0, 0, "Séjour de l’Anachorète"},
                {0, 0, "Telmor"},
                {0, 0, "Tuurem"},
            },
        },
        ["Nagrand"] = {
            achievementID = 8942,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Terres Ancestrales"},
                {0, 0, "Portes de Grommashar"},
                {0, 0, "Port de Cognefort"},
                {0, 0, "Lok-Rath"},
                {0, 0, "Poste de garde de Mok’gol"},
                {0, 0, "Telaar"},
                {0, 0, "Arène des Épreuves"},
                {0, 0, "Rivage de Zangar"},
                {0, 0, "Précipice Brisé"},
                {0, 0, "Fort-Vaillance"},
                {0, 0, "Port Poing-de-Fer"},
                {0, 0, "Belvédère de Mar’gok"},
                {0, 0, "Oshu’gun"},
                {0, 0, "Arène de Sang"},
                {0, 0, "Trône des éléments"},
            },
        },
    },
    ["Battle for Azeroth"] = {
        ["la rade de Tiragarde"] = {
            achievementID = 12556,
            proxyLocation = {0, 0, "la rade de Tiragarde"},
            waypoints = {
                {0, 0, "Quai du Trident"},
                {0, 0, "Crête du bois des Fougères"},
                {0, 0, "Domaine Norwington"},
                {0, 0, "Décharge abandonnée"},
                {0, 0, "Estuaire Gémissant"},
                {0, 0, "Glacier Déclinant"},
                {0, 0, "Boralus"},
                {0, 0, "Port-Liberté"},
                {0, 0, "Crique de la Malédiction du kraken"},
                {0, 0, "Pavillon Kennings"},
                {0, 0, "Colline de la Vigie"},
            },
        },
        ["la vallée Chantorage"] = {
            achievementID = 12558,
            proxyLocation = {0, 0, "la vallée Chantorage"},
            waypoints = {
                {0, 0, "Brennadam"},
                {0, 0, "Rivage du Marin"},
                {0, 0, "Reflux mort"},
                {0, 0, "Séminaire des Eaugures"},
                {0, 0, "Hameau du Meunier"},
                {0, 0, "Kraal des Roncedos"},
                {0, 0, "Camp Croc-de-Guerre"},
                {0, 0, "Fort Daelin"},
                {0, 0, "Sanctuaire des Tempêtes"},
            },
        },
        ["Nazmir"] = {
            achievementID = 12561,
            proxyLocation = {0, 0, "Nazmir"},
            waypoints = {
                {0, 0, "Mangrove Primitive"},
                {0, 0, "Rive-Mare"},
                {0, 0, "Zalamar"},
                {0, 0, "Nazwatha"},
                {0, 0, "La Raine-Mare"},
                {0, 0, "Cœur des ténèbres"},
                {0, 0, "La Nécropole"},
                {0, 0, "Repos de Torga"},
                {0, 0, "Zal’amak"},
            },
        },
        ["Drustvar"] = {
            achievementID = 12557,
            proxyLocation = {0, 0, "Drustvar"},
            waypoints = {
                {0, 0, "Ferté-d’Arom"},
                {0, 0, "Port du Désosseur"},
                {0, 0, "Forêt Cramoisie"},
                {0, 0, "Val-Archer"},
                {0, 0, "Route du Haut-Col"},
                {0, 0, "Glacier du Voile gelé"},
                {0, 0, "Cimetière de Tertrebois"},
                {0, 0, "Corlain"},
                {0, 0, "Havrebrune"},
                {0, 0, "Gol Koval"},
                {0, 0, "Guet de l’Ouest"},
                {0, 0, "Manoir Malvoie"},
            },
        },
        ["Zuldazar"] = {
            achievementID = 12559,
            proxyLocation = {0, 0, "Zuldazar"},
            waypoints = {
                {0, 0, "Atal’Dazar"},
                {0, 0, "Porte de Sang"},
                {0, 0, "Crique de la Perle-Maudite"},
                {0, 0, "Terres Sauvages"},
                {0, 0, "Île de la Défense"},
                {0, 0, "Xibala"},
                {0, 0, "Atal’Gral"},
                {0, 0, "Dazar’alor"},
                {0, 0, "Jardin des Loas"},
                {0, 0, "Le Défilé"},
                {0, 0, "Semonce de Talanji"},
                {0, 0, "Zeb’ahari"},
            },
        },
        ["Vol’dun"] = {
            achievementID = 12560,
            proxyLocation = {0, 0, "Vol’dun"},
            waypoints = {
                {0, 0, "Atul’Aman"},
                {0, 0, "Port de Zem’lan"},
                {0, 0, "Port de Ruinepierre"},
                {0, 0, "Temple d’Akunda"},
                {0, 0, "La fosse aux Ossements"},
                {0, 0, "Côte Fissurée"},
                {0, 0, "Oasis Pépiflore"},
                {0, 0, "Crique Sombrebois"},
                {0, 0, "Port Rocherouge"},
                {0, 0, "Goulet Sinueux"},
                {0, 0, "Terrasse des Dévoués"},
                {0, 0, "Le bassin Salant"},
                {0, 0, "Refuge Tortaka"},
            },
        },
    },
    ["Kalimdor"] = {
        ["Durotar"] = {
            achievementID = 728,
            proxyLocation = {0, 0, "Durotar"},
            waypoints = {
                {0, 0, "Vallée des Épreuves"},
                {0, 0, "Débord de la Furie-du-Sud"},
                {0, 0, "Îles de l’Écho"},
                {0, 0, "Tranchecolline"},
                {0, 0, "Falaises du Tonnerre"},
                {0, 0, "Rocher du Crâne"},
                {0, 0, "Tête de pont de Guet-du-Nord"},
                {0, 0, "Village de Sen’jin"},
                {0, 0, "Donjon de Tiragarde"},
                {0, 0, "Terres des Tranchecrins"},
                {0, 0, "Ravin Asséché"},
                {0, 0, "Orgrimmar"},
            },
        },
        ["Teldrassil"] = {
            achievementID = 842,
            proxyLocation = {0, 0, "Teldrassil"},
            waypoints = {
                {0, 0, "Sombrevallon"},
                {0, 0, "Dolanaar"},
                {0, 0, "Camp des Pins-tordus"},
                {0, 0, "Bassins d’Arlithrien"},
                {0, 0, "La clairière de l’Oracle"},
                {0, 0, "Darnassus"},
                {0, 0, "La Faille"},
                {0, 0, "Creux de Ban’ethil"},
                {0, 0, "Lac Al’Ameth"},
                {0, 0, "Brise-Stellaire"},
                {0, 0, "Lac d’Aigue-vive"},
                {0, 0, "Rut’theran"},
            },
        },
        ["Tarides du Nord"] = {
            achievementID = 750,
            proxyLocation = {0, 0, "Tarides du Nord"},
            waypoints = {
                {0, 0, "Mine des Pierriers"},
                {0, 0, "Le Rempart de Mor’shan"},
                {0, 0, "Pic de Brume-Funeste"},
                {0, 0, "Les bassins Oubliés"},
                {0, 0, "Poste de Guet-Lointain"},
                {0, 0, "La Croisée"},
                {0, 0, "Cabestan"},
                {0, 0, "Oasis Luxuriante"},
                {0, 0, "La Videfange"},
                {0, 0, "Les collines Arides"},
                {0, 0, "Ferme de Grol’dom"},
                {0, 0, "Colline des Épines"},
                {0, 0, "L’oasis Stagnante"},
                {0, 0, "Côte des Marchands"},
            },
        },
        ["Tarides du Sud"] = {
            achievementID = 4996,
            proxyLocation = {0, 0, "Tarides du Sud"},
            waypoints = {
                {0, 0, "Bael Modan"},
                {0, 0, "Quartier général Avancé"},
                {0, 0, "Le Séjour de l’honneur"},
                {0, 0, "Fort de Guet-du-Nord"},
                {0, 0, "Ruines de Taurajo"},
                {0, 0, "Halte de la Vendetta"},
                {0, 0, "La Balafre"},
                {0, 0, "Veine de Folcrame"},
                {0, 0, "Colline du Chasseur"},
                {0, 0, "Kraal de Tranchebauge"},
                {0, 0, "Le Lacis"},
            },
        },
        ["l'île de Brume-Sang"] = {
            achievementID = 861,
            proxyLocation = {0, 0, "l'île de Brume-Sang"},
            waypoints = {
                {0, 0, "Passe d’Ambretoile"},
                {0, 0, "Le rivage de Vase noire"},
                {0, 0, "Île du Sang maudit"},
                {0, 0, "L’enclave des Bras-hirsutes"},
                {0, 0, "Ordeval"},
                {0, 0, "Nazzivian"},
                {0, 0, "Ruines de Loreth’Aran"},
                {0, 0, "Camp de Tel’athion"},
                {0, 0, "Le reflux Sanglant"},
                {0, 0, "Le Cryocœur"},
                {0, 0, "Le récif Caché"},
                {0, 0, "La Bobine vectorielle"},
                {0, 0, "Cap viridien"},
                {0, 0, "Repaire des Irécailles"},
                {0, 0, "Axxarien"},
                {0, 0, "Bois des Lames"},
                {0, 0, "Guet du sang"},
                {0, 0, "La croisée de Kessel"},
                {0, 0, "Bois Brumeux"},
                {0, 0, "Crête des Rageplumes"},
                {0, 0, "Séjour des serres"},
                {0, 0, "Le récif du Sang maudit"},
                {0, 0, "Les confins Cramoisis"},
                {0, 0, "Le bassin Souillé"},
                {0, 0, "Le Repli perdu"},
                {0, 0, "Le Piston de distorsion"},
                {0, 0, "Repos du redresseur de torts"},
                {0, 0, "Île Balafre-du-ver"},
            },
        },
        ["Mille pointes"] = {
            achievementID = 846,
            proxyLocation = {0, 0, "Mille pointes"},
            waypoints = {
                {0, 0, "La Grande élévation"},
                {0, 0, "Site de fouilles englouti"},
                {0, 0, "La Flétrissure du Crépuscule"},
                {0, 0, "Sommet Occidental"},
                {0, 0, "Poste de Librevent"},
                {0, 0, "Les profondeurs Salines"},
                {0, 0, "Souilles de Tranchebauge"},
                {0, 0, "Redoute des mers du Sud"},
                {0, 0, "Barricade du Crépuscule"},
                {0, 0, "Cime de Noir-Nuage"},
                {0, 0, "Hauteurs du Sabot-Fendu"},
                {0, 0, "Haut-Perchoir"},
            },
        },
        ["Désolace"] = {
            achievementID = 848,
            proxyLocation = {0, 0, "Désolace"},
            waypoints = {
                {0, 0, "Tethris Aran"},
                {0, 0, "Combe de Nijel"},
                {0, 0, "Forteresse de Hache-Tonnerre"},
                {0, 0, "Territoire Magram"},
                {0, 0, "Vallée des Lances"},
                {0, 0, "Proie-de-l’Ombre"},
                {0, 0, "Convent de Mannoroc"},
                {0, 0, "Ravin de Brèche-de-l’Ombre"},
                {0, 0, "Camp de Thargad"},
                {0, 0, "Sargeron"},
                {0, 0, "Terres sauvages Cénariennes"},
                {0, 0, "Île de Ranazjar"},
                {0, 0, "Cimetière des Kodos"},
                {0, 0, "Village des Gelkis"},
                {0, 0, "Shok’Thokar"},
                {0, 0, "Rivage des Ondulames"},
            },
        },
        ["Féralas"] = {
            achievementID = 849,
            proxyLocation = {0, 0, "Féralas"},
            waypoints = {
                {0, 0, "Étendues Sauvages"},
                {0, 0, "Les Colosses jumeaux"},
                {0, 0, "Hache-Tripes"},
                {0, 0, "Ruines d’Isildien"},
                {0, 0, "Camp Mojache"},
                {0, 0, "Avant-poste des Gordunni"},
                {0, 0, "Bastion de Pennelune"},
                {0, 0, "Ruines de Pennelune"},
                {0, 0, "La côte Oubliée"},
                {0, 0, "Val des Griffes farouches"},
                {0, 0, "Gouffre Grouillant"},
                {0, 0, "Base des Totems-Sinistres"},
                {0, 0, "Ruines de Sombrebrume"},
            },
        },
        ["Exploration d'Azshara"] = {
            achievementID = 852,
            proxyLocation = {0, 0, "Exploration d'Azshara"},
            waypoints = {
                {0, 0, "Palais des Plaisirs de Gallywix"},
                {0, 0, "Havre Baille-Fonds"},
                {0, 0, "Tour d’Eldara"},
                {0, 0, "Camp de base Darnassien"},
                {0, 0, "Tête d’ours"},
                {0, 0, "Porte d’Azshara"},
                {0, 0, "Plage des Crêtes du sud"},
                {0, 0, "Lac Mennar"},
                {0, 0, "Falaises de la Tempête"},
                {0, 0, "La grève Fracassée"},
                {0, 0, "Confins Amers"},
                {0, 0, "Ruines d’Arkkoran"},
                {0, 0, "Le laboratoire secret"},
                {0, 0, "Repaire des Noiregueules"},
                {0, 0, "Ruines d’Eldarath"},
                {0, 0, "Chute de Corvaltus"},
                {0, 0, "Les confins Dévastés"},
            },
        },
        ["Exploration du cratère d'Un'Goro"] = {
            achievementID = 854,
            proxyLocation = {0, 0, "Exploration du cratère d'Un'Goro"},
            waypoints = {
                {0, 0, "Crête de la Fournaise"},
                {0, 0, "Camp retranché des Marshal"},
                {0, 0, "Les jardins Mouvants"},
                {0, 0, "Sources de Golakka"},
                {0, 0, "La Balafre sinueuse"},
                {0, 0, "Plateau de Rochefer"},
                {0, 0, "Rocher fongique"},
                {0, 0, "Tertre Moussu"},
                {0, 0, "Les confins Hurlants"},
                {0, 0, "Coteaux de la Terreur"},
                {0, 0, "La Fondrière"},
                {0, 0, "Fosses de goudron de Lakkari"},
            },
        },
        ["Silithus"] = {
            achievementID = 856,
            proxyLocation = {0, 0, "Silithus"},
            waypoints = {
                {0, 0, "La vallée des Cristaux"},
                {0, 0, "Fort Cénarien"},
                {0, 0, "Ruche’Regal"},
                {0, 0, "Ruche’Ashi"},
                {0, 0, "Village de Sudevent"},
                {0, 0, "Ruche’Zora"},
                {0, 0, "Mur du Scarabée"},
                {0, 0, "Repos des vaillants"},
            },
        },
        ["Mulgore"] = {
            achievementID = 736,
            proxyLocation = {0, 0, "Mulgore"},
            waypoints = {
                {0, 0, "Mesa de Nuage rouge"},
                {0, 0, "Sabot-de-Sang"},
                {0, 0, "Les plaines Vallonnées"},
                {0, 0, "Caravane dévastée"},
                {0, 0, "Puits Corne-tonnerre"},
                {0, 0, "Rochers Rouges"},
                {0, 0, "Puits Crin-Sauvage"},
                {0, 0, "Rocher des Crins-pâles"},
                {0, 0, "Puits Sabot-d’Hiver"},
                {0, 0, "La mine de la KapitalRisk"},
                {0, 0, "Les plaines Dorées"},
                {0, 0, "Site de fouilles de Bael’Dun"},
                {0, 0, "Crête des Furies-des-vents"},
            },
        },
        ["l'île de Brume-Azur"] = {
            achievementID = 860,
            proxyLocation = {0, 0, "l'île de Brume-Azur"},
            waypoints = {
                {0, 0, "Val d’Ammen"},
                {0, 0, "Guet d’azur"},
                {0, 0, "Clairière de Braise"},
                {0, 0, "Camp de Geezle"},
                {0, 0, "Point d’accostage d’Odesyus"},
                {0, 0, "Débris de Capsule"},
                {0, 0, "Île de Brume-Argent"},
                {0, 0, "L’Exodar"},
                {0, 0, "Cap des Irécailles"},
                {0, 0, "Gué d’Ammen"},
                {0, 0, "Village des Bras-hirsutes"},
                {0, 0, "Rivage de Pontgallant"},
                {0, 0, "Bois Frôle-lune"},
                {0, 0, "Grappe de capsules"},
                {0, 0, "Rivage Envasé"},
                {0, 0, "Repaire des Calmepins"},
                {0, 0, "Amarrage de Valaar"},
            },
        },
        ["Exploration du Berceau-de-l'Hiver"] = {
            achievementID = 857,
            proxyLocation = {0, 0, "Exploration du Berceau-de-l'Hiver"},
            waypoints = {
                {0, 0, "Sources de Givrefeu"},
                {0, 0, "Lac Kel’Theril"},
                {0, 0, "Mazthoril"},
                {0, 0, "Fourré de l’Aile de la chouette"},
                {0, 0, "Village des Tombe-hiver"},
                {0, 0, "Roc des Sabres-de-Givre"},
                {0, 0, "Poste des Grumegueules"},
                {0, 0, "Pluie-d’Étoiles"},
                {0, 0, "Long-Guet"},
                {0, 0, "Collines des Chardons de glace"},
                {0, 0, "Le bosquet Caché"},
                {0, 0, "Gorge du Blanc murmure"},
            },
        },
        ["Sombrivage"] = {
            achievementID = 844,
            proxyLocation = {0, 0, "Sombrivage"},
            waypoints = {
                {0, 0, "Ruines d’Auberdine"},
                {0, 0, "Camp de guerre des Briselances"},
                {0, 0, "Fourré Flétri"},
                {0, 0, "L’Œil du Vortex"},
                {0, 0, "Lor’danel"},
                {0, 0, "Le Glaive du Maître"},
                {0, 0, "La vallée des Briselances"},
                {0, 0, "La Sinueuse"},
                {0, 0, "Ruines de Mathystra"},
                {0, 0, "Ameth’Aran"},
                {0, 0, "Nazj’vel"},
            },
        },
        ["Exploration d'Orneval"] = {
            achievementID = 845,
            proxyLocation = {0, 0, "Exploration d'Orneval"},
            waypoints = {
                {0, 0, "La grève de Zoram"},
                {0, 0, "Refuge de Vent-d’Argent"},
                {0, 0, "Lac Falathim"},
                {0, 0, "Village des Crins-de-Chardon"},
                {0, 0, "Astranaar"},
                {0, 0, "Le val Hurlant"},
                {0, 0, "Lac Tombeciel"},
                {0, 0, "Satyrnaar"},
                {0, 0, "Camp de bûcherons Chanteguerre"},
                {0, 0, "Retraite d’Orendil"},
                {0, 0, "Le Pic-Tonnerre"},
                {0, 0, "Poste de Maestra"},
                {0, 0, "Le sanctuaire d’Aessina"},
                {0, 0, "Les ruines de Chimétoile"},
                {0, 0, "Retraite de Raynebois"},
                {0, 0, "Poste de Bois-Brisé"},
                {0, 0, "L’Ombrage"},
                {0, 0, "Colline Gangrefeu"},
            },
        },
        ["Serres-Rocheuses"] = {
            achievementID = 847,
            proxyLocation = {0, 0, "Serres-Rocheuses"},
            waypoints = {
                {0, 0, "Vallée de la Balafre"},
                {0, 0, "Ruines d’Eldre’thar"},
                {0, 0, "Terres Exhumées"},
                {0, 0, "Bastion des Cisailles"},
                {0, 0, "Malaka’jin"},
                {0, 0, "Ravin des Éboulis"},
                {0, 0, "Combe des Cisailles"},
                {0, 0, "Le val Calciné"},
                {0, 0, "Pic des Serres-Rocheuses"},
                {0, 0, "Forteresse Krom’gar"},
                {0, 0, "Surplomb de Thal’darah"},
                {0, 0, "Creux des Tisseuses"},
                {0, 0, "Poste de Rôde-Falaise"},
                {0, 0, "Sentier des Tisseuses"},
                {0, 0, "Val de Grandbois"},
                {0, 0, "Retraite de Roche-Soleil"},
                {0, 0, "Lac Mirkfallon"},
            },
        },
        ["Exploration du marécage d'Âprefange"] = {
            achievementID = 850,
            proxyLocation = {0, 0, "Exploration du marécage d'Âprefange"},
            waypoints = {
                {0, 0, "Île de Theramore"},
                {0, 0, "Poste de Navrecorne"},
                {0, 0, "Auberge du Repos ombragé"},
                {0, 0, "Mur-de-Fougères"},
                {0, 0, "Île d’Alcaz"},
                {0, 0, "Sabot-Noir"},
                {0, 0, "Bourbe-à-Brac"},
                {0, 0, "Rivage de Troubleffroi"},
                {0, 0, "Tourbière du Ver"},
            },
        },
        ["Tanaris"] = {
            achievementID = 851,
            proxyLocation = {0, 0, "Tanaris"},
            waypoints = {
                {0, 0, "Gadgetzan"},
                {0, 0, "Vallée des Guetteurs"},
                {0, 0, "Désert Abysséen"},
                {0, 0, "Le repaire Nuisible"},
                {0, 0, "Rivage de Brisesud"},
                {0, 0, "Ruines d’Estelune"},
                {0, 0, "Ruines de Sudelune"},
                {0, 0, "Zul’Farrak"},
                {0, 0, "Guet de Tristesable"},
                {0, 0, "Crique des Gréements"},
                {0, 0, "Pilier Brisé"},
                {0, 0, "Base des Cognedunes"},
                {0, 0, "Le gouffre Béant"},
                {0, 0, "Plage du Bout-du-Monde"},
                {0, 0, "Vallée des Chardonniers"},
                {0, 0, "Grottes du Temps"},
            },
        },
        ["Gangrebois"] = {
            achievementID = 853,
            proxyLocation = {0, 0, "Gangrebois"},
            waypoints = {
                {0, 0, "Village de Gangrepatte"},
                {0, 0, "Bois d’Arbrefer"},
                {0, 0, "Val Grêlé"},
                {0, 0, "Jaedenar"},
                {0, 0, "Vallon des Jadefeu"},
                {0, 0, "Village des Mort-bois"},
                {0, 0, "Clairière de Griffebranche"},
                {0, 0, "Défilé des Jadefeu"},
                {0, 0, "Chutes de la Vénéneuse"},
                {0, 0, "Ruines de Constellas"},
                {0, 0, "Sanctuaire d’Émeraude"},
                {0, 0, "Morlos’Aran"},
            },
        },
        ["Reflet-de-Lune"] = {
            achievementID = 855,
            proxyLocation = {0, 0, "Reflet-de-Lune"},
            waypoints = {
                {0, 0, "Lac Élune’ara"},
                {0, 0, "Sanctuaire de Remulos"},
                {0, 0, "Havrenuit"},
                {0, 0, "Refuge des saisons de Malfurion"},
            },
        },
    },
    ["Exploration du Norfendre"] = {
        ["la toundra Boréenne"] = {
            achievementID = 1264,
            proxyLocation = {0, 0, "la toundra Boréenne"},
            waypoints = {
                {0, 0, "Ville-temple d’En’kilah"},
                {0, 0, "Grève des Courcinglants"},
                {0, 0, "Point d’accostage de Garrosh"},
                {0, 0, "Frimarra"},
                {0, 0, "Escarpement d’Ambre"},
                {0, 0, "Donjon de la Bravoure"},
                {0, 0, "Les tanières du Trépas"},
                {0, 0, "Caravane de Mâchoire-d’acier"},
                {0, 0, "Kaskala"},
                {0, 0, "Le séjour de la Mort"},
                {0, 0, "Avant-poste de Bor’gorok"},
                {0, 0, "Bastion Chanteguerre"},
                {0, 0, "Les champs de Geysers"},
            },
        },
        ["la Désolation des dragons"] = {
            achievementID = 1265,
            proxyLocation = {0, 0, "la Désolation des dragons"},
            waypoints = {
                {0, 0, "Le Repos de Galakrond"},
                {0, 0, "Sanctuaire draconique Obsidien"},
                {0, 0, "Naxxramas"},
                {0, 0, "Brume-Glace"},
                {0, 0, "Hauts de Vent-Froid"},
                {0, 0, "Marteau d’Agmar"},
                {0, 0, "Camp de réfugiés de Ponevent"},
                {0, 0, "La côte Oubliée"},
                {0, 0, "Halte Écarlate"},
                {0, 0, "Lac Indu’le"},
                {0, 0, "Nouvelle-Âtreval"},
                {0, 0, "La Confiance de Lumière"},
                {0, 0, "Sanctuaire draconique Émeraude"},
                {0, 0, "Angrathar, le portail du Courroux"},
                {0, 0, "Temple du Repos du ver"},
                {0, 0, "Vexevenin"},
                {0, 0, "L’Étau de cristal"},
            },
        },
        ["Zul'Drak"] = {
            achievementID = 1267,
            proxyLocation = {0, 0, "Zul'Drak"},
            waypoints = {
                {0, 0, "Gundrak"},
                {0, 0, "Amphithéâtre de l’Angoisse"},
                {0, 0, "Autel de Rhunok"},
                {0, 0, "Autel de Mam’toth"},
                {0, 0, "Zim’Torga"},
                {0, 0, "Voltarus"},
                {0, 0, "La Brèche de Lumière"},
                {0, 0, "Champs de Drak’Sotra"},
                {0, 0, "Autel de Sseratus"},
                {0, 0, "Autel de Quetz’lun"},
                {0, 0, "Autel de Har’koa"},
                {0, 0, "Zeramas"},
                {0, 0, "Fin de Thrym"},
                {0, 0, "Kolramas"},
            },
        },
        ["la forêt du Chant de cristal"] = {
            achievementID = 1457,
            proxyLocation = {0, 0, "la forêt du Chant de cristal"},
            waypoints = {
                {0, 0, "Le front Azur"},
                {0, 0, "Quartier général de Saccage-Soleil"},
                {0, 0, "Surplomb de Coursevent"},
                {0, 0, "Le Séjour pourpre"},
                {0, 0, "Le courant Stagnant"},
                {0, 0, "Bois Lugubre"},
                {0, 0, "Le Grand arbre"},
                {0, 0, "Le fourré Délié"},
            },
        },
        ["la Couronne de glace"] = {
            achievementID = 1270,
            proxyLocation = {0, 0, "la Couronne de glace"},
            waypoints = {
                {0, 0, "Le Bombardement"},
                {0, 0, "Port de l’Assaut"},
                {0, 0, "La Charognerie"},
                {0, 0, "La chute de Sindragosa"},
                {0, 0, "Vallée des Échos"},
                {0, 0, "La Déflagration"},
                {0, 0, "Jotunheim"},
                {0, 0, "Le caveau des Ombres"},
                {0, 0, "Citadelle de la Couronne de glace"},
                {0, 0, "Le front Brisé"},
                {0, 0, "Aldur’thar : la Porte de la Désolation"},
                {0, 0, "Valhalas"},
                {0, 0, "Ymirheim"},
                {0, 0, "Corp’rethar : la porte de l’Horreur"},
                {0, 0, "Fléaulme"},
            },
        },
        ["Exploration du fjord Hurlant"] = {
            achievementID = 1263,
            proxyLocation = {0, 0, "Exploration du fjord Hurlant"},
            waypoints = {
                {0, 0, "Kamagua"},
                {0, 0, "Camp Sabot-d’Hiver"},
                {0, 0, "Accostage de la Vengeance"},
                {0, 0, "Cap du Forban"},
                {0, 0, "Gjalerbron"},
                {0, 0, "La piste des Géants"},
                {0, 0, "Ruines d’Ivald"},
                {0, 0, "Nouvelle-Agamand"},
                {0, 0, "La clairière Tordue"},
                {0, 0, "Donjon de la Garde de l’Ouest"},
                {0, 0, "Torvheim"},
                {0, 0, "Île Calderos"},
                {0, 0, "Camp des Apothicaires"},
                {0, 0, "Porte d’Acier"},
                {0, 0, "Nifflevar"},
                {0, 0, "Étreinte de braise"},
                {0, 0, "Fort Hardivar"},
                {0, 0, "Halegrince"},
                {0, 0, "Mörg"},
                {0, 0, "Donjon d’Utgarde"},
                {0, 0, "Excavations de Baelgun"},
            },
        },
        ["Grisonnes"] = {
            achievementID = 1266,
            proxyLocation = {0, 0, "Grisonnes"},
            waypoints = {
                {0, 0, "Bastion de la Conquête"},
                {0, 0, "Ruines de Drakil’jin"},
                {0, 0, "Sources de Granit"},
                {0, 0, "Sanctuaire du Croc rageur"},
                {0, 0, "Baie de la KapitalRisk"},
                {0, 0, "Gîte Ambrepin"},
                {0, 0, "Camp Oneqwah"},
                {0, 0, "Donjon de Drak’Tharon"},
                {0, 0, "Dun Argol"},
                {0, 0, "Grisegueule"},
                {0, 0, "Thor Modan"},
                {0, 0, "Voldrune"},
                {0, 0, "Chantier d’abattage du Ciel bleu"},
                {0, 0, "Campement de la brigade de la marche de l’Ouest"},
            },
        },
        ["Exploration du bassin de Sholazar"] = {
            achievementID = 1268,
            proxyLocation = {0, 0, "Exploration du bassin de Sholazar"},
            waypoints = {
                {0, 0, "Le Cœur du fleuve"},
                {0, 0, "Le pilier Mousselume"},
                {0, 0, "Perchoir du Faiseur"},
                {0, 0, "La canopée Parlepluie"},
                {0, 0, "L’Avalanche"},
                {0, 0, "Bastion de Kartak"},
                {0, 0, "Le fourré Sauvage"},
                {0, 0, "Surplomb du Faiseur"},
                {0, 0, "Le pilier Solegrâce"},
                {0, 0, "Le pilier Sang-de-vie"},
                {0, 0, "Le pilier Scintillant"},
                {0, 0, "La saillie de Forgetempête"},
            },
        },
        ["pics Foudroyés"] = {
            achievementID = 1269,
            proxyLocation = {0, 0, "pics Foudroyés"},
            waypoints = {
                {0, 0, "Brunnhildar"},
                {0, 0, "Dun Niffelem"},
                {0, 0, "Valkyrion"},
                {0, 0, "Champ de mines de Grilledouille"},
                {0, 0, "Temple de la Vie"},
                {0, 0, "Chute-tonnerre"},
                {0, 0, "Plaines des Congères"},
                {0, 0, "Fort du Givre"},
                {0, 0, "Le Berceau de Narvir"},
                {0, 0, "Souffle de Bor"},
                {0, 0, "Terrasse des Faiseurs"},
                {0, 0, "Moteur des Faiseurs"},
                {0, 0, "Ulduar"},
                {0, 0, "Temple des Tempêtes"},
                {0, 0, "Plaie-de-Garm"},
                {0, 0, "Nidavelir"},
            },
        },
    },
    ["Pandarie"] = {
        ["la forêt de Jade"] = {
            achievementID = 6351,
            proxyLocation = {0, 0, "la forêt de Jade"},
            waypoints = {
                {0, 0, "Monastère de Tian"},
                {0, 0, "Le pavillon du rêveur"},
                {0, 0, "Lac de Perle"},
                {0, 0, "Carrière de Pierre-Verte"},
                {0, 0, "Camp Nouka Nouka"},
                {0, 0, "Cœur du serpent"},
                {0, 0, "Temple du Serpent de jade"},
                {0, 0, "Point Garrosh’ar"},
                {0, 0, "Rosée-de-Miel"},
                {0, 0, "Fleur-de-l’Aurore"},
                {0, 0, "Présage de l’empereur"},
                {0, 0, "Tertre des Groukards"},
                {0, 0, "Verger de Brise-de-Nectar"},
                {0, 0, "Terrasse des Cent tonnerres"},
                {0, 0, "Fosses de Queutapulte"},
                {0, 0, "L’Arboretum"},
                {0, 0, "Île Front-du-Vent"},
            },
        },
        ["étendues sauvages de Krasarang"] = {
            achievementID = 6975,
            proxyLocation = {0, 0, "étendues sauvages de Krasarang"},
            waypoints = {
                {0, 0, "Quai des Hameçonneurs"},
                {0, 0, "Rivière Dojani"},
                {0, 0, "Crique de Krasarang"},
                {0, 0, "Lagon de Nayeli"},
                {0, 0, "Ruines de Dojan"},
                {0, 0, "Temple de la Grue rouge"},
                {0, 0, "La jungle Interdite"},
                {0, 0, "Unga Ingou"},
                {0, 0, "Berceau de Chi Ji"},
                {0, 0, "Chant-des-Flots"},
                {0, 0, "Les ruines Krasari"},
                {0, 0, "Refuge des Aile-de-Grue"},
                {0, 0, "Ruines de Korja"},
                {0, 0, "Profondeurs sauvages"},
                {0, 0, "Les îles du Sud"},
                {0, 0, "Guet de Zhu"},
            },
        },
        ["steppes de Tanglong"] = {
            achievementID = 6977,
            proxyLocation = {0, 0, "steppes de Tanglong"},
            waypoints = {
                {0, 0, "Ligne de front de Gao Ran"},
                {0, 0, "Poste de garde de Rensai"},
                {0, 0, "Campement d’Osul"},
                {0, 0, "Garnison des Pandashan"},
                {0, 0, "Sik’vess"},
                {0, 0, "Le marais des Joncs"},
                {0, 0, "Kri’vess"},
                {0, 0, "Temple de Niuzao"},
                {0, 0, "Étau de la haine"},
                {0, 0, "Dao Shan’ze"},
                {0, 0, "Sra’vess"},
            },
        },
        ["Exploration du val de l’Éternel printemps"] = {
            achievementID = 6979,
            proxyLocation = {0, 0, "Exploration du val de l’Éternel printemps"},
            waypoints = {
                {0, 0, "Ruines de Guo-Lai"},
                {0, 0, "Palais Mogu’shan"},
                {0, 0, "L’escalier Doré"},
                {0, 0, "La Pagode dorée"},
                {0, 0, "Sanctuaire des Deux-Lunes"},
                {0, 0, "Les Cinq Sœurs"},
                {0, 0, "Tombe-Brume"},
                {0, 0, "Garnison du Soleil couchant"},
                {0, 0, "Sanctuaire des Sept-Étoiles"},
                {0, 0, "Terres sacrées de Tu Shen"},
                {0, 0, "Lac Blanc-Pétale"},
            },
        },
        ["la vallée des Quatre vents"] = {
            achievementID = 6969,
            proxyLocation = {0, 0, "la vallée des Quatre vents"},
            waypoints = {
                {0, 0, "Arête des Vents"},
                {0, 0, "Le delta Doré"},
                {0, 0, "Micolline"},
                {0, 0, "Kunzen"},
                {0, 0, "Safari de Nesingwary"},
                {0, 0, "Bassins de la Pureté"},
                {0, 0, "Les champs Soyeux"},
                {0, 0, "Brasserie Brune d’Orage"},
                {0, 0, "Élevage Pied de Foudre"},
                {0, 0, "Gorge de Saléchine"},
                {0, 0, "Le grenier Impérial"},
                {0, 0, "Chasse-Pierre"},
                {0, 0, "Maison de Gueule de Boue"},
                {0, 0, "Creux de Paoquan"},
                {0, 0, "Terrasse Grondante"},
                {0, 0, "Marais Chantants"},
                {0, 0, "Le Giron"},
                {0, 0, "Descente de Zhu"},
            },
        },
        ["Exploration du sommet de Kun-Lai"] = {
            achievementID = 6976,
            proxyLocation = {0, 0, "Exploration du sommet de Kun-Lai"},
            waypoints = {
                {0, 0, "Binan"},
                {0, 0, "Porte des Astres vénérables"},
                {0, 0, "Pic de Kota"},
                {0, 0, "Mont Sans-Repos"},
                {0, 0, "Pic de la Sérénité"},
                {0, 0, "Temple du Tigre blanc"},
                {0, 0, "Vallée des Empereurs"},
                {0, 0, "Retraite de Rameau-de-feu"},
                {0, 0, "L’île du Jugement"},
                {0, 0, "Mogujia"},
                {0, 0, "Élevage Patte Musquée"},
                {0, 0, "Monastère des Pandashan"},
                {0, 0, "La piste de la Toile de jute"},
                {0, 0, "Zouchin"},
            },
        },
        ["terres de l’Angoisse"] = {
            achievementID = 6978,
            proxyLocation = {0, 0, "terres de l’Angoisse"},
            waypoints = {
                {0, 0, "Cœur de la peur"},
                {0, 0, "Kypari Vor"},
                {0, 0, "Rikkitun"},
                {0, 0, "Terrasse de Gurthan"},
                {0, 0, "Nids de Shek’zeer"},
                {0, 0, "Bois Grouillant"},
                {0, 0, "Klaxxi’vess"},
                {0, 0, "Kypari Zar"},
                {0, 0, "Pari de Trempette"},
                {0, 0, "Bourbe saumâtre"},
                {0, 0, "Le Chai du couchant"},
                {0, 0, "Zan’vess"},
            },
        },
    },
    ["îles Brisées"] = {
        ["Exploration d’Azsuna"] = {
            achievementID = 10665,
            proxyLocation = {0, 0, "Exploration d’Azsuna"},
            waypoints = {
                {0, 0, "Faronaar"},
                {0, 0, "Voie Verte"},
                {0, 0, "Hautes-terres de Llothien"},
                {0, 0, "Nar’thalas"},
                {0, 0, "Sanctum en ruines"},
                {0, 0, "Ruines telluriques de Zarkhenar"},
                {0, 0, "Gueule du Brasier infernal"},
                {0, 0, "Île du Guet"},
                {0, 0, "Verger Perdu"},
                {0, 0, "Grotte d’Océanus"},
                {0, 0, "Temple des Lumières"},
            },
        },
        ["Haut-Roc"] = {
            achievementID = 10667,
            proxyLocation = {0, 0, "Haut-Roc"},
            waypoints = {
                {0, 0, "Terres-de-Sang"},
                {0, 0, "Guet de Sabot-de-Givre"},
                {0, 0, "Perchoir du Veilleur de la nuit"},
                {0, 0, "Courbe-Rive"},
                {0, 0, "Crique de l’Épave"},
                {0, 0, "Guet de Sabot-de-Pierre"},
                {0, 0, "Totem-du-Tonnerre"},
                {0, 0, "Marécage Aveugle"},
                {0, 0, "Enclave des Cornes-de-Fer"},
                {0, 0, "Bassin Rochepin"},
                {0, 0, "Bas-fonds de Roc-Lointain"},
                {0, 0, "Corne-Céleste"},
                {0, 0, "Chutes Sylvestres"},
                {0, 0, "Pavillon du Traqueur"},
            },
        },
        ["Suramar"] = {
            achievementID = 10669,
            proxyLocation = {0, 0, "Suramar"},
            waypoints = {
                {0, 0, "Val d’Ambre"},
                {0, 0, "Falanaar"},
                {0, 0, "La Grande promenade"},
                {0, 0, "Bastion de la garde de la Lune"},
                {0, 0, "Ruines d’Élune’eth"},
                {0, 0, "Tel’anor"},
                {0, 0, "Fourré Cramoisi"},
                {0, 0, "Bastion Gangrâme"},
                {0, 0, "Jandvik"},
                {0, 0, "Goulet des Murmelune"},
                {0, 0, "Suramar"},
            },
        },
        ["Val’sharah"] = {
            achievementID = 10666,
            proxyLocation = {0, 0, "Val’sharah"},
            waypoints = {
                {0, 0, "Andu’talah"},
                {0, 0, "Ruissecôte"},
                {0, 0, "Récif du Déclin"},
                {0, 0, "Lorlathil"},
                {0, 0, "Val des Griffelunes"},
                {0, 0, "Fourré des Brûlepoils"},
                {0, 0, "Thas’talah"},
                {0, 0, "Bastion du Freux"},
                {0, 0, "La Sylverêve"},
                {0, 0, "Bosquet de Cénarius"},
                {0, 0, "Valbrume"},
                {0, 0, "Shala’nir"},
                {0, 0, "Temple d’Élune"},
            },
        },
        ["Tornheim"] = {
            achievementID = 10668,
            proxyLocation = {0, 0, "Tornheim"},
            waypoints = {
                {0, 0, "Caveau d’Aggramar"},
                {0, 0, "Accostage de Noirsillage"},
                {0, 0, "Griseveille"},
                {0, 0, "Haustvald"},
                {0, 0, "Gueule de Nashal"},
                {0, 0, "Nastrondir"},
                {0, 0, "Le Runebois"},
                {0, 0, "Skold-Ashil"},
                {0, 0, "Repos de la Serre"},
                {0, 0, "Valdisdall"},
                {0, 0, "Surplomb Noirbec"},
                {0, 0, "Dreyrgrot"},
                {0, 0, "Portes des Valeureux"},
                {0, 0, "Hrydshal"},
                {0, 0, "Morheim"},
                {0, 0, "Rocher du Guetteur"},
                {0, 0, "Repos du bouclier"},
                {0, 0, "Confins de la Tempête"},
                {0, 0, "Port des Mörgestran"},
                {0, 0, "Les pitons Larmoyants"},
            },
        },
    },
    -- Add other continents...
    ["Continents"] = {
        ["Eastern Kingdoms"] = "Royaumes de l’Est",
        ["Kalimdor"]         = "Kalimdor",
        ["Outland"]          = "Outreterre",
        ["Northrend"]        = "Norfendre",
        ["Pandaria"]         = "Pandarie",
        ["Draenor"]          = "Draenor",
        ["Broken Isles"]     = "Îles Brisées",
        ["Zandalar"]         = "Zandalar",
        ["Kul Tiras"]        = "Kul Tiras",
        ["The Maelstrom"]    = "Le Maelström",
        ["Vashj'ir"]         = "Vashj'ir",
        -- etc. if you need more...
    },
}