Localization = Localization or {}

Localization["itIT"] = {
    ["Regni Orientali"] = {
        ["Foresta di Elwynn"] = {
            achievementID = 776,
            proxyLocation = {0, 0, "Foresta di Elwynn"},
            waypoints = {
                {0, 0, "Valle della Contea del Nord"},
                {0, 0, "Borgodoro"},
                {0, 0, "Molo di Jerod"},
                {0, 0, "Campo di Zucche dei Pozzonero"},
                {0, 0, "Torre Cresta Alta"},
                {0, 0, "Lago del Memoriale"},
                {0, 0, "Presidio Rivombroso"},
                {0, 0, "Miniera Antrocupo"},
                {0, 0, "Torre di Azora"},
                {0, 0, "Campo di Taglio di Vallevante"},
                {0, 0, "Lago di Cristallo"},
            },
        },
        ["Maleterre"] = {
            achievementID = 765,
            proxyLocation = {0, 0, "Maleterre"},
            waypoints = {
                {0, 0, "Piana di Lethlor"},
                {0, 0, "Uldaman"},
                {0, 0, "Sfregio del Devastamondi"},
                {0, 0, "Fortezza di Angor"},
                {0, 0, "Presidio di Mirasangue"},
                {0, 0, "Fossa di Agmond"},
                {0, 0, "Campo Cagg"},
                {0, 0, "Piana della Polvere"},
                {0, 0, "Campo Kosh"},
                {0, 0, "Nuova Kargath"},
            },
        },
        ["Steppe Ardenti"] = {
            achievementID = 775,
            proxyLocation = {0, 0, "Steppe Ardenti"},
            waypoints = {
                {0, 0, "Masso dei Maglioinfame"},
                {0, 0, "Sentiero del Terrore Alato"},
                {0, 0, "Rovine di Thaurissan"},
                {0, 0, "Fortezza Roccianera"},
                {0, 0, "Altare delle Tempeste"},
                {0, 0, "Presidio di Morgan"},
                {0, 0, "Passo di Roccianera"},
                {0, 0, "Tugurio di Dente Nero"},
                {0, 0, "Collina dei Draghetti"},
                {0, 0, "Massiccio Roccianera"},
            },
        },
        ["Boscovespro"] = {
            achievementID = 778,
            proxyLocation = {0, 0, "Boscovespro"},
            waypoints = {
                {0, 0, "Argine Silenzioso"},
                {0, 0, "Collecorvo"},
                {0, 0, "Tumulo degli Ogre Vul'Gol"},
                {0, 0, "Cascina degli Yorgen"},
                {0, 0, "Frutteto Marcescente"},
                {0, 0, "Borgoscuro"},
                {0, 0, "Argine Fosco"},
                {0, 0, "Cascina degli Addle"},
                {0, 0, "Cimitero di Collecorvo"},
                {0, 0, "Bosco del Crepuscolo"},
                {0, 0, "Bosco Legnoradioso"},
                {0, 0, "Cimitero Parcosereno"},
                {0, 0, "Maniero dei Foscomanto"},
            },
        },
        ["Loch Modan"] = {
            achievementID = 779,
            proxyLocation = {0, 0, "Loch Modan"},
            waypoints = {
                {0, 0, "Loch"},
                {0, 0, "Roccaforte di Mo'grosh"},
                {0, 0, "Passo Settentrionale"},
                {0, 0, "Scavi di Ferrocollo"},
                {0, 0, "Thelsamar"},
                {0, 0, "Valle dei Re"},
                {0, 0, "Diga di Pietrasalda"},
                {0, 0, "Miniera Vena d'Argento"},
                {0, 0, "Padiglione Lungopasso"},
                {0, 0, "Dorsale di Zampagrigia"},
                {0, 0, "Valle Pietrarotta"},
            },
        },
        ["Radure di Tirisfal"] = {
            achievementID = 768,
            proxyLocation = {0, 0, "Radure di Tirisfal"},
            waypoints = {
                {0, 0, "Albamorta"},
                {0, 0, "Mulini degli Agamand"},
                {0, 0, "Maniero Cuorduro"},
                {0, 0, "Covo di Garren"},
                {0, 0, "Cascina dei Balnir"},
                {0, 0, "Presidio Scarlatto"},
                {0, 0, "Rovine di Lordaeron"},
                {0, 0, "Granbarricata"},
                {0, 0, "Cascina dei Solliden"},
                {0, 0, "Valle degli Incubi"},
                {0, 0, "Brill"},
                {0, 0, "Lago di Acqualucente"},
                {0, 0, "Avamposto dei Crociati"},
                {0, 0, "Valle Tela Venefica"},
                {0, 0, "Ingresso al Monastero Scarlatto"},
                {0, 0, "Tenuta dei Calston"},
            },
        },
        ["Gorgia Rovente"] = {
            achievementID = 774,
            proxyLocation = {0, 0, "Gorgia Rovente"},
            waypoints = {
                {0, 0, "Cresta Mirafuoco"},
                {0, 0, "Caverna Bracenera"},
                {0, 0, "Scavi di Golasporca"},
                {0, 0, "Presidio del Torio"},
                {0, 0, "Caldera Magmatica"},
                {0, 0, "Mare di Cenere"},
                {0, 0, "Valle di Sabbia Arsa"},
                {0, 0, "Massiccio Roccianera"},
            },
        },
        ["Terre Spettrali"] = {
            achievementID = 858,
            proxyLocation = {0, 0, "Terre Spettrali"},
            waypoints = {
                {0, 0, "Tranquillien"},
                {0, 0, "Brumadoro"},
                {0, 0, "Santuario della Luna"},
                {0, 0, "Torre degli Albastella"},
                {0, 0, "Ziggurat Urlante"},
                {0, 0, "Zeb'Nowa"},
                {0, 0, "Pinnacolo di Ventolesto"},
                {0, 0, "Crocevia di Elrendar"},
                {0, 0, "Solcorona"},
                {0, 0, "Ventolesto"},
                {0, 0, "Santuario del Sole"},
                {0, 0, "Enclave dei Lungopasso"},
                {0, 0, "Mortorium"},
                {0, 0, "Passo degli Amani"},
                {0, 0, "Ziggurat Sanguinante"},
                {0, 0, "Passo Thalassiano"},
            },
        },
        ["il Capo di Rovotorto"] = {
            achievementID = 4995,
            proxyLocation = {0, 0, "il Capo di Rovotorto"},
            waypoints = {
                {0, 0, "Baia del Bottino"},
                {0, 0, "Arena dei Gurubashi"},
                {0, 0, "Isola di Jaguero"},
                {0, 0, "Sorgente di Nek'mani"},
                {0, 0, "Rovine di Jubuwal"},
                {0, 0, "Miniera di Cristallo"},
                {0, 0, "Rifugio di Serrabullona"},
                {0, 0, "Vallebruma"},
                {0, 0, "Rovine di Aboraz"},
                {0, 0, "Rive Selvagge"},
            },
        },
        ["Entroterre"] = {
            achievementID = 773,
            proxyLocation = {0, 0, "Entroterre"},
            waypoints = {
                {0, 0, "Picco dell'Aquila"},
                {0, 0, "Zun'watha"},
                {0, 0, "Shadra'Alor"},
                {0, 0, "Agol'watha"},
                {0, 0, "Altare di Zul"},
                {0, 0, "Tumulo Strisciante"},
                {0, 0, "Jintha'alor"},
                {0, 0, "Gola di Piagabruma"},
                {0, 0, "Padiglione Quel'Danil"},
                {0, 0, "Lago di Ardivento"},
                {0, 0, "Rovine Infestate"},
                {0, 0, "Seradane"},
                {0, 0, "Shaol'watha"},
                {0, 0, "Scogliera Altosguardo"},
            },
        },
        ["Paludi Grigie"] = {
            achievementID = 841,
            proxyLocation = {0, 0, "Paludi Grigie"},
            waypoints = {
                {0, 0, "Porto di Menethil"},
                {0, 0, "Palude dei Branchiazzurra"},
                {0, 0, "Palude del Tramonto"},
                {0, 0, "Sepolcro di Barbaferrea"},
                {0, 0, "Accampamento Zannarabbiosa"},
                {0, 0, "Selva di Guardiaverde"},
                {0, 0, "Colle Forgiatroce"},
                {0, 0, "Missione di Sondapietra"},
                {0, 0, "Acquitrino Solconero"},
                {0, 0, "Scavi di Whelgar"},
                {0, 0, "Radura Salmastra"},
                {0, 0, "Dun Modr"},
                {0, 0, "Masso di Thelgen"},
                {0, 0, "Pantano dei Pelomusco"},
                {0, 0, "Dun Algaz"},
                {0, 0, "Dorsale dei Raptor"},
            },
        },
        ["Terre Infette Occidentali"] = {
            achievementID = 770,
            proxyLocation = {0, 0, "Terre Infette Occidentali"},
            waypoints = {
                {0, 0, "Lago Darrowmere"},
                {0, 0, "Collina del Cordoglio"},
                {0, 0, "Granbarricata"},
                {0, 0, "Fattoria dei Dalson"},
                {0, 0, "Campo di Taglio Cresta Nord"},
                {0, 0, "Valletta dei Pinorosso"},
                {0, 0, "Grotta Piangente"},
                {0, 0, "Caer Darrow"},
                {0, 0, "Andorhal"},
                {0, 0, "Campo di Vilpietra"},
                {0, 0, "Il Campo Putrido"},
                {0, 0, "Valsalda"},
                {0, 0, "Podere di Gahrron"},
                {0, 0, "Fiume Thondroril"},
            },
        },
        ["l'Isola di Quel'Danas"] = {
            achievementID = 868,
            proxyLocation = {0, 0, "l'Isola di Quel'Danas"},
            waypoints = {
            },
        },
        ["gli Altopiani d'Arathi"] = {
            achievementID = 761,
            proxyLocation = {0, 0, "gli Altopiani d'Arathi"},
            waypoints = {
                {0, 0, "Circolo del Vincolo Occidentale"},
                {0, 0, "Roccia'gor"},
                {0, 0, "Forte di Stromgarde"},
                {0, 0, "Circolo del Vincolo Interno"},
                {0, 0, "Fortilizio dei Rocciadura"},
                {0, 0, "Circolo del Vincolo Esterno"},
                {0, 0, "Fattoria di Go'shek"},
                {0, 0, "Circolo del Vincolo Orientale"},
                {0, 0, "Maniero dei Norten"},
                {0, 0, "Caduta di Galen"},
                {0, 0, "Baia di Faldir"},
                {0, 0, "Viadotto di Thandol"},
                {0, 0, "Fosso dei Rifugiati"},
                {0, 0, "Villaggio degli Scorzasecca"},
                {0, 0, "Cascina dei Dabyrie"},
                {0, 0, "Requie del Martello"},
            },
        },
        ["Terre Devastate"] = {
            achievementID = 766,
            proxyLocation = {0, 0, "Terre Devastate"},
            waypoints = {
                {0, 0, "Rocca dei Maglioinfame"},
                {0, 0, "Forte di Guardiafatua"},
                {0, 0, "Portale Oscuro"},
                {0, 0, "Avamposto dei Maglioinfame"},
                {0, 0, "Alture del Profanatore"},
                {0, 0, "Spedizione di Solvelato"},
                {0, 0, "Insenature Rosse"},
                {0, 0, "Campi di Rifornimento di Guardiafatua"},
                {0, 0, "Spira del Serpente"},
                {0, 0, "Altare delle Tempeste"},
                {0, 0, "Landa Corrotta"},
                {0, 0, "Spiaggia dei Relitti"},
                {0, 0, "Surwich"},
                {0, 0, "Bosco Corrotto"},
            },
        },
        ["Dun Morogh"] = {
            achievementID = 627,
            proxyLocation = {0, 0, "Dun Morogh"},
            waypoints = {
                {0, 0, "Passo Crestafredda"},
                {0, 0, "Fronte dei Mantogelido"},
                {0, 0, "Aerodromo di Forgiardente"},
                {0, 0, "Kharanos"},
                {0, 0, "Tenuta di Ambraquieta"},
                {0, 0, "Cava di Gol'Bolar"},
                {0, 0, "Covo dei Mantogelido"},
                {0, 0, "Cancelli di Forgiardente"},
                {0, 0, "Valle Crestafredda"},
                {0, 0, "Nuova Rabberciopoli"},
                {0, 0, "Cresta Brillante"},
                {0, 0, "Colline di Tundrid"},
                {0, 0, "Lago di Lettofreddo"},
                {0, 0, "Avamposto Settentrionale"},
                {0, 0, "Lago di Ghiacciospesso"},
            },
        },
        ["Alture di Colletorto"] = {
            achievementID = 772,
            proxyLocation = {0, 0, "Alture di Colletorto"},
            waypoints = {
                {0, 0, "Miniera di Venazzurra"},
                {0, 0, "Daga di Corrahn"},
                {0, 0, "Gola di Ventofreddo"},
                {0, 0, "Avvallamento di Dandred"},
                {0, 0, "Dun Garok"},
                {0, 0, "Crocevia della Forca"},
                {0, 0, "Caverna Ringhiante"},
                {0, 0, "Cascina dei Nethander"},
                {0, 0, "Rovine d'Alterac"},
                {0, 0, "Antro del Martirio"},
                {0, 0, "Porta del Sud"},
                {0, 0, "Mulino di Tarren"},
                {0, 0, "Campi Fangosi"},
                {0, 0, "Cascina di Brazie"},
                {0, 0, "Rocca degli Sfasciacresta"},
                {0, 0, "Cratere di Dalaran"},
                {0, 0, "Collina di Darrow"},
                {0, 0, "Forte Durnholde"},
                {0, 0, "Promontorio di Gavin"},
                {0, 0, "Lido delle Nebbie"},
                {0, 0, "Isola della Purificazione"},
                {0, 0, "Rovine di Riva del Sud"},
                {0, 0, "Promontorio di Sofera"},
                {0, 0, "Strahnbrad"},
                {0, 0, "Altocolle"},
                {0, 0, "Terre Alte"},
            },
        },
        ["Montagne Crestarossa"] = {
            achievementID = 780,
            proxyLocation = {0, 0, "Montagne Crestarossa"},
            waypoints = {
                {0, 0, "Borgolago"},
                {0, 0, "Tre Cammini"},
                {0, 0, "Canyon di Crestarossa"},
                {0, 0, "Cascate di Guardamasso"},
                {0, 0, "Accampamento di Rend"},
                {0, 0, "Valle di Galardell"},
                {0, 0, "Accampamento Placido"},
                {0, 0, "Lago Placido"},
                {0, 0, "Cammino Bordolago"},
                {0, 0, "Segheria di Alther"},
                {0, 0, "Valle di Rend"},
                {0, 0, "Mastio di Guardamasso"},
                {0, 0, "Canyon di Ventoscisto"},
            },
        },
        ["i Boschi di Cantoeterno"] = {
            achievementID = 859,
            proxyLocation = {0, 0, "i Boschi di Cantoeterno"},
            waypoints = {
                {0, 0, "Isola di Solealto"},
                {0, 0, "Santuario dell'Ovest"},
                {0, 0, "Santuario del Nord"},
                {0, 0, "Ritiro dei Lungopasso"},
                {0, 0, "Terre di Lungovespro"},
                {0, 0, "Selvaviva"},
                {0, 0, "Bosco Arso"},
                {0, 0, "Costa di Brezzazzurra"},
                {0, 0, "Passo Ramo d'Oro"},
                {0, 0, "Pietra Runica Falithas"},
                {0, 0, "Rifugio di Saltheril"},
                {0, 0, "Allevamento di Thuron"},
                {0, 0, "Zeb'Watha"},
                {0, 0, "Rovine di Lunargenta"},
                {0, 0, "Ancoraggio di Vela del Sole"},
                {0, 0, "Santuario dell'Est"},
                {0, 0, "Stagno di Vocequieta"},
                {0, 0, "Brezzaserena"},
                {0, 0, "Tor'Watha"},
                {0, 0, "Lunargenta"},
                {0, 0, "Cascate di Elrendar"},
                {0, 0, "Lago Elrendar"},
                {0, 0, "Pietra Runica Shan'dor"},
                {0, 0, "Spiaggia Dorata"},
                {0, 0, "Spiaggia Placida"},
            },
        },
        ["Selva Pinargento"] = {
            achievementID = 769,
            proxyLocation = {0, 0, "Selva Pinargento"},
            waypoints = {
                {0, 0, "Linea del Fronte"},
                {0, 0, "Fronte dei Reietti"},
                {0, 0, "Sbarco della Marea del Nord"},
                {0, 0, "Campo di Valgan"},
                {0, 0, "Abisso di Elem"},
                {0, 0, "Mulino d'Ambra"},
                {0, 0, "Alto Comando dei Reietti"},
                {0, 0, "Retroguardia dei Reietti"},
                {0, 0, "Campi Fatiscenti"},
                {0, 0, "Oscurità Brulicante"},
                {0, 0, "Isola di Fenris"},
                {0, 0, "Mausolea"},
                {0, 0, "Tenuta degli Olsen"},
                {0, 0, "Forte di Zannascura"},
                {0, 0, "Costa della Marea del Nord"},
            },
        },
        ["Rovotorto Settentrionale"] = {
            achievementID = 781,
            proxyLocation = {0, 0, "Rovotorto Settentrionale"},
            waypoints = {
                {0, 0, "Forte di Grom'gol"},
                {0, 0, "Bambala"},
                {0, 0, "Rovine di Zuuldaia"},
                {0, 0, "Campo dei Ribelli"},
                {0, 0, "Rovine di Kal'ai"},
                {0, 0, "Tumulo degli Ogre Mosh'ogg"},
                {0, 0, "Rovine di Bal'lal"},
                {0, 0, "Rovine di Zul'Kunda"},
                {0, 0, "Rovine di Balia'mah"},
                {0, 0, "Fortino Livingston"},
                {0, 0, "Spedizione di Nesingwary"},
                {0, 0, "Insediamento di Kurzen"},
                {0, 0, "Rovine di Mizjah"},
                {0, 0, "Lago Nazferiti"},
                {0, 0, "Scogliera Infame"},
                {0, 0, "Zul'gurub"},
            },
        },
        ["Palude del Dolore"] = {
            achievementID = 782,
            proxyLocation = {0, 0, "Palude del Dolore"},
            waypoints = {
                {0, 0, "Valbruma"},
                {0, 0, "Bivio di Frangilancia"},
                {0, 0, "Pietrachiusa"},
                {0, 0, "Bragonero"},
                {0, 0, "Spalatorba"},
                {0, 0, "Caverna di Fontepura"},
                {0, 0, "Rifugio dei Corrotti"},
                {0, 0, "Pantano Mutevole"},
                {0, 0, "Bacino delle Lacrime"},
                {0, 0, "Acquatriste"},
                {0, 0, "Riva di Cannamarcia"},
                {0, 0, "Forte di Fangosecco"},
            },
        },
        ["Marche Occidentali"] = {
            achievementID = 802,
            proxyLocation = {0, 0, "Marche Occidentali"},
            waypoints = {
                {0, 0, "Guardiacolle"},
                {0, 0, "Campo di Zucche dei Ciglioarcuato"},
                {0, 0, "Miniera Venacava"},
                {0, 0, "Acro della Morte"},
                {0, 0, "Cascina degli Alexston"},
                {0, 0, "Catena delle Daghe"},
                {0, 0, "Piane Incolte"},
                {0, 0, "Fattoria dei Saldean"},
                {0, 0, "Cascina dei Jansen"},
                {0, 0, "Fattoria dei Molsen"},
                {0, 0, "Rivoluna"},
                {0, 0, "Podere di Demont"},
                {0, 0, "Baratro Furioso"},
            },
        },
        ["il Valico Ventomorto"] = {
            achievementID = 777,
            proxyLocation = {0, 0, "il Valico Ventomorto"},
            waypoints = {
                {0, 0, "Crocevia del Morto"},
                {0, 0, "Karazhan"},
                {0, 0, "Malvezzo"},
            },
        },
        ["Terre Infette Orientali"] = {
            achievementID = 771,
            proxyLocation = {0, 0, "Terre Infette Orientali"},
            waypoints = {
                {0, 0, "Fiume Thondroril"},
                {0, 0, "Cripta di Zaeldarr"},
                {0, 0, "Valfungosa"},
                {0, 0, "Gola Pestilenziale"},
                {0, 0, "Lago Mereldar"},
                {0, 0, "Cappella della Luce"},
                {0, 0, "Radura Venefica"},
                {0, 0, "Lago di Selvanera"},
                {0, 0, "Zul'mashar"},
                {0, 0, "Padiglione Quel'Lithien"},
                {0, 0, "Malaselva"},
                {0, 0, "Rovine dell'Enclave Scarlatta"},
                {0, 0, "Cascina dei Marris"},
                {0, 0, "Torre della Corona"},
                {0, 0, "Borgo di Darrow"},
                {0, 0, "Crocevia di Corin"},
                {0, 0, "Mano di Tyr"},
                {0, 0, "Cicatrice Infetta"},
                {0, 0, "Torre di Levante"},
                {0, 0, "Valnordia"},
                {0, 0, "Torre Passo Nord"},
                {0, 0, "Valterrore"},
                {0, 0, "Stratholme"},
            },
        },
    },  -- World of Warcraft (Vanilla)
    ["Terre Esterne"] = {
        ["Penisola del Fuoco Infernale"] = {
            achievementID = 862,
            proxyLocation = {0, 0, "Penisola del Fuoco Infernale"},
            waypoints = {
                {0, 0, "Scalinata del Destino"},
                {0, 0, "Torrione del Falco"},
                {0, 0, "Rocca dell'Onore"},
                {0, 0, "Pozze di Aggonar"},
                {0, 0, "Tempio di Telhamat"},
                {0, 0, "Thrallmar"},
                {0, 0, "Zeth'gor"},
                {0, 0, "Cresta del Cielo Infranto"},
                {0, 0, "Campi di Distorsione"},
                {0, 0, "Bastioni della Spedizione"},
                {0, 0, "Cittadella del Fuoco Infernale"},
                {0, 0, "Accampamento dei Mag'har"},
                {0, 0, "Rovine di Sha'naar"},
                {0, 0, "Fronte della Legione"},
                {0, 0, "Trono di Kil'jaeden"},
                {0, 0, "Antro di Haal'esh"},
                {0, 0, "Cresta del Vuoto"},
                {0, 0, "Fornace Mageddon"},
            },
        },
        ["Foresta di Terokk"] = {
            achievementID = 867,
            proxyLocation = {0, 0, "Foresta di Terokk"},
            waypoints = {
                {0, 0, "Rovine dei Guerci Insanguinati"},
                {0, 0, "Macchia Cenariana"},
                {0, 0, "Grangol'var"},
                {0, 0, "Tuurem"},
                {0, 0, "Acquitrino di Raastok"},
                {0, 0, "Passo di Tranciaspina"},
                {0, 0, "Terre degli Auchenai"},
                {0, 0, "Carovana dei Rifugiati"},
                {0, 0, "Tomba delle Ombre"},
                {0, 0, "Vol Rhaze"},
                {0, 0, "Skettis"},
                {0, 0, "Fortezza di Alleria"},
                {0, 0, "Presidio di Alardente"},
                {0, 0, "Mastio di Spaccapietra"},
                {0, 0, "Shattrath"},
                {0, 0, "Monti Granbarriera"},
                {0, 0, "Rovine dei Tritaossa"},
                {0, 0, "Colle delle Carogne"},
                {0, 0, "Anello dell'Osservanza"},
                {0, 0, "Carovana Abbandonata"},
                {0, 0, "Tumulo Inquieto"},
            },
        },
        ["Montagne Spinaguzza"] = {
            achievementID = 865,
            proxyLocation = {0, 0, "Montagne Spinaguzza"},
            waypoints = {
                {0, 0, "Approdo di Bash'ir"},
                {0, 0, "Rocca dei Lamacurva"},
                {0, 0, "Avamposto dei Magliorosso"},
                {0, 0, "Cerchio del Sangue"},
                {0, 0, "Fornace Collera"},
                {0, 0, "Fornace Ira"},
                {0, 0, "Antro di Gruul"},
                {0, 0, "Mok'Nathal"},
                {0, 0, "Cresta delle Lame"},
                {0, 0, "Skald"},
                {0, 0, "Dorsale di Cristallo"},
                {0, 0, "Vol Lashh"},
                {0, 0, "Spianata di Vekhaar"},
                {0, 0, "Gola Tagliente"},
                {0, 0, "Accampamento dei Magliorosso"},
                {0, 0, "Lande Spezzate"},
                {0, 0, "Portale della Morte"},
                {0, 0, "Fornace Terrore"},
                {0, 0, "Grishna"},
                {0, 0, "Cresta Frastagliata"},
                {0, 0, "Selva del Corvo"},
                {0, 0, "Bosco di Ruuan"},
                {0, 0, "Sylvanaar"},
                {0, 0, "Roccaforte degli Spaccatuono"},
                {0, 0, "Vol Ruuan"},
                {0, 0, "Altopiano del Vortice"},
            },
        },
        ["Valle di Torvaluna"] = {
            achievementID = 864,
            proxyLocation = {0, 0, "Valle di Torvaluna"},
            waypoints = {
                {0, 0, "Presidio dei Malaspira"},
                {0, 0, "Roccaforte della Legione"},
                {0, 0, "Villaggio di Torvaluna"},
                {0, 0, "Forgiamorte"},
                {0, 0, "Prigione della Guardiana"},
                {0, 0, "Altare degli Sha'tar"},
                {0, 0, "Campi degli Alafatua"},
                {0, 0, "Presidio dell'Eclisse"},
                {0, 0, "Isola degli Alafatua"},
                {0, 0, "Tempio Nero"},
                {0, 0, "Mano di Gul'dan"},
                {0, 0, "Roccaforte dei Granmartello"},
                {0, 0, "Presidio degli Illidari"},
            },
        },
        ["Paludi di Zangar"] = {
            achievementID = 863,
            proxyLocation = {0, 0, "Paludi di Zangar"},
            waypoints = {
                {0, 0, "Rifugio Cenariano"},
                {0, 0, "Villaggio dei Limofurioso"},
                {0, 0, "Lago di Luceamara"},
                {0, 0, "Telredor"},
                {0, 0, "Grande Laguna"},
                {0, 0, "Villaggio dei Limombroso"},
                {0, 0, "Roccaforte degli Ango'rosh"},
                {0, 0, "Rifugio di Orebor"},
                {0, 0, "Zabra'jin"},
                {0, 0, "Terre degli Ango'rosh"},
                {0, 0, "Palude di Fungomozzo"},
                {0, 0, "Cresta Boleta"},
                {0, 0, "Melmamorta"},
                {0, 0, "Rovine delle Guglie Gemelle"},
                {0, 0, "Sporeggar"},
                {0, 0, "Terre degli Scagliacremisi"},
                {0, 0, "Radura della Procreazione"},
                {0, 0, "Costa dei Crestascura"},
            },
        },
        ["Nagrand"] = {
            achievementID = 866,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Fornace Paura"},
                {0, 0, "Halaa"},
                {0, 0, "Rovine dei Teschio Ridente"},
                {0, 0, "Accampamento di Solenuovo"},
                {0, 0, "Circolo delle Sfide"},
                {0, 0, "Colle dei Fortemaglio"},
                {0, 0, "Presidio dei Clan"},
                {0, 0, "Faglia Vento del Sud"},
                {0, 0, "Passo dei Brezzalorda"},
                {0, 0, "Cresta di Zangar"},
                {0, 0, "Garadar"},
                {0, 0, "Fortezza di Kil'sorin"},
                {0, 0, "Campi degli Spiriti"},
                {0, 0, "Telaar"},
                {0, 0, "Trono degli Elementi"},
                {0, 0, "Rovine delle Lame Ardenti"},
                {0, 0, "Fornace Odio"},
                {0, 0, "Cresta del Crepuscolo"},
                {0, 0, "Villaggio dei Brezzalorda"},
            },
        },
        ["Landa Fatua"] = {
            achievementID = 843,
            proxyLocation = {0, 0, "Landa Fatua"},
            waypoints = {
                {0, 0, "Area 52"},
                {0, 0, "Manaforgia Coruu"},
                {0, 0, "Manaforgia Ara"},
                {0, 0, "Rovine di Farahlon"},
                {0, 0, "Cumulo di Rottami"},
                {0, 0, "Cresta Celeste"},
                {0, 0, "Pietrafatua"},
                {0, 0, "Presidio dei Furia del Sole"},
                {0, 0, "Ponte Giromatico"},
                {0, 0, "Campo Base degli Etereum"},
                {0, 0, "Fornace Oblio"},
                {0, 0, "La Manaforgia B'naar"},
                {0, 0, "Manaforgia Duro"},
                {0, 0, "Manaforgia Ultris"},
                {0, 0, "Forte Tempesta"},
                {0, 0, "Rovine di Arklon"},
                {0, 0, "Kirin'Var"},
                {0, 0, "Rovine di Enkaat"},
                {0, 0, "Guglia Tempestosa"},
                {0, 0, "Ecosfera Camporemoto"},
                {0, 0, "Trono di Socrethar"},
                {0, 0, "Ecosfera Mezzoregno"},
            },
        },
    }, -- The Burning Crusade
    ["Cataclisma"] = {
        ["Hyjal"] = {
            achievementID = 4863,
            proxyLocation = {0, 0, "Hyjal"},
            waypoints = {
                {0, 0, "Margine del Mondo"},
                {0, 0, "Lago delle Ceneri"},
                {0, 0, "Portale di Sothann"},
                {0, 0, "Nido di Sethria"},
                {0, 0, "Desolazione di Fuoco"},
                {0, 0, "Trono delle Fiamme"},
                {0, 0, "Circolo delle Braci"},
                {0, 0, "Gola di Mormoscuro"},
                {0, 0, "Nordrassil"},
                {0, 0, "Sacrario di Goldrinn"},
                {0, 0, "Pianura Bruciata"},
            },
        },
        ["Rocciafonda"] = {
            achievementID = 4864,
            proxyLocation = {0, 0, "Rocciafonda"},
            waypoints = {
                {0, 0, "Caduta di Alamorte"},
                {0, 0, "Macerie di Rocciaguglia"},
                {0, 0, "Relitto della Furia dei Cieli"},
                {0, 0, "Trespolo Pallido"},
                {0, 0, "Campi Sismici"},
                {0, 0, "Portale dei Maestri"},
                {0, 0, "Baratro di Rocciaguglia"},
                {0, 0, "Cordipietra"},
                {0, 0, "Tempio della Terra"},
                {0, 0, "Trono di Therazane"},
                {0, 0, "Presidio del Crepuscolo"},
                {0, 0, "Distesa Cremisi"},
            },
        },
        ["Alture del Crepuscolo"] = {
            achievementID = 4866,
            proxyLocation = {0, 0, "Alture del Crepuscolo"},
            waypoints = {
                {0, 0, "Forra del Sangue"},
                {0, 0, "Spezzacollo"},
                {0, 0, "Porto delle Fauci di Drago"},
                {0, 0, "Bastione dei Barbafiamma"},
                {0, 0, "Campo di Guerra di Gorshak"},
                {0, 0, "Altariva"},
                {0, 0, "Conflagrazione di Humboldt"},
                {0, 0, "Foresta d'Ossidiana"},
                {0, 0, "Cala Sinuosa"},
                {0, 0, "Grandirupo"},
                {0, 0, "Breccia del Crepuscolo"},
                {0, 0, "Riva del Crepuscolo"},
                {0, 0, "Presidio della Vittoria"},
                {0, 0, "Fauci della Follia"},
                {0, 0, "Crogiolo della Carneficina"},
                {0, 0, "Passo delle Fauci di Drago"},
                {0, 0, "Rovine di Dunwald"},
                {0, 0, "Antro dei Rodibudella"},
                {0, 0, "Grim Batol"},
                {0, 0, "Altobosco"},
                {0, 0, "Borgogaio"},
                {0, 0, "Rovine di Drakgor"},
                {0, 0, "Breccia Nera"},
                {0, 0, "Krazzopoli"},
                {0, 0, "Tuonocupo"},
                {0, 0, "Trincea Vermiglia"},
                {0, 0, "China dei Dragoni"},
            },
        },
        ["Vashj'ir"] = {
            achievementID = 4825,
            proxyLocation = {0, 0, "Vashj'ir"},
            waypoints = {
                {0, 0, "Distesa Sterile"},
                {0, 0, "Canyon di Sottoluce"},
                {0, 0, "Riposo di Korthun"},
                {0, 0, "Selvamarina"},
                {0, 0, "Faglia di Fondaluce"},
                {0, 0, "Scogliera di Branchiabigia"},
                {0, 0, "Tomba dei Marinai"},
                {0, 0, "Scogliera dei Relitti"},
                {0, 0, "Nespirah"},
                {0, 0, "Rovine di Vashj'ir"},
                {0, 0, "Grotta di Marea d'Argento"},
                {0, 0, "Breccia Abissale"},
                {0, 0, "Altura dei Pinnafonda"},
                {0, 0, "L'ghorek"},
                {0, 0, "Baratro Bollente"},
                {0, 0, "Carnaio di Gnaws"},
                {0, 0, "Grinfiastretta"},
                {0, 0, "Fato della Legione"},
                {0, 0, "Cresta di Beth'mora"},
                {0, 0, "Rovine del Tempio di Thelserai"},
                {0, 0, "Scogliera Scintillante"},
            },
        },
        ["Uldum"] = {
            achievementID = 4865,
            proxyLocation = {0, 0, "Uldum"},
            waypoints = {
                {0, 0, "Campi di Akhenet"},
                {0, 0, "Tomba di Khartut"},
                {0, 0, "Mar'at"},
                {0, 0, "Neferset"},
                {0, 0, "Obelisco delle Stelle"},
                {0, 0, "Orsis"},
                {0, 0, "Rovine di Ahmtul"},
                {0, 0, "Approdo di Schnottz"},
                {0, 0, "Tempio di Uldum"},
                {0, 0, "Portale dei Cicli Infiniti"},
                {0, 0, "Via della Devastazione"},
                {0, 0, "Culla degli Antichi"},
                {0, 0, "Città Perduta dei Tol'vir"},
                {0, 0, "Nahom"},
                {0, 0, "Obelisco della Luna"},
                {0, 0, "Obelisco del Sole"},
                {0, 0, "Ramkahen"},
                {0, 0, "Rovine di Ammon"},
                {0, 0, "Terre di Tahret"},
                {0, 0, "Approdo Maledetto"},
                {0, 0, "Tombe dei Precursori"},
                {0, 0, "Diga di Vir'naal"},
            },
        },
    }, -- Cataclysm
    ["Draenor"] = {
        ["Landa di Fuocogelo"] = {
            achievementID = 8937,
            proxyLocation = {0, 0, "Landa di Fuocogelo"},
            waypoints = {
                {0, 0, "Fortezza dei Lamacurva"},
                {0, 0, "Ossa di Agurak"},
                {0, 0, "Crepaccio delle Fauci Aguzze"},
                {0, 0, "Collina dei Gelotetro"},
                {0, 0, "Officina Bellica di Ferro"},
                {0, 0, "Magnarok"},
                {0, 0, "Ossarotte"},
                {0, 0, "Wor'gol"},
                {0, 0, "Roccaforte dei Magliorosso"},
                {0, 0, "Caduta del Colosso"},
                {0, 0, "Rupe di Brezzafredda"},
                {0, 0, "Grom'gar"},
                {0, 0, "Postazione di Ferro"},
                {0, 0, "Avamposto dell'Artiglio di Pietra"},
                {0, 0, "Distese Ghiacciate"},
            },
        },
        ["Gorgrond"] = {
            achievementID = 8939,
            proxyLocation = {0, 0, "Gorgrond"},
            waypoints = {
                {0, 0, "Altura del Bastione"},
                {0, 0, "Treno Frecciacupa"},
                {0, 0, "Ghignotetro"},
                {0, 0, "Sorgenti di Vespreterno"},
                {0, 0, "Altopasso"},
                {0, 0, "Arena dei Mazzapietra"},
                {0, 0, "Approdo di Ferro"},
                {0, 0, "Roccabestia"},
                {0, 0, "Pantano Cremisi"},
                {0, 0, "Giungla di Verdeterno"},
                {0, 0, "Canyon dei Gronn"},
                {0, 0, "Bosco di Iyu"},
                {0, 0, "Cuor del Groviglio"},
                {0, 0, "Fossatetra"},
                {0, 0, "Fossatetra"},
                {0, 0, "Fossatetra"},
            },
        },
        ["Guglie di Arakk"] = {
            achievementID = 8941,
            proxyLocation = {0, 0, "Guglie di Arakk"},
            waypoints = {
                {0, 0, "Skettis"},
                {0, 0, "Pantano Inquieto"},
                {0, 0, "Vol Zekk"},
                {0, 0, "Approdo del Sud"},
                {0, 0, "Terrazza dell'Alba"},
                {0, 0, "Forte di Manotagliente"},
                {0, 0, "Vol Anzu Perduta"},
                {0, 0, "Graffiacorvo"},
                {0, 0, "Calascure"},
                {0, 0, "Rupe Ululante"},
                {0, 0, "Promontorio Brillabotti"},
                {0, 0, "Vol Akraz"},
                {0, 0, "Terrazza Impetuosa"},
                {0, 0, "Conca dei Sethekk"},
                {0, 0, "Guarnigione dell'Ammiraglio Taylor"},
                {0, 0, "Stabilimenti Brillabotti"},
                {0, 0, "Valle dei Mantorosso"},
            },
        },
        ["Valle di Torvaluna"] = {
            achievementID = 8938,
            proxyLocation = {0, 0, "Valle di Torvaluna"},
            waypoints = {
                {0, 0, "Fortezza del Tormento"},
                {0, 0, "Elodor"},
                {0, 0, "Boschetto di Ombracupa"},
                {0, 0, "Karabor"},
                {0, 0, "Foresta Iridescente"},
                {0, 0, "Isola delle Ombre"},
                {0, 0, "Covo dei Foscamarea"},
                {0, 0, "Embaari"},
                {0, 0, "Gul'var"},
                {0, 0, "Shaz'gul"},
                {0, 0, "Altura di Socrethar"},
            },
        },
        ["Talador"] = {
            achievementID = 8940,
            proxyLocation = {0, 0, "Talador"},
            waypoints = {
                {0, 0, "Aruuna"},
                {0, 0, "Isola di Calavespro"},
                {0, 0, "Forte Wrynn"},
                {0, 0, "Gul'rok"},
                {0, 0, "Costa Orunai"},
                {0, 0, "Shattrath"},
                {0, 0, "Tomba delle Luci"},
                {0, 0, "Zangarra"},
                {0, 0, "Auchindoun"},
                {0, 0, "Corte delle Anime"},
                {0, 0, "Fortezza Gordal"},
                {0, 0, "Cammino della Gloria"},
                {0, 0, "Dimora dell'Anacoreta"},
                {0, 0, "Telmor"},
                {0, 0, "Tuurem"},
            },
        },
        ["Nagrand"] = {
            achievementID = 8942,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Terre Ancestrali"},
                {0, 0, "Porte di Grommashar"},
                {0, 0, "Porto di Altomaglio"},
                {0, 0, "Lok-Rath"},
                {0, 0, "Posto di Guardia dei Mok'gol"},
                {0, 0, "Telaar"},
                {0, 0, "Circolo delle Sfide"},
                {0, 0, "Spiaggia di Zangar"},
                {0, 0, "Precipizio Infranto"},
                {0, 0, "Rocca delle Lame"},
                {0, 0, "Porto Pugnoferreo"},
                {0, 0, "Fortezza di Mar'gok"},
                {0, 0, "Oshu'gun"},
                {0, 0, "Circolo del Sangue"},
                {0, 0, "Trono degli Elementi"},
            },
        },
    }, -- Warlords of Draenor
    ["Battaglia per Azeroth"] = {
        ["Baia di Tiragarde"] = {
            achievementID = 12556,
            proxyLocation = {0, 0, "Baia di Tiragarde"},
            waypoints = {
                {0, 0, "Pontile di Pescagrossa"},
                {0, 0, "Cresta Felcedura"},
                {0, 0, "Tenuta dei Norwington"},
                {0, 0, "Discarica Abbandonata"},
                {0, 0, "Marea Lamentosa"},
                {0, 0, "Ghiacciaio Calante"},
                {0, 0, "Boralus"},
                {0, 0, "Covo della Libertà"},
                {0, 0, "Baia degli Spezzakraken"},
                {0, 0, "Rifugio dei Kennings"},
                {0, 0, "Colle Vigile"},
            },
        },
        ["Valle dei Sacraonda"] = {
            achievementID = 12558,
            proxyLocation = {0, 0, "Valle dei Sacraonda"},
            waypoints = {
                {0, 0, "Brennadam"},
                {0, 0, "Riva del Marinaio"},
                {0, 0, "Flussomorto"},
                {0, 0, "Loggia dei Saggi"},
                {0, 0, "Borgo della Macina"},
                {0, 0, "Gallerie degli Spinomanto"},
                {0, 0, "Forte di Zannaguerra"},
                {0, 0, "Forte Daelin"},
                {0, 0, "Santuario della Tempesta"},
            },
        },
        ["Nazmir"] = {
            achievementID = 12561,
            proxyLocation = {0, 0, "Nazmir"},
            waypoints = {
                {0, 0, "Paludi Primordiali"},
                {0, 0, "Rivolento"},
                {0, 0, "Zalamar"},
                {0, 0, "Nazwatha"},
                {0, 0, "Paludi Gracidanti"},
                {0, 0, "Cuore di Tenebra"},
                {0, 0, "Necropoli"},
                {0, 0, "Riposo di Torga"},
                {0, 0, "Zal'amak"},
            },
        },
        ["Drustvar"] = {
            achievementID = 12557,
            proxyLocation = {0, 0, "Drustvar"},
            waypoints = {
                {0, 0, "Presidio di Arom"},
                {0, 0, "Porto del Norcino"},
                {0, 0, "Foresta Cremisi"},
                {0, 0, "Conca degli Impennatori"},
                {0, 0, "Passo Montano"},
                {0, 0, "Ghiacciaio Velogelido"},
                {0, 0, "Cimitero di Poggiostretto"},
                {0, 0, "Corlain"},
                {0, 0, "Malautunno"},
                {0, 0, "Gol Koval"},
                {0, 0, "Presidio Occidentale"},
                {0, 0, "Maniero dei Crestabianca"},
            },
        },
        ["Zuldazar"] = {
            achievementID = 12559,
            proxyLocation = {0, 0, "Zuldazar"},
            waypoints = {
                {0, 0, "Atal'dazar"},
                {0, 0, "Porta Insanguinata"},
                {0, 0, "Litorale delle Perle"},
                {0, 0, "Terre Selvagge"},
                {0, 0, "Isola delle Zanne"},
                {0, 0, "Xibala"},
                {0, 0, "Atal'gral"},
                {0, 0, "Dazar'alor"},
                {0, 0, "Giardino dei Loa"},
                {0, 0, "Scheggia"},
                {0, 0, "Ritiro di Talanji"},
                {0, 0, "Zeb'ahari"},
            },
        },
        ["Vol'dun"] = {
            achievementID = 12560,
            proxyLocation = {0, 0, "Vol'dun"},
            waypoints = {
                {0, 0, "Atul'aman"},
                {0, 0, "Porto di Zem'lan"},
                {0, 0, "Porto di Frangipietra"},
                {0, 0, "Tempio di Akunda"},
                {0, 0, "Fossa delle Ossa"},
                {0, 0, "Costa Spaccata"},
                {0, 0, "Oasi Cantafiori"},
                {0, 0, "Secca di Boscoscuro"},
                {0, 0, "Porto dei Rocciarossa"},
                {0, 0, "Fossa dei Serpenti"},
                {0, 0, "Terrazza dei Devoti"},
                {0, 0, "Bacino Salmastro"},
                {0, 0, "Rifugio dei Tortaka"},
            },
        },
    }, -- Battle for Azeroth
    ["Kalimdor"] = {
        ["Durotar"] = {
            achievementID = 728,
            proxyLocation = {0, 0, "Durotar"},
            waypoints = {
                {0, 0, "Valle delle Sfide"},
                {0, 0, "Bacino di Furialunga"},
                {0, 0, "Isole dell'Eco"},
                {0, 0, "Tranciacolle"},
                {0, 0, "Fossa del Tuono"},
                {0, 0, "Roccia del Teschio"},
                {0, 0, "Avamposto dei Custodi del Nord"},
                {0, 0, "Villaggio di Sen'jin"},
                {0, 0, "Forte di Tiragarde"},
                {0, 0, "Terre dei Chiomaguzza"},
                {0, 0, "Gola di Fossosecco"},
                {0, 0, "Orgrimmar"},
            },
        },
        ["Teldrassil"] = {
            achievementID = 842,
            proxyLocation = {0, 0, "Teldrassil"},
            waypoints = {
                {0, 0, "Vallombra"},
                {0, 0, "Dolanaar"},
                {0, 0, "Accampamento dei Mordipigna"},
                {0, 0, "Pozze di Arlithrien"},
                {0, 0, "Radura dell'Oracolo"},
                {0, 0, "Darnassus"},
                {0, 0, "Faglia Infida"},
                {0, 0, "Vallata di Ban'ethil"},
                {0, 0, "Lago Al'ameth"},
                {0, 0, "Brezzastella"},
                {0, 0, "Lago di Buonpozzo"},
                {0, 0, "Rut'theran"},
            },
        },
        ["Savane Settentrionali"] = {
            achievementID = 750,
            proxyLocation = {0, 0, "Savane Settentrionali"},
            waypoints = {
                {0, 0, "Miniera di Pietravera"},
                {0, 0, "Bastione di Mor'shan"},
                {0, 0, "Picco di Brumafunesta"},
                {0, 0, "Sorgenti Dimenticate"},
                {0, 0, "Presidio Lungosguardo"},
                {0, 0, "Crocevia"},
                {0, 0, "Porto Paranco"},
                {0, 0, "Oasi Acquefertili"},
                {0, 0, "Palude Fangosa"},
                {0, 0, "Colli Aridi"},
                {0, 0, "Fattoria di Grol'dom"},
                {0, 0, "Colli Spinosi"},
                {0, 0, "Oasi Stagnante"},
                {0, 0, "Costa dei Mercanti"},
            },
        },
        ["Savane Meridionali"] = {
            achievementID = 4996,
            proxyLocation = {0, 0, "Savane Meridionali"},
            waypoints = {
                {0, 0, "Bael Modan"},
                {0, 0, "Comando Avanzato"},
                {0, 0, "Bastione dell'Onore"},
                {0, 0, "Fortezza dei Custodi del Nord"},
                {0, 0, "Rovine di Taurajo"},
                {0, 0, "Presidio Vendetta"},
                {0, 0, "Fossa di Guerra"},
                {0, 0, "Campo Minerario di Vangastorta"},
                {0, 0, "Colle del Cacciatore"},
                {0, 0, "Gallerie di Lamaspina"},
                {0, 0, "Labirinto Verde"},
            },
        },
        ["l'Isola Brumacremisi"] = {
            achievementID = 861,
            proxyLocation = {0, 0, "l'Isola Brumacremisi"},
            waypoints = {
                {0, 0, "Passo Tela d'Ambra"},
                {0, 0, "Riva dei Sabbianera"},
                {0, 0, "Isola di Sangue Dannato"},
                {0, 0, "Enclave dei Braccioirsuto"},
                {0, 0, "Val Lorda"},
                {0, 0, "Nazzivian"},
                {0, 0, "Rovine di Loreth'aran"},
                {0, 0, "Accampamento di Tel'athion"},
                {0, 0, "Riva dei Fiottorosso"},
                {0, 0, "Nucleo Criogenico"},
                {0, 0, "Scogliera Celata"},
                {0, 0, "Bobina di Alimentazione"},
                {0, 0, "Capo Veridiano"},
                {0, 0, "Santuario degli Scagliarabbiosa"},
                {0, 0, "Axxarien"},
                {0, 0, "Selva Tagliente"},
                {0, 0, "Presidio Vermiglio"},
                {0, 0, "Crocicchio di Kessel"},
                {0, 0, "Bosco Brumo"},
                {0, 0, "Cresta di Piumadura"},
                {0, 0, "Colle Artiglio"},
                {0, 0, "Scogliera di Sangue Dannato"},
                {0, 0, "Litorale del Sangue"},
                {0, 0, "Bacino Infetto"},
                {0, 0, "Rottami Dispersi"},
                {0, 0, "Pistone di Distorsione"},
                {0, 0, "Riposo del Vendicatore"},
                {0, 0, "Isola di Fendragone"},
            },
        },
        ["Millepicchi"] = {
            achievementID = 846,
            proxyLocation = {0, 0, "Millepicchi"},
            waypoints = {
                {0, 0, "Grande Ascensore"},
                {0, 0, "Scavi Sommersi"},
                {0, 0, "Radura del Crepuscolo"},
                {0, 0, "Vetta Occidentale"},
                {0, 0, "Presidio di Ventolibero"},
                {0, 0, "Profondità Salate"},
                {0, 0, "Sotterranei di Lamaspina"},
                {0, 0, "Presidio dei Mari del Sud"},
                {0, 0, "Baluardo del Crepuscolo"},
                {0, 0, "Pinnacolo Nubenera"},
                {0, 0, "Alture di Zoccolo Spezzato"},
                {0, 0, "Covoalto"},
            },
        },
        ["Desolanda"] = {
            achievementID = 848,
            proxyLocation = {0, 0, "Desolanda"},
            waypoints = {
                {0, 0, "Tethris Aran"},
                {0, 0, "Presidio di Nijel"},
                {0, 0, "Fortezza Ascia del Tuono"},
                {0, 0, "Territorio dei Magram"},
                {0, 0, "Valle delle Lance"},
                {0, 0, "Predombra"},
                {0, 0, "Congrega di Mannoroc"},
                {0, 0, "Gola delle Ombre Infrante"},
                {0, 0, "Bivacco di Thargad"},
                {0, 0, "Sargeron"},
                {0, 0, "Terre Fertili Cenariane"},
                {0, 0, "Isola di Ranazjar"},
                {0, 0, "Cimitero dei Kodo"},
                {0, 0, "Villaggio dei Gelkis"},
                {0, 0, "Shok'Thokar"},
                {0, 0, "Spiaggia dei Lamasalmastra"},
            },
        },
        ["Feralas"] = {
            achievementID = 849,
            proxyLocation = {0, 0, "Feralas"},
            waypoints = {
                {0, 0, "Bassopiano Selvaggio"},
                {0, 0, "Colossi Gemelli"},
                {0, 0, "Maglio Infausto"},
                {0, 0, "Rovine di Isildien"},
                {0, 0, "Accampamento Mojache"},
                {0, 0, "Avamposto dei Gordunni"},
                {0, 0, "Roccaforte di Piumaluna"},
                {0, 0, "Rovine di Piumaluna"},
                {0, 0, "Costa dell'Oblio"},
                {0, 0, "Valsfregiata"},
                {0, 0, "Fossa Fremente"},
                {0, 0, "Insediamento dei Totem Truce"},
                {0, 0, "Rovine di Brumafosca"},
            },
        },
        ["Azshara"] = {
            achievementID = 852,
            proxyLocation = {0, 0, "Azshara"},
            waypoints = {
                {0, 0, "Palazzo dei Piaceri di Gallywix"},
                {0, 0, "Porto degli Acqualorda"},
                {0, 0, "Torre di Eldara"},
                {0, 0, "Campo Base Darnassiano"},
                {0, 0, "Testa d'Orso"},
                {0, 0, "Ingresso Posteriore di Orgrimmar"},
                {0, 0, "Spiaggia Costa del Sud"},
                {0, 0, "Lago Mennar"},
                {0, 0, "Scogliere della Tempesta"},
                {0, 0, "Costa Infranta"},
                {0, 0, "Lande Amare"},
                {0, 0, "Rovine di Arkkoran"},
                {0, 0, "Laboratorio Segreto"},
                {0, 0, "Tana degli Zannanera"},
                {0, 0, "Rovine di Eldarath"},
                {0, 0, "Colosso di Crinocorvo"},
                {0, 0, "Confini Spezzati"},
            },
        },
        ["il Cratere di Un'Goro"] = {
            achievementID = 854,
            proxyLocation = {0, 0, "il Cratere di Un'Goro"},
            waypoints = {
                {0, 0, "Rilievo del Magma Colante"},
                {0, 0, "Accampamento dei Grant"},
                {0, 0, "Giardini Torbidi"},
                {0, 0, "Sorgenti Calde di Golakka"},
                {0, 0, "Anfratto Brulicante"},
                {0, 0, "Altopiano Pietradura"},
                {0, 0, "Roccia del Fungo"},
                {0, 0, "Tumulo Muschioso"},
                {0, 0, "Confini Urlanti"},
                {0, 0, "Landa del Terrore"},
                {0, 0, "Acquitrini Selvaggi"},
                {0, 0, "Pozze di Pece di Lakkari"},
            },
        },
        ["Silitus"] = {
            achievementID = 856,
            proxyLocation = {0, 0, "Silitus"},
            waypoints = {
                {0, 0, "Valle di Cristallo"},
                {0, 0, "Fortezza Cenariana"},
                {0, 0, "Alveare Regal"},
                {0, 0, "Alveare Ashi"},
                {0, 0, "Vento del Sud"},
                {0, 0, "Alveare Zora"},
                {0, 0, "Vallo dello Scarabeo"},
                {0, 0, "Asilo dei Valorosi"},
            },
        },
        ["Mulgore"] = {
            achievementID = 736,
            proxyLocation = {0, 0, "Mulgore"},
            waypoints = {
                {0, 0, "Mesa Nuvola Rossa"},
                {0, 0, "Villaggio di Zoccolo Sanguinario"},
                {0, 0, "Piana Ondulata"},
                {0, 0, "Carovana Depredata"},
                {0, 0, "Pozzo dei Corno Tonante"},
                {0, 0, "Massi Rossi"},
                {0, 0, "Pozzo dei Manto Selvaggio"},
                {0, 0, "Roccia dei Mantopallido"},
                {0, 0, "Pozzo degli Zoccolo Artico"},
                {0, 0, "Miniera della S.P.R. & Co."},
                {0, 0, "Piana Dorata"},
                {0, 0, "Scavi di Bael'dun"},
                {0, 0, "Dorsale delle Furie del Vento"},
            },
        },
        ["l'Isola Brumazzurra"] = {
            achievementID = 860,
            proxyLocation = {0, 0, "l'Isola Brumazzurra"},
            waypoints = {
                {0, 0, "Valle di Ammen"},
                {0, 0, "Presidio Azzurro"},
                {0, 0, "Radura Ardente"},
                {0, 0, "Accampamento di Geezle"},
                {0, 0, "Approdo di Odesyus"},
                {0, 0, "Capsula Distrutta"},
                {0, 0, "Isola di Brumargento"},
                {0, 0, "Exodar"},
                {0, 0, "Capo degli Scagliarabbiosa"},
                {0, 0, "Guado di Ammen"},
                {0, 0, "Villaggio dei Braccioirsuto"},
                {0, 0, "Riva di Pontevecchio"},
                {0, 0, "Selvaluna"},
                {0, 0, "Capsula di Salvataggio"},
                {0, 0, "Costa Limacciosa"},
                {0, 0, "Rifugio dei Pinosaldo"},
                {0, 0, "Ormeggio di Valaar"},
            },
        },
        ["Fontefredda"] = {
            achievementID = 857,
            proxyLocation = {0, 0, "Fontefredda"},
            waypoints = {
                {0, 0, "Sorgenti di Fuocogelo"},
                {0, 0, "Lago Kel'Theril"},
                {0, 0, "Mazthoril"},
                {0, 0, "Selva Ala di Gufo"},
                {0, 0, "Villaggio dei Freddinverno"},
                {0, 0, "Roccia delle Fiere Glaciali"},
                {0, 0, "Accampamento dei Mordilegno"},
                {0, 0, "Padiglione Pioggia di Stelle"},
                {0, 0, "Lungavista"},
                {0, 0, "Colline dei Cardighiaccio"},
                {0, 0, "Boschetto Segreto"},
                {0, 0, "Gola Eco Freddo"},
            },
        },
        ["Rivafosca"] = {
            achievementID = 844,
            proxyLocation = {0, 0, "Rivafosca"},
            waypoints = {
                {0, 0, "Rovine di Auberdine"},
                {0, 0, "Campo di Guerra dei Lanciarotta"},
                {0, 0, "Boschetto Avvizzito"},
                {0, 0, "Occhio del Vortice"},
                {0, 0, "Lor'danel"},
                {0, 0, "Gladio del Maestro"},
                {0, 0, "Valle dei Lanciarotta"},
                {0, 0, "Fiume Lettocurvo"},
                {0, 0, "Rovine di Mathystra"},
                {0, 0, "Ameth'aran"},
                {0, 0, "Nazj'vel"},
            },
        },
        ["Valtetra"] = {
            achievementID = 845,
            proxyLocation = {0, 0, "Valtetra"},
            waypoints = {
                {0, 0, "Spiaggia di Zoram"},
                {0, 0, "Rifugio Vento Argentato"},
                {0, 0, "Lago Falathim"},
                {0, 0, "Villaggio dei Mantocardo"},
                {0, 0, "Astranaar"},
                {0, 0, "Valle Ululante"},
                {0, 0, "Lago Cielinfranto"},
                {0, 0, "Satirnaar"},
                {0, 0, "Campo di Taglio dei Cantaguerra"},
                {0, 0, "Rifugio di Orendil"},
                {0, 0, "Vetta del Tuono"},
                {0, 0, "Accampamento di Maestra"},
                {0, 0, "Santuario di Aessina"},
                {0, 0, "Rovine della Polvere Stellare"},
                {0, 0, "Rifugio di Legnovivo"},
                {0, 0, "Avamposto di Troncorotto"},
                {0, 0, "Frondascura"},
                {0, 0, "Colle Vilfuoco"},
            },
        },
        ["Vette di Petrartiglio"] = {
            achievementID = 847,
            proxyLocation = {0, 0, "Vette di Petrartiglio"},
            waypoints = {
                {0, 0, "Valle della Fossa di Guerra"},
                {0, 0, "Rovine di Eldre'thar"},
                {0, 0, "Terre Dissotterrate"},
                {0, 0, "Bastione di Tagliavento"},
                {0, 0, "Malaka'jin"},
                {0, 0, "Gola dei Franamassi"},
                {0, 0, "Landa di Tagliavento"},
                {0, 0, "Valle Bruciata"},
                {0, 0, "Picco di Petrartiglio"},
                {0, 0, "Fortezza di Krom'gar"},
                {0, 0, "Presidio di Thal'darah"},
                {0, 0, "Valle di Passocurvo"},
                {0, 0, "Accampamento dei Cavalca Rupe"},
                {0, 0, "Sentiero Passocurvo"},
                {0, 0, "Valle Grandalbero"},
                {0, 0, "Rifugio Roccia del Sole"},
                {0, 0, "Lago Mirkfallon"},
            },
        },
        ["Acquemorte"] = {
            achievementID = 850,
            proxyLocation = {0, 0, "Acquemorte"},
            waypoints = {
                {0, 0, "Isola di Theramore"},
                {0, 0, "Accampamento Corno Furente"},
                {0, 0, "Locanda Ombracalma"},
                {0, 0, "Felcimura"},
                {0, 0, "Isola di Alcaz"},
                {0, 0, "Villaggio di Zoccolo Nero"},
                {0, 0, "Melmarmitta"},
                {0, 0, "Costa di Acquatruce"},
                {0, 0, "Brago dei Dragoni"},
            },
        },
        ["Tanaris"] = {
            achievementID = 851,
            proxyLocation = {0, 0, "Tanaris"},
            waypoints = {
                {0, 0, "Meccania"},
                {0, 0, "Valle dei Guardiani"},
                {0, 0, "Sabbie Abissali"},
                {0, 0, "Antro Venefico"},
                {0, 0, "Spiaggia della Risacca"},
                {0, 0, "Rovine di Luna dell'Est"},
                {0, 0, "Rovine di Luna del Sud"},
                {0, 0, "Zul'farrak"},
                {0, 0, "Osservatorio di Sabbiamesta"},
                {0, 0, "Cala del Sartiame"},
                {0, 0, "Pilastro Spezzato"},
                {0, 0, "Insediamento dei Mazzaduna"},
                {0, 0, "Abisso Golaperta"},
                {0, 0, "Ultima Spiaggia"},
                {0, 0, "Valle dei Cardosecco"},
                {0, 0, "Caverne del Tempo"},
            },
        },
        ["Vilbosco"] = {
            achievementID = 853,
            proxyLocation = {0, 0, "Vilbosco"},
            waypoints = {
                {0, 0, "Villaggio di Vilzampa"},
                {0, 0, "Bosco di Troncoferro"},
                {0, 0, "Valle dei Crateri Infernali"},
                {0, 0, "Jaedenar"},
                {0, 0, "Valle dei Giadafulgida"},
                {0, 0, "Villaggio dei Legnomorto"},
                {0, 0, "Radura di Ramocurvo"},
                {0, 0, "Bivacco dei Giadafulgida"},
                {0, 0, "Cascate Sanguemarcio"},
                {0, 0, "Rovine di Constellas"},
                {0, 0, "Santuario di Smeraldo"},
                {0, 0, "Morlos'aran"},
            },
        },
        ["Radaluna"] = {
            achievementID = 855,
            proxyLocation = {0, 0, "Radaluna"},
            waypoints = {
                {0, 0, "Lago Elune'ara"},
                {0, 0, "Santuario di Remulos"},
                {0, 0, "Nottequieta"},
                {0, 0, "Eremi di Grantempesta"},
            },
        },
    },  -- World of Warcraft (Vanilla)
    ["Nordania"] = {
        ["Tundra Boreale"] = {
            achievementID = 1264,
            proxyLocation = {0, 0, "Tundra Boreale"},
            waypoints = {
                {0, 0, "Acropoli di En'kilah"},
                {0, 0, "Sponda degli Sferzalama"},
                {0, 0, "Approdo di Garrosh"},
                {0, 0, "Ibernia"},
                {0, 0, "Scogliera d'Ambra"},
                {0, 0, "Forte degli Arditi"},
                {0, 0, "Antro del Trapasso"},
                {0, 0, "Carovana di Mordiferro"},
                {0, 0, "Kaskala"},
                {0, 0, "Presidio del Sacrificio"},
                {0, 0, "Avamposto di Bor'gorok"},
                {0, 0, "Forte dei Cantaguerra"},
                {0, 0, "Solfatare"},
            },
        },
        ["Dracombra"] = {
            achievementID = 1265,
            proxyLocation = {0, 0, "Dracombra"},
            waypoints = {
                {0, 0, "Fossa di Galakrond"},
                {0, 0, "Santuario dei Draghi di Ossidiana"},
                {0, 0, "Naxxramas"},
                {0, 0, "Foscogelo"},
                {0, 0, "Alture di Ventogelido"},
                {0, 0, "Martello di Agmar"},
                {0, 0, "Campo Profughi di Ventoponente"},
                {0, 0, "Riva dell'Oblio"},
                {0, 0, "Avamposto Scarlatto"},
                {0, 0, "Lago Indu'le"},
                {0, 0, "Nuova Valsalda"},
                {0, 0, "Speranza di Luce"},
                {0, 0, "Santuario dei Draghi di Smeraldo"},
                {0, 0, "Angrathar, Cancello dell'Ira"},
                {0, 0, "Tempio della Lega dei Draghi"},
                {0, 0, "Venefica"},
                {0, 0, "Morsa di Cristallo"},
            },
        },
        ["Zul'drak"] = {
            achievementID = 1267,
            proxyLocation = {0, 0, "Zul'drak"},
            waypoints = {
                {0, 0, "Gundrak"},
                {0, 0, "Anfiteatro del Tormento"},
                {0, 0, "Altare di Rhunok"},
                {0, 0, "Altare di Mam'toth"},
                {0, 0, "Zim'Torga"},
                {0, 0, "Voltarus"},
                {0, 0, "Breccia della Luce"},
                {0, 0, "Campi di Drak'Sotra"},
                {0, 0, "Altare di Sseratus"},
                {0, 0, "Altare di Quetz'lun"},
                {0, 0, "Altare di Har'koa"},
                {0, 0, "Zeramas"},
                {0, 0, "Riposo di Thrym"},
                {0, 0, "Kolramas"},
            },
        },
        ["Foresta di Cristallo"] = {
            achievementID = 1457,
            proxyLocation = {0, 0, "Foresta di Cristallo"},
            waypoints = {
                {0, 0, "Fronte Azzurro"},
                {0, 0, "Comando dei Predatori del Sole"},
                {0, 0, "Osservatorio dei Ventolesto"},
                {0, 0, "Baluardo Violaceo"},
                {0, 0, "Bacino Decrepito"},
                {0, 0, "Selva Triste"},
                {0, 0, "Grande Albero"},
                {0, 0, "Boscostile"},
            },
        },
        ["Corona di Ghiaccio"] = {
            achievementID = 1270,
            proxyLocation = {0, 0, "Corona di Ghiaccio"},
            waypoints = {
                {0, 0, "Zona di Bombardamento"},
                {0, 0, "Porto delle Furie"},
                {0, 0, "Officina della Carne"},
                {0, 0, "Fossa di Sindragosa"},
                {0, 0, "Valle degli Echi"},
                {0, 0, "Deflagrazione delle Fiamme"},
                {0, 0, "Jotunheim"},
                {0, 0, "Volta dell'Ombra"},
                {0, 0, "Rocca della Corona di Ghiaccio"},
                {0, 0, "Il Fronte Spezzato"},
                {0, 0, "Aldur'thar, Cancello della Desolazione"},
                {0, 0, "Valhalas"},
                {0, 0, "Ymirheim"},
                {0, 0, "Corp'rethar, Cancello dell'Orrore"},
                {0, 0, "Bastioni del Flagello"},
            },
        },
        ["il Fiordo Echeggiante"] = {
            achievementID = 1263,
            proxyLocation = {0, 0, "il Fiordo Echeggiante"},
            waypoints = {
                {0, 0, "Kamagua"},
                {0, 0, "Accampamento degli Zoccolo Artico"},
                {0, 0, "Attracco della Vendetta"},
                {0, 0, "Capo di Granfurto"},
                {0, 0, "Gjalerbron"},
                {0, 0, "Percorso dei Giganti"},
                {0, 0, "Rovine di Ivald"},
                {0, 0, "Nuova Agamand"},
                {0, 0, "Radura Contorta"},
                {0, 0, "Forte di Guardia dell'Ovest"},
                {0, 0, "Baleheim"},
                {0, 0, "Isola Cauldros"},
                {0, 0, "Accampamento dello Speziale"},
                {0, 0, "Chiusa d'Acciaio"},
                {0, 0, "Nifflevar"},
                {0, 0, "Selvardente"},
                {0, 0, "Fortilizio di Wildervar"},
                {0, 0, "Halgrind"},
                {0, 0, "Skorn"},
                {0, 0, "Forte Utgarde"},
                {0, 0, "Scavi di Baelgun"},
            },
        },
        ["i Colli Bradi"] = {
            achievementID = 1266,
            proxyLocation = {0, 0, "i Colli Bradi"},
            waypoints = {
                {0, 0, "Fortezza della Conquista"},
                {0, 0, "Rovine di Drakil'jin"},
                {0, 0, "Accampamento Mezzapozza"},
                {0, 0, "Santuario di Fauce Rabbiosa"},
                {0, 0, "Baia della S.P.R. & Co."},
                {0, 0, "Rifugio di Pinambrato"},
                {0, 0, "Accampamento Oneqwah"},
                {0, 0, "Forte di Drak'Tharon"},
                {0, 0, "Dun Argol"},
                {0, 0, "Faucebigia"},
                {0, 0, "Thor Modan"},
                {0, 0, "Voldrune"},
                {0, 0, "Campo di Taglio di Ciel Sereno"},
                {0, 0, "Presidio Brigata delle Marche"},
            },
        },
        ["il Bacino di Sholazar"] = {
            achievementID = 1268,
            proxyLocation = {0, 0, "il Bacino di Sholazar"},
            waypoints = {
                {0, 0, "Cuordifiume"},
                {0, 0, "Pilastro del Muschio Brillante"},
                {0, 0, "Riparo dei Creatori"},
                {0, 0, "Villaggio di Cantapioggia"},
                {0, 0, "Grande Slavina"},
                {0, 0, "Palizzata di Kartak"},
                {0, 0, "Selva Rovente"},
                {0, 0, "Loggia dei Creatori"},
                {0, 0, "Pilastro del Sole"},
                {0, 0, "Pilastro della Vita"},
                {0, 0, "Pilastro dei Cristalli"},
                {0, 0, "Altopiano della Tempesta Selvaggia"},
            },
        },
        ["Cime Tempestose"] = {
            achievementID = 1269,
            proxyLocation = {0, 0, "Cime Tempestose"},
            waypoints = {
                {0, 0, "Brunnhildar"},
                {0, 0, "Dun Niffelem"},
                {0, 0, "Valkyrion"},
                {0, 0, "Campo Minato di Sprizzascintille"},
                {0, 0, "Tempio della Vita"},
                {0, 0, "Impietrituono"},
                {0, 0, "Piana di Fluttaneve"},
                {0, 0, "Fortegelo"},
                {0, 0, "Impalcatura di Narvir"},
                {0, 0, "Forra di Bor"},
                {0, 0, "Terrazza dei Creatori"},
                {0, 0, "Motrice dei Creatori"},
                {0, 0, "Ulduar"},
                {0, 0, "Tempio delle Tempeste"},
                {0, 0, "Sbarramento di Garm"},
                {0, 0, "Nidavelir"},
            },
        },
    }, -- Wrath of the Lich King
    ["Pandaria"] = {
        ["Foresta di Giada"] = {
            achievementID = 6351,
            proxyLocation = {0, 0, "Foresta di Giada"},
            waypoints = {
                {0, 0, "Monastero Tian"},
                {0, 0, "Padiglione del Sognatore"},
                {0, 0, "Lago Vitreo"},
                {0, 0, "Cava di Pietraverde"},
                {0, 0, "Accampamento Nuga Nuga"},
                {0, 0, "Cuore della Serpe"},
                {0, 0, "Tempio della Serpe di Giada"},
                {0, 0, "Approdo Garrosh'ar"},
                {0, 0, "Dolcemiele"},
                {0, 0, "Alba Fiorita"},
                {0, 0, "Presagio dell'Imperatore"},
                {0, 0, "Colle dei Gruggatori"},
                {0, 0, "Frutteto Dolce Brezza"},
                {0, 0, "Terrazza dei Dieci Tuoni"},
                {0, 0, "Fosse dei Codalesta"},
                {0, 0, "Arboreto"},
                {0, 0, "Isola di Guardiavento"},
            },
        },
        ["Giungla di Krasarang"] = {
            achievementID = 6975,
            proxyLocation = {0, 0, "Giungla di Krasarang"},
            waypoints = {
                {0, 0, "Palafitte dei Lancialenza"},
                {0, 0, "Fiume Dojani"},
                {0, 0, "Baia di Krasarang"},
                {0, 0, "Laguna Nayeli"},
                {0, 0, "Rovine di Dojan"},
                {0, 0, "Tempio della Gru Rossa"},
                {0, 0, "Foresta Proibita"},
                {0, 0, "Unga Ingu"},
                {0, 0, "Culla di Chi-Ji"},
                {0, 0, "Acquamantra"},
                {0, 0, "Rovine Krasari"},
                {0, 0, "Bivacco della Gru Selvaggia"},
                {0, 0, "Rovine di Korja"},
                {0, 0, "Selvafonda"},
                {0, 0, "Isole Meridionali"},
                {0, 0, "Baluardo di Zhu"},
            },
        },
        ["Steppe di Tong Long"] = {
            achievementID = 6977,
            proxyLocation = {0, 0, "Steppe di Tong Long"},
            waypoints = {
                {0, 0, "Fronte di Gao-Ran"},
                {0, 0, "Posto di Guardia di Rensai"},
                {0, 0, "Presidio del Fuoco Osul"},
                {0, 0, "Guarnigione degli Shandaren"},
                {0, 0, "Sik'vess"},
                {0, 0, "Acquitrini"},
                {0, 0, "Kri'vess"},
                {0, 0, "Tempio di Niuzao"},
                {0, 0, "Morsa dell'Odio"},
                {0, 0, "Shan'ze Dao"},
                {0, 0, "Sra'vess"},
            },
        },
        ["Vallata dell'Eterna Primavera"] = {
            achievementID = 6979,
            proxyLocation = {0, 0, "Vallata dell'Eterna Primavera"},
            waypoints = {
                {0, 0, "Rovine di Guo-Lai"},
                {0, 0, "Palazzo Mogu'shan"},
                {0, 0, "Scalinata Dorata"},
                {0, 0, "Pagoda Dorata"},
                {0, 0, "Santuario delle Due Lune"},
                {0, 0, "Cinque Sorelle"},
                {0, 0, "Calanebbia"},
                {0, 0, "Guarnigione del Sole Calante"},
                {0, 0, "Santuario delle Sette Stelle"},
                {0, 0, "Tumulo di Tu Shen"},
                {0, 0, "Lago del Petalo Bianco"},
            },
        },
        ["Valle dei Quattro Venti"] = {
            achievementID = 6969,
            proxyLocation = {0, 0, "Valle dei Quattro Venti"},
            waypoints = {
                {0, 0, "Limitare del Vento"},
                {0, 0, "Acquitrino Dorato"},
                {0, 0, "Mezzocolle"},
                {0, 0, "Villaggio dei Kunzen"},
                {0, 0, "Bivacco di Nesingwary"},
                {0, 0, "Stagni della Purezza"},
                {0, 0, "Bottega dei Mastri Setai"},
                {0, 0, "Birrificio Triplo Malto"},
                {0, 0, "Tenuta dei Palmo Tonante"},
                {0, 0, "Gola dei Pellebrulla"},
                {0, 0, "Granaio Imperiale"},
                {0, 0, "Arapietra"},
                {0, 0, "Casale di Pintapalta"},
                {0, 0, "Rifugio di Paoquan"},
                {0, 0, "Terrazza Rombante"},
                {0, 0, "Paludi Risonanti"},
                {0, 0, "Cuorflorido"},
                {0, 0, "Pendio di Zhu"},
            },
        },
        ["il Massiccio del Kun-Lai"] = {
            achievementID = 6976,
            proxyLocation = {0, 0, "il Massiccio del Kun-Lai"},
            waypoints = {
                {0, 0, "Binan"},
                {0, 0, "Porta dei Venerabili Celestiali"},
                {0, 0, "Picco Kota"},
                {0, 0, "Monte Neverest"},
                {0, 0, "Picco della Serenità"},
                {0, 0, "Tempio della Tigre Bianca"},
                {0, 0, "Valle degli Imperatori"},
                {0, 0, "Radura di Bosco Ardente"},
                {0, 0, "Isola della Ricerca"},
                {0, 0, "Mogujia"},
                {0, 0, "Tenuta di Palmo Muschioso"},
                {0, 0, "Monastero degli Shandaren"},
                {0, 0, "Sentiero della Iuta"},
                {0, 0, "Zouchin"},
            },
        },
        ["Distese del Terrore"] = {
            achievementID = 6978,
            proxyLocation = {0, 0, "Distese del Terrore"},
            waypoints = {
                {0, 0, "Cuore della Paura"},
                {0, 0, "Kypari Vor"},
                {0, 0, "Rikkitun"},
                {0, 0, "Terrazza dei Gurthan"},
                {0, 0, "Artigli di Shek'zeer"},
                {0, 0, "Boscotorto"},
                {0, 0, "Klaxxi'vess"},
                {0, 0, "Kypari Zar"},
                {0, 0, "Azzardo di Libeccio"},
                {0, 0, "Acquitrino Salmastro"},
                {0, 0, "Resinificio del Tramonto"},
                {0, 0, "Zan'vess"},
            },
        },
    }, -- Mists of Pandaria
    ["Isole Disperse"] = {
        ["Azsuna"] = {
            achievementID = 10665,
            proxyLocation = {0, 0, "Azsuna"},
            waypoints = {
                {0, 0, "Faronaar"},
                {0, 0, "Verdevia"},
                {0, 0, "Altopiano di Llothien"},
                {0, 0, "Nar'thalas"},
                {0, 0, "Santuario in Rovina"},
                {0, 0, "Faglia delle Rovine di Zarkhenar"},
                {0, 0, "Soglia della Vilfiamma"},
                {0, 0, "Isola delle Custodi"},
                {0, 0, "Frutteto Disperso"},
                {0, 0, "Baia di Oceanus"},
                {0, 0, "Tempio delle Luci"},
            },
        },
        ["Alto Monte"] = {
            achievementID = 10667,
            proxyLocation = {0, 0, "Alto Monte"},
            waypoints = {
                {0, 0, "Alture Cacciasangue"},
                {0, 0, "Presidio Zoccolo Gelido"},
                {0, 0, "Torre dei Guardiani della Notte"},
                {0, 0, "Rivocurvo"},
                {0, 0, "Baia dei Relitti"},
                {0, 0, "Presidio Zoccolo Granitico"},
                {0, 0, "Totem del Fulmine"},
                {0, 0, "Acquitrini Ciechi"},
                {0, 0, "Enclave dei Corno Ferreo"},
                {0, 0, "Bacino Pignadura"},
                {0, 0, "Riviera delle Rocce Perdute"},
                {0, 0, "Corno Celeste"},
                {0, 0, "Cascate Silvane"},
                {0, 0, "Rifugio Tirosaldo"},
            },
        },
        ["Suramar"] = {
            achievementID = 10669,
            proxyLocation = {0, 0, "Suramar"},
            waypoints = {
                {0, 0, "Valambrata"},
                {0, 0, "Falanaar"},
                {0, 0, "Gran Terrazza"},
                {0, 0, "Forte delle Guardie della Luna"},
                {0, 0, "Rovine di Elun'eth"},
                {0, 0, "Tel'anor"},
                {0, 0, "Bosco Cremisi"},
                {0, 0, "Forte Vilanima"},
                {0, 0, "Jandvik"},
                {0, 0, "Burrone dei Soffialuna"},
                {0, 0, "Suramar"},
            },
        },
        ["Val'sharah"] = {
            achievementID = 10666,
            proxyLocation = {0, 0, "Val'sharah"},
            waypoints = {
                {0, 0, "Andutalah"},
                {0, 0, "Rivofosco"},
                {0, 0, "Scogliera del Tramonto"},
                {0, 0, "Lorlathil"},
                {0, 0, "Vallata degli Zannaluna"},
                {0, 0, "Radura dei Pelleardente"},
                {0, 0, "Thas'talah"},
                {0, 0, "Forte Corvonero"},
                {0, 0, "Bosco dei Sogni"},
                {0, 0, "Boschetto di Cenarius"},
                {0, 0, "Vallebruma"},
                {0, 0, "Shala'nir"},
                {0, 0, "Tempio di Elune"},
            },
        },
        ["Stromheim"] = {
            achievementID = 10668,
            proxyLocation = {0, 0, "Stromheim"},
            waypoints = {
                {0, 0, "Cripta di Aggramar"},
                {0, 0, "Approdo dei Destamorte"},
                {0, 0, "Presidio Grigio"},
                {0, 0, "Haustvald"},
                {0, 0, "Fauci di Nashal"},
                {0, 0, "Nastrondir"},
                {0, 0, "Selvarunica"},
                {0, 0, "Skold-Ashil"},
                {0, 0, "Riposo dell'Artiglio"},
                {0, 0, "Valdisdall"},
                {0, 0, "Promontorio di Becconero"},
                {0, 0, "Dreyrgrot"},
                {0, 0, "Cancelli del Valore"},
                {0, 0, "Hrydshal"},
                {0, 0, "Morheim"},
                {0, 0, "Roccia del Sorvegliante"},
                {0, 0, "Riposo dello Scudo"},
                {0, 0, "Presa della Tempesta"},
                {0, 0, "Porto degli Abiskorn"},
                {0, 0, "Rupi Piangenti"},
            },
        },
    }, -- Legion
    -- Continents dictionary ...
    ["Continents"] = {
        ["Eastern Kingdoms"] = "Regni Orientali",
        ["Outland"] = "Terre Esterne",
        ["Cataclysm"] = "Cataclisma", -- Hyjal, Uldum, Deepholm, Twillight Highlands, Vashj'ir
        ["Draenor"] = "Draenor",
        ["Battle for Azeroth"] = "Battaglia per Azeroth", -- Zandalar and Kul Tiras
        ["Kalimdor"] = "Kalimdor",
        ["Northrend"] = "Nordania",
        ["Pandaria"] = "Pandaria",
        ["Broken Isles"] = "Isole Disperse",
    }
}