Localization = Localization or {}

Localization["ptBR"] = {
    ["Reinos do Leste"] = {
        ["Floresta de Elwynn"] = {
            achievementID = 776,
            proxyLocation = {0, 0, "Floresta de Elwynn"},
            waypoints = {
                {0, 0, "Vale de Vila Norte"},
                {0, 0, "Vila d'Ouro"},
                {0, 0, "Ancoradouro de Jerod"},
                {0, 0, "Plantação de Abóboras dos Braga"},
                {0, 0, "Torre Serrana"},
                {0, 0, "Lago do Monumento"},
                {0, 0, "Guarnição da Ribeira d'Oeste"},
                {0, 0, "Mina Vailafundo"},
                {0, 0, "Torre de Azora"},
                {0, 0, "Madeireira Vale do Leste"},
                {0, 0, "Lago de Cristal"},
            },
        },
        ["Ermos"] = {
            achievementID = 765,
            proxyLocation = {0, 0, "Ermos"},
            waypoints = {
                {0, 0, "Ravina Lethlor"},
                {0, 0, "Uldaman"},
                {0, 0, "Cicatriz do Quebramundo"},
                {0, 0, "Fortaleza Angor"},
                {0, 0, "Posto Vigília de Sangue"},
                {0, 0, "Ruína de Agmundo"},
                {0, 0, "Acampamento Cang"},
                {0, 0, "Terrasseca"},
                {0, 0, "Acampamento Kosh"},
                {0, 0, "Nova Karrath"},
            },
        },
        ["Estepes Ardentes"] = {
            achievementID = 775,
            proxyLocation = {0, 0, "Estepes Ardentes"},
            waypoints = {
                {0, 0, "Rochedo Malhorrendo"},
                {0, 0, "Vale Asa do Terror"},
                {0, 0, "Ruínas de Thaurissan"},
                {0, 0, "Fortaleza Rocha Negra"},
                {0, 0, "Altar das Tempestades"},
                {0, 0, "Vigia de Morgan"},
                {0, 0, "Estreito Rocha Negra"},
                {0, 0, "Casebre Dente Preto"},
                {0, 0, "Colina dos Dragonetes"},
                {0, 0, "Montanha Rocha Negra"},
            },
        },
        ["Floresta do Crepúsculo"] = {
            achievementID = 778,
            proxyLocation = {0, 0, "Floresta do Crepúsculo"},
            waypoints = {
                {0, 0, "Margem Silenciada"},
                {0, 0, "Monte Corvo"},
                {0, 0, "Gruta de Vul'Gol"},
                {0, 0, "Fazenda dos Figueira"},
                {0, 0, "O Horto Pútrido"},
                {0, 0, "Vila Sombria"},
                {0, 0, "Margem Escurecida"},
                {0, 0, "Quinta dos Aguiar"},
                {0, 0, "Cemitério de Monte Corvo"},
                {0, 0, "Bosque do Crepúsculo"},
                {0, 0, "Bosque Brilhante"},
                {0, 0, "Cemitério Jardins da Paz"},
                {0, 0, "Casarão dos Brumanto"},
            },
        },
        ["Loch Modan"] = {
            achievementID = 779,
            proxyLocation = {0, 0, "Loch Modan"},
            waypoints = {
                {0, 0, "Loch"},
                {0, 0, "Fortaleza Mo'grosh"},
                {0, 0, "Desfiladeiro do Portão Norte"},
                {0, 0, "Sítio de Escavação de Bandaferro"},
                {0, 0, "Thelsamar"},
                {0, 0, "Vale dos Reis"},
                {0, 0, "Dique Lapidado"},
                {0, 0, "Mina da Prata"},
                {0, 0, "Pavilhão dos Andarilhos"},
                {0, 0, "Serra Garracinza"},
                {0, 0, "Vale Lascapedra"},
            },
        },
        ["Clareiras de Tirisfal"] = {
            achievementID = 768,
            proxyLocation = {0, 0, "Clareiras de Tirisfal"},
            waypoints = {
                {0, 0, "Plangemortis"},
                {0, 0, "Moinhos dos Agamand"},
                {0, 0, "Casarão Lar Glacial"},
                {0, 0, "Sítio dos Garren"},
                {0, 0, "Fazenda dos Balnir"},
                {0, 0, "Posto da Vigília Escarlate"},
                {0, 0, "Ruínas de Lordaeron"},
                {0, 0, "O Baluarte"},
                {0, 0, "Fazenda dos Solliden"},
                {0, 0, "Vale do Pesadelo"},
                {0, 0, "Montalvo"},
                {0, 0, "Lago Águas Claras"},
                {0, 0, "Guarita dos Cruzados"},
                {0, 0, "Vale Veneracnídeo"},
                {0, 0, "Entrada do Monastério Escarlate"},
                {0, 0, "Propriedade Calston"},
            },
        },
        ["Garganta Abrasadora"] = {
            achievementID = 774,
            proxyLocation = {0, 0, "a Garganta Abrasadora"},
            waypoints = {
                {0, 0, "Cerro da Sentinela de Fogo"},
                {0, 0, "Caverna Calcinar"},
                {0, 0, "Escavação Pedrassuja"},
                {0, 0, "Posto de Tório"},
                {0, 0, "O Caldeirão"},
                {0, 0, "Mar de Cinzas"},
                {0, 0, "Vale Calcinado"},
                {0, 0, "Montanha Rocha Negra"},
            },
        },
        ["Terra Fantasma"] = {
            achievementID = 858,
            proxyLocation = {0, 0, "a Terra Fantasma"},
            waypoints = {
                {0, 0, "Tranquillien"},
                {0, 0, "Vila de Aurinévoa"},
                {0, 0, "Sacrário Lunar"},
                {0, 0, "Torre Aurestela"},
                {0, 0, "Zigurate Uivante"},
                {0, 0, "Zeb'Nowa"},
                {0, 0, "Pico dos Correventos"},
                {0, 0, "Passagem de Elrendar"},
                {0, 0, "Vila Corona Solar"},
                {0, 0, "Vila dos Correventos"},
                {0, 0, "Sacrário Solar"},
                {0, 0, "Enclave dos Andarilhos"},
                {0, 0, "Cidadela da Morte"},
                {0, 0, "Desfiladeiro Amani"},
                {0, 0, "Zigurate Sangrento"},
                {0, 0, "Caminho Thalassiano"},
            },
        },
        ["Cabo do Espinhaço"] = {
            achievementID = 4995,
            proxyLocation = {0, 0, "o Cabo do Espinhaço"},
            waypoints = {
                {0, 0, "Angra do Butim"},
                {0, 0, "Arena de Gurubashi"},
                {0, 0, "Ilha Jaguara"},
                {0, 0, "Olho-d'água Nek'mani"},
                {0, 0, "Ruínas de Jubuwal"},
                {0, 0, "Mina Veio de Cristal"},
                {0, 0, "Esconderijo da Chaveforte"},
                {0, 0, "Vale da Névoa"},
                {0, 0, "Ruínas de Aboraz"},
                {0, 0, "A Praia Selvagem"},
            },
        },
        ["Terras Agrestes"] = {
            achievementID = 773,
            proxyLocation = {0, 0, "as Terras Agrestes"},
            waypoints = {
                {0, 0, "Ninho da Águia"},
                {0, 0, "Zun'watha"},
                {0, 0, "Shadra'Alor"},
                {0, 0, "Agol'watha"},
                {0, 0, "Altar de Zul"},
                {0, 0, "Rocha Oculta"},
                {0, 0, "Jintha'Alor"},
                {0, 0, "Trilha da Névoa Pestilenta"},
                {0, 0, "Pavilhão Quel'Danil"},
                {0, 0, "Lago Valovento"},
                {0, 0, "Ruína Assustadora"},
                {0, 0, "Seradane"},
                {0, 0, "Shaol'watha"},
                {0, 0, "Penhascos Panorâmicos"},
            },
        },
        ["Pantanal"] = {
            achievementID = 841,
            proxyLocation = {0, 0, "o Pantanal"},
            waypoints = {
                {0, 0, "Porto de Menethil"},
                {0, 0, "Pântano Peixeazul"},
                {0, 0, "Pântano do Ocaso"},
                {0, 0, "Tumba dos Barbaférreos"},
                {0, 0, "Acampamento Presirada"},
                {0, 0, "Bosque do Verdião"},
                {0, 0, "Monte Umbraforja"},
                {0, 0, "Guarda de Cinzelaje"},
                {0, 0, "Pântano do Canal Negro"},
                {0, 0, "Sítio de Escavação de Whelgar"},
                {0, 0, "Vale Espuma de Sal"},
                {0, 0, "Dun Modr"},
                {0, 0, "Rocha de Thelgen"},
                {0, 0, "Charco Pelemusgo"},
                {0, 0, "Dun Algaz"},
                {0, 0, "Serra dos Raptores"},
            },
        },
        ["Terras Pestilentas Ocidentais"] = {
            achievementID = 770,
            proxyLocation = {0, 0, "as Terras Pestilentas Ocidentais"},
            waypoints = {
                {0, 0, "Lago das Flechas"},
                {0, 0, "Colina do Pesar"},
                {0, 0, "O Baluarte"},
                {0, 0, "Fazenda dos Dalson"},
                {0, 0, "Madeireira Beiranorte"},
                {0, 0, "Vale Pinhorrubro"},
                {0, 0, "Caverna das Lágrimas"},
                {0, 0, "Castro das Flechas"},
                {0, 0, "Andorhal"},
                {0, 0, "Campo Pedravil"},
                {0, 0, "O Antro Repelente"},
                {0, 0, "Amparo"},
                {0, 0, "Aridez de Garrão"},
                {0, 0, "Rio Thondroril"},
            },
        },
        ["Ilha de Quel'Danas"] = {
            achievementID = 868,
            proxyLocation = {0, 0, "a Ilha de Quel'Danas"},
            waypoints = {
            },
        },
        ["Planalto Arathi"] = {
            achievementID = 761,
            proxyLocation = {0, 0, "o Planalto Arathi"},
            waypoints = {
                {0, 0, "Círculo da União Ocidental"},
                {0, 0, "Pedre'gor"},
                {0, 0, "Bastilha de Stromgarde"},
                {0, 0, "Círculo da União Interna"},
                {0, 0, "Forte Punho de Pedra"},
                {0, 0, "Círculo da União Externa"},
                {0, 0, "Fazenda Go'Shek"},
                {0, 0, "Círculo da União Oriental"},
                {0, 0, "Casa Grande do Norte"},
                {0, 0, "Ruína de Galen"},
                {0, 0, "Enseada de Faldir"},
                {0, 0, "Ponte Thandol"},
                {0, 0, "Ponta do Refúgio"},
                {0, 0, "Aldeia Cascasseca"},
                {0, 0, "Fazenda dos Dabyrie"},
                {0, 0, "Ruína do Martelo"},
            },
        },
        ["Barreira do Inferno"] = {
            achievementID = 766,
            proxyLocation = {0, 0, "a Barreira do Inferno"},
            waypoints = {
                {0, 0, "Domínio de Malhorrendo"},
                {0, 0, "Bastilha de Etergarde"},
                {0, 0, "Portal Negro"},
                {0, 0, "Posto Malhorrendo"},
                {0, 0, "Cerro do Profanador"},
                {0, 0, "Acampamento Clarovéu"},
                {0, 0, "Recôndito Vermelho"},
                {0, 0, "Bases de Suprimentos de Etergarde"},
                {0, 0, "Cavernas Serpeantes"},
                {0, 0, "Altar das Tempestades"},
                {0, 0, "Rasgo Infecto"},
                {0, 0, "Costa Partida"},
                {0, 0, "Mecassur"},
                {0, 0, "Floresta Maculada"},
            },
        },
        ["Dun Morogh"] = {
            achievementID = 627,
            proxyLocation = {0, 0, "Dun Morogh"},
            waypoints = {
                {0, 0, "Caminho de Cristálgida"},
                {0, 0, "Front Jubafria"},
                {0, 0, "Base Aérea de Altaforja"},
                {0, 0, "Kharanos"},
                {0, 0, "Rancho Ambarmanso"},
                {0, 0, "Pedreira Gol'Bolar"},
                {0, 0, "Fortaleza Jubafria"},
                {0, 0, "Portões de Altaforja"},
                {0, 0, "Vale Cristálgida"},
                {0, 0, "Vila da Gambiarra"},
                {0, 0, "Cordilheira Cintilante"},
                {0, 0, "Montes Túndricos"},
                {0, 0, "Lago Helm"},
                {0, 0, "Posto de Guarda do Portão Norte"},
                {0, 0, "Lago Nevado"},
            },
        },
        ["Contraforte de Eira dos Montes"] = {
            achievementID = 772,
            proxyLocation = {0, 0, "o Contraforte de Eira dos Montes"},
            waypoints = {
                {0, 0, "Mina Veioazul"},
                {0, 0, "Adaga de Corrahn"},
                {0, 0, "Morro do Ventogelante"},
                {0, 0, "Nicho de Dandred"},
                {0, 0, "Dun Garok"},
                {0, 0, "Canto da Forca"},
                {0, 0, "Caverna Rugido"},
                {0, 0, "Sítio de Nethander"},
                {0, 0, "Ruínas de Alterac"},
                {0, 0, "Antro do Massacre"},
                {0, 0, "Portão do Sul"},
                {0, 0, "Serraria Tarren"},
                {0, 0, "Campos Lodosos"},
                {0, 0, "Fazenda do Zeca Rioka"},
                {0, 0, "Bastilha Esmagaterra"},
                {0, 0, "Cratera de Dalaran"},
                {0, 0, "Monte das Flechas"},
                {0, 0, "Forte do Desterro"},
                {0, 0, "Promontório de Gavin"},
                {0, 0, "Costa da Bruma"},
                {0, 0, "Ilha da Purgação"},
                {0, 0, "Ruínas da Costa Sul"},
                {0, 0, "Promontório de Sofera"},
                {0, 0, "Strahnbrad"},
                {0, 0, "Terralta"},
                {0, 0, "As Terras Altas"},
            },
        },
        ["Montanhas Cristarrubra"] = {
            achievementID = 780,
            proxyLocation = {0, 0, "as Montanhas Cristarrubra"},
            waypoints = {
                {0, 0, "Vila Plácida"},
                {0, 0, "Três Caminhos"},
                {0, 0, "Garganta Cristarrubra"},
                {0, 0, "Cachoeira do Mirante de Pedra"},
                {0, 0, "Acampamento dos Laceradores"},
                {0, 0, "Vale Galardell"},
                {0, 0, "Acampamento Lago Plácido"},
                {0, 0, "Lago Plácido"},
                {0, 0, "Estrada Beira-lago"},
                {0, 0, "Serraria Alther"},
                {0, 0, "Vale dos Laceradores"},
                {0, 0, "Bastilha Mirante de Pedra"},
                {0, 0, "Garganta do Barro Seco"},
            },
        },
        ["Floresta do Canto Eterno"] = {
            achievementID = 859,
            proxyLocation = {0, 0, "a Floresta do Canto Eterno"},
            waypoints = {
                {0, 0, "Ilha Andassol"},
                {0, 0, "Sacrário do Oeste"},
                {0, 0, "Sacrário do Norte"},
                {0, 0, "Retiro dos Andarilhos"},
                {0, 0, "Terras do Ocaso"},
                {0, 0, "Floresta Viva"},
                {0, 0, "Mata Queimada"},
                {0, 0, "Costa da Brisa Azul"},
                {0, 0, "Caminho Ramadouro"},
                {0, 0, "Pedra Rúnica Falithas"},
                {0, 0, "Refúgio de Saltheril"},
                {0, 0, "Cocheira de Thuron"},
                {0, 0, "Zeb'Watha"},
                {0, 0, "Ruínas de Luaprata"},
                {0, 0, "Ancoradouro Velaclara"},
                {0, 0, "Sacrário do Leste"},
                {0, 0, "Lagoa do Eterno Sussurro"},
                {0, 0, "Vila de Brisabela"},
                {0, 0, "Tor'Watha"},
                {0, 0, "Luaprata"},
                {0, 0, "Cachoeira Elrendar"},
                {0, 0, "Lago Elrendar"},
                {0, 0, "Pedra Rúnica Shan'dor"},
                {0, 0, "Areal Dourado"},
                {0, 0, "Costa Plácida"},
            },
        },
        ["Floresta de Pinhaprata"] = {
            achievementID = 769,
            proxyLocation = {0, 0, "a Floresta de Pinhaprata"},
            waypoints = {
                {0, 0, "A Frente de Batalha"},
                {0, 0, "Linha de Frente dos Renegados"},
                {0, 0, "Atracadouro da Maré do Norte"},
                {0, 0, "Sítio do Valgan"},
                {0, 0, "Mina Elenfunda"},
                {0, 0, "Lenhâmbar"},
                {0, 0, "Alto Comando dos Renegados"},
                {0, 0, "Retaguarda dos Renegados"},
                {0, 0, "Campos Apodrecidos"},
                {0, 0, "Penumbra Furtiva"},
                {0, 0, "Ilha de Fenris"},
                {0, 0, "O Sepulcro"},
                {0, 0, "Miséria de Olsen"},
                {0, 0, "Bastilha da Presa Negra"},
                {0, 0, "Costa da Maré do Norte"},
            },
        },
        ["Selva do Espinhaço Setentrional"] = {
            achievementID = 781,
            proxyLocation = {0, 0, "a Selva do Espinhaço Setentrional"},
            waypoints = {
                {0, 0, "Acampamento Grom'gol"},
                {0, 0, "Bambala"},
                {0, 0, "Ruínas Zuuldaia"},
                {0, 0, "Acampamento dos Rebeldes"},
                {0, 0, "Ruínas de Kal'ai"},
                {0, 0, "Gruta de Mosh'Ogg"},
                {0, 0, "Ruínas de Bal'lal"},
                {0, 0, "Ruínas de Zul'Kanda"},
                {0, 0, "Ruínas de Balia'mah"},
                {0, 0, "Forte Pedraviva"},
                {0, 0, "Expedição do Rosarães"},
                {0, 0, "Complexo do Kurzen"},
                {0, 0, "Ruínas de Nizjah"},
                {0, 0, "Lago Nazferiti"},
                {0, 0, "O Arrecife Torpe"},
                {0, 0, "Zul'Gurub"},
            },
        },
        ["o Pântano das Mágoas"] = {
            achievementID = 782,
            proxyLocation = {0, 0, "o Pântano das Mágoas"},
            waypoints = {
                {0, 0, "Vale Nebuloso"},
                {0, 0, "Entroncamento da Lança Lascada"},
                {0, 0, "Pedregal"},
                {0, 0, "Pantanal dos Cervos"},
                {0, 0, "Brejo do Goblin"},
                {0, 0, "Caverna Fonte Clara"},
                {0, 0, "O Refúgio"},
                {0, 0, "Lodaçal Mutante"},
                {0, 0, "Poço de Lágrimas"},
                {0, 0, "Penumbra das Mágoas"},
                {0, 0, "Praia Brumalga"},
                {0, 0, "Posto Maré do Pântano"},
            },
        },
        ["o Cerro Oeste"] = {
            achievementID = 802,
            proxyLocation = {0, 0, "o Cerro Oeste"},
            waypoints = {
                {0, 0, "Morro da Sentinela"},
                {0, 0, "Plantação de Abóboras do Taturana"},
                {0, 0, "Mina Veiojango"},
                {0, 0, "O Alqueire Morto"},
                {0, 0, "Fazenda dos Aleixo"},
                {0, 0, "Os Obeliscos"},
                {0, 0, "Planícies do Pó"},
                {0, 0, "Fazenda dos Saldanha"},
                {0, 0, "Sítio dos Jansen"},
                {0, 0, "Fazenda dos Peçanha"},
                {0, 0, "Arroio da Lua"},
                {0, 0, "Recanto de Demont"},
                {0, 0, "Abismo Atroz"},
            },
        },
        ["a Trilha do Vento Morto"] = {
            achievementID = 777,
            proxyLocation = {0, 0, "a Trilha do Vento Morto"},
            waypoints = {
                {0, 0, "Encruzilhada do Defunto"},
                {0, 0, "Karazhan"},
                {0, 0, "A Garra"},
            },
        },
        ["as Terras Pestilentas Orientais"] = {
            achievementID = 771,
            proxyLocation = {0, 0, "as Terras Pestilentas Orientais"},
            waypoints = {
                {0, 0, "Rio Thondroril"},
                {0, 0, "Chácara Secreta"},
                {0, 0, "Vale Fungi"},
                {0, 0, "Cicatriz Pestilenta"},
                {0, 0, "Lago Mereldar"},
                {0, 0, "Capela Esperança da Luz"},
                {0, 0, "Clareira Nociva"},
                {0, 0, "Lago Bosquenero"},
                {0, 0, "Zul'Mashar"},
                {0, 0, "Abrigo Quel'Lithien"},
                {0, 0, "Bosque Pestilento"},
                {0, 0, "Ruínas do Enclave Escarlate"},
                {0, 0, "Sítio dos Marris"},
                {0, 0, "Torre da Coroa"},
                {0, 0, "Vila das Flechas"},
                {0, 0, "Cruzamento de Corin"},
                {0, 0, "Manopla de Tyr"},
                {0, 0, "Fenda Infectis"},
                {0, 0, "Torre da Muralha Leste"},
                {0, 0, "Vilarejo do Norte"},
                {0, 0, "Torre do Passo Norte"},
                {0, 0, "Várzea do Medo"},
                {0, 0, "Stratholme"},
            },
        },
    }, -- World of Warcraft (Vanilla)
    ["Terralém"] = {
        ["a Península Fogo do Inferno"] = {
            achievementID = 862,
            proxyLocation = {0, 0, "a Península Fogo do Inferno"},
            waypoints = {
                {0, 0, "Degraus do Destino"},
                {0, 0, "Vigília do Falcão"},
                {0, 0, "Fortaleza da Honra"},
                {0, 0, "Poços de Aggonar"},
                {0, 0, "Templo de Telhamat"},
                {0, 0, "Thrallmar"},
                {0, 0, "Zeth'Gor"},
                {0, 0, "Serra do Céu Caído"},
                {0, 0, "Campos Dimensionais"},
                {0, 0, "Arsenal da Expedição"},
                {0, 0, "Cidadela Fogo do Inferno"},
                {0, 0, "Posto Mag'har"},
                {0, 0, "Ruínas de Sha'naar"},
                {0, 0, "O Front da Legião"},
                {0, 0, "Trono de Kil'jaeden"},
                {0, 0, "Antro de Haal'esh"},
                {0, 0, "Escarpa do Caos"},
                {0, 0, "Campo-forja: Megido"},
            },
        },
        ["a Mata Terokkar"] = {
            achievementID = 867,
            proxyLocation = {0, 0, "a Mata Terokkar"},
            waypoints = {
                {0, 0, "Ruínas dos Olhos Sangrentos"},
                {0, 0, "Mata Cenariana"},
                {0, 0, "Aldeia Grangol'var"},
                {0, 0, "Tuurem"},
                {0, 0, "Clareira Raastok"},
                {0, 0, "Passagem Espinhosa"},
                {0, 0, "Território Auchenai"},
                {0, 0, "Caravana dos Refugiados"},
                {0, 0, "Tumba Sombria"},
                {0, 0, "Véu Rhaze"},
                {0, 0, "Skettis"},
                {0, 0, "Fortaleza Alleriana"},
                {0, 0, "Pontal Asardente"},
                {0, 0, "Vila de Quebrapedra"},
                {0, 0, "Shattrath"},
                {0, 0, "Picos da Barreira"},
                {0, 0, "Ruínas Mascaosso"},
                {0, 0, "Monte Carniçal"},
                {0, 0, "Círculo da Obediência"},
                {0, 0, "Caravana Abandonada"},
                {0, 0, "Morro Retorcido"},
            },
        },
        ["as Montanhas da Lâmina Afiada"] = {
            achievementID = 865,
            proxyLocation = {0, 0, "as Montanhas da Lâmina Afiada"},
            waypoints = {
                {0, 0, "Patamar de Bash'ir"},
                {0, 0, "Bastião Giralança"},
                {0, 0, "Posto Avançado Malho Sangrento"},
                {0, 0, "Círculo Sangrento"},
                {0, 0, "Campo-forja: Fúria"},
                {0, 0, "Campo-forja: Ira"},
                {0, 0, "Covil de Gruul"},
                {0, 0, "Vila de Mok'nathal"},
                {0, 0, "Espinhaço Cortante"},
                {0, 0, "Skald"},
                {0, 0, "Serra dos Cristais"},
                {0, 0, "Véu Lashh"},
                {0, 0, "Bosque de Vekhaar"},
                {0, 0, "Ravina das Lâminas"},
                {0, 0, "Base dos Malho Sangrento"},
                {0, 0, "Espinhaço Inóspito"},
                {0, 0, "Porta da Morte"},
                {0, 0, "Campo-forja: Terror"},
                {0, 0, "Grishnath"},
                {0, 0, "Serra dos Espigões"},
                {0, 0, "Mata do Corvo"},
                {0, 0, "Bosque Ruuan"},
                {0, 0, "Sylvanaar"},
                {0, 0, "Cidadela do Senhor do Trovão"},
                {0, 0, "Véu Ruuan"},
                {0, 0, "Auge do Vórtice"},
            },
        },
        ["o Vale da Lua Negra"] = {
            achievementID = 864,
            proxyLocation = {0, 0, "o Vale da Lua Negra"},
            waypoints = {
                {0, 0, "Pontal dos Serpentálios"},
                {0, 0, "Cidadela da Legião"},
                {0, 0, "Aldeia Lua Negra"},
                {0, 0, "Forja da Morte"},
                {0, 0, "Jaula do Carcereiro"},
                {0, 0, "Altar de Sha'tar"},
                {0, 0, "Campos da Asa Etérea"},
                {0, 0, "Ponta do Eclipse"},
                {0, 0, "Plataforma da Asa Etérea"},
                {0, 0, "Templo Negro"},
                {0, 0, "A Mão de Gul'dan"},
                {0, 0, "Fortaleza Martelo Feroz"},
                {0, 0, "Pontal Illidari"},
            },
        },
        ["o Pântano Zíngaro"] = {
            achievementID = 863,
            proxyLocation = {0, 0, "o Pântano Zíngaro"},
            waypoints = {
                {0, 0, "Refúgio Cenariano"},
                {0, 0, "Vila do Charco das Feras"},
                {0, 0, "Lago Pantanoso"},
                {0, 0, "Telredor"},
                {0, 0, "A Lagoa"},
                {0, 0, "Aldeia do Charco Sombrio"},
                {0, 0, "Fortaleza Ango'rosh"},
                {0, 0, "Porto Orebor"},
                {0, 0, "Zabra'jin"},
                {0, 0, "Terras de Ango'rosh"},
                {0, 0, "Brejo Ceifado"},
                {0, 0, "Serra Quagg"},
                {0, 0, "O Charco Fantasma"},
                {0, 0, "Ruínas das Agulhas Gêmeas"},
                {0, 0, "Sporeggar"},
                {0, 0, "Terras dos Sangrescamas"},
                {0, 0, "Vale dos Rebentos"},
                {0, 0, "Praia da Cristanegra"},
            },
        },
        ["Nagrand"] = {
            achievementID = 866,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Campo-forja: Medo"},
                {0, 0, "Halaa"},
                {0, 0, "Ruínas Gargaveira"},
                {0, 0, "Posto Solavera"},
                {0, 0, "Ringue da Provação"},
                {0, 0, "Morro Guerramalho"},
                {0, 0, "Vila dos Clãs"},
                {0, 0, "Fenda do Vento Sul"},
                {0, 0, "Desfiladeiro Canavento"},
                {0, 0, "Crista Zíngara"},
                {0, 0, "Garadar"},
                {0, 0, "Fortaleza Kil'pesar"},
                {0, 0, "Campos dos Espíritos"},
                {0, 0, "Telaar"},
                {0, 0, "Trono dos Elementos"},
                {0, 0, "Ruínas da Lâmina Ardente"},
                {0, 0, "Campo-forja: Ódio"},
                {0, 0, "Cordilheira do Crepúsculo"},
                {0, 0, "Aldeia Canavento"},
            },
        },
        ["Eternévoa"] = {
            achievementID = 843,
            proxyLocation = {0, 0, "Eternévoa"},
            waypoints = {
                {0, 0, "Área 52"},
                {0, 0, "Manaforja Coruu"},
                {0, 0, "Manaforja Ara"},
                {0, 0, "Ruínas de Farahlon"},
                {0, 0, "Os Destroços"},
                {0, 0, "Pico Celestial"},
                {0, 0, "Pedra Etérea"},
                {0, 0, "Acampamento Solfúria"},
                {0, 0, "Ponte Giroprancha"},
                {0, 0, "Bivaques do Eteréum"},
                {0, 0, "Base-forja: Oblívio"},
                {0, 0, "Manaforja B'naar"},
                {0, 0, "Manaforja Dúria"},
                {0, 0, "Manaforja Ultris"},
                {0, 0, "Bastilha da Tormenta"},
                {0, 0, "Ruínas Arklon"},
                {0, 0, "Vila Kirin'Var"},
                {0, 0, "Ruínas de Enkaat"},
                {0, 0, "Pináculo da Tempestade"},
                {0, 0, "Eco-domo Campolonge"},
                {0, 0, "Trono de Socrethar"},
                {0, 0, "Eco-domo Terramédia"},
            },
        },
    }, -- The Burning Crusade
    ["Cataclismo"] = {
        ["Hyjal"] = {
            achievementID = 4863,
            proxyLocation = {0, 0, "Hyjal"},
            waypoints = {
                {0, 0, "Perímetro do Mundo"},
                {0, 0, "Lago Pálido"},
                {0, 0, "Portões de Sothann"},
                {0, 0, "Mirante de Sethria"},
                {0, 0, "A Ardilanta"},
                {0, 0, "Trono das Chamas"},
                {0, 0, "O Círculo das Brasas"},
                {0, 0, "Garganta do Sussurro Sombrio"},
                {0, 0, "Nordrassil"},
                {0, 0, "Santuário de Goldrinn"},
                {0, 0, "Terra Queimada"},
            },
        },
        ["o Geodomo"] = {
            achievementID = 4864,
            proxyLocation = {0, 0, "o Geodomo"},
            waypoints = {
                {0, 0, "Queda do Asa da Morte"},
                {0, 0, "Vila Pedragulha"},
                {0, 0, "Destroços do Fúria da Tempestade"},
                {0, 0, "Alcândor Pálido"},
                {0, 0, "Campos Sísmicos"},
                {0, 0, "Portão do Mestre"},
                {0, 0, "Fenda Pedragulha"},
                {0, 0, "Larpétreo"},
                {0, 0, "Templo da Terra"},
                {0, 0, "Trono de Therazane"},
                {0, 0, "Mirante do Crepúsculo"},
                {0, 0, "Vastidão Carmesim"},
            },
        },
        ["o Planalto do Crepúsculo"] = {
            achievementID = 4866,
            proxyLocation = {0, 0, "o Planalto do Crepúsculo"},
            waypoints = {
                {0, 0, "Ravina de Sangue"},
                {0, 0, "Cachamorra"},
                {0, 0, "Porto Presa do Dragão"},
                {0, 0, "Patrulha do Barbarruiva"},
                {0, 0, "Acampamento de Guerra Gorshak"},
                {0, 0, "Beiralta"},
                {0, 0, "Conflagração de Humboldt"},
                {0, 0, "Floresta Obsidiana"},
                {0, 0, "Angra do Resvalo"},
                {0, 0, "A Gorja"},
                {0, 0, "Lacuna Crepuscular"},
                {0, 0, "Costa do Crepúsculo"},
                {0, 0, "Pontal do Vencedor"},
                {0, 0, "Ventre da Loucura"},
                {0, 0, "Caldeirão da Carnificina"},
                {0, 0, "Desfiladeiro da Presa do Dragão"},
                {0, 0, "Ruínas Dunwald"},
                {0, 0, "Ravina do Tripasseca"},
                {0, 0, "Grim Batol"},
                {0, 0, "Floresta do Planalto"},
                {0, 0, "Kirthaven"},
                {0, 0, "Ruínas de Drakgor"},
                {0, 0, "Lacuna Negra"},
                {0, 0, "Os Krazzodutos"},
                {0, 0, "Trondamar"},
                {0, 0, "Rubro Reduto"},
                {0, 0, "Curva das Serpes"},
            },
        },
        ["Vashj'ir"] = {
            achievementID = 4825,
            proxyLocation = {0, 0, "Vashj'ir"},
            waypoints = {
                {0, 0, "Recife Abandonado"},
                {0, 0, "Garganta Telúmina"},
                {0, 0, "Ruína de Korthun"},
                {0, 0, "Onda do Mar"},
                {0, 0, "Abismo das Profundezas Cintilantes"},
                {0, 0, "Salto de Gurboggle"},
                {0, 0, "Tumba do Marinheiro"},
                {0, 0, "Recife Esquelético"},
                {0, 0, "Nespirah"},
                {0, 0, "Ruínas de Vashj'ir"},
                {0, 0, "Antro da Maré Prateada"},
                {0, 0, "Brecha Abissal"},
                {0, 0, "Crista das Barbatanas"},
                {0, 0, "L'ghorek"},
                {0, 0, "Abismo Escaldante"},
                {0, 0, "Ossário do Roedor"},
                {0, 0, "A Amarra"},
                {0, 0, "Destino da Legião"},
                {0, 0, "Pico Beth'mora"},
                {0, 0, "Ruínas do Templo Thelserai"},
                {0, 0, "Gruta Cintilante"},
            },
        },
        ["Uldum"] = {
            achievementID = 4865,
            proxyLocation = {0, 0, "Uldum"},
            waypoints = {
                {0, 0, "Campos Akhenet"},
                {0, 0, "Tumba de Khartut"},
                {0, 0, "Mar'at"},
                {0, 0, "Cidade dos Neferset"},
                {0, 0, "Obelisco das Estrelas"},
                {0, 0, "Orsis"},
                {0, 0, "Ruínas de Ahmtul"},
                {0, 0, "Porto de Schnottz"},
                {0, 0, "Templo de Uldum"},
                {0, 0, "Portão dos Ciclos sem Fim"},
                {0, 0, "Trilha da Devastação"},
                {0, 0, "Berço dos Anciãos"},
                {0, 0, "Cidade Perdida dos Tol'vir"},
                {0, 0, "Nahom"},
                {0, 0, "Obelisco da Lua"},
                {0, 0, "Obelisco do Sol"},
                {0, 0, "Ramkahen"},
                {0, 0, "Ruínas de Ammon"},
                {0, 0, "Terras de Tahret"},
                {0, 0, "Porto Amaldiçoado"},
                {0, 0, "Tumbas dos Antecessores"},
                {0, 0, "Dique Vir'naal"},
            },
        },
    }, -- Cataclysm
    ["Draenor"] = {
        ["a Serra Fogofrio"] = {
            achievementID = 8937,
            proxyLocation = {0, 0, "a Serra Fogofrio"},
            waypoints = {
                {0, 0, "Cidadela Giralança"},
                {0, 0, "Ossos de Agurak"},
                {0, 0, "Ravina Gorjadaga"},
                {0, 0, "Colina Calafrio"},
                {0, 0, "Área de Cerco de Ferro"},
                {0, 0, "Magnarok"},
                {0, 0, "Escória de Ossos"},
                {0, 0, "Wor'gol"},
                {0, 0, "Forte Malho Sangrento"},
                {0, 0, "A Queda do Colosso"},
                {0, 0, "Rochedo do Vento Gélido"},
                {0, 0, "Grom'gar"},
                {0, 0, "Estação de Ferro"},
                {0, 0, "Posto Avançado da Presa Pétrea"},
                {0, 0, "Planície Esfacelada"},
            },
        },
        ["Gorgrond"] = {
            achievementID = 8939,
            proxyLocation = {0, 0, "Gorgrond"},
            waypoints = {
                {0, 0, "Platô do Bastião"},
                {0, 0, "Central do Carrilcruel"},
                {0, 0, "Risomorto"},
                {0, 0, "Fontes Perenalba"},
                {0, 0, "Passoalto"},
                {0, 0, "Arena Pedramalho"},
                {0, 0, "A aproximação de Ferro"},
                {0, 0, "Guarda das Feras"},
                {0, 0, "Charco Carmesim"},
                {0, 0, "Selva Floretérnia"},
                {0, 0, "Cânion dos Gronns"},
                {0, 0, "Bosque Iyun"},
                {0, 0, "Coração Emaranhado"},
                {0, 0, "Fosso"},
                {0, 0, "Fosso"},
                {0, 0, "Fosso"},
            },
        },
        ["as Agulhas de Arak"] = {
            achievementID = 8941,
            proxyLocation = {0, 0, "as Agulhas de Arak"},
            waypoints = {
                {0, 0, "Skettis"},
                {0, 0, "Charco Retorcido"},
                {0, 0, "Véu Zekk"},
                {0, 0, "Porto Sul"},
                {0, 0, "Terraço da Aurora"},
                {0, 0, "O Forte Carpunhal"},
                {0, 0, "Véu Anzu Perdido"},
                {0, 0, "Skaracorvo"},
                {0, 0, "Ashakai"},
                {0, 0, "Despenhadeiro Uivante"},
                {0, 0, "Pontal Beliscapito"},
                {0, 0, "Véu Akraz"},
                {0, 0, "Terraço Sopravento"},
                {0, 0, "Vale dos Sethekk"},
                {0, 0, "A guarnição do almirante Taylor"},
                {0, 0, "Geringonças Beliscapito"},
                {0, 0, "Vale Jubassangue"},
            },
        },
        ["o Vale da Lua Negra"] = {
            achievementID = 8938,
            proxyLocation = {0, 0, "o Vale da Lua Negra"},
            waypoints = {
                {0, 0, "Fortaleza da Angústia"},
                {0, 0, "Elodor"},
                {0, 0, "Bosque da Penumbra"},
                {0, 0, "Karabor"},
                {0, 0, "Charco Cintilante"},
                {0, 0, "Ilha das Sombras"},
                {0, 0, "Mirante Ondanegra"},
                {0, 0, "Aldeia Embaari"},
                {0, 0, "Gul'var"},
                {0, 0, "Shaz'gul"},
                {0, 0, "Elevado de Socrethar"},
            },
        },
        ["Talador"] = {
            achievementID = 8940,
            proxyLocation = {0, 0, "Talador"},
            waypoints = {
                {0, 0, "Aruuna"},
                {0, 0, "Ilha do Ocaso"},
                {0, 0, "Forte Wrynn"},
                {0, 0, "Gul'rok"},
                {0, 0, "Costa Orunai"},
                {0, 0, "Shattrath"},
                {0, 0, "Tumba das Luzes"},
                {0, 0, "Zangarra"},
                {0, 0, "Auchindoun"},
                {0, 0, "Paço das Almas"},
                {0, 0, "Fortaleza Gordal"},
                {0, 0, "O Caminho da Glória"},
                {0, 0, "Pouso do Anacoreta"},
                {0, 0, "Telmor"},
                {0, 0, "Tuurem"},
            },
        },
        ["Nagrand"] = {
            achievementID = 8942,
            proxyLocation = {0, 0, "Nagrand"},
            waypoints = {
                {0, 0, "Terras Ancestrais"},
                {0, 0, "Portão de Grommashar"},
                {0, 0, "Porto do Malho Imponente"},
                {0, 0, "Lok-rath"},
                {0, 0, "Posto de Vigia Mok'gol"},
                {0, 0, "Telaar"},
                {0, 0, "O ringue das provações"},
                {0, 0, "Costa Zíngara"},
                {0, 0, "Precipício Alquebrado"},
                {0, 0, "Hallvalor"},
                {0, 0, "Enseada Punho de Ferro"},
                {0, 0, "Vedeta de Mar'gok"},
                {0, 0, "Oshu'gun"},
                {0, 0, "Ringue de Sangue"},
                {0, 0, "Trono dos Elementos"},
            },
        },
    }, -- Warlords of Draenor
    ["Batalha por Azeroth"] = {
        ["Estreito Tiragarde"] = {
            achievementID = 12556,
            proxyLocation = {0, 0, "o Estreito Tiragarde"},
            waypoints = {
                {0, 0, "Cais do Caniço"},
                {0, 0, "Serra das Samambaias"},
                {0, 0, "Herdade dos Lancastre"},
                {0, 0, "Pilha de Sucata Abandonada"},
                {0, 0, "Canal Ululante"},
                {0, 0, "Geleira Minguante"},
                {0, 0, "Boralus"},
                {0, 0, "Angra do Facão"},
                {0, 0, "Enseada Ruína do Kraken"},
                {0, 0, "Rancho Kennings"},
                {0, 0, "Colina da Vigília"},
            },
        },
        ["Vale Trovamare"] = {
            achievementID = 12558,
            proxyLocation = {0, 0, "o Vale Trovamare"},
            waypoints = {
                {0, 0, "Brennadam"},
                {0, 0, "Praia do Marujo"},
                {0, 0, "Água Morta"},
                {0, 0, "Enclave dos Sábios"},
                {0, 0, "Vila Pedra do Moinho"},
                {0, 0, "Urzal Dorsarça"},
                {0, 0, "Guarnição Presa de Guerra"},
                {0, 0, "Forte Daelin"},
                {0, 0, "Santuário da Tempestade"},
            },
        },
        ["Nazmir"] = {
            achievementID = 12561,
            proxyLocation = {0, 0, "Nazmir"},
            waypoints = {
                {0, 0, "Pantanal Primevo"},
                {0, 0, "Pântano do Rio"},
                {0, 0, "Zalamar"},
                {0, 0, "Naz'watha"},
                {0, 0, "Pântano dos Sapos"},
                {0, 0, "Coração das Trevas"},
                {0, 0, "A Necrópole"},
                {0, 0, "Descanso de Torga"},
                {0, 0, "Zal'amak"},
            },
        },
        ["Drustvar"] = {
            achievementID = 12557,
            proxyLocation = {0, 0, "Drustvar"},
            waypoints = {
                {0, 0, "Brado de Arom"},
                {0, 0, "Porto Trincha"},
                {0, 0, "Floresta Carmesim"},
                {0, 0, "Clareira do Flecheiro"},
                {0, 0, "Passo da Estrada Alta"},
                {0, 0, "Geleira Gelovéu"},
                {0, 0, "Cemitério Tumbapétrea"},
                {0, 0, "Corlain"},
                {0, 0, "Refúgio Outonal"},
                {0, 0, "Gol Koval"},
                {0, 0, "Posto do Oeste"},
                {0, 0, "Mansão Capelo"},
            },
        },
        ["Zuldazar"] = {
            achievementID = 12559,
            proxyLocation = {0, 0, "Zuldazar"},
            waypoints = {
                {0, 0, "Atal'Dazar"},
                {0, 0, "Portal Sangrento"},
                {0, 0, "Baixio da Pérola Medonha"},
                {0, 0, "Selvajada"},
                {0, 0, "Ilha das Presas"},
                {0, 0, "Xibala"},
                {0, 0, "Atal'Gral"},
                {0, 0, "Dazar'alor"},
                {0, 0, "Jardim dos Loas"},
                {0, 0, "A Estilha"},
                {0, 0, "Repreensão da Talanji"},
                {0, 0, "Zeb'ahari"},
            },
        },
        ["Vol'dun"] = {
            achievementID = 12560,
            proxyLocation = {0, 0, "Vol'dun"},
            waypoints = {
                {0, 0, "Atul'Aman"},
                {0, 0, "Porto de Zem'lan"},
                {0, 0, "Porto Rachapedra"},
                {0, 0, "Templo de Akunda"},
                {0, 0, "Poço dos Ossos"},
                {0, 0, "Costa Fendida"},
                {0, 0, "Oásis Florassilva"},
                {0, 0, "Baixio Lenhanegra"},
                {0, 0, "Porto Rubrapedra"},
                {0, 0, "Ravina Sibilante"},
                {0, 0, "Terraço dos Devotos"},
                {0, 0, "Bacia Salmoura"},
                {0, 0, "Refúgio Tortaka"},
            },
        },
    }, -- Battle for Azeroth
    ["Kalimdor"] = {
        ["Durotar"] = {
            achievementID = 728,
            proxyLocation = {0, 0, "Durotar"},
            waypoints = {
                {0, 0, "Vale das Provações"},
                {0, 0, "Bacia Furiaustral"},
                {0, 0, "Ilhas do Eco"},
                {0, 0, "Monte Navalha"},
                {0, 0, "Desfiladeiro do Trovão"},
                {0, 0, "Rocha da Caveira"},
                {0, 0, "Base da Guardanorte"},
                {0, 0, "Aldeia Sen'jin"},
                {0, 0, "Bastilha Tiragarde"},
                {0, 0, "Terras Crinavalha"},
                {0, 0, "Barranco da Ravina Seca"},
                {0, 0, "Orgrimmar"},
            },
        },
        ["Teldrassil"] = {
            achievementID = 842,
            proxyLocation = {0, 0, "Teldrassil"},
            waypoints = {
                {0, 0, "Umbravale"},
                {0, 0, "Dolanaar"},
                {0, 0, "Acampamento Masca-pinho"},
                {0, 0, "Águas de Arlithrien"},
                {0, 0, "Clareira do Oráculo"},
                {0, 0, "Darnassus"},
                {0, 0, "A Fenda"},
                {0, 0, "Ravina de Ban'ethil"},
                {0, 0, "Lago Al'Ameth"},
                {0, 0, "Vilarejo Brisastral"},
                {0, 0, "Lago Olho-d'Água"},
                {0, 0, "Vila de Rut'theran"},
            },
        },
        ["os Sertões Setentrionais"] = {
            achievementID = 750,
            proxyLocation = {0, 0, "os Sertões Setentrionais"},
            waypoints = {
                {0, 0, "Mina Veio do Pedregulho"},
                {0, 0, "Paliçada Mor'shan"},
                {0, 0, "Morro de Brumedo"},
                {0, 0, "Os Charcos Esquecidos"},
                {0, 0, "Posto Remoto"},
                {0, 0, "A Encruzilhada"},
                {0, 0, "Vila Catraca"},
                {0, 0, "Oásis das Águas Claras"},
                {0, 0, "Charco de Lodo"},
                {0, 0, "Montes Áridos"},
                {0, 0, "Fazenda Grol'dom"},
                {0, 0, "Morro dos Espinhos"},
                {0, 0, "O Oásis Estagnado"},
                {0, 0, "Costa dos Mercadores"},
            },
        },
        ["os Sertões Meridionais"] = {
            achievementID = 4996,
            proxyLocation = {0, 0, "os Sertões Meridionais"},
            waypoints = {
                {0, 0, "Bael Modan"},
                {0, 0, "Comando Avançado"},
                {0, 0, "Posto da Honra"},
                {0, 0, "Fortaleza da Guardanorte"},
                {0, 0, "Ruínas de Taurajo"},
                {0, 0, "Ponta Vendeta"},
                {0, 0, "Chaga de Guerra"},
                {0, 0, "Veio Lufa-lufa"},
                {0, 0, "Morro dos Caçadores"},
                {0, 0, "Urzal dos Tuscos"},
                {0, 0, "Profusão Verde"},
            },
        },
        ["a Ilha Névoa Rubra"] = {
            achievementID = 861,
            proxyLocation = {0, 0, "a Ilha Névoa Rubra"},
            waypoints = {
                {0, 0, "Desfiladeiro da Teia Âmbar"},
                {0, 0, "Praia Trevareia"},
                {0, 0, "Ilha do Sangue Maldito"},
                {0, 0, "Enclave dos Ericerdos"},
                {0, 0, "Vale da Podridão"},
                {0, 0, "Nazzivian"},
                {0, 0, "Ruínas de Loreth'Aran"},
                {0, 0, "Acampamento do Tel'athion"},
                {0, 0, "Maré Sangrenta"},
                {0, 0, "Crio-núcleo"},
                {0, 0, "Recife Oculto"},
                {0, 0, "Espiral Vetorial"},
                {0, 0, "Ponta Viridiana"},
                {0, 0, "Covil dos Escamódios"},
                {0, 0, "Axxarien"},
                {0, 0, "Mata Cortante"},
                {0, 0, "Entreposto Rubro"},
                {0, 0, "Travessia de Kessel"},
                {0, 0, "Bosque das Névoas"},
                {0, 0, "Crista Penabrava"},
                {0, 0, "Planalto da Garra"},
                {0, 0, "Recife do Sangue Maldito"},
                {0, 0, "Rincão Rubro"},
                {0, 0, "O Lago Pútrido"},
                {0, 0, "Recôncavo Perdido"},
                {0, 0, "Pistão Dimensional"},
                {0, 0, "Recanto do Vindicante"},
                {0, 0, "Ilha Mal-da-serpe"},
            },
        },
        ["Mil Agulhas"] = {
            achievementID = 846,
            proxyLocation = {0, 0, "Mil Agulhas"},
            waypoints = {
                {0, 0, "O Grande Elevador"},
                {0, 0, "Sítio Arqueológico Submerso"},
                {0, 0, "O Definhar do Crepúsculo"},
                {0, 0, "Pico dos Confins do Oeste"},
                {0, 0, "Aldeia Vento Livre"},
                {0, 0, "Abismo Cintilante"},
                {0, 0, "Urzal dos Mortos"},
                {0, 0, "Raízes dos Mares do Sul"},
                {0, 0, "Baluarte do Crepúsculo"},
                {0, 0, "Pináculo da Nuvem Negra"},
                {0, 0, "Serra do Casco Fendido"},
                {0, 0, "Alcândora"},
            },
        },
        ["Desolação"] = {
            achievementID = 848,
            proxyLocation = {0, 0, "Desolação"},
            waypoints = {
                {0, 0, "Tethris Aran"},
                {0, 0, "Posto do Nijel"},
                {0, 0, "Fortaleza Machado do Trovão"},
                {0, 0, "Território Magram"},
                {0, 0, "Vale das Lanças"},
                {0, 0, "Aldeia Pescassombra"},
                {0, 0, "Ruínas de Mannoroc"},
                {0, 0, "Ravina da Sombra Partida"},
                {0, 0, "Acampamento de Thargad"},
                {0, 0, "Sargeron"},
                {0, 0, "Terras Virgens Cenarianas"},
                {0, 0, "Ilha Ranazjar"},
                {0, 0, "Cemitério dos Kodos"},
                {0, 0, "Aldeia Gelkis"},
                {0, 0, "Shok'Thokar"},
                {0, 0, "Praia Sibilâmina"},
            },
        },
        ["Feralas"] = {
            achievementID = 849,
            proxyLocation = {0, 0, "Feralas"},
            waypoints = {
                {0, 0, "Baixio Selvagem"},
                {0, 0, "Colossos Gêmeos"},
                {0, 0, "Gládio Cruel"},
                {0, 0, "Ruínas de Isildien"},
                {0, 0, "Aldeia Mojache"},
                {0, 0, "Assentamento Gordunni"},
                {0, 0, "Domínio de Plumaluna"},
                {0, 0, "Ruínas de Plumaluna"},
                {0, 0, "Costa Esquecida"},
                {0, 0, "Vale dos Abomináveis"},
                {0, 0, "Profundeza Atormentada"},
                {0, 0, "Complexo do Temível Totem"},
                {0, 0, "Ruínas Névoa Negra"},
            },
        },
        ["Azshara"] = {
            achievementID = 852,
            proxyLocation = {0, 0, "Azshara"},
            waypoints = {
                {0, 0, "Palacete de Gallywix"},
                {0, 0, "Ancoradouro Borraquilha"},
                {0, 0, "Torre de Eldara"},
                {0, 0, "Base Darnassiana"},
                {0, 0, "Campo dos Ursos"},
                {0, 0, "Portão Traseiro de Orgrimmar"},
                {0, 0, "Praia do Recife Sul"},
                {0, 0, "Lago Mennar"},
                {0, 0, "Penhascos Tempestuosos"},
                {0, 0, "Areal Despedaçado"},
                {0, 0, "Confins Amargos"},
                {0, 0, "Ruínas de Arkkoran"},
                {0, 0, "Laboratório Secreto"},
                {0, 0, "Gruta Bocanera"},
                {0, 0, "Ruínas de Eldarath"},
                {0, 0, "Monumento a Cristacorvo"},
                {0, 0, "Profundezas Devastadas"},
            },
        },
        ["a Cratera Un'Goro"] = {
            achievementID = 854,
            proxyLocation = {0, 0, "a Cratera Un'Goro"},
            waypoints = {
                {0, 0, "Pico Penacho de Fogo"},
                {0, 0, "Posto Avançado do Marshal"},
                {0, 0, "Jardins Turbulentos"},
                {0, 0, "Fontes Termais Golakka"},
                {0, 0, "Fenda Coleante"},
                {0, 0, "Platô Petraferro"},
                {0, 0, "Pedra do Limo"},
                {0, 0, "Viga Musgosa"},
                {0, 0, "Costa dos Gritos"},
                {0, 0, "Terroral"},
                {0, 0, "Os Pântanos"},
                {0, 0, "Poços de Piche Lakkari"},
            },
        },
        ["Silithus"] = {
            achievementID = 856,
            proxyLocation = {0, 0, "Silithus"},
            waypoints = {
                {0, 0, "Vale de Cristal"},
                {0, 0, "Forte Cenariano"},
                {0, 0, "Colme'Régia"},
                {0, 0, "Colme'Ashi"},
                {0, 0, "Vila do Vento Sul"},
                {0, 0, "Colme'Zora"},
                {0, 0, "Muralha do Escaravelho"},
                {0, 0, "Repouso dos Valorosos"},
            },
        },
        ["Mulgore"] = {
            achievementID = 736,
            proxyLocation = {0, 0, "Mulgore"},
            waypoints = {
                {0, 0, "Chapada Nuvem Vermelha"},
                {0, 0, "Aldeia Casco Sangrento"},
                {0, 0, "Morros Ondulantes"},
                {0, 0, "Caravana Devastada"},
                {0, 0, "Poço Chifre Troante"},
                {0, 0, "Rochedo Vermelho"},
                {0, 0, "Poço Juba Agreste"},
                {0, 0, "Rochedo Jubalba"},
                {0, 0, "Poço Casco Invernal"},
                {0, 0, "Mina da Empreendimentos S.A."},
                {0, 0, "Planícies Douradas"},
                {0, 0, "Sítio de Escavação de Bael'Dun"},
                {0, 0, "Serra Ventofúria"},
            },
        },
        ["a Ilha Névoa Lazúli"] = {
            achievementID = 860,
            proxyLocation = {0, 0, "a Ilha Névoa Lazúli"},
            waypoints = {
                {0, 0, "Vale Ammen"},
                {0, 0, "Entreposto Lazúli"},
                {0, 0, "Campo das Cinzas"},
                {0, 0, "Acampamento do Zé Ruela"},
                {0, 0, "Assentamento de Odisseu"},
                {0, 0, "Destroços do Módulo Espacial"},
                {0, 0, "Ilha Nevoaprata"},
                {0, 0, "Exodar"},
                {0, 0, "Posto Escamódio"},
                {0, 0, "Vau Ammen"},
                {0, 0, "Aldeia dos Ericerdos"},
                {0, 0, "Praia Pontebela"},
                {0, 0, "Matas do Pasto Lunar"},
                {0, 0, "Módulos Espaciais"},
                {0, 0, "Baía do Limo"},
                {0, 0, "Aldeia de Pinhoquieto"},
                {0, 0, "Atracadouro de Valaar"},
            },
        },
        ["Hibérnia"] = {
            achievementID = 857,
            proxyLocation = {0, 0, "Hibérnia"},
            waypoints = {
                {0, 0, "Fontes Termais de Fogofrio"},
                {0, 0, "Lago Kel'Theril"},
                {0, 0, "Mazthoril"},
                {0, 0, "Matagal da Asa da Coruja"},
                {0, 0, "Aldeia dos Invernosos"},
                {0, 0, "Pedra Sabre-de-gelo"},
                {0, 0, "Posto Presamatos"},
                {0, 0, "Aldeia Chuva Estelar"},
                {0, 0, "Visteterna"},
                {0, 0, "Serra Cardo de Gelo"},
                {0, 0, "Bosque Oculto"},
                {0, 0, "Garganta dos Sussurros Gelados"},
            },
        },
        ["a Costa Negra"] = {
            achievementID = 844,
            proxyLocation = {0, 0, "a Costa Negra"},
            waypoints = {
                {0, 0, "Ruínas de Auberdine"},
                {0, 0, "Acampamento de Guerra Lança Partida"},
                {0, 0, "Mata Murcha"},
                {0, 0, "Olho do Vórtice"},
                {0, 0, "Lor'danel"},
                {0, 0, "Glaive do Mestre"},
                {0, 0, "Vale da Lança Partida"},
                {0, 0, "Rio Crenado"},
                {0, 0, "Ruínas de Mathistra"},
                {0, 0, "Ameth'Aran"},
                {0, 0, "Nazj'vel"},
            },
        },
        ["o Vale Gris"] = {
            achievementID = 845,
            proxyLocation = {0, 0, "o Vale Gris"},
            waypoints = {
                {0, 0, "Praia de Zoram"},
                {0, 0, "Refúgio Brisaprata"},
                {0, 0, "Lago Falathim"},
                {0, 0, "Aldeia dos Pelocardo"},
                {0, 0, "Astranaar"},
                {0, 0, "Vale Uivante"},
                {0, 0, "Lago Céu Caído"},
                {0, 0, "Satyrnaar"},
                {0, 0, "Acampamento de Lenhadores Brado Guerreiro"},
                {0, 0, "Retiro de Orendil"},
                {0, 0, "Pico do Trovão"},
                {0, 0, "Entreposto de Maestra"},
                {0, 0, "Altar de Aessina"},
                {0, 0, "Ruínas de Poeira Estelar"},
                {0, 0, "Refúgio Bosque Real"},
                {0, 0, "Posto Machadada"},
                {0, 0, "Sombrarrama"},
                {0, 0, "Monte Fogovil"},
            },
        },
        ["a Cordilheira das Torres de Pedra"] = {
            achievementID = 847,
            proxyLocation = {0, 0, "a Cordilheira das Torres de Pedra"},
            waypoints = {
                {0, 0, "Vale Chaga de Guerra"},
                {0, 0, "Ruínas de Eldre'thar"},
                {0, 0, "Terras Escavadas"},
                {0, 0, "Vila de Cortavento"},
                {0, 0, "Malaka'jin"},
                {0, 0, "Ravina da Avalanche"},
                {0, 0, "Rochedo Cortavento"},
                {0, 0, "Vale Carbonizado"},
                {0, 0, "Morro das Torres de Pedra"},
                {0, 0, "Fortaleza Krom'gar"},
                {0, 0, "Mirante de Thal'darah"},
                {0, 0, "Antro Enrediço"},
                {0, 0, "Posto Andarilho da Montanha"},
                {0, 0, "Passagem Tramateia"},
                {0, 0, "Vale Matagrande"},
                {0, 0, "Retiro Rocha do Sol"},
                {0, 0, "Lago Mirkfallon"},
            },
        },
        ["o Pântano Vadeoso"] = {
            achievementID = 850,
            proxyLocation = {0, 0, "o Pântano Vadeoso"},
            waypoints = {
                {0, 0, "Ilha Theramore"},
                {0, 0, "Posto Chifrebravo"},
                {0, 0, "Estalagem Pouso do Umbral"},
                {0, 0, "Aldeia Muralha Verde"},
                {0, 0, "Ilha Alcaz"},
                {0, 0, "Aldeia Casco Negro"},
                {0, 0, "Coroa de Barro"},
                {0, 0, "Costa Tenebrosa"},
                {0, 0, "Pântano da Serpe"},
            },
        },
        ["Tanaris"] = {
            achievementID = 851,
            proxyLocation = {0, 0, "Tanaris"},
            waypoints = {
                {0, 0, "Geringontzan"},
                {0, 0, "Vale dos Vigilantes"},
                {0, 0, "Areias Abissais"},
                {0, 0, "Covil Nóxio"},
                {0, 0, "Costa Quebra-sul"},
                {0, 0, "Ruínas de Lunaleste"},
                {0, 0, "Ruínas de Lunassul"},
                {0, 0, "Zul'Farrak"},
                {0, 0, "Posto Silitriste"},
                {0, 0, "Enseada do Armador Perdido"},
                {0, 0, "Pilar Partido"},
                {0, 0, "Complexo Dunamalho"},
                {0, 0, "Fenda Hazzali"},
                {0, 0, "Praia do Fim do Mundo"},
                {0, 0, "Vale Moitagulhas"},
                {0, 0, "Cavernas do Tempo"},
            },
        },
        ["a Selva Maleva"] = {
            achievementID = 853,
            proxyLocation = {0, 0, "a Selva Maleva"},
            waypoints = {
                {0, 0, "Aldeia Patavil"},
                {0, 0, "Floresta Ferrárbol"},
                {0, 0, "Vale das Escaras Pungentes"},
                {0, 0, "Jaedenar"},
                {0, 0, "Grota Flamejade"},
                {0, 0, "Vila da Lenha Morta"},
                {0, 0, "Clareira da Galhaça"},
                {0, 0, "Aldeia Flamejade"},
                {0, 0, "Salto da Peçonha"},
                {0, 0, "Ruínas de Constellas"},
                {0, 0, "Santuário Esmeralda"},
                {0, 0, "Morlos'Aran"},
            },
        },
        ["a Clareira da Lua"] = {
            achievementID = 855,
            proxyLocation = {0, 0, "a Clareira da Lua"},
            waypoints = {
                {0, 0, "Lago Eluna'ara"},
                {0, 0, "Santuário de Remulos"},
                {0, 0, "Refúgio Noturno"},
                {0, 0, "Templos de Tempesfúria"},
            },
        },
    }, -- World of Warcraft (Vanilla)
    ["Nortúndria"] = {
        ["a Tundra Boreana"] = {
            achievementID = 1264,
            proxyLocation = {0, 0, "a Tundra Boreana"},
            waypoints = {
                {0, 0, "Cidade-templo de En'kilah"},
                {0, 0, "Areal Quebramar"},
                {0, 0, "Ancoradouro de Garrosh"},
                {0, 0, "Gelarra"},
                {0, 0, "Promontório Âmbar"},
                {0, 0, "Bastilha Valentia"},
                {0, 0, "Tocas da Morte"},
                {0, 0, "Caravana do Queixoduro"},
                {0, 0, "Kaskala"},
                {0, 0, "Campo da Morte"},
                {0, 0, "Posto Avançado Bor'gorok"},
                {0, 0, "Fortaleza Brado Guerreiro"},
                {0, 0, "Campos de Gêiser"},
            },
        },
        ["o Ermo das Serpes"] = {
            achievementID = 1265,
            proxyLocation = {0, 0, "o Ermo das Serpes"},
            waypoints = {
                {0, 0, "Repouso de Galakrond"},
                {0, 0, "Santuário Dragônico Obsidiano"},
                {0, 0, "Naxxramas"},
                {0, 0, "Aldeia Bruma Boreal"},
                {0, 0, "Planalto Vento Frio"},
                {0, 0, "Martelo de Agmar"},
                {0, 0, "Campo de Refugiados de Zefirália"},
                {0, 0, "Costa Abandonada"},
                {0, 0, "Vista Escarlate"},
                {0, 0, "Lago Indu'le"},
                {0, 0, "Nova Amparo"},
                {0, 0, "Guarda da Luz"},
                {0, 0, "Santuário Dragônico Esmeralda"},
                {0, 0, "Angrathar, o Portão da Ira"},
                {0, 0, "Templo do Repouso das Serpes"},
                {0, 0, "Perfídia"},
                {0, 0, "Fenda Cristalina"},
            },
        },
        ["Zul'Drak"] = {
            achievementID = 1267,
            proxyLocation = {0, 0, "Zul'Drak"},
            waypoints = {
                {0, 0, "Gundrak"},
                {0, 0, "Anfiteatro da Angústia"},
                {0, 0, "Altar de Rhunok"},
                {0, 0, "Altar de Mam'toth"},
                {0, 0, "Zim'Torga"},
                {0, 0, "Voltarus"},
                {0, 0, "Campo da Luz"},
                {0, 0, "Campos de Drak'Sotra"},
                {0, 0, "Altar de Sseratus"},
                {0, 0, "Altar de Quetz'lun"},
                {0, 0, "Altar de Har'koa"},
                {0, 0, "Zeramas"},
                {0, 0, "Ruína de Thrym"},
                {0, 0, "Kolramas"},
            },
        },
        ["a Floresta do Canto Cristalino"] = {
            achievementID = 1457,
            proxyLocation = {0, 0, "a Floresta do Canto Cristalino"},
            waypoints = {
                {0, 0, "Front Lazúli"},
                {0, 0, "Comando Fendessol"},
                {0, 0, "Penhasco Correventos"},
                {0, 0, "Fortaleza Violácea"},
                {0, 0, "Córrego Decrépito"},
                {0, 0, "Bosque Esquecido"},
                {0, 0, "A Grande Árvore"},
                {0, 0, "Selva Franca"},
            },
        },
        ["a Coroa de Gelo"] = {
            achievementID = 1270,
            proxyLocation = {0, 0, "a Coroa de Gelo"},
            waypoints = {
                {0, 0, "O Bombardeio"},
                {0, 0, "Porto da Ofensiva"},
                {0, 0, "Usina de Carne"},
                {0, 0, "Queda de Sindragosa"},
                {0, 0, "Vale dos Ecos"},
                {0, 0, "A Conflagração"},
                {0, 0, "Jotunheim"},
                {0, 0, "Abóbada das Sombras"},
                {0, 0, "Cidadela da Coroa de Gelo"},
                {0, 0, "O Front Partido"},
                {0, 0, "Aldur'thar: o Portão da Desolação"},
                {0, 0, "Valhalas"},
                {0, 0, "Ymarheim"},
                {0, 0, "Corp'rethar: o Portão do Horror"},
                {0, 0, "Forte do Flagelo"},
            },
        },
        ["o Fiorde Uivante"] = {
            achievementID = 1263,
            proxyLocation = {0, 0, "o Fiorde Uivante"},
            waypoints = {
                {0, 0, "Kamagua"},
                {0, 0, "Aldeia Casco Invernal"},
                {0, 0, "Porto Vendeta"},
                {0, 0, "Angra dos Malandros"},
                {0, 0, "Gjalerbron"},
                {0, 0, "Passo do Gigante"},
                {0, 0, "Ruína de Ivald"},
                {0, 0, "Nova Agamand"},
                {0, 0, "Clareira Deformada"},
                {0, 0, "Bastilha da Guarda Oeste"},
                {0, 0, "Baleheim"},
                {0, 0, "Ilha Cauldros"},
                {0, 0, "Acampamento da Sociedade dos Boticários"},
                {0, 0, "Portão de Aço"},
                {0, 0, "Niffelvar"},
                {0, 0, "Ninho Incandescente"},
                {0, 0, "Forte Vildervar"},
                {0, 0, "Halgrind"},
                {0, 0, "Skorn"},
                {0, 0, "Bastilha Utgarde"},
                {0, 0, "Sítio de Escavação de Baelgun"},
            },
        },
        ["a Serra Gris"] = {
            achievementID = 1266,
            proxyLocation = {0, 0, "a Serra Gris"},
            waypoints = {
                {0, 0, "Forte da Conquista"},
                {0, 0, "Ruínas de Drakil'jin"},
                {0, 0, "Fontes Graníticas"},
                {0, 0, "Ermida Presa Raivosa"},
                {0, 0, "Baía dos Empreendimentos"},
                {0, 0, "Chalé do Pinho Âmbar"},
                {0, 0, "Aldeia Oneqwah"},
                {0, 0, "Bastilha Drak'Tharon"},
                {0, 0, "Dun Argol"},
                {0, 0, "Bocaina Velha"},
                {0, 0, "Thor Modan"},
                {0, 0, "Runavold"},
                {0, 0, "Madeireira Céu Azul"},
                {0, 0, "Acampamento da Brigada de Cerro Oeste"},
            },
        },
        ["a Bacia Sholazar"] = {
            achievementID = 1268,
            proxyLocation = {0, 0, "a Bacia Sholazar"},
            waypoints = {
                {0, 0, "Coração do Rio"},
                {0, 0, "Pilar Verdeluz"},
                {0, 0, "Alcândora dos Criadores"},
                {0, 0, "Frondes Voz-da-chuva"},
                {0, 0, "A Avalanche"},
                {0, 0, "Aldeia de Kartak"},
                {0, 0, "Floresta Selvagem"},
                {0, 0, "Mirante dos Criadores"},
                {0, 0, "Pilar Tocado pelo Sol"},
                {0, 0, "Pilar Sangue da Vida"},
                {0, 0, "Pilar Rutilante"},
                {0, 0, "Prateleira do Criador da Tempestade"},
            },
        },
        ["os Picos Tempestuosos"] = {
            achievementID = 1269,
            proxyLocation = {0, 0, "os Picos Tempestuosos"},
            waypoints = {
                {0, 0, "Aldeia Brunnhildar"},
                {0, 0, "Dun Niffelem"},
                {0, 0, "Valkyrion"},
                {0, 0, "Campo Minado do Curtomada"},
                {0, 0, "Templo da Vida"},
                {0, 0, "Tormentério"},
                {0, 0, "Planícies Nevadas"},
                {0, 0, "Fortaleza Gelada"},
                {0, 0, "Berço de Narvir"},
                {0, 0, "Vale de Bor"},
                {0, 0, "Terraço dos Criadores"},
                {0, 0, "Maquinário dos Criadores"},
                {0, 0, "Ulduar"},
                {0, 0, "Templo das Tempestades"},
                {0, 0, "Perdição de Garm"},
                {0, 0, "Nidavelir"},
            },
        },
    }, -- Wrath of the Lich King
    ["Pandária"] = {
        ["a Floresta de Jade"] = {
            achievementID = 6351,
            proxyLocation = {0, 0, "a Floresta de Jade"},
            waypoints = {
                {0, 0, "Monastério de Tian"},
                {0, 0, "Pavilhão do Sonhador"},
                {0, 0, "Lago Pérola"},
                {0, 0, "Pedreira Rocha Verde"},
                {0, 0, "Aldeia Nuka Nuka"},
                {0, 0, "Coração da Serpente"},
                {0, 0, "Templo da Serpente de Jade"},
                {0, 0, "Posto Garrosh'ar"},
                {0, 0, "Aldeia do Mel"},
                {0, 0, "Flor da Manhã"},
                {0, 0, "Agouro do Imperador"},
                {0, 0, "Morro Bagarai"},
                {0, 0, "Pomar Sopro de Néctar"},
                {0, 0, "Terraço dos Dez Trovões"},
                {0, 0, "Fossos Bodoqueiros"},
                {0, 0, "O Arboreto"},
                {0, 0, "Ilha Ventaneira"},
            },
        },
        ["a Selva de Krasarang"] = {
            achievementID = 6975,
            proxyLocation = {0, 0, "a Selva de Krasarang"},
            waypoints = {
                {0, 0, "Cais dos Pescadores"},
                {0, 0, "Rio Dojani"},
                {0, 0, "Angra de Krasarang"},
                {0, 0, "Lagoa Nayeli"},
                {0, 0, "Ruínas de Dojan"},
                {0, 0, "Templo da Garça Vermelha"},
                {0, 0, "A Selva Proibida"},
                {0, 0, "Ungá Ingô"},
                {0, 0, "Berço de Chi-Ji"},
                {0, 0, "Vila Canção do Outono"},
                {0, 0, "Ruínas Krasari"},
                {0, 0, "Refúgio Asa da Garça"},
                {0, 0, "Ruínas de Korja"},
                {0, 0, "Ermo profundo"},
                {0, 0, "Ilhas do Sul"},
                {0, 0, "Vigia de Zhu"},
            },
        },
        ["as Estepes de Taolong"] = {
            achievementID = 6977,
            proxyLocation = {0, 0, "as Estepes de Taolong"},
            waypoints = {
                {0, 0, "Front de Gao-Ran"},
                {0, 0, "Posto de Guarda Rensai"},
                {0, 0, "Guarnição Avançada Osul"},
                {0, 0, "Guarnição Shado-Pan"},
                {0, 0, "Sik'vess"},
                {0, 0, "Os Reservatórios"},
                {0, 0, "Kri'vess"},
                {0, 0, "Templo Niuzao"},
                {0, 0, "Torno do Ódio"},
                {0, 0, "Shan'ze Dao"},
                {0, 0, "Sra'vess"},
            },
        },
        ["o Vale das Flores Eternas"] = {
            achievementID = 6979,
            proxyLocation = {0, 0, "o Vale das Flores Eternas"},
            waypoints = {
                {0, 0, "Ruínas de Guo-Lai"},
                {0, 0, "Palácio Mogu'shan"},
                {0, 0, "A Escada Dourada"},
                {0, 0, "O Pagode Dourado"},
                {0, 0, "Santuário das Duas Luas"},
                {0, 0, "As cinco irmãs"},
                {0, 0, "Vila do Cair da Bruma"},
                {0, 0, "Guarnição do Sol Poente"},
                {0, 0, "Santuário das Sete Estrelas"},
                {0, 0, "Solo Sagrado Tu Shen"},
                {0, 0, "Lago Pétala Branca"},
            },
        },
        ["o Vale dos Quatro Ventos"] = {
            achievementID = 6969,
            proxyLocation = {0, 0, "o Vale dos Quatro Ventos"},
            waypoints = {
                {0, 0, "Beirada do Vento"},
                {0, 0, "Leque Dourado"},
                {0, 0, "Meia Colina"},
                {0, 0, "Vila Kunzen"},
                {0, 0, "Safári Rosarães"},
                {0, 0, "Lagoas da Pureza"},
                {0, 0, "Campos de Seda"},
                {0, 0, "Cervejaria Malte do Trovão"},
                {0, 0, "Rancho Pé de Trovão"},
                {0, 0, "Garganta Poenta"},
                {0, 0, "O Celeiro Imperial"},
                {0, 0, "Arado de Pedra"},
                {0, 0, "Venda do Caneca de Barro"},
                {0, 0, "Ravina Paoquan"},
                {0, 0, "Terraço Retumbante"},
                {0, 0, "Pântanos Cantantes"},
                {0, 0, "O Coração da Terra"},
                {0, 0, "Descenso de Zhu"},
            },
        },
        ["o Monte Kun-Lai"] = {
            achievementID = 6976,
            proxyLocation = {0, 0, "o Monte Kun-Lai"},
            waypoints = {
                {0, 0, "Vila Binan"},
                {0, 0, "Portão dos Celestiais Majestosos"},
                {0, 0, "Monte Kota"},
                {0, 0, "Monte Neverest"},
                {0, 0, "Pico da Serenidade"},
                {0, 0, "Templo do Tigre Branco"},
                {0, 0, "Vale dos Imperadores"},
                {0, 0, "Gruta Galhareda"},
                {0, 0, "Ilha da Desforra"},
                {0, 0, "Mogujia"},
                {0, 0, "Rancho do Almiscarado"},
                {0, 0, "Monastério Shado-Pan"},
                {0, 0, "Trilha da Juta"},
                {0, 0, "Vila Zouchin"},
            },
        },
        ["o Ermo do Medo"] = {
            achievementID = 6978,
            proxyLocation = {0, 0, "o Ermo do Medo"},
            waypoints = {
                {0, 0, "Coração do Medo"},
                {0, 0, "Kypari Vor"},
                {0, 0, "Vila de Rikkitun"},
                {0, 0, "Terraço de Gurthan"},
                {0, 0, "As garras de Shek'zeer"},
                {0, 0, "Bosque Retorcido"},
                {0, 0, "Klaxxi'vess"},
                {0, 0, "Kypari Zar"},
                {0, 0, "Gambito do Encharco"},
                {0, 0, "Alagados"},
                {0, 0, "Parque Cervejeiro do Poente"},
                {0, 0, "Zan'vess"},
            },
        },
    }, -- Mists of Pandaria
    ["Ilhas Partidas"] = {
        ["Azsuna"] = {
            achievementID = 10665,
            proxyLocation = {0, 0, "Azsuna"},
            waypoints = {
                {0, 0, "Faronaar"},
                {0, 0, "A Via Verde"},
                {0, 0, "Planalto de Llothien"},
                {0, 0, "Nar'thalas"},
                {0, 0, "O Santuário Arruinado"},
                {0, 0, "Ruínas Meridionais de Zarkhenar"},
                {0, 0, "Passagem Brasavil"},
                {0, 0, "Ilha dos Vigilantes"},
                {0, 0, "Pomar Perdido"},
                {0, 0, "Enseada de Oceanus"},
                {0, 0, "Templo das Luzes"},
            },
        },
        ["Alta Montanha"] = {
            achievementID = 10667,
            proxyLocation = {0, 0, "Alta Montanha"},
            waypoints = {
                {0, 0, "Planalto Caçabruta"},
                {0, 0, "Vigília do Casco Gélido"},
                {0, 0, "Alcândor do Vigia da Noite"},
                {0, 0, "Curva do Rio"},
                {0, 0, "Enseada do Naufrágio"},
                {0, 0, "Vigília do Casco de Pedra"},
                {0, 0, "Totem do Trovão"},
                {0, 0, "Pântano Cego"},
                {0, 0, "Enclave Chifre de Ferro"},
                {0, 0, "Bacia Pinhapetra"},
                {0, 0, "Baixios Rochalonge"},
                {0, 0, "Chifre Celeste"},
                {0, 0, "Cataratas de Sylvam"},
                {0, 0, "Tenda Tirocerto"},
            },
        },
        ["Suramar"] = {
            achievementID = 10669,
            proxyLocation = {0, 0, "Suramar"},
            waypoints = {
                {0, 0, "Vale Âmbar"},
                {0, 0, "Falanaar"},
                {0, 0, "O Grande Passeio"},
                {0, 0, "Fortaleza da Guarda da Lua"},
                {0, 0, "Ruínas de Elun'eth"},
                {0, 0, "Tel'anor"},
                {0, 0, "Mata Carmesim"},
                {0, 0, "Castelo Almavil"},
                {0, 0, "Jandvik"},
                {0, 0, "Ravina Sileluna"},
                {0, 0, "Suramar"},
            },
        },
        ["Val'sharah"] = {
            achievementID = 10666,
            proxyLocation = {0, 0, "Val'sharah"},
            waypoints = {
                {0, 0, "Andutalah"},
                {0, 0, "Bradensbrook"},
                {0, 0, "Recife Crepuscular"},
                {0, 0, "Lorlathil"},
                {0, 0, "Vale Garralua"},
                {0, 0, "Bosque Courofumo"},
                {0, 0, "Thas'talah"},
                {0, 0, "Castelo Corvo Negro"},
                {0, 0, "O Bosque Onírico"},
                {0, 0, "Bosque de Cenarius"},
                {0, 0, "Vale da Névoa"},
                {0, 0, "Shala'nir"},
                {0, 0, "Templo de Eluna"},
            },
        },
        ["Trommheim"] = {
            achievementID = 10668,
            proxyLocation = {0, 0, "Trommheim"},
            waypoints = {
                {0, 0, "Câmara de Aggramar"},
                {0, 0, "Pouso de Trilhamedo"},
                {0, 0, "Grisvigília"},
                {0, 0, "Haustvald"},
                {0, 0, "Gorja de Nashal"},
                {0, 0, "Nastrondir"},
                {0, 0, "Mata Rúnica"},
                {0, 0, "Skold-Ashil"},
                {0, 0, "Descanso da Garra"},
                {0, 0, "Valdisdall"},
                {0, 0, "Mirante Biconegro"},
                {0, 0, "Dreyrgrot"},
                {0, 0, "Portões da Bravura"},
                {0, 0, "Hrydshal"},
                {0, 0, "Morheim"},
                {0, 0, "Rocha do Vigia"},
                {0, 0, "Pouso do Escudo"},
                {0, 0, "Fronte da Tempestade"},
                {0, 0, "Porto Mareskárnio"},
                {0, 0, "Penhascos Plangentes"},
            },
        },
    }, -- Legion
    -- Continents dictionary ...
    ["Continents"] = {
        ["Eastern Kingdoms"] = "Reinos do Leste",
        ["Outland"] = "Terralém",
        ["Cataclysm"] = "Cataclismo", -- Hyjal, Uldum, Deepholm, Twillight Highlands, Vashj'ir
        ["Draenor"] = "Draenor",
        ["Battle for Azeroth"] = "Batalha por Azeroth", -- Zandalar and Kul Tiras
        ["Kalimdor"] = "Kalimdor",
        ["Northrend"] = "Nortúndria",
        ["Pandaria"] = "Pandária",
        ["Broken Isles"] = "Ilhas Partidas",
    }  
}